= Notes de version 5.x
:revdate: 2025-08-26
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/01.5x/01.5x.md
:page-opendocs-slug:  /releasenotes/5x

== Notes de version pour 5.x

[NOTE]
====
Pour recevoir des notifications par e-mail des nouvelles versions, veuillez vous abonner à cette liste de diffusion SUSE : https://lists.suse.com/mailman/listinfo/neuvector-updates
====

=== 5.4.6 Août 2025

==== Nouvelles fonctionnalités

* *NVSHAS-6733* : Exporter les règles de réponse en tant que CRD.
* *NVSHAS-9899* : Les alertes de profil de processus NeuVector pour les services Java contiennent des données sensibles.
* *NVSHAS-9990* : Adopter un nouvel algorithme de hachage pour les mots de passe des utilisateurs.
* *NVSHAS-9968* : Support pour définir le mot de passe par défaut du compte administrateur par défaut.

==== Bugs corrigés

* *NVSHAS-10062* : Le gestionnaire ne montre pas d'ERREUR lors de l'échec de la création du mot de passe administrateur lors de la première connexion.
* *NVSHAS-10041* : L'opération de fédération a échoué "données invalides" lors de la configuration de la fédération via ConfigMap.
* *NVSHAS-10018*: Neuvector ne scanne pas toutes les images dans le registre GitLab.
* *NVSHAS-10017*: Alerte de sécurité de faux positif liée au processus autorisé.
* *NVSHAS-10001*: Les mesures de protection/surveillance "persistent" après la suppression du groupe.
* *NVSHAS-9985*:    NeuVector (Fed Master) crée un problème pour toutes les demandes venant de l'extérieur.
* *NVSHAS-9981*:    Un événement de sécurité est déclenché chaque fois qu'une nouvelle "règle de profil de processus" est ajoutée ou modifiée dans un groupe.

==== Avis de sécurité

* https://github.com/neuvector/neuvector/security/advisories/GHSA-8pxw-9c75-6w56[Le compte admin a un mot de passe par défaut non sécurisé]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-8ff6-pc43-jwv3[Gestion des mots de passe non sécurisée vulnérable aux attaques par rainbow]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-w54x-xfxg-4gxq[Le processus avec des arguments sensibles entraîne des fuites]

Voir la documentation xref:cve.adoc[Avis de sécurité et CVEs] pour plus d'informations.

=== 5.4.5 Juillet 2025

==== Nouvelles fonctionnalités

* *NVSHAS-9776*: Ajouter la tolérance etcd dans le graphique Helm.

==== Corrections de bogues

* *NVSHAS-9507*: Le conteneur OCI ne se fait pas scanner.
* *NVSHAS-9787*: Supprimer le journal du gestionnaire inutile.
* *NVSHAS-9788*: Affiner l'algorithme pour générer le certificat.
* *NVSHAS-9789*: Supprimer le journal du gestionnaire inutile sur la configuration du registre distant.
* *NVSHAS-9867*: NeuVector montre `+.NET Library System.Formats.Asn1 v8.013+` CVE 2024-38095 affectés.
* *NVSHAS-9883*: [quay.io] Les filtres génériques ne fonctionnent pas pour le registre Docker.
* *NVSHAS-9911*: Scanner le dépôt en utilisant l'API REST donne un "message" incorrect.
* *NVSHAS-9930*: CVE-2018-20796 pour `+glibc/libc-bin : 2.36-9+deb12u10+` – Faux positif.
* *NVSHAS-9933*: La fonctionnalité d'adaptateur de registre (Harbor) montre des erreurs dans le registre cible lors du scan.
* *NVSHAS-9934*: Fonctionnalité suspectée de dérive zéro défaillante.
* *NVSHAS-9940*: Problème de mode sous-domaine JFrog NV scan.
* *NVSHAS-9942*: Les analyses d'images pour les images des clients échouent.
* *NVSHAS-9945*: Lorsque le nom du processus est trop long, il est difficile de déterminer comment créer la règle de profil de processus appropriée.
* *NVSHAS-9946*: Problème d'affichage avec l'alerte de contrôle d'admission pour le type de credential.
* *NVSHAS-9947*: [UI-ext] Graphique de conformité manquant le statut "Manuel" dans Rancher NeuVector.
* *NVSHAS-9948*: Après la mise à niveau vers `+5.4.3+`, la configuration de NeuVector a été perdue.
* *NVSHAS-9949*: [Harbor][Utilisateur/mot de passe incorrect] Il continue à analyser les images même avec une saisie d'utilisateur/mot de passe incorrecte.
* *NVSHAS-9952*: Supprimer 'signature' du rapport d'utilisation car NV n'émet plus/vérifie la clé de licence.
* *NVSHAS-9953*: Les Pods Enforcer continuent de redémarrer.
* *NVSHAS-9954*: L'exportateur Prometheus de NeuVector génère des métriques dupliquées.
* *NVSHAS-9958*: L'application des règles réseau prend beaucoup de temps.
* *NVSHAS-9960*: Les scanners ne fonctionnent pas.
* *NVSHAS-9969*: Erreur fatale : des écritures de carte concurrentes entraînent le redémarrage du composant Enforcer.
* *NVSHAS-9971*: À propos de NV UI `+Get Bootstrap Password+`.
* *NVSHAS-9975*: [Manager] TypeError : `+this.mousemoveListener+` n'est pas une fonction observée dans NV GUI.
* *NVSHAS-9986*: Les règles d'accès aux processus et aux fichiers ne peuvent pas être modifiées ou supprimées dans la vue du groupe de politiques fédérées.
* *NVSHAS-9988*: UI : Les pages de groupe ne montrent pas tous les groupes lorsque plus de 2 000 groupes sont présents.
* *NVSHAS-9991*: Le groupe `+nv.gatekeeper-controller-manager.openshift-azure-guardrails+` est manquant dans l'UI.
* *NVSHAS-9993*: Remplacer MD5 par SHA256.
* *NVSHAS-9994*: Le pod Enforcer continue de redémarrer.
* *NVSHAS-9996*: Le graphique Helm devrait permettre un mode non privilégié des pods Enforcer.
* *NVSHAS-9998*: Impossible d'exporter le groupe du maître fédéré de NeuVector.
* *NVSHAS-10000*: Mettre à niveau NV vers BCI 15.7.
* *NVSHAS-10003*: Le rechargement de la page ne fonctionne pas sur la page NV autonome pendant que l'interface utilisateur Rancher est ouverte.
* *NVSHAS-10008*: Analyse du registre – Le menu d'affichage est cassé pour l'image scannée.
* *NVSHAS-10010*: L'inondation TCP SYN bloque l'entrée, entraînant un blocage total du trafic entrant.

=== 5.4.4 Mai 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9915**: Afficher les résultats de l'analyse du module scanner Harbor dans l'interface utilisateur NeuVector.
* **NVSHAS-9904**: Exposer `+imagePullPolicy+` à `+values.yaml+` pour chaque composant.
* **NVSHAS-9869**: UI : Déplacer les contrôles DDoS vers le panneau de groupe.
* **NVSHAS-9840**: [GCP] Support NeuVector Autopilot pour GCP.
* **NVSHAS-9248**: Afficher les règles de processus/réseau inutilisées avec des compteurs et un horodatage `+Last Used+`.
* **NVSHAS-8160**: [Contrôleur] Ajuster certains éléments pour le calcul du score de risque de sécurité.
* **NVSHAS-4673**: Suggestion d'ajouter un message avant d'exporter des groupes.

==== Corrections de bogues

* **NVSHAS-9931**: Ajouter un avertissement s'il y a des versions incohérentes des produits NeuVector dans un multi-cluster.
* **NVSHAS-9925**: `+/v1/scan/asset/images+` L'API sur la page du registre échoue.
* **NVSHAS-9913**: Problème de suppression de plusieurs règles réseau liées aux groupes Workload:XYZ.
* **NVSHAS-9912**: Mise à jour de Helm concernant certaines autorisations RBAC K8s nécessaires au compte de service du contrôleur.
* **NVSHAS-9909**: Message "Déconnecté - Aller à la page de chargement" affiché lors de l'utilisation de NeuVector Rancher NavLink.
* **NVSHAS-9898**: Dans un environnement fédéré, modifier les critères d'un groupe fed.* créé par le client (par exemple, fed.core-systems) ne fonctionne pas.
* **NVSHAS-9894**: [Enforcer] `+Nv.protect+` refuse la commande de sonde de disponibilité du contrôleur `+cat /tmp/ready+`.
* **NVSHAS-9886**: L'activité réseau ne résout pas les noms de domaine pour les connexions de groupe externe personnalisées.
* **NVSHAS-9884**: [Analyse de nœud][Analyse de conteneur] L'analyse échouera.
* **NVSHAS-9873**: Problème de recherche dans le filtre avancé de l'UI dans NeuVector 5.4.2.
* **NVSHAS-9865**: Les politiques réseau exportées diffèrent, selon l'ordre de sélection (mêmes groupes sélectionnés).
* **NVSHAS-9828**: [Enforcer: processus] L'Enforcer NeuVector n'est pas capable de détecter les pods à courte durée de vie (moins de 5 secondes).
* **NVSHAS-9783**: Après avoir ajouté la politique réseau pour interdire les paquets icmp, NeuVector ne voit aucune alerte dans `+Security Events+`.
* **NVSHAS-9176**: Afficher une erreur de script dans la page **Risques de sécurité > Vulnérabilités** si un utilisateur avec le rôle d'espace de noms `+rt_scan:w+` est connecté.

=== 5.4.3 Mars 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9793**: Autoriser les rôles Fed Global dans LDAP/userinitcfg lors du déploiement de NeuVector via le ConfigMap et le Secret.
* **NVSHAS-9764**: [RFE] Ajouter le support pour Azure pour "Configuration de dépôt distant".
* **NVSHAS-9759**: Ajouter des détails de date dans le rapport d'exposition Ingress.
* **NVSHAS-9755**: Demande d'affichage des noms de variables d'environnement avec les valeurs dans les alertes pour les secrets.
* **NVSHAS-9748**: [Helm] Mise à jour de NeuVector Helm pour prendre en charge la référence de nom pour les groupes communs dans CRD (NVSHAS0-4717).
* **NVSHAS-9426**: Ajouter hostPath pour Scanner au graphique Helm.
* **NVSHAS-9326**: NeuVector - Module Scanner Pluggable Harbor.
* **NVSHAS-9835**: UI pour désactiver l'auto-scan pour le nœud.
* **NVSHAS-7997**: Connecteur de scanner pour ghcr.io.
* **NVSHAS-7982**: Attribuer des capteurs WAF à partir du Maître de Fédération.

==== Corrections de bogues

* **NVSHAS-9849**: Les agents ne s'enregistrent pas auprès des contrôleurs.
* **NVSHAS-9847**: Les filtres génériques ne fonctionnent pas pour le registre Docker.
* **NVSHAS-9833**: La restauration de la configuration échoue dans les déploiements Rancher.
* **NVSHAS-9832**: Problème de création de règles réseau en utilisant le groupe de charges de travail.
* **NVSHAS-9821**: Le nom du processus ne correspond pas à partir de la ligne de commande pour l'alerte de règle de profit de processus.
* **NVSHAS-9817**: La création de la règle de sécurité NvClusterSecurityRule CRD montre une création réussie, mais elle n'a pas été réellement créée en raison d'entrées de règles de processus dupliquées.
* **NVSHAS-9812**: NeuVector prometheus-exporter métriques incorrectes.
* **NVSHAS-9811**: [Manager] Impossible d'accéder à l'interface graphique lors de l'utilisation d'un certificat personnalisé (CA) avec CA racine et CA intermédiaire sur le secret.
* **NVSHAS-9801**: Le mode FIPS + `+manager.env.ssl=false+` provoque une erreur dans le gestionnaire.
* **NVSHAS-9792**: La synchronisation de la stratégie de fédération échoue en raison de la taille du corps dépassant le maximum de Consul.
* **NVSHAS-9784**: NeuVector renvoie 404 lors de l'analyse du dépôt d'images Jfrog.
* **NVSHAS-9783**: Après avoir ajouté la stratégie réseau pour refuser les paquets icmp, l'utilisateur ne voit aucune alerte dans "Événements de sécurité".
* **NVSHAS-9780**: La connexion unique NeuVector ne fonctionne pas avec Rancher NavLink.
* **NVSHAS-9777**: Webhook JSON avec des clés "niveau" dupliquées.
* **NVSHAS-9770**: Le commutateur automatique après le mode Zero-Drift change la stratégie incorrecte.
* **NVSHAS-9765**: L'accès au fichier n'est pas complètement bloqué en mode Protect.
* **NVSHAS-9756**: L'Enforcer a atteint le maximum de CPU et a plusieurs alertes de pression mémoire.
* **NVSHAS-9668**: Le test de conformité échoue sur RKE2.
* **NVSHAS-9265**: Résultats de scan de vulnérabilité incomplets et incorrects sur l'environnement PRE PCI.
* **NVSHAS-9227**: Le scan du registre se bloque au milieu du processus de scan et passe à l'état "Inactif".
* **NVSHAS-9729**: Un nombre incorrect de vulnérabilités est observé lorsque plusieurs statefulsets avec le "même nom" dans les espaces de noms sont déployés dans un projet.
* **NVSHAS-9810**: Le contrôleur NeuVector ne répond pas et l'interface utilisateur n'est pas accessible.

=== 5.4.2 Janvier 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9726**: Le moniteur passe maintenant l'URL du proxy.
* **NVSHAS-9719**: Annonce la retraite des certificats intégrés.
* **NVSHAS-9715**: Support de valeur Helm Chart pour définir le nodeport sur le contrôleur et le gestionnaire.
* **NVSHAS-9710**: Inclure une colonne `+feed_rating+` triable dans l'onglet **Vulnérabilités**.
* **NVSHAS-9669**: Score de sécurité global via l'API REST.
* **NVSHAS-9590**: Capacité de choisir quel score de vulnérabilité pour tous les actifs.
* **NVSHAS-7555**: Inclure l'option "Actualiser automatiquement" sous Événements de sécurité.

==== Corrections de bogues

* **NVSHAS-9662**: Logique de rôle/RoleBinding incohérente dans le chart Helm 2.8.2.
* **NVSHAS-9652**: Différence observée dans le format syslog dans splunk.
* **NVSHAS-9649**: Le lien du conteneur produit un code de réponse 404 dans l'événement de sécurité.
* **NVSHAS-9613**: Erreur du pod NeuVector Manager / Interface Web NeuVector indisponible.
* **NVSHAS-9507**: Le conteneur OCI ne se fait pas scanner.
* **NVSHAS-9443**: La mise à niveau/l'installation via ArgoCD échoue car elle ne peut pas créer l'objet leases.coordination.k8s.io.
* **NVSHAS-9436**: Faux négatif CVE possible contre CVE-2024-7347.
* **NVSHAS-8386**: Les clés privées et les certificats auto-signés sont toujours expédiés dans plusieurs images.
* **NVSHAS-9754**: [UI] Empêcher Rancher de désactiver l'authentification SSO de l'utilisateur OpenShift ou RBAC de Rancher.
* **NVSHAS-9751**: [Protection d'exécution] Le mode de surveillance + Zero Drift ne génère aucune alerte lorsqu'un processus enfant est exécuté.
* **NVSHAS-9721**: L'interface utilisateur doit afficher un message d'erreur approprié lorsque l'utilisateur saisit un mauvais nom de registre.
* **NVSHAS-9696**: Indication de couleur incohérente des actifs sur la page de vulnérabilité.
* **NVSHAS-9686**: Espace de noms codé en dur pour le certificat de l'adaptateur de registre dans le graphique Helm de Neuvector.
* **NVSHAS-9678**: Traces d'erreur excessives après les modifications du linter.
* **NVSHAS-9670**: Gestionnaire: Problème de guillemets doubles dans la réponse en texte brut et problème de bibliothèque java sans nom dans sbt run.
* **NVSHAS-9667**: Définir la variable d'environnement `+CTRL_PATH_DEBUG+` sur une erreur dans le déploiement du contrôleur ne fonctionne pas.
* **NVSHAS-9665**: Règle d'accès au fichier: La suppression des règles prédéfinies produit une erreur "setRowData".
* **NVSHAS-9664**: Groupe de stratégie: La suppression du script personnalisé produit une erreur de type "setRowData".

[NOTE]
====
Les types par défaut du gestionnaire et du service d'adaptateur de registre ont été changés en ClusterIP.  Les utilisateurs peuvent toujours remplacer le paramètre en remplaçant le `+manager.svc.type+` et le `+cve.adapter.svc.type+` si NodePort est préféré.
====

Dans la version 5.4.2 de NeuVector, le support est interrompu pour les déploiements utilisant le certificat interne intégré. Le certificat trouvé à `+/etc/neuvector/certs/internal+` dans les images de conteneur NeuVector 5.4.2 sera supprimé. Pour continuer à utiliser NeuVector, les utilisateurs doivent :

==== 5.4.2 Nouvelle installation :

===== Utilisation de Helm :

- Activer les drapeaux `+internal.autoGenerateCert+` et `+internal.autoRotateCert+` dans les graphiques Helm (ceux-ci seront activés par défaut à partir de la version 5.4.2). Alternativement, une méthode YAML est liée ci-dessous.

===== Utilisation de YAML :

- Fournir un xref:internal.adoc#_replacing_certificates_used_in_internal_communications_of_suse_security[certificat interne en utilisant les méthodes existantes].

==== Mise à niveau des versions précédentes vers 5.4.2 :

Veuillez créer et configurer des certificats internes à partir du scanner pour le contrôleur, l'exécuteur et l'adaptateur de registre afin d'effectuer une mise à jour continue sans perdre de données. Il est toujours recommandé de faire une sauvegarde de votre configuration avant la mise à niveau. 

Les étapes suivantes ne sont nécessaires que si votre déploiement utilise un fichier `+.yaml+`. La mise à niveau via Helm n'a pas besoin de ces étapes supplémentaires en raison des certificats internes créés par défaut via les drapeaux suivants : `+internal.autoGenerateCert+` et `+internal.autoRotateCert+`.

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/ca.cert" > ca.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.pem" > tls.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.key" > tls.key
----

[,shell]
----
kubectl create secret generic internal-cert -n neuvector  --from-file=tls.key --from-file=tls.crt --from-file=ca.crt
----

Exemple de yaml 5.4.2 avec certificat interne configuré :
*https://github.com/neuvector/manifests/blob/main/kubernetes/5.4.0/neuvector-k8s.yaml* 

Informations supplémentaires sur xref:internal.adoc[les certificats internes].


Dans le cas d'une configuration PVC, les utilisateurs peuvent configurer un PVC existant dans la nouvelle installation pour restaurer une configuration.


**Remarque supplémentaire pour le scanner :**

Pour les utilisateurs actuels avec des versions antérieures à 5.4.2, le certificat restera disponible dans le `+neuvector/scanner:latest+` jusqu'au 31 mars 2025. Après cette date, il sera supprimé. Les utilisateurs doivent prévoir de fournir le même certificat interne au contrôleur, à l'exécuteur, au scanner et à l'adaptateur de registre pour continuer à utiliser le scanner.

Veuillez noter que le scanner autonome ne sera pas affecté par ces changements.

=== 5.4.1 Novembre 2024

==== Nouvelles fonctionnalités

* **NVSHAS-8583**: Définir des modes de politique granulaires pour les ensembles de règles, mode de politique réseau séparé et mode de profil au niveau de chaque groupe.
* **NVSHAS-9440**: Supporter le mode réseau séparé et le mode Processus et Fichier dans CRD.
* **NVSHAS-9369**: Ajouter une catégorie de journal de débogage via le support de déploiement helm pour le contrôleur.
* **NVSHAS-9040**: Améliorer le message syslog lorsque la règle de contrôle d'admission est refusée en mode de surveillance.

==== Corrections de bogues

* **NVSHAS-9416**: [Scanner] activemq-all-5.8.0.redhat-60024.jar ne peut PAS être détecté avec aucune vulnérabilité (mais la version précédente du scanner peut).
* **NVSHAS-9447**: Les pods Controller/Scanner plantent - "Sortie système non prise en charge".
* **NVSHAS-9278**: CVE-2024-41110 est trouvé dans la dernière image du scanner.
* **NVSHAS-9467**: Le groupe personnalisé défini par l'étiquette du pod ne propage pas ses données de profil sur les conteneurs enfants.
* **NVSHAS-9442**: Problème de déploiement sur ArgoCD.
* **NVSHAS-9436**: Faux négatif CVE possible contre CVE-2024-7347.
* **NVSHAS-9468**: Corriger CVE-2020-26160 pour remplacer jwt-go par jwt:v5.
* **NVSHAS-9517**: Le contrôle d'admission n'est pas cohérent, obtenant des résultats incorrects.
* **NVSHAS-9532**: Le scan d'image est terminé mais le déploiement n'est toujours pas autorisé.
* **NVSHAS-9558**: Le jeton JWT expire rapporte http.StatusRequestTimeout 408.
* **NVSHAS-9576**: Effacer le champ de mot de passe pour les données du registre lorsque l'utilisateur utilise le mode contrôleur avec Jenkins pour scanner.
* **NVSHAS-9425**: Créer nfq lorsque le conteneur a vxlan.
* **NVSHAS-9571**: [Registres] Le filtre pour toutes les images scannées ne fonctionne pas bien.
* **NVSHAS-9589**: Clusters gérés déconnectés - Incompatibilité de version avec le cluster principal.
* **NVSHAS-8824**: L'utilisateur échoue à supprimer ses propres groupes, ne peut pas créer de groupes à portée d'espace de noms.
* **NVSHAS-9605**: Exporter un groupe avec des valeurs de mode de politique et de mode de profil de processus invalides est à tort autorisé.
* **NVSHAS-9608**: Le scanner ne signale aucune erreur lorsque le contrôleur signale une erreur pour d'énormes résultats de scan ~23MB.
* **NVSHAS-9534**: Afficher l'erreur dans les contrôles d'admission.
* **NVSHAS-9600**: Impossible de désactiver le débogage du contrôleur.
* **NVSHAS-9631**: Réduire certaines erreurs d'exécution.
* **NVSHAS-9645**: Le traitement CRD préexistant échoue.
* **NVSHAS-9592**: Aucun nouveau scan malgré la nouvelle version de la base de données.
* **NVSHAS-9212**: Afficher le message d'alerte dans GET(/v1/eula) si le rôle de neuvector-binding-secret (binding) est incorrect.
* **NVSHAS-9367**: Améliorer les messages d'erreur lorsque le registre ne parvient pas à se connecter.
* **NVSHAS-9475**: L'impression de la grille d'arrière-plan ne couvre pas entièrement lorsque le menu est réduit.
* **NVSHAS-9485**: Message incorrect pour 'Mode de Politique de Sécurité Réseau' dans l'interface utilisateur.
* **NVSHAS-9480**: L'interface utilisateur NV déployée sur le cluster en aval de Rancher renvoie HTTP/403 après la déconnexion de Rancher.
* **NVSHAS-9547**: Le tri est cassé sur le tableau des risques de sécurité --> vulnérabilités.
* **NVSHAS-9570**: [Vulnérabilités] Modifier la description de la légende pour différents statuts sur les actifs.
* **NVSHAS-9561**: Le score de sécurité global du tableau de bord doit correspondre au score réel.
* **NVSHAS-9572**: [Vulnérabilités] Les données filtrées ont été conservées peu importe le rafraîchissement de l'utilisateur ou la reconnexion sur la page.
* **NVSHAS-9597**: L'interface utilisateur ne répond à aucune erreur lorsque le contrôleur renvoie 403 pour POST(v1/group).
* **NVSHAS-8682**: Le service webhook CRD doit être déplacé du graphique helm crd au graphique helm de l'application.

==== Problèmes connus

* Dans la version 2.8.3 du graphique, nous avons déplacé une ressource précédemment mal allouée des crds vers le noyau. Si vous utilisez à la fois les graphiques crds et core, vous pourriez rencontrer des problèmes lors de la mise à niveau si vous déployez d'abord le noyau. Pour résoudre cela, mettez à niveau les crds d'abord puis les graphiques core.

=== 5.4 Septembre 2024

* **Améliorations de l'UI**: 
** Afficher les utilisateurs SSO de Rancher.
** Gérer les jetons JWT.
** Navigation d'image améliorée et liens vers les résultats de scan.
* **Améliorations de la sécurité**: 
** Nouveaux filtres de conformité.
** Support pour les benchmarks CIS et la signature d'images OCI.
* **Réseau & Surveillance**: 
** Suivi avancé de la bande passante et des sessions.
** Surveillance DDoS.
** Support du réseau Multus.
* **Gestion des certificats**: 
** Nouvelles notifications pour les certificats internes expirants, y compris les capacités de rotation.
* **Automatisation & Intégration**: 
** Automatisation de la fédération.
** Intégration RBAC de Rancher.
** Amélioration du contrôle d'admission.
* **Performance & Efficacité**: 
** Réduction de l'utilisation de la mémoire.
** Réduction des frais de données ISP.
** Exposition des statistiques de cache du scanner.
* **Améliorations de l'Utilisabilité**: 
** Support du mot de passe de démarrage.
** Archivage des données de facturation cloud.
** Application des limites de l'espace de noms.

==== Nouvelles fonctionnalités

* **NVSHAS-9012**: Affichage des utilisateurs SSO Rancher sur l'interface NV ayant le même nom d'utilisateur.
* **NVSHAS-8939**: Fournir une option sur l'interface NV afin que les utilisateurs de session SSO Rancher puissent supprimer le jeton JWT actuel (c'est-à-dire se déconnecter).
* **NVSHAS-7522**: Navigation facile dans les images à travers les registres.
* **NVSHAS-8148**: Lien de l'image du conteneur aux résultats de scan d'image du registre.
* **NVSHAS-9258**: Ajouter une nouvelle notification pour les certificats expirants et les certificats internes.
* **NVSHAS-8915**: Support pour de nouveaux filtres de conformité et rapport de conformité.
* **NVSHAS-9403**: Filemonitor-UI: Permettre à l'utilisateur de supprimer une règle de surveillance de fichier prédéfinie.
* **NVSHAS-8423**: Détecter la bande passante au niveau du groupe, le nombre de sessions actives et la violation du taux de session en fonction des seuils configurés.
* **NVSHAS-9218**: Support pour les groupes fédéraux et CRD pour la surveillance DDoS.
* **NVSHAS-8461**: Prise en charge des benchmarks CIS pour les services k8s gérés dans le cloud.
* **NVSHAS-7664**: Réduire les frais de données des fournisseurs de services Internet lors de l'analyse du registre.
* **NVSHAS-8868**: Exposer les statistiques du cache du scanner.
* **NVSHAS-8676**: Amélioration de NV Protect pour les scripts de benchmark.
* **NVSHAS-9255**: Personnaliser les registres de recherche de contrôle d'admission pour les noms d'images sans FQDN.
* **NVSHAS-9144**: ID ajouté pour le fichier de contrôle des vulnérabilités pour une identification facile.
* **NVSHAS-7687**: Prise en charge de la configuration du niveau de journalisation (déboguer/erreur/info/avertir) pour l'exécuteur et le contrôleur depuis l'interface de ligne de commande.
* **NVSHAS-7518**: Changer les certificats internes pour les composants {product-name}.
* **NVSHAS-9287**: Activer la rotation des certificats internes.
* **NVSHAS-8562**: Ajouter une notification d'expiration des certificats internes.
* **NVSHAS-8486**: Support de l'interface réseau Multus.
* **NVSHAS-7447**: Intégration RBAC Rancher avec {product-name}.
* **NVSHAS-7822**: Automatisation de la fédération sans appels API de script.
* **NVSHAS-8799**: Créer un cadre de conformité pour importer des modèles de conformité.
* **NVSHAS-8773**: Support du mot de passe de démarrage lors du déploiement initial.
* **NVSHAS-6740**: Amélioration du profil de référence à zéro dérive en appliquant la liste apprise en mode protection.
* **NVSHAS-8325**: Faire respecter la limite de l'espace de noms du conteneur pour la règle réseau.
* **NVSHAS-8723**: Archiver les données de facturation cloud.
* **NVSHAS-9086**: Réduire l'utilisation de la mémoire du processus du contrôleur en éliminant la structure de données vulTrait.
* **NVSHAS-6979**: Capacité d'inclure le commentaire de la règle de réponse dans le contenu de l'alerte.
* **NVSHAS-8845**: Créer une clé API avec le rôle FedReader et FedAdmin.
* **NVSHAS-9306**: L'évaluation de la configuration du contrôle d'admission montre l'ID de règle responsable des déploiements autorisés ou refusés.
* **NVSHAS-9078**: Prise en charge de la signature d'image pour les images OCI.
* **NVSHAS-7945**: Prise en charge de la référence STIG DISA pour Kubernetes.
* **NVSHAS-8234**: Logique de contrôle d'admission permettant des images qui devraient être refusées.

==== Corrections de bogues

* **NVSHAS-9005**: TypeError dans les registres : Impossible de lire les propriétés de non défini (lecture de 'total_records').
* **NVSHAS-9085**: Le rapport PDF de la vue des actifs montre 0 % de vulnérabilité même avec des vulnérabilités présentes.
* **NVSHAS-9084**: Le rapport PDF de la vue des actifs montre NaN lorsque la liste des images est vide.
* **NVSHAS-9128**: Événements de sécurité : Le conteneur ne peut pas être affiché s'il n'y a pas de valeur d'espace de noms de charge de travail.
* **NVSHAS-9025**: Portée d'acceptation des vulnérabilités Neuvector pour les conteneurs.
* **NVSHAS-9155**: Nom de colonne incorrect et nom de fichier manquant lors de l'analyse du registre d'image
* **NVSHAS-9122**: Les journaux principaux de Neuvector se déconnectent à chaque fois que l'on utilise "Cluster multiple" avec la connexion SSO Rancher.
* **NVSHAS-9266**: Analyse du registre: Le bouton Rapport d'analyse par couche doit être masqué ou désactivé lorsqu'il n'y a pas de vulnérabilité.
* **NVSHAS-9219**: Permettre aux utilisateurs d'activer la validation du certificat du serveur pour les serveurs d'authentification.
* **NVSHAS-9246**: Le filtrage pour l'exportation CSV/PDF ne fonctionne pas.
* **NVSHAS-8947**: Impossible d'importer la configuration NV lors de l'authentification via Rancher SSO.
* **NVSHAS-9282**: UI : L'édition de l'entrée du registre OpenShift échoue en raison d'un jeton manquant.
* **NVSHAS-9098**: Améliorer l'expérience utilisateur lors du chargement de la page de risque.
* **NVSHAS-9267**: Ne pas permettre à l'interface utilisateur sur le cluster principal 5.4 de passer aux clusters gérés avant 5.4 en raison des changements de l'API REST.
* **NVSHAS-9285**: UI : Le bouton de la liste déroulante chevauche d'autres éléments.
* **NVSHAS-9302** : Impossible de créer une APIKEY avec le rôle FedReader et FedAdmin.
* **NVSHAS-8539** : La reconfiguration des paramètres de proxy perd le mot de passe.
* **NVSHAS-9293** : Suppression des détails d'image non liés dans les rapports de vulnérabilité.
* **NVSHAS-9238** : L'interface utilisateur ne rafraîchit pas le nom du cluster affiché après qu'il a été changé.
* **NVSHAS-9363** : Configuration des notifications > La grille des webhooks n'est pas correctement alignée.
* **NVSHAS-9362** : Le filtre des vulnérabilités de risque de sécurité ne renvoie aucun résultat.
* **NVSHAS-8699** : Impossible de distinguer l'utilisateur si l'utilisateur AD de Rancher est le même.
* **NVSHAS-9062** : Affichage des utilisateurs SSO de Rancher sur l'interface utilisateur NV ayant le même nom d'utilisateur (Conversion sur le contrôleur).
* **NVSHAS-9071** : Certains modules ne sont signalés que dans le scan du conteneur.
* **NVSHAS-8242**: appel gRPC pour tester si le contrôleur gère la gravité critique.
* **NVSHAS-8908**: Analyser correctement le port X-Forwarded en tenant compte du séparateur de virgule.
* **NVSHAS-9024**: Rôle risqué de contrôle d'admission perf.
* **NVSHAS-9091**: Impossible de signaler tous les modules sous ol:9.1, photon:5.0, rhel:9.1 et amzn:2023 source dans le dépôt, le registre et l'analyse autonome.
* **NVSHAS-8997**: Réduire considérablement le nombre de slots de politique par nœud pour améliorer les performances.
* **NVSHAS-9059**: Groupes CRD visibles dans NV même après suppression de K8s.
* **NVSHAS-9107**: Crash de goroutine à rest.handlerConfigLocalCluster.
* **NVSHAS-9108**: Le port 18500 ne devrait pas être ouvert.
* **NVSHAS-9119**: Crash de goroutine à probe.(*FileNotificationCtr).AddContainer().
* **NVSHAS-9125**: Une entrée CRD avec des paramètres invalides ne devrait pas être autorisée à créer.
* **NVSHAS-9124**: Docker : de nombreux incidents inattendus de processus de vérification de l'état sont signalés.
* **NVSHAS-9111**: NV doit vérifier `+--event-qps > 0+`.
* **NVSHAS-9130**: Des incidents inattendus de mise à jour de Container.Package sont trouvés après le démarrage d'un conteneur spécifique.
* **NVSHAS-9080**: L'utilisateur du lecteur Fed ne peut pas accéder à certaines API REST.
* **NVSHAS-9092**: L'utilisateur avec espace de noms ne doit pas voir les ressources globales.
* **NVSHAS-9116**: Le cluster de travailleurs peut partir si la connexion est interrompue.
* **NVSHAS-8980**: Obtenez l'interface hôte et tunnel sur le nœud avec succès dans oc 4.15.
* **NVSHAS-9188**: Définir l'interface mgmt-br comme interface hôte pour le nœud de récolte.
* **NVSHAS-4858**: Ne pas développer le groupe de conteneurs dans le contrôleur pour améliorer les performances de déploiement de la stratégie et réduire l'utilisation du CPU et de la mémoire.
* **NVSHAS-8700**: L'utilisateur AD de Rancher ne peut pas se connecter à {product-name} parfois.
* **NVSHAS-9121**: Le paramètre de seuil de surveillance du réseau du groupe ne peut pas être modifié.
* **NVSHAS-9189**: Le scan se bloquera dans la planification après que le contrôleur soit arrêté et redémarré.
* **NVSHAS-9019**: Corriger l'état de lien non synchronisé pour l'interface hôte.
* **NVSHAS-8305**: Supprimer le certificat intégré.
* **NVSHAS-9013**: Suppression du filtre BPF sur le moniteur de processus.
* **NVSHAS-7853**: EOF de la poignée TLS.
* **NVSHAS-9290**: La règle de profil de processus ajoutée par l'utilisateur n'a pas d'effet avec ZD activé.
* **NVSHAS-9301**: NV déployé sur Rancher Prime ne peut pas indiquer son goût Rancher.
* **NVSHAS-9289**: Autoriser la mise à niveau lorsque RBAC est manquant.
* **NVSHAS-7601**: Améliorer la restauration à partir de la sauvegarde de configuration PV pendant les scénarios.
* **NVSHAS-7687**: Ajouter le paramètre de niveau syslog pour l'enforcer.
* **NVSHAS-9292**: Corriger l'exposition Ingress Egress qui montre 0 vulnérabilités.
* **NVSHAS-9270**: Supporter k3s pour le pipeline de référence CIS.
* **NVSHAS-9338**: Alerte 'Le cluster géré [id] est déconnecté du principal'.
* **NVSHAS-9358**: L'analyse d'image utilisant un proxy échouerait.
* **NVSHAS-9337**: Envoyer un message de journal lorsque l'attaque SYN flood est détectée.
* **NVSHAS-9209**: Supprimer le cache de domaine lorsque l'espace de noms est supprimé de k8s.
* **NVSHAS-8985**: Les registres fédérés disparaissent après le redémarrage du contrôleur.

==== Problème connu:

* **NVSHAS-9443**: La mise à niveau/l'installation via ArgoCD échoue car il ne peut pas créer l'objet leases.coordination.k8s.io.
* **Workaround**: Créer les objets de bail donnés avant de mettre à niveau vers 5.4.0 en utilisant ARGO CD. Changez l'espace de noms s'il est différent de neuvector.
+
--
[,bash]
----
cat <<EOF | kubectl apply -f -
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-controller
  namespace: neuvector
spec:
  leaseTransitions: 0
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-cert-upgrader
  namespace: neuvector
spec:
  leaseTransitions: 0
EOF
----
--

=== 5.3.4 Juillet 2024

==== Corrections de bogues

* L'interface `+host+` et `+tunnel+` sont récupérées avec succès avec OpenShift CLI v4.15.
* La plage IP 169.254.x.x est exclue des IPs d'interface hôte.
* Réexaminez l'interface hôte après 1 minute de démarrage de l'enforcer.
* Correction d'un problème où l'URL du fournisseur OpenID échouait à cause de la regex.
* Remédie aux CVEs suivants :
+
|===
| CVE | S'applique à | Impact

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.2.4-s5 Juillet 2024

* Remédie aux CVEs suivants :

|===
| CVE | S'applique à | Impact

| CVE-2023-42363
| busybox
| {CVE-medium}

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2023-42366
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4603
| openssl
| {CVE-medium}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.3.3 Juin 2024

==== Améliorations

* Permet aux utilisateurs de bloquer l'utilisation de classes de stockage spécifiques depuis la page `+Admission Controls+`.
* Le `+LDAP Authentication+` a des champs séparés pour la configuration `+baseDN+` et `+groupDN+`.
* Le `+Egress and Ingress chart+` a une nouvelle colonne de vulnérabilité qui contient le nombre de vulnérabilités `+High+` et `+Medium+` pour chaque service.

==== Corrections de bogues

* Correction d'un bug lié à `+regex+` lors de l'utilisation d'une virgule (`+,+`) dans une entrée multi-`+Admission Control user criteria+`.
* Correction d'un bug où le scan CVE des paquets `+jar+` ne montrait pas tous les paquets affectés par un même CVE. Maintenant, toutes les occurrences sont signalées.
* Remédie aux CVEs suivants :

|===
| CVE | S'applique à | Impact

| CVE-2024-35195
| python:requests
| {CVE-medium}

| CVE-2024-21011
| openjdk11
| {CVE-low}

| CVE-2024-21012
| openjdk11
| {CVE-low}

| CVE-2024-21068
| openjdk11
| {CVE-low}

| CVE-2024-21085
| openjdk11
| {CVE-low}

| CVE-2024-21094
| openjdk11
| {CVE-low}
|===

==== Autre

* Permettre aux utilisateurs de définir des ressources pour `+updater-cron-job+` lors de l'installation de {product-name} avec le graphique Helm.
* Versionnage du conteneur de l'exportateur Prometheus révisé et dissocié du versionnage de `+controller+`.
* (Scanner) Détecter le paquet/module `+R+` dans Ubuntu et Red Hat Enterprise Linux.
* (Scanner) Ajout du support pour le scan PHP Composer.

=== 5.2.4-s3 Avril 2024

* Remédie aux CVEs suivants :

|===
| CVE | S'applique à | Impact

| CVE-2021-40633
| giflib
| {CVE-high}

| CVE-2023-48161
| giflib
| {CVE-high}

| CVE-2024-28757
| expat
| {CVE-high}

| CVE-2023-39742
| giflib
| {CVE-medium}

| CVE-2023-45288
| go:golang.org/x/net
| {CVE-medium}

| CVE-2024-25629
| c-ares
| {CVE-medium}

| CVE-2024-3651
| python:idna
| {CVE-medium}

| CVE-2024-2511
| openssl
| {CVE-low}
|===

=== 5.3.2 Avril 2024

==== Corrections de bogues

* Après la mise à niveau vers v5.3.1 à partir d'une version précédente {product-name}, les ressources personnalisées NvClusterSecurityRule existantes peuvent être supprimées par inadvertance. REMARQUE : La version 5.3.1 a été supprimée de docker hub afin de prévenir le problème de mise à niveau.

=== 5.3.1 Avril 2024

[IMPORTANT]
====
La version 5.3.1 a été supprimée de docker hub afin de prévenir le problème de mise à niveau corrigé dans 5.3.2. Veuillez utiliser la version 5.3.2.
====

==== Améliorations

* Permettre aux utilisateurs de définir &apos;`+accepted+`&apos; vulnérabilités lors de l'utilisation des actions Github afin qu'elles n'affectent pas les flux de travail.
* Ajouter des filtres de gravité, de niveau de score et de notation de flux à Assets > Registry > Vue des vulnérabilités d'image.
* Autoriser lors de la configuration d'un registre s'il doit utiliser le proxy défini pour les analyses d'images du registre.

==== Corrections de bogues

* Risques de sécurité > Vulnérabilités > Le filtre avancé ne filtre pas 'CVE sans correction'
* Violation inattendue du conteneur au conteneur en mode hôte
* Accepter le format d'image OCI lors du passage à l'API docker 1.24
* L'analyse du registre ne doit pas analyser les artefacts non-image / ne pas enregistrer d'erreur
* Permettre la vérification de la signature d'image de paire de clés sans racine sans dépendance à Internet ou à sigstore.
* Événements de sécurité non autorisés par les règles réseau dans un nœud spécifique (lié aux messages d'erreur "Container Task chan full")
* Le conteneur ne parvient pas à s'ajouter au workload avec succès (occurrences fréquentes). Résultant d'un blocage des messages de canal.

==== Autre

* Mettre à jour les plugins de scanner pour Jenkins, l'action GitHub et Bamboo.
* (Scanner) Accepter le format d'image OCI lors du passage à l'API docker 1.24.
* (Scanner) L'analyse du registre ne doit pas analyser les artefacts non-image / ne pas enregistrer d'erreur.
* (Scanner) Ajouter le support pour l'analyse de php composer.

==== {product-name} Extension UI v. 1.0 pour Rancher Mars 2024

* Après l'installation de {product-name}, xref:rancher.adoc#_suse_security_ui_extension_for_rancher[activation/installation] de l'extension UI {product-name} de Rancher affichera un tableau de bord pour le cluster, y compris des liens vers SSO vers le cluster complet {product-name}. REMARQUE : L'extension peut s'afficher comme un tiers, ce qui sera corrigé dans une future version. De plus, après l'installation, les utilisateurs de Rancher 2.7.x peuvent voir deux icônes {product-name} UI Ext dans la liste (bug). Une icône indiquera Désinstaller (ce qui signifie qu'elle est installée), et l'autre devrait indiquer Installer. Cela peut rester tel quel, c'est-à-dire, ne pas Installer à nouveau si l'extension est déjà installée.

=== 5.2.4-s2 Février 2024

* Remédie aux CVEs suivants :
* Haute cve : CVE-2023-52425 dans expat, CVE-2024-20952 et CVE-2024-20918 dans openjdk11
* Moyenne cve : CVE-2023-52426 dans expat, CVE-2024-20926, CVE-2024-20921, CVE-2024-20945 et CVE-2024-20919 dans openjdk11, CVE-2024-0727 et CVE-2023-6237 dans openssl

=== 5.3.0 Février 2024

==== Améliorations

* Afficher les URL de destination externes (FQDN) dans le tableau de bord (egress), les rapports PDF et CSV, ainsi que dans l'écran d'activité réseau et les listes d'événements de sécurité (violations)
* En mode Découverte, apprendre les sorties vers des groupes d'adresses FQDN externes automatiquement. Un nouveau groupe personnalisé FQDN externe sera créé à moins que la connexion externe ne corresponde à une règle existante.
* Activer l'apprentissage ICMP (mode Découverte) et le blocage (mode Protection) via une nouvelle variable d'environnement du contrôleur CTRL_EN_ICMP_POLICY = 1
* Exporter les CRDs vers Github pour soutenir gitops vers un dépôt par défaut en utilisant la console ou l'API REST.
* Supporter la déconnexion unique SAML SSO avec ADFS iDP
* Ajouter le support pour la plateforme ARM64. Le tirage depuis des plateformes basées sur ARM tirera automatiquement les images ARM64 {product-name} appropriées.
* Supporter les webhooks via un proxy
* Améliorer la fonction d'audit de contrôle d'admission pour inclure les résultats de toutes les règles. Lister le résultat de chaque règle et ajouter une autre entrée pour l'action finale qui se produirait lorsqu'elle est évaluée dans un déploiement de contrôle d'admission en direct.
* Appliquer les règles de contrôle d'admission désactivées via CRD ou yaml (kubectl)
* Exportation / importation du profil de vulnérabilité via la console, CRD ou API REST. L'importation remplacera le profil existant. La suppression du CRD entraînera un profil vide.
* Exportation / importation du modèle de profil de conformité via la console, CRD ou API REST. L'importation remplacera le modèle existant.
* Ajouter un statut 'Manuel' dans les rapports de conformité pour les benchmarks CIS qui doivent être exécutés manuellement par les utilisateurs (non exécutés par {product-name}).
* Améliorer le chargement/performance de l'interface utilisateur de la page des vulnérabilités
* Unifier la connexion de session du navigateur. Avec cela, tous les onglets du navigateur partagent la même session de connexion, l'ouverture d'un nouvel onglet à partir d'une session existante ne demande pas d'identifiants, et lorsque un onglet se déconnecte, tous les onglets se déconnectent.
* Améliorations de la sécurité de la console (UI) : 1) ajouter des en-têtes de sécurité obligatoires (X-Content-Type-Options nosniff ; X-XSS-Protection 1 ; mode=block ; X-Frame-Options SAMEORIGIN ; Cache-Control privé, no-cache, no-store, must-revalidate
HTTP Strict Transport Security max-age=15724800, 2) ajouter un en-tête CSP (par exemple, définir une directive &apos;`+default-src+`&apos;), 3) supprimer la divulgation du nom du serveur
* Prise en charge des versions plus récentes des benchmarks CIS. Kubernetes (1.8.0), Kubernetes V1.24 (1.0.0), Kubernetes V1.23 (1.0.1), RedHat OpenShift Container Platform (1.4.0)
* Afficher dans les Actifs -> Conteneurs -> Détails des conteneurs qui ont été scannés dans les registres par rapport à l'exécution
* Ajouter un lien vers le Groupe dans les Risques de Sécurité -> Vulnérabilités -> Popup Impact pour modifier facilement le mode de groupe
* Prise en charge des liens profonds dans les URL vers la page de vulnérabilité d'image et/ou de conteneur
* Ajouter une option de réinitialisation de mot de passe pour l'administrateur afin de réinitialiser le mot de passe de l'utilisateur dans les paramètres de la console -> Utilisateurs
* Autoriser l'envoi des journaux d'événements aux journaux du pod contrôleur dans les paramètres -> Configuration -> Notification. Les événements envoyés commenceront par 'notification=' et seront enregistrés uniquement dans le pod contrôleur principal. Notez qu'il y a un bug dans cette version où, pour changer le niveau d'événement, SYSLOG doit être activé (et peut être désactivé si désiré après avoir changé le niveau).
* Supprimer l'exigence pour le contrôleur/enforceur de monter "/host/cgroup".
* Ajouter le menu Obtenir de l'aide avec des liens vers slack, la documentation et d'autres ressources
* Remplir le champ message pour /v1/log/activity logs

==== Corrections de bogues

* Erreur interne du serveur dans les risques de sécurité -> vulnérabilités avec un grand nombre de CVE
* SIGSEGV : violation de segmentation sur le contrôleur
* La suppression des fichiers vulnérables (par exemple, jar) ne les retire pas de la liste des vulnérabilités
* Certificat Syslog invalide utilisant l'algorithme de signature SHA256withECDSA
* {product-name} montre les événements de sécurité qui devraient être autorisés par une règle réseau
* Nœud non géré avec un enforceur "zombie" en cours d'exécution
* Le filtre avancé montre les champs de remédiation et d'impact vides
* Corriger la gestion des chaînes pour éviter un redémarrage inattendu de l'enforceur
* Violations inattendues liées aux groupes intégrés
* Appel RPC de débogage de l'enforceur de bundle de support pour les données renvoie une erreur
* Le groupe ne correspond pas dans les événements de sécurité
* L'envoi d'événements à slack ne fonctionne pas - avec proxy
* Affichage des événements de sécurité pour les règles réseau autorisées

==== Autre

* Ajouter la détection automatique du moteur de conteneur à l'exécution (socket) au graphique Helm
* Supprimer le paramètre pour exécuter le contrôleur en mode privilégié dans le graphique Helm, et l'exigence pour le contrôleur/enforceur de monter "/host/cgroup".
* Les fichiers d'exemple de déploiement kubernetes ont été supprimés des docs {product-name}. Veuillez vous référer au lien pour des exemples.

==== Changements mis en évidence qui peuvent nécessiter des modifications pour les déploiements manuels (tous les changements sont déjà reflétés dans le dernier graphique Helm pour 5.3.x)

* La détection automatique du temps d'exécution du conteneur (socket) supprime le besoin de spécifier le temps d'exécution du conteneur et le chemin du socket.
* La suppression de l'exigence d'exécuter le contrôleur en mode privilégié supprime le besoin de monter le socket d'exécution et monté /host/cgroup/
* Ajout de rôle/liaison de rôle pour neuvector-binding-secret ainsi que neuvector-secret dans yaml.
* Nouveaux comptes de service et liaisons de rôle requis pour 5.3
* Tous les fichiers yaml de déploiement référencés ont maintenant /5.3.0/ dans leurs chemins

=== 5.2.4-s1 Janvier 2024

==== Publication de correctif de sécurité

* Remédie à CVE-2023-6129 dans openssl, et CVE-2023-46219, CVE-2023-46218 dans curl.

=== 5.2.4 Novembre 2023

==== Corrections de bogues

* Modifications de la configuration ValidatingWebhookConfiguration Azure AKS et journalisation des erreurs.

=== 5.2.3 Novembre 2023

==== Améliorations

* Ajoutez le support pour l'API NVD 2.0 dans Scanner.
* Analysez l'hôte du conteneur en mode autonome du scanner.

[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n
----

==== Corrections de bogues

* L'analyse sur un nœud échoue en raison d'un problème de blocage de docker cp / grpc.

=== 5.2.2-s1 Octobre 2023

==== Mise à jour de sécurité

* Mettez à jour les packages pour remédier aux CVE y compris le CVE-2023-38545 et le CVE-2023-43804.

=== 5.2.2 Octobre 2023

==== Avis de sécurité pour CVE-2023-32188

* Remédier à CVE-2023-32188 &quot;`+JWT token compromise can allow malicious actions including Remote Code Execution (RCE)+`&quot; en générant automatiquement le certificat utilisé pour signer le jeton JWT lors du déploiement et de la mise à niveau, et en générant automatiquement le certificat Manager/RESTful API lors des déploiements basés sur Helm.
 ** Le certificat pour la signature JWT est créé automatiquement par le contrôleur avec une validité de 90 jours et est tourné automatiquement.
 ** La génération automatique du certificat Manager, REST API et adaptateur de registre nécessite d'utiliser une installation basée sur Helm avec {product-name} la version helm 2.6.3 ou ultérieure.
 ** Le certificat intégré est toujours utilisé pour les déploiements basés sur yaml s'il n'est pas remplacé lors du déploiement ; cependant, il est recommandé de remplacer ceux-ci (voir la ligne suivante).
 ** Le xref:replacecert.adoc[remplacement manuel de certificat] est toujours pris en charge et recommandé pour les versions précédentes ou les déploiements basés sur yaml. Voir l'{product-name} avis de sécurité GitHub https://github.com/neuvector/neuvector/security/advisories/GHSA-622h-h2p8-743x[ici] pour une description.
 ** L'utilisation de certificats fournis par l'utilisateur est toujours prise en charge comme auparavant pour les déploiements basés sur Helm et yaml.
* Ajouter des contrôles supplémentaires sur les scripts de conformité personnalisés. Par défaut, les scripts personnalisés ne peuvent plus être ajoutés, à moins que la variable d'environnement CUSTOM_CHECK_CONTROL ne soit ajoutée au Contrôleur et à l'Enforcer. Les valeurs sont "désactiver" (par défaut, non autorisé), "strict" (rôle admin uniquement), ou "libéral" (rôles admin, conformité et politique d'exécution).
* Prévenir l'injection LDAP - le champ nom d'utilisateur est échappé.

==== Améliorations

* Ajouter des données de scan supplémentaires aux résultats CVE envoyés par SYSLOG pour les scans en couches
* Support de l'API NVD 2.0 pour la base de données CVE de scan
* Fournir la date de construction de l'image du conteneur dans les détails -> du conteneur
* Ajuster le tri pour les règles réseau : désactiver le tri dans la vue des règles réseau mais activer le tri des règles réseau dans la vue Groupe.
* Activer/désactiver la détection/l'alerte TLS 1.0 et TLS 1.1 avec des variables d'environnement pour l'Enforcer THRT_SSL_TLS_1DOT0, THRT_SSL_TLS_1DOT1. Désactivé par défaut.
* Ajouter la variable d'environnement AUTO_PROFILE_COLLECT pour le Contrôleur et l'Enforcer afin d'aider à capturer l'utilisation de la mémoire lors de l'examen des événements de pression mémoire. Définir la valeur = 1 pour activer.
* Les évaluations de configuration par rapport au contrôle d'admission doivent montrer toutes les violations avec un seul scan.
* Ajouter plus d'options pour les critères de rapport CVE dans les règles de réponse. Exemple 1 - "cve-high-with-fix:X" signifie : Lorsque le nombre de (vulnérabilités élevées qui ont été corrigées) >= X, déclencher la règle de réponse. Exemple 2 - "cve-high-with-fix:X/Y" signifie : Lorsque le nombre de (vulnérabilités élevées qui ont été signalées il y a Y jours et qui ont été corrigées) >= X, déclencher la règle de réponse.

==== Corrections de bogues

* L'exportation de la stratégie de groupe ne renvoie aucun contenu YAML réel.
* Améliorer l'élagage des espaces de noms avec une fonction dédiée.
* {product-name} l'utilisateur de l'espace de noms ne peut pas voir les actifs-->espaces de noms
* Ignorer le traitement des demandes de CRD CREATE/UPDATE si l'espace de noms du CR a déjà été supprimé.
* Fournir une solution de contournement pour une partie des groupes CRD qui ne peuvent pas être élagués avec succès après la suppression des espaces de noms.

=== 5.2.1 Août 2023

==== Améliorations

* Rapporter les résultats de scan superposés et les données CVE supplémentaires dans les messages SYSLOG. Cela est activé par une case à cocher dans les paramètres -> Configuration -> SYSLOG.
* Exporter les mappages NIST 800-53 (vers les benchmarks CIS docker) dans le rapport de conformité csv exporté.
* Supporter le paramètre Proxy dans la vérification de la signature de l'image.
* Inclure le résultat du scan de signature d'image dans le rapport CVE téléchargé.
* Supporter les annotations de pod pour les politiques de contrôle d'admission, disponibles via les critères personnalisés.
* Ajouter le champ Dernière modification pour filtrer l'impression des rapports de vulnérabilités, ainsi que le filtre avancé dans la vue des vulnérabilités.

==== Corrections de bogues

* Ne pas créer d'administrateur par défaut avec un mot de passe par défaut dans le déploiement initial {product-name} pour l'offre de facturation AWS (adaptateur CSP), nécessitant que l'utilisateur utilise un secret pour créer un nom d'utilisateur et un mot de passe administrateur
* Corriger le fichier .json qui a augmenté en taille et a fait planter un nœud kubernetes
* Améliorer la logique de détection des injections SQL
* Lors de l'installation du graphique crd helm d'abord avant d'installer le graphique noyau {product-name}, les comptes de service manquent
* Le résultat de conformité de l'analyse d'image I.4.1 est incorrect
* Le rapport de filtre avancé de vulnérabilité montre des images de tous les autres espaces de noms

=== 5.2.0 Juillet 2023

==== Améliorations

* Support des jetons pour l'accès à l'API {product-name}. Voir Paramètres -> Utilisateur, Clés API... pour créer une nouvelle clé API. Les clés peuvent être définies sur des rôles par défaut ou personnalisés.
* Support de la facturation PAYG AWS Marketplace pour les abonnements de support mensuels {product-name}. Les utilisateurs peuvent s'abonner à {product-name} par le support SUSE, facturé mensuellement à leur compte AWS en fonction de l'utilisation moyenne du nombre de nœuds du mois précédent. Détails https://open-docs.neuvector.com/deploying/awsmarketplace[ici].
* Support de la signature d'image pour les contrôles d'admission. Les utilisateurs peuvent exiger {product-name} pour vérifier que les images sont signées par des parties spécifiques avant qu'elles ne puissent être déployées dans l'environnement de production, grâce à une intégration avec Sigstore/Cosign. Voir Actifs -> Vérificateurs Sigstore pour créer de nouveaux actifs de signature. Des règles peuvent alors être créées avec les critères Signature d'image et/ou Vérificateurs Sigstore d'image.
* Activer chaque règle de contrôle d'admission pour avoir son propre mode de Surveillance ou de Protection. Une action de Refus en mode Surveillance alertera, et une action de Refus en mode Protection bloquera. Les actions autorisées ne sont pas affectées.
* Ajoutez un nouvel opérateur regex dans Politique > Contrôle d'admission > Ajouter une règle pour les utilisateurs et les groupes d'utilisateurs pour prendre en charge regex. Prise en charge des opérateurs "correspond à n'importe quel regex dans" et "ne correspond à aucun regex dans".
* Ajoutez la prise en charge des critères de contrôle d'admission tels que les limites de ressources. Un nouveau critère est ajouté pour les limites de ressources, et des critères supplémentaires sont pris en charge via les paramètres de critères personnalisés.
* Prise en charge de l'invocation du {product-name} scanner à partir des registres Harbor via l'interface https://github.com/goharbor/pluggable-scanner-spec[scanner pluggable]. Cela nécessite la configuration de la connexion au contrôleur (API exposée). L'adaptateur Harbor appelle le point de terminaison du contrôleur pour déclencher un scan, qui peut être effectué automatiquement lors de l'envoi. Les services d'interrogation peuvent être utilisés pour des scans périodiques. Les résultats de scan des contrôleurs principaux de la fédération SONT propagés aux clusters distants.  REMARQUE : Il y a un problème avec l'erreur de point de terminaison de l'adaptateur basé sur HTTPS : veuillez ignorer l'erreur de test de connexion, cela fonctionne même si une erreur est affichée (ignorer la validation du certificat).
* Service SaaS consultable pour les recherches CVE. Recherchez la dernière base de données {product-name} CVE pour voir si un CVE spécifique existe dans la base de données. Ce service est disponible pour les clients {product-name} Prime (abonnement de support payant). Contactez le support via votre portail SCC pour l'accès.
* Permettre à l'utilisateur de désactiver la protection réseau mais de garder le WAF/DLP fonctionnant. Configurer l'activation de la politique réseau dans les paramètres -> Configuration.
* Utilisez des comptes de services moins privilégiés selon les besoins pour chaque composant {product-name}. Une variable &quot;`+leastPrivilege+`&quot; est introduite. La valeur par défaut est fausse. REMARQUE : Utiliser le graphique helm actuel avec cette variable sur une version antérieure à 5.2.0 ne fonctionnera pas correctement.
* Lier à un compte de service non par défaut pour répondre à la recommandation CIS 1.5 5.1.5.
* Activer l'administrateur pour configurer le délai d'expiration de la session par défaut de l'utilisateur dans les paramètres -> Utilisateurs, Clés API et Rôles.
* Bannière de connexion personnalisable et texte d'en-tête d'interface utilisateur personnalisable pour les déploiements réglementés et gouvernementaux. Les exigences pour la configuration peuvent être trouvées xref:customui.adoc[ici].
* Support SYSLOG pour le transport chiffré TLS. Sélectionner TCP/TLS dans les paramètres -> Configuration pour SYSLOG.
* Activer le déploiement du {product-name} graphique helm de moniteur depuis Rancher Manager.
* Supprimer la limite supérieure pour le domaine de premier niveau dans le validateur d'URL pour le scan de registre.
* Scanner les dépendances golang, y compris les scans en temps réel.
* Supporter le scan de vulnérabilités Debian 12 (Bookworm).
* Ajouter l'exportation CSV pour le Registre / Détails pour exporter les CVE pour toutes les images dans le registre configuré dans les Actifs -> Registres pour un registre sélectionné.
* Permettre à {product-name} de définir plusieurs certificats ADFS en parallèle dans le champ de certificat x.509.
* Ajouter et afficher le champ de commentaire pour les Règles de Réponse.
* Spécifier ce que {product-name} considère comme des conteneurs système via une variable d'environnement. Par exemple, pour Rancher et les espaces de noms par défaut : NV_SYSTEM_GROUPS=*cattle-system;default
* Ajouter le support pour Kubernetes 1.27 et OpenShift 4.12

==== Corrections de bogues

* Réduire les journaux répétitifs dans les journaux de l'enforcer/contrôleur.
* La page des clusters multiples ne se rend pas.
* La suppression automatique du groupe vide prend 2 heures pour être supprimée au lieu de 1 heure selon le calendrier.
* La règle de réseau manuellement autorisée ne s'applique pas et entraîne une violation pour l'image de pause.
* Blocage des connexions SSL même si une règle réseau permet le trafic dans certaines conditions initiales.
* Événements de sécurité avertissant même avec des règles réseau autorisées en raison d'un problème de mise à jour de la politique dans la synchronisation.
* Activités réseau associant à tort le trafic de groupe personnalisé à l'externe.
* Le jeton de compte de service par défaut de l'espace de noms monté dans chaque pod est trop privilégié.
* Malgré la définition des règles réseau, les violations sont enregistrées sous les événements de sécurité (faux positifs) lorsque le conteneur s'est arrêté en raison d'une erreur de mémoire insuffisante (OOM).
* Permettre à l'utilisateur de désactiver/activer la détection et la protection contre les conteneurs non gérés dans le cluster. Cela peut être défini via l'interface de ligne de commande du gestionnaire :

[,shell]
----
set system detect_unmanaged_wl status -h
Usage: cli set system detect_unmanaged_wl status [OPTIONS] {true|false}

  Enable/disable detect unmanaged container
----

==== Autre

* Ajouter le paramètre "leastPrivilege" dans le graphique Helm. Ajouter l'option helm pour New_Service_Profile_Baseline. Une nouvelle version du graphique Helm (noyau) est publiée pour 5.2.
* Activer les paramètres d'intégration AWS Marketplace (adaptateur de facturation) dans le graphique Helm.
* Mettre à jour le configmap pour prendre en charge de nouvelles fonctionnalités (certificats ADFS multiples, dérive nulle, New_Service_Profile_Baseline, SYSLOG TLS, délai d'expiration de l'utilisateur)
* Mettre à jour les versions Kubernetes prises en charge à 1.19+ et OpenShift 4.6+ (1.19+ avec CRI-O)

=== 5.1.3 Mai 2023

==== Améliorations

* Ajouter un nouveau flux de vulnérabilités pour scanner le framework Microsoft .NET.
* Les statistiques de l'enforcer sont désactivées par défaut dans l'exportateur Prometheus pour améliorer l'évolutivité.
* Amélioration de l'utilisabilité : Utiliser le scanner pour scanner une seule image et imprimer le résultat (voir exemple ci-dessous).
* Ajouter une vérification de imagePullPolicy dans les critères des règles de contrôle d'admission.
* Afficher un message d'avertissement lorsque le schéma CRD est obsolète.

==== Corrections de bogues

* L'écran d'activité du réseau ne s'affiche pas ou s'affiche incorrectement.
* La suppression automatique du groupe vide prend 2 heures pour être supprimée au lieu de 1 heure selon le calendrier.
* Le fichier de contrôle de conformité ne s'affiche pas dans la console UI.
* Le filtre avancé dans les événements de sécurité manque le niveau "Erreur".
* Le mot de passe enregistré avec un caractère spécial échoue lors de la tentative d'authentification future.
* La page des clusters multiples ne s'affiche pas correctement lorsque les demandes sont élevées.
* Le panneau de détails du registre (en bas) ne se met pas à jour.

==== Sortie d'échantillon du scanner

[,shell]
----
Image: https://registry.hub.docker.comlibrary/alpine:3.4
Base OS: alpine:3.4.6
TOTAL: 6, HIGH: 1, MEDIUM: 5, LOW: 0, UNKNOWN: 0
┌─────────┬───────────────┬──────────┬───────────┬───────────────┬────────────┐
│ PACKAGE │ VULNERABILITY │ SEVERITY │ VERSION   │ FIXED VERSION │ PUBLISHED  │
├─────────┼───────────────┼──────────┼───────────┼───────────────┼────────────┤
│ openssl │ CVE-2018-0732 │ High     │ 1.0.2n-r0 │ 1.0.2o-r1     │ 2018-06-12 │
│         ├───────────────┼──────────┤           ├───────────────┼────────────┤
│         │ CVE-2018-0733 │ Medium   │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0734 │          │           │ 1.0.2q-r0     │ 2018-10-30 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0737 │          │           │ 1.0.2o-r2     │ 2018-04-16 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0739 │          │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-5407 │          │           │ 1.0.2q-r0     │ 2018-11-15 │
└─────────┴───────────────┴──────────┴───────────┴───────────────┴────────────┘
----

=== 5.1.2 Mars 2023

==== Améliorations

* Prise en charge du groupe d'adresses basé sur l'hôte virtuel et de la stratégie de correspondance des protections réseau. Cela permet un cas d'utilisation où deux adresses FQDN différentes sont résolues à la même adresse IP, mais des règles différentes pour chaque FQDN doivent être appliquées. Un nouveau groupe personnalisé avec &apos;`+address=vh:xxx.yyy+`&apos; peut être créé en utilisant l'indicateur &apos;`+vh:+`&apos; pour activer cette protection. Une règle réseau peut ensuite utiliser le groupe personnalisé comme source &apos;`+From+`&apos; basée sur le nom d'hôte virtuel (au lieu de l'adresse IP résolue) pour appliquer différentes règles aux hôtes virtuels.
* Liste des conteneurs de conformité pour exclure les conteneurs sortis.
* Améliorer les règles DLP pour prendre en charge le caractère générique simple dans le modèle.
* Ajouter la prise en charge de cri-o 1.26+ et OpenShift 4.11+.
* Rendre gravatar optionnel.
* Afficher la ressource de l'espace de noms du cluster dans la console / UI.
* Afficher la gravité/classification de la source (par exemple, Red Hat, Ubuntu...) avec le score de gravité NVD dans la console.
* Ne pas autoriser la désactivation de SSO/RBAC pour Rancher et OpenShift si l'utilisateur est authentifié via SSO.
* Ajouter l'activation de l'auto-scan et la suppression des groupes inutilisés vieillissants au configMap.
* Inclure l'adresse IP pour la source/destination externe dans csv/pdf pour les violations de refus implicite
* Diverses optimisations de performance et d'évolutivité pour l'utilisation du CPU et de la mémoire du contrôleur et de l'exécuteur.

==== Corrections de bogues

* Corriger la lenteur de l'application sur les nœuds GKE Container Optimized OS (COS) en mode Protect.
* SUSE Linux (SLES) 15.4 CVE ne correspondant pas dans le scanner. Avec cette correction, si la gravité est fournie dans le flux, la vulnérabilité sera ajoutée à la base de données, même si l'enregistrement NVD est manquant. Il est possible que le rapport inclue des vulnérabilités sans scores CVE.

==== Autre

* Améliorer les options CRD de contrôle d'admission dans helm https://github.com/neuvector/neuvector-helm/pull/237.
* Ajouter de nouvelles variables d'environnement d'exécuteur au graphique helm.

=== 5.1.1 Février, 2023

==== Améliorations

* Ajouter &quot;`+package+`&quot; comme information à l'événement syslog pour une vulnérabilité détectée.
* Ajouter la variable d'environnement de l'exécuteur ENF_NETPOLICY_PULL_INTERVAL - Valeur en secondes (valeur recommandée 60) pour réduire le trafic réseau et la consommation de ressources résultante par l'exécuteur en raison des mises à jour/recalculs de stratégie. (Remarque : il s'agissait d'un ajout non documenté jusqu'en août 2023).

[,yaml]
----
           - name: ENF_NETPOLICY_PULL_INTERVAL
             value: "60"   <== regulate the pulling gap by 60 seconds
----

==== Corrections de bogues

* Erreurs de suppression de groupe vide "Objet non trouvé"
* Trafic au sein du même conteneur alertant/bloquant
* Violations implicites inattendues pour le trafic egress istio avec règle d'autorisation en place
* Lors de la mise à niveau depuis la version {product-name} 4.x, une appartenance incorrecte au groupe de pods provoque une violation de politique inattendue
* L'authentification OIDC a échoué avec ADFS lorsque des caractères d'encodage supplémentaires apparaissent dans la demande
* Utilisation élevée de la mémoire par dp créant et supprimant des pods
* Mettre à jour alpine pour remédier à plusieurs CVE, y compris Manager : CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552
* Divers bugs d'interface corrigés

==== Autre

* Graphique Helm mis à jour pour permettre le remplacement du certificat pour les communications internes

=== 5.1.0 Décembre 2022

==== Améliorations

* Base de données de scan centralisée et multi-cluster (CVE). Le cluster principal (maître) peut scanner un registre/repo désigné comme un registre fédéré. Les résultats de scan de ces registres seront synchronisés avec tous les clusters gérés (distants). Cela permet d'afficher les résultats de scan dans la console du cluster géré ainsi que d'utiliser les résultats dans les règles de contrôle d'admission du cluster géré. Les registres n'ont besoin d'être scannés qu'une seule fois au lieu de par chaque cluster, réduisant l'utilisation du CPU/mémoire et de la bande passante réseau.
* Améliorer les règles de contrôle d'admission :
 ** Critères personnalisés pour les règles de contrôle d'admission. Permettre aux utilisateurs de définir des critères de ressources sur tous les champs liés aux pods et d'être utilisés dans les règles, par exemple item.metadata.annotationsKey contient 'neuvector', item.metadata.name='xyzzy', etc.
 ** Ajouter des critères pour vérifier les paramètres RBAC à haut risque pour les comptes de service lors du déploiement de pods. Ceci inclut les critères 'toute action sur les ressources de charge de travail', 'toute action sur RBAC', 'créer des ressources de charge de travail', 'lister les secrets', et 'exécuter dans un conteneur'.
 ** Ajouter une comparaison de version sémantique aux modules pour les règles de contrôle d'admission. Cela permet d'appliquer les opérateurs > ou < aux numéros de version dans les règles (par exemple, ne pas autoriser le module curl<6.2.0 à être déployé). Cela permet des vérifications de version spécifiques sur les paquets installés.
 ** Ajouter une règle de contrôle d'admission pour l'admission de sécurité des pods (PSA) prise en charge dans Kubernetes 1.25+.
* Ajouter une nouvelle variable d'environnement NO_DEFAULT_ADMIN qui, lorsqu'elle est activée, ne crée pas d'utilisateur 'admin'. Ceci est utilisé pour l'intégration SSO de Rancher par défaut. Si non activé, avertir de manière persistante l'utilisateur et enregistrer des événements pour changer le mot de passe admin par défaut s'il n'est pas changé par défaut.
* Le blocage de la connexion après des tentatives de connexion échouées devient désormais le paramètre par défaut. La valeur par défaut est de 5 tentatives, et configurable dans les paramètres -> Utilisateurs & Rôles-> Profil de mot de passe.
* Ajouter une nouvelle variable d'environnement pour l'optimisation des performances ENF_NO_SYSTEM_PROFILES, valeur : "1". Lorsqu'il est activé, cela désactivera les moniteurs de processus et de fichiers. Aucun processus d'apprentissage, aucun mode de profil, aucun incident de processus/fichier (paquet) et aucune surveillance de l'activité des fichiers ne sera effectué. Cela réduira l'utilisation des ressources CPU/mémoire et les opérations sur les fichiers.
* Ajouter un paramètre d'auto-scaling personnalisé pour les pods de scanner, avec les valeurs Retardé, Immédiat et Désactivé. Important : L'auto-scaling des scanners n'est pas pris en charge lorsque le scanner est déployé avec un opérateur OpenShift, car l'opérateur changera toujours le nombre de pods à sa valeur configurée.
 ** *_Stratégie retardée :_*
  *** Lorsque le contrôleur principal voit en continu "nombre de tâches" > 0 pendant > 90 secondes, un nouveau pod de scanner est démarré si maxScannerPods n'est pas encore atteint.
  *** Lorsque le contrôleur principal voit en continu que "le nombre de tâches" est 0 pendant > 180 secondes, il réduit d'un pod de scanner si minScannerPods n'est pas encore atteint.
 ** *_Stratégie immédiate :_*
  *** Chaque fois que le contrôleur principal voit "nombre de tâches" > 0, un nouveau pod de scanner est démarré si maxScannerPods n'est pas encore atteint.
  *** Lorsque le contrôleur principal voit en continu que "le nombre de tâches" est 0 pendant > 180 secondes, il réduit d'un pod de scanner si minScannerPods n'est pas encore atteint.
* Les groupes personnalisés peuvent désormais utiliser des étiquettes d'espace de noms, y compris les étiquettes d'espace de noms de Rancher. En général, les étiquettes de pod et d'espace de noms peuvent désormais être ajoutées aux groupes personnalisés.
* Ajouter la possibilité de masquer les espaces de noms et groupes sélectionnés dans la vue d'activité réseau.
* Support complet pour Cilium cni.
* Support complet d'OpenShift 4.9 et 4.10.
* Les outils de construction sont désormais disponibles pour le projet {product-name}/Open Zero Trust (OZT) à https://github.com/openzerotrust/openzerotrust.io..
* {product-name} répertorie désormais l'ID de version et le hachage SHA256 pour chaque version du contrôleur, du gestionnaire, de l'exécuteur à https://github.com/neuvector/manifests/tree/main/versions..
* Les données télémétriques anonymes (nombre de nœuds, groupes, règles) sont désormais signalées à un service cloud Rancher lors du déploiement pour aider l'équipe projet à comprendre le comportement d'utilisation. Cela peut être désactivé (opt-out) dans l'interface utilisateur ou avec configMap (No_Telemetry_Report) ou REST API.
* (Addendum janvier 2023). Prise en charge de la stratégie réseau basée sur ServiceEntry avec Istio. La fonctionnalité d'application de la stratégie réseau sortante a été ajoutée dans la version 5.1.0 pour les pods vers les destinations ServiceEntry déclarées avec Istio. Typiquement, un ServiceEntry définit comment un service externe référencé par un nom DNS est résolu en une adresse IP de destination. Avant la v5.1, {product-name} ne pouvait pas détecter et appliquer des règles pour les connexions à un ServiceEntry, donc toutes les connexions étaient classées comme externes. Avec la 5.1, des règles peuvent être appliquées pour des destinations ServiceEntry spécifiques. IMPORTANT : Si vous mettez à niveau vers la v5.1 avec un déploiement basé sur Istio, de nouvelles règles doivent être créées pour permettre ces connexions et éviter les alertes de violation. Après la mise à niveau, des violations implicites seront signalées pour le trafic nouvellement visible si les règles d'autorisation n'existent pas. De nouvelles règles de trafic peuvent être apprises et auto-créées en mode Découverte. Pour autoriser ce trafic, vous pouvez mettre le groupe en mode découverte ou créer un groupe personnalisé avec des adresses (ou un nom DNS) et une nouvelle règle réseau vers cette destination pour autoriser le trafic. REMARQUE : Il y a un bug dans la 5.1.0 dans la destination signalée par les violations de refus qui ne représentent pas la destination correcte.  Le bug signale que server_name et client_name sont identiques.  Ce problème sera résolu dans une prochaine version de correctif.

==== Corrections de bugs

* Réduire la consommation de mémoire du contrôleur due aux données de référence cis inutiles créées lors des mises à jour progressives. Ce problème ne se produit pas sur les nouveaux déploiements.
* Supprimer la licence de l'écran de configuration (plus nécessaire).

=== 5.0.6-s1 Mars, 2023

==== Corrections de bugs

* Mettre à jour les paquets alpine pour remédier aux CVE dans curl, y compris CVE-2023-23914, CVE-2023-23915 et CVE-2023-23916.

=== 5.0.6 Février, 2023

==== Corrections de bugs

* Utilisation élevée de la mémoire dans dpMsgConnection
* Utilisation élevée de la mémoire sur le processus dp dans l'enforcer s'il y a de nombreuses règles de stratégie apprises avec une charge de travail non gérée (fuite de mémoire)
* tcpdump ne parvient pas à démarrer avec succès lors de l'analyse d'un trafic sur le conteneur
* Mettre à jour alpine pour remédier à plusieurs CVE, y compris Manager : CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552

=== 5.0.5 Novembre, 2022

==== Corrections de bugs

* La mise à niveau vers 5.0.x entraîne un message d'erreur concernant Manager, Controller, Enforcer exécutant différentes versions.
* Les enforcers rencontrent une panique de routine go entraînant un dp kill.  WebUI ne reflète pas l'enforcer comme étant en ligne.
* Incident de violation inattendu de Process.Profile.Violation dans le groupe NV.Protect sur lequel commande sur coreos.

=== 5.0.4 Octobre, 2022

==== Mises à jour de sécurité

* Mettre à jour alpine pour supprimer la CVE critique-2022-40674 dans la bibliothèque expat du manager, ainsi que d'autres CVE mineures.

==== Améliorations

* Ajouter le support pour Antrea CNI

==== Corrections de bugs

* Corriger l'incident inattendu de violation de process.profile dans le groupe NV.Protect.
* Lorsque SSL est désactivé sur l'accès UI du manager, le mot de passe de l'utilisateur est imprimé dans le journal du manager.

=== 5.0.3 Septembre, 2022

==== Améliorations

* Ne pas afficher le contrat de licence après un redémarrage réussi à partir du volume persistant.
* Utilisez le filtre d'image dans les paramètres de profil de vulnérabilité pour ignorer les résultats de scan de conteneur.
* Prise en charge du scanner dans les actions GitHub à https://github.com/neuvector/neuvector-image-scan-action.
* Ajoutez des variables d'environnement Enforcer pour désactiver le scan des secrets et exécuter les benchmarks CIS

[,yaml]
----
    env:
      - name: ENF_NO_SECRET_SCANS  (available after v4.4.4)
        value: "1"
      - name: ENF_NO_AUTO_BENCHMARK (after v5.0.3)
        value: "1"
----

==== Corrections de bugs

* Enforcer incapable de démarrer occasionnellement.
* Fuite de connexion sur des environnements de fédération multi-clusters.
* La page de conformité ne se charge pas parfois dans les risques de sécurité -> conformité

=== 5.0.2 Juillet 2022

==== Améliorations

* Les clusters Rancher durcis et SELinux sont pris en charge.

==== Corrections de bugs

* Processus d'agent à forte utilisation CPU sur les systèmes k3s.
* Les groupes AD LDAP ne fonctionnent pas correctement après la mise à niveau vers 5.0.
* Enforcer continue de redémarrer en raison de l'erreur= trop de fichiers ouverts (rke2/cilium).
* Le journal de support ne peut pas être téléchargé avec succès.

=== 5.0.1 Juin 2022

==== Améliorations

* Prise en charge du scan de vulnérabilité de l'OS openSUSE Leap (dans l'image du scanner).
* Scanner : implémenter des attributs de suppression lors de la reconstruction du dépôt d'images.
* Vérifiez le déploiement {product-name} et le support pour les hôtes avec SELinux activé. Voir ci-dessous pour les détails sur le patch intérimaire jusqu'à ce que le graphique helm soit mis à jour.
* Distinguer plus clairement entre le graphique de fonctionnalités et les graphiques partenaires dans l'interface utilisateur de Rancher. + Améliorer l'annotation d'entrée pour nginx dans le graphique helm de Rancher. Ajouter / mettre à jour
ingress.kubernetes.io/protocol : https à nginx.ingress.kubernetes.io/backend-protocol : "HTTPS".
* L'opérateur OpenShift actuel prend en charge les routes de passage pour les services API et de fédération. Des paramètres supplémentaires de valeur Helm sont ajoutés pour prendre en charge les types de terminaison de route edge et de réencryption.

==== Corrections de bugs

* Le cluster AKS pourrait ajouter une clé inattendue dans le webhook de contrôle d'admission.
* L'enforcer ne devient pas opérationnel sur le cluster k8s 1.24 avec le runtime containerd 1.64. Séparément, l'enforcer échoue parfois à démarrer.
* Tout utilisateur avec le rôle d'administrateur (utilisateur local ou SSO) qui promeut un cluster en maître fédéré devrait être automatiquement promu au rôle de fedAdmin.
* Lorsque SSO utilise l'administrateur par défaut de Rancher dans {product-name} sur le cluster maître, le rôle de connexion {product-name} est admin, pas fedAdmin.
* Corriger plusieurs plantages de goroutine.
* Violation implicite de l'IP hôte non associée au nœud.
* Le ComplianceProfile ne montre pas le tag PCI.
* Le mappage de groupe LDAP n'est parfois pas affiché.
* L'outil d'examen et d'amélioration des risques entraînera un message d'erreur "Échec de la mise à jour de la configuration système : Demande au mauvais format".
* OKD 3.11 - L'erreur de Clusterrole s'affiche même si elle existe.

==== Remédiations CVE

* CVE-2022-29458 cve élevé trouvé sur le paquet ncurses dans toutes les images.
* CVE-2022-27778 et CVE-2022-27782 élevés trouvés sur le paquet curl dans l'image Updater.

==== Détails sur le support SELinux

{product-name} n'a pas besoin de paramètres supplémentaires pour les clusters avec SELinux activé pour déployer et fonctionner. Testé le déploiement de {product-name} sur un cluster RKE2 durci basé sur RHEL 8.5 avec SELinux activé. {product-name} déployé avec succès si PSP est activé et déploiement du gestionnaire de patch et du scanner. La prochaine version du graphique devrait corriger le problème ci-dessous.

Exemple ci-joint pour activer psp à partir du graphique Rancher et les commandes ci-dessous pour patcher le déploiement du Manager et du Scanner. L'ID utilisateur dans la commande de patch peut être n'importe quel nombre.

[,shell]
----
kubectl patch deploy -ncattle-neuvector-system neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
kubectl patch deploy -ncattle-neuvector-system neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
----

Exemple pour activer PSP :

[,shell]
----
[neuvector@localhost nv]$ getenforce
Enforcing
[neuvector@localhost nv]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

[neuvector@localhost nv]$ kk get psp
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS                                      SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
global-restricted-psp     false                                             RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
neuvector-binding-psp     true    SYS_ADMIN,NET_ADMIN,SYS_PTRACE,IPC_LOCK   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
system-unrestricted-psp   true    *                                         RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
[neuvector@localhost nv]$ nvpo.sh
NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE                    NOMINATED NODE   READINESS GATES
neuvector-controller-pod-54f69f7f9c-6h822   1/1     Running   0          5m51s   10.42.0.29   localhost.localdomain   <none>           <none>
neuvector-enforcer-pod-jz77b                1/1     Running   0          5m51s   10.42.0.30   localhost.localdomain   <none>           <none>
neuvector-manager-pod-588488bb78-p6vf9      1/1     Running   0          111s    10.42.0.32   localhost.localdomain   <none>           <none>
neuvector-scanner-pod-87474dcff-s8vgt       1/1     Running   0          114s    10.42.0.31   localhost.localdomain   <none>           <none>
----

=== 5.0.0 Version de disponibilité générale (GA) Mai 2022

==== Améliorations

* Promotion automatisée des modes de groupe. Promeut le mode de protection d'un groupe en fonction du temps écoulé et des critères. Ne s'applique pas aux groupes créés par CRD. Cette fonctionnalité permet à une nouvelle application de s'exécuter dans Discover pendant une certaine période, apprenant le comportement et {product-name} créant des règles de liste d'autorisation pour le réseau et le processus, puis passant automatiquement en mode Monitor, puis Protect. Critère de Discover à Monitor : Temps écoulé pour apprendre toute l'activité réseau et processus d'au moins un pod en direct dans le groupe. Critère de Monitor à Protect : Il n'y a pas d'événements de sécurité (réseau, processus, etc.) pour la période définie pour le groupe.
* Support pour les applications Rancher 2.6.5 et le graphique Marketplace. Déploie dans l'espace de noms cattle-neuvector-system et active SSO de Rancher à {product-name}. Remarque : Les déploiements précédents de Rancher (par exemple, les graphiques du catalogue partenaire, version 1.9.x et antérieure) doivent être complètement supprimés pour mettre à jour vers le nouveau graphique.
* Support pour le scan de SUSE Linux (SLE, SLES) et Microsoft Mariner
* Protection des processus et des fichiers sans dérive. C'est le nouveau mode par défaut pour les protections des processus et des fichiers. Zero-drift permet automatiquement uniquement les processus qui proviennent du processus parent qui se trouve dans l'image de conteneur d'origine, et n'autorise pas les mises à jour de fichiers ou l'installation de nouveaux fichiers. Lorsque vous êtes en mode Découverte ou Surveillance, le zéro-dérive alertera sur toute activité de processus ou de fichier suspecte. En mode Protection, il bloquera une telle activité. Le zéro-dérive ne nécessite pas que les processus soient appris ou ajoutés à une liste d'autorisation. Désactiver le zéro-dérive pour un groupe fera en sorte que les règles de processus et de fichiers énumérées pour le groupe prennent effet à la place.
* Protection en mode politique divisée pour le réseau, le processus/fichier. Il existe maintenant un paramètre global disponible dans les Paramètres -> Configuration pour définir séparément le mode de protection du réseau pour l'application des règles réseau. Activer cela (par défaut désactivé) fait en sorte que toutes les règles réseau soient dans le mode de protection sélectionné (Découverte, Surveillance, Protection), tandis que les règles de processus/fichier restent dans le mode de protection pour ce groupe, comme affiché dans l'écran Politique -> Groupes. De cette manière, les règles réseau peuvent être définies sur Protection (blocage), tandis que la politique de processus/fichier peut être définie sur Surveillance, ou vice versa.
* Détection de règles WAF, règles DLP améliorées (en-tête, URL, paquet complet). Utilisé pour les connexions entrantes aux pods d'application web ainsi que pour les connexions sortantes aux services API pour appliquer la sécurité API.
* CRD pour WAF, DLP et contrôles d'admission. REMARQUE : des liaisons de rôle de cluster/permissions supplémentaires sont requises. Voir les sections de déploiement Kubernetes et OpenShift. Import/export de CRD et versionnage pour les contrôles d'admission pris en charge via CRD.
* Intégration SSO Rancher pour lancer la console {product-name} via Rancher Manager. Cette fonctionnalité n'est disponible que si les conteneurs {product-name} sont déployés via Rancher. Ce déploiement tire du dépôt Rancher miroir (par exemple, rancher/mirrored-neuvector-controller:5.0.0) et se déploie dans l'espace de noms cattle-neuvector-system. REMARQUE : Nécessite une version mise à jour de Rancher 2.6.5 Mai 2022 ou ultérieure, et seuls les rôles d'administrateur et de propriétaire de cluster sont pris en charge pour le moment.
* Prend en charge le déploiement sur RKE2.
* Prise en charge de la fédération de clusters (gestionnaire multi-cluster) via un proxy. Configurer le proxy dans les paramètres -> Configuration, et activer le proxy lors de la configuration des connexions de fédération.
* Surveiller les rôles de cluster/bindings rbac requis et alerter dans les événements et l'interface utilisateur s'il en manque.
* Supporter les critères de limitations de ressources dans les règles de contrôle d'admission.
* Supporter le format Microsoft Teams pour les webhooks.
* Supporter les groupes imbriqués AD/LDAP sous le groupe de rôle mappé.
* Supporter les clusterrolebindings ou rolebindings avec des informations de groupe dans l'IDP pour Openshift.
* Autoriser les règles réseau et les règles de contrôle d'admission à être promues en une règle fédérée.

==== Corrections de bugs

* Corriger le problème de sauvegarde du rôle de fédération des travailleurs qui devrait se restaurer dans des clusters non fédérés.
* Améliorer les temps de chargement des pages pour un grand nombre de CVEs dans les Risques de Sécurité -> Vulnérabilités.
* Permettre à l'utilisateur de changer de mode lorsqu'il sélectionne tous les groupes dans la Politique -> Menu des Groupes. Avertir si le groupe des Nœuds est également sélectionné.
* Réduire les éléments de vérification de conformité du même nom et les rendre extensibles.
* Améliorer la sécurité des communications gRPC.
* Corrigé : impossible d'obtenir les bonnes informations de privilège de charge de travail dans la configuration rke2.
* Corriger le problème de support d'openSUSE Leap 15.3 (k8s/crio).

==== Autres mises à jour

* Mise à jour du chart Helm appVersion à 5.0.0 et version du chart à 2.2.0
* Fonctionnalité/menu de scan sans serveur supprimé.
* Support pour l'intégration des résultats de scan Jfrog Xray supprimé (le scan du registre Artifactory est toujours supporté).
* Le support pour le déploiement sur ECS n'est plus fourni. L'allinone devrait toujours pouvoir être déployé sur ECS, cependant, la documentation des étapes et des paramètres n'est plus supportée.

=== Mise à niveau de {product-name} 4.x à 5.x (avant 5.2.x)

[NOTE]
====
Les instructions ci-dessous s'appliquent aux mises à niveau vers 5.0.x et 5.1.x. Pour 5.2.x, les comptes de service et les liaisons ont changé et doivent être xref:kubernetes.adoc#_deploy_suse_security[révisés] pour planifier les mises à niveau.
====


Pour les utilisateurs de Helm, mettez à jour vers {product-name} le chart Helm 2.0.0 ou ultérieur. Si vous mettez à jour un opérateur ou une installation Helm sur OpenShift, voir la note ci-dessous.

. Supprimez l'ancienne définition de rôle de cluster neuvector-binding-customresourcedefinition

[,shell]
----
kubectl delete clusterrole neuvector-binding-customresourcedefinition
----

. Appliquez le nouveau verbe de mise à jour pour le rôle de cluster neuvector-binding-customresourcedefinition

[,shell]
----
kubectl create clusterrole neuvector-binding-customresourcedefinition --verb=watch,create,get,update --resource=customresourcedefinitions
----

. Supprimez l'ancien schéma crd pour Kubernetes 1.19+

[,shell]
----
kubectl delete -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/crd-k8s-1.19.yaml
----

. Créez un nouveau schéma crd pour Kubernetes 1.19+

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/waf-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/dlp-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/admission-crd-k8s-1.19.yaml
----

. Créez un nouveau rôle de cluster Admission, DLP et WAF et une liaison de rôle de cluster

[,shell]
----
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----

. Mettez à jour les noms et chemins d'image pour tirer {product-name} des images depuis Docker hub (docker.io), par exemple.

* neuvector/manager:5.0.0
* neuvector/controller:5.0.0
* neuvector/enforcer:5.0.0
* neuvector/scanner:latest
* neuvector/updater:latest

En option, supprimez toute référence à la {product-name} licence et au secret de registre dans les charts Helm, le yaml de déploiement, le configmap, les scripts, etc., car ceux-ci ne sont plus nécessaires pour tirer les images ou pour commencer à utiliser {product-name}.

*Note concernant SCC et mise à niveau via Operator/Helm*

Le SCC privilégié est ajouté au compte de service spécifié dans le yaml de déploiement par la version de l'opérateur 1.3.4 et supérieure dans les nouveaux déploiements. Dans le cas de la mise à niveau de l'opérateur {product-name} d'une version précédente à 1.3.4 ou de Helm à 2.0.0, veuillez supprimer le SCC privilégié avant la mise à niveau.

[,shell]
----
oc delete rolebinding -n neuvector system:openshift:scc:privileged
----

==== Version bêta 1 publiée en avril 2022

* Fonctionnalité complète, y compris la promotion automatisée des modes de groupe. Promeut le mode de protection d'un groupe en fonction du temps écoulé et des critères. Ne s'applique pas aux groupes créés par CRD. Cette fonctionnalité permet à une nouvelle application de s'exécuter dans Discover pendant une certaine période, apprenant le comportement et {product-name} créant des règles de liste d'autorisation pour le réseau et le processus, puis passant automatiquement en mode Monitor, puis Protect. Critère de Discover à Monitor : Temps écoulé pour apprendre toute l'activité réseau et processus d'au moins un pod en direct dans le groupe. Critère de Monitor à Protect : Il n'y a pas d'événements de sécurité (réseau, processus, etc.) pour la période définie pour le groupe.
* Support pour les applications Rancher 2.6.5 et le graphique Marketplace. Déploie dans l'espace de noms cattle-neuvector-system et active SSO de Rancher à {product-name}. Remarque : Les déploiements précédents de Rancher (par exemple, les graphiques du catalogue partenaire, version 1.9.x et antérieure) doivent être complètement supprimés pour mettre à jour vers le nouveau graphique.
* Tags pour Enforcer, Manager, Controller : 5.0.0-b1 (par exemple neuvector/controller:5.0.0-b1)

==== Version Preview.3 publiée en mars 2022

[CAUTION]
.important
====

Pour mettre à jour les déploiements de prévisualisation précédents pour les nouvelles fonctionnalités CRD WAF, DLP et contrôle d'admission, veuillez mettre à jour le yaml CRD et ajouter de nouveaux rbac/attributions de rôle :

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/latest/crd-k8s-1.19.yaml
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----
====


==== Améliorations

* Support pour le scan de SUSE Linux (SLE, SLES) et Microsoft Mariner
* Protection des processus et des fichiers sans dérive. C'est le nouveau mode par défaut pour les protections des processus et des fichiers. Zero-drift permet automatiquement uniquement les processus qui proviennent du processus parent qui se trouve dans l'image de conteneur d'origine, et n'autorise pas les mises à jour de fichiers ou l'installation de nouveaux fichiers. Lorsque vous êtes en mode Découverte ou Surveillance, le zéro-dérive alertera sur toute activité de processus ou de fichier suspecte. En mode Protection, il bloquera une telle activité. Le zéro-dérive ne nécessite pas que les processus soient appris ou ajoutés à une liste d'autorisation. Désactiver le zéro-dérive pour un groupe fera en sorte que les règles de processus et de fichiers énumérées pour le groupe prennent effet à la place.
* Protection en mode politique divisée pour le réseau, le processus/fichier. Il existe maintenant un paramètre global disponible dans les Paramètres -> Configuration pour définir séparément le mode de protection du réseau pour l'application des règles réseau. Activer cela (par défaut désactivé) fait en sorte que toutes les règles réseau soient dans le mode de protection sélectionné (Découverte, Surveillance, Protection), tandis que les règles de processus/fichier restent dans le mode de protection pour ce groupe, comme affiché dans l'écran Politique -> Groupes. De cette manière, les règles réseau peuvent être définies sur Protection (blocage), tandis que la politique de processus/fichier peut être définie sur Surveillance, ou vice versa.
* Détection de règles WAF, règles DLP améliorées (en-tête, URL, paquet complet)
* CRD pour WAF, DLP et contrôles d'admission. REMARQUE : des liaisons de rôle de cluster/permissions supplémentaires sont requises. Voir les sections de déploiement Kubernetes et OpenShift. Import/export de CRD et versionnage pour les contrôles d'admission pris en charge via CRD.
* Intégration SSO Rancher pour lancer la console {product-name} via Rancher Manager. Cette fonctionnalité n'est disponible que si les conteneurs {product-name} sont déployés via Rancher. REMARQUE : Nécessite une version mise à jour de Rancher (date/version à déterminer).
* Prend en charge le déploiement sur RKE2.
* Prise en charge de la fédération de clusters (gestionnaire multi-cluster) via un proxy.
* Surveiller les rôles de cluster/bindings rbac requis et alerter dans les événements et l'interface utilisateur s'il en manque.
* Supporter les critères de limitations de ressources dans les règles de contrôle d'admission.

==== Corrections de bugs

* Corriger le problème de sauvegarde du rôle de fédération des travailleurs qui devrait se restaurer dans des clusters non fédérés.

==== Version Preview.2 publiée en février 2022

* Modifications mineures de fichiers et de licences dans la source, aucune fonctionnalité ajoutée.

==== Support pour le déploiement sur AWS ECS obsolète

Le support pour le déploiement sur ECS n'est plus fourni. L'allinone devrait toujours pouvoir être déployé sur ECS, cependant, la documentation des étapes et des paramètres n'est plus supportée.

=== 5.0 'Tech Preview' janvier 2022

==== Améliorations

* Première version d'une version 'tech-preview' non prise en charge de {product-name} 5.0 version open source.
* Ajouter le support pour OWASP Top-10, règles similaires à WAF pour détecter les attaques réseau dans les en-têtes ou le corps. Inclut le support pour les définitions CRD de signatures et l'application aux groupes appropriés.
* Supprime les fonctionnalités de scan Serverless.

==== Corrections de bugs

* TBD

==== Autre

* Le chart Helm v1.8.9 est publié pour les déploiements 5.0.0. Si vous utilisez cela avec la version preview de 5.0.0, les modifications suivantes doivent être apportées à values.yml :
 ** Mettre à jour le registre vers docker.io
 ** Mettre à jour les noms/étiquettes d'image vers la version preview sur Docker hub
 ** Laissez les imagePullSecrets vides
