= Contrôle de l'air {product-name}
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /02.deploying/09.airgap/09.airgap.md
:page-opendocs-slug: /déploiement/airgap

== Outils nécessaires

Nous devons installer trois outils pour télécharger tous les bits pour {product-name}.

* https://helm.sh/[Helm] - Gestionnaire du cycle de vie des applications
* https://github.com/containers/skopeo[Skopeo] - Outil d'enregistrement d'images
* https://github.com/facebook/zstd[ZStandard] - Algorithme de compression

[,bash]
----
# install helm
curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# install skopeo - rocky linux based
yum install zstd skopeo -y
----

== Obtenir des images et des graphiques

Pour obtenir toutes les images, nous allons utiliser le graphique lui-même. En utilisant https://helm.sh/[Helm], ajoutons le repo et téléchargeons le graphique. Nous utiliserons également https://github.com/containers/skopeo[skopeo] pour le téléchargement et le chargement.

[,bash]
----
# make a directory
mkdir -p neuvector/images

# add repo
helm repo add neuvector https://neuvector.github.io/neuvector-helm/

# update local chart
helm repo update

# pull
helm pull neuvector/core -d neuvector
----

Vous devriez maintenant voir un fichier comme `+core-2.4.0.tgz+`. La version peut varier, mais elle est correcte. Voici le tableau téléchargé. Il nous faut maintenant les images. C'est une bonne chose que nous puissions utiliser le tableau pour résoudre ce problème.

[,bash]
----
# create image list
helm template neuvector/core-*.tgz | awk '$1 ~ /image:/ {print $2}' | sed -e 's/\"//g' > neuvector/images/list.txt

# get images
for i in $(cat neuvector/images/list.txt); do
  skopeo copy docker://$i docker-archive:neuvector/images/$(echo $i| awk -F/ '{print $3}'|sed 's/:/_/g').tar:$(echo $i| awk -F/ '{print $3}')
done
----

Fantastique, nous devrions avoir un répertoire qui ressemble à :

[,bash]
----
[root@flux ~]# ls -lR neuvector
neuvector:
total 16
-rw-r--r--. 1 root root 15892 Jan  8 14:33 core-2.4.0.tgz
drwxr-xr-x. 2 root root   153 Jan  8 14:35 images

neuvector/images:
total 953920
-rw-r--r--. 1 root root 236693504 Jan  8 14:35 controller_5.3.2.tar
-rw-r--r--. 1 root root 226704384 Jan  8 14:35 enforcer_5.3.2.tar
-rw-r--r--. 1 root root       176 Jan  8 14:34 list.txt
-rw-r--r--. 1 root root 331550208 Jan  8 14:35 manager_5.3.2.tar
-rw-r--r--. 1 root root 169589760 Jan  8 14:35 scanner_latest.tar
-rw-r--r--. 1 root root  12265472 Jan  8 14:35 updater_latest.tar
----

Et nous pouvons tout compresser et déplacer.

== Comprimer et déplacer

La compression est assez simple. Nous utiliserons `+tar+` avec le format ZST pour une compression maximale.

[,bash]
----
# compress
tar -I zstd -vcf neuvector_airgap.zst neuvector
----

Il suffit maintenant de déplacer le 400M `+neuvector_airgap.zst+` sur votre réseau.

== Décompresser et charger

Il ne nous reste plus qu'à décompresser à l'aide d'une commande similaire. Les données suivantes seront affichées dans un répertoire appelé `+neuvector+`.

[,bash]
----
tar -I zstd -vxf neuvector_airgap.zst
----

Le chargement des images dans un registre va nécessiter une compréhension de votre réseau interne. Pour ce document, nous utiliserons "registry.awesome.sauce" comme nom DNS. Le chargement des images est relativement simple avec `+skopeo+`. Veillez à ce qu'il soit installé sur la machine "intérieure". Vous devrez probablement vous authentifier avec `+skopeo login+` pour que cela fonctionne.

[,bash]
----
# skopeo load
export REGISTRY=registry.awesome.sauce
for file in $(ls neuvector/images | grep -v txt ); do
     skopeo copy docker-archive:neuvector/images/$file docker://$(echo $file | sed 's/.tar//g' | awk -F_ '{print "'$REGISTRY'/neuvector/"$1":"$2}')
done
----

Une fois toutes les images chargées dans un registre, nous pouvons procéder à l'installation avec Helm.

== Déployer avec Helm

Le déploiement avec Helm est assez simple. Quelques valeurs sont nécessaires pour s'assurer que les images proviennent du registre local. En voici un bon exemple. Il se peut que vous deviez modifier quelques paramètres. Veuillez suivre les meilleures pratiques de Helm pour `+values.yaml+`. Notez le champ `+imagePullSecrets+`. Il s'agit du secret permettant à votre cluster de s'authentifier auprès du registre.

[,bash]
----
# helm install example
# variables
export REGISTRY=registry.awesome.sauce  # registry URL
export NEU_URL=neuvector.awesome.sauce   # neuvector URL

# helm all the things -- read all the options being set
helm upgrade -i neuvector --namespace neuvector neuvector/core --create-namespace  --set imagePullSecrets=regsecret --set k3s.enabled=true --set k3s.runtimePath=/run/k3s/containerd/containerd.sock  --set manager.ingress.enabled=true --set controller.pvc.enabled=true --set controller.pvc.capacity=10Gi --set manager.svc.type=ClusterIP --set registry=$REGISTRY --set tag=5.3.2 --set controller.image.repository=neuvector/controller --set enforcer.image.repository=neuvector/enforcer --set manager.image.repository=neuvector/manager --set cve.updater.image.repository=neuvector/updater --set manager.ingress.host=$NEU_URL
----
