= Détails des variables d'environnement
:revdate: 2024-12-03
:page-revdate: {revdate}
:page-opendocs-origin: /02.deploying/01.production/03.details/03.details.md
:page-opendocs-slug: /déploiement/production/détails

== Variables d'environnement

=== Pour le contrôleur (Allinone) et l'agent d'exécution

* CLUSTER_JOIN_ADDR
+
____
Définissez la variable à l'adresse IP de l'hôte pour le premier contrôleur et définissez-la à l'adresse IP de l'hôte du contrôleur principal pour les autres contrôleurs et les agents d'exécution. Il n'est pas nécessaire de définir cette IP pour les déploiements basés sur Kubernetes, il suffit d'utiliser le fichier d'exemple.
____

* CLUSTER_LAN_PORT
+
____
(Facultatif) Port LAN du cluster Serf. Les ports TCP et UDP doivent être reliés directement à l'hôte. Facultatif s'il n'y a pas de conflit de port sur l'hôte. Défaut `+18301+`
____

* DOCKER_URL
+
____
(Facultatif) Si le moteur Docker sur l'hôte ne se lie pas sur le socket Unix normal, utilisez cette variable pour spécifier le point de connexion TCP, au format `+tcp://10.0.0.1:2376+`.
____

* NV_PLATFORM_INFO
+
____
(Facultatif) Utilisez la valeur platform=Docker pour les déploiements Docker Swarm/EE, ou platform=Kubernetes:GKE pour GKE (pour exécuter les tests CIS GKE).
____

* CUSTOM_CHECK_CONTROL
+
____
(Facultatif) Permet d'activer/désactiver la possibilité de créer des scripts de conformité personnalisés dans les conteneurs/hôtes. Les valeurs sont "disable" (par défaut, non autorisé), "strict" (rôle d'administrateur uniquement) ou "loose" (rôles d'administrateur, de conformité et de politique d'exécution).
____

* AUTO_PROFILE_COLLECT
+
____
(Facultatif) Attribuez la valeur 1 pour permettre la collecte de données sur le profil de la mémoire afin de faciliter l'analyse des problèmes de pression de la mémoire.
____

=== Contrôleur

* CTRL_PERSIST_CONFIG
+
____
(Facultatif) Pour sauvegarder les fichiers de configuration et les restaurer à partir d'un volume persistant. Ajoutez ceci au fichier yaml pour l'activer ; enlevez-le pour le désactiver.
____

* CLUSTER_RPC_PORT
+
____
(Facultatif) Port RPC du serveur de cluster. Doit être relié directement à l'hôte. La variable d'environnement est facultative s'il n'y a pas de conflit de port sur l'hôte. Défaut `+18300+`
____

* CTRL_SERVER_PORT
+
____
(Facultatif) Port HTTPS sur lequel le serveur REST doit écouter. La valeur par défaut est `+10443+`. Normalement, il peut être laissé par défaut et utiliser l'option docker port pour mapper le port sur l'hôte.
____

* DISABLE_PACKET_CAPTURE
+
____
(Facultatif) Ajoutez ceci au fichier yaml pour désactiver la capture de paquets ; enlevez ceci pour réactiver (par défaut).
____

* NO_DEFAULT_ADMIN
+
____
(Facultatif) Lorsque cette option est activée, elle ne crée pas d'utilisateur "admin" dans le cluster local. Il est utilisé par défaut pour l'intégration SSO de Rancher. Si cette option n'est pas activée, un avertissement persistant est envoyé à l'utilisateur et des événements sont enregistrés afin qu'il modifie le mot de passe administrateur par défaut s'il n'est pas modifié.
____

* CTRL_EN_ICMP_POLICY
+
____
(Facultatif) Lorsque cette option est activée (valeur=1), le trafic icmp peut être appris en mode découverte et une politique peut être générée. S'il n'y a pas de politique de réseau en mode surveillance ou protection pour le groupe, une violation implicite sera générée pour le trafic icmp.
____

=== Gestionnaire

* CTRL_SERVER_IP
+
____
(Facultatif pour le tout-en-un) Adresse IP du serveur REST du contrôleur. La valeur par défaut est `+127.0.0.1+`. Pour les conteneurs tout-en-un, laisser la valeur par défaut. Si le gestionnaire fonctionne séparément, il doit spécifier cette adresse IP pour se connecter au contrôleur.
____

* CTRL_SERVER_PORT
+
____
(Facultatif pour le tout-en-un) Port du serveur REST du contrôleur. La valeur par défaut est `+10443+`. Pour les conteneurs tout-en-un, laisser la valeur par défaut. Si le gestionnaire fonctionne séparément, il doit spécifier cette variable pour se connecter au contrôleur.
____

* MANAGER_SERVER_PORT
+
____
(Facultatif) Port de l'interface utilisateur du gestionnaire. La valeur par défaut est `+8443+`. Sauf si le Manager fonctionne en mode hôte, laissez-le et utilisez l'option docker port pour mapper le port sur l'hôte.
____

* MANAGER_SSL
+
____
(Facultatif) Le gestionnaire utilise par défaut une connexion HTTPS/SSL. Réglez la valeur sur &quot;`+off+`&quot; pour utiliser HTTP.
____
+
[IMPORTANT]
====
Cette variable d'environnement ne concerne que le produit autonome NeuVector. Veuillez mettre la variable à "on" si vous utilisez Rancher SSO ou laissez la variable à "on" car NeuVector utilisera HTTPS par défaut.
====

=== Enforcer

* CONTAINER_NET_TYPE
+
____
(Facultatif) Pour prendre en charge un plug-in réseau spécial, définissez la valeur à "macvlan`"
____

* ENF_NO_SECRET_SCANS
+
____
(Facultatif) Définissez la valeur sur &quot;`+1+`&quot; pour désactiver la recherche de secrets dans les fichiers (ce qui améliore les performances).
____

* ENF_NO_AUTO_BENCHMARK
+
____
(Facultatif) Définissez la valeur sur &quot;`+1+`&quot; pour désactiver les tests CIS sur l'hôte et les conteneurs (amélioration des performances).
____

* ENF_NO_SYSTEM_PROFILES
+
____
(Facultatif) Réglez la valeur sur "1" pour désactiver les moniteurs de processus et de fichiers. Aucun processus d'apprentissage, aucun mode de profil, aucun incident de processus/fichier (paquet) et aucun contrôle de l'activité des fichiers ne sera effectué. Cela permettra de réduire l'utilisation des ressources de l'unité centrale et de la mémoire, ainsi que les opérations sur les fichiers.
____

* ENF_NETPOLICY_PULL_INTERVAL
+
____
(Facultatif) Valeur en secondes (valeur recommandée : 60) pour réduire le trafic réseau et la consommation de ressources par Enforcer en raison des mises à jour/recalculs de politiques, dans les clusters avec un nombre élevé de nœuds ou de charges de travail. La valeur par défaut est zéro, ce qui signifie qu'il n'y a pas de retard dans la mise à jour de la politique de l'Enforcer.
____

* THRT_SSL_TLS_1DOT0
+
____
(Facultatif) Définissez la valeur sur &quot;`+1+`&quot; pour activer la détection de TLS Version 1.0 (Deprecated).
____

* THRT_SSL_TLS_1DOT1
+
____
(Facultatif) Définissez la valeur sur &quot;`+1+`&quot; pour activer la détection de TLS Version 1.1 (Deprecated).
____

* NV_SYSTEM_GROUPS
+
____
(Facultatif) Indiquez les groupes ou les espaces de noms que {product-name} considère comme des "conteneurs système", en les séparant par des points-virgules. Par exemple, pour les applications basées sur Rancher et l'espace de noms par défaut, NV_SYSTEM_GROUPS=cattle-system__;__default. Ces valeurs sont traduites en regex. Les conteneurs système (qui comprennent également les conteneurs système {product-name} et Kubernetes) fonctionnent uniquement en mode Monitor (alerte uniquement), même si le groupe est configuré en mode Protect.
____

== Ports ouverts

* CLUSTER_RPC_PORT - sur le contrôleur et le tout-en-un. Valeur par défaut : 18300.
* CLUSTER_LAN_PORT - sur le contrôleur, l'exécuteur et le tout-en-un. Défaut 18301.
* MANAGER_SERVER_PORT - sur le gestionnaire ou le tout-en-un. Défaut 8443.
* CTRL_SERVER_PORT - sur le contrôleur. Défaut 10443.

Veuillez consulter la section xref:installation.adoc[Préparation du déploiement] pour une description complète des exigences en matière de communication portuaire pour les conteneurs {product-name}.
