= 5.x Notes de mise à jour
:revdate: 2025-08-26
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/01.5x/01.5x.md
:page-opendocs-slug:  /releasenotes/5x

== Notes de mise à jour pour la version 5.x

[NOTE]
====
Pour recevoir des notifications par courrier électronique concernant les nouvelles versions, veuillez vous inscrire à la liste de diffusion de SUSE : https://lists.suse.com/mailman/listinfo/neuvector-updates
====

=== 5.4.6 Août 2025

==== Nouvelles fonctionnalités

* *NVSHAS-6733*: Exporter les règles de réponse en tant que CRD.
* *NVSHAS-9899*: Les alertes du profil de processus NeuVector pour les services Java contiennent des données sensibles.
* *NVSHAS-9990*: Adopter un nouvel algorithme de hachage pour les mots de passe des utilisateurs.
* *NVSHAS-9968*: Prise en charge de la définition du mot de passe par défaut du compte administrateur.

==== Bugs corrigés

* *NVSHAS-10062*: Le gestionnaire n'affiche pas d'ERREUR lorsqu'il ne parvient pas à créer le mot de passe administrateur lors de la première connexion.
* *NVSHAS-10041*: L'opération de fédération a échoué "données non valides" lors de la configuration de la fédération via ConfigMap.
* *NVSHAS-10018*: Neuvector n'analyse pas toutes les images du GitLab Registry.
* *NVSHAS-10017*: Alerte de sécurité faussement positive liée à un processus autorisé.
* *NVSHAS-10001*: Les mesures de protection/surveillance "perdurent" après la suppression du groupe.
* *NVSHAS-9985*:    NeuVector (Fed Master) crée un problème pour toutes les demandes provenant de l'extérieur.
* *NVSHAS-9981*:    L'événement de sécurité est déclenché chaque fois qu'une nouvelle "règle de profil de processus" est ajoutée ou modifiée dans un groupe.

==== Avis de sécurité

* https://github.com/neuvector/neuvector/security/advisories/GHSA-8pxw-9c75-6w56[Le mot de passe par défaut du compte administrateur n'est pas sûr]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-8ff6-pc43-jwv3[Une gestion des mots de passe non sécurisée est vulnérable aux attaques de l'arc-en-ciel]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-w54x-xfxg-4gxq[Les processus comportant des arguments sensibles entraînent des fuites]

Voir l'xref:cve.adoc[avis de sécurité et la] documentation sur les xref:cve.adoc[CVE] pour plus d'informations.

=== 5.4.5 Juillet 2025

==== Nouvelles fonctionnalités

* *NVSHAS-9776*: Ajouter la tolérance etcd dans le tableau de bord.

==== Corrections de bugs

* *NVSHAS-9507*: Le conteneur OCI n'est pas scanné.
* *NVSHAS-9787*: Supprimer le journal du gestionnaire inutile.
* *NVSHAS-9788*: Affiner l'algorithme de génération de certificats.
* *NVSHAS-9789*: Suppression de la configuration inutile du registre des gestionnaires à distance.
* *NVSHAS-9867*: NeuVector montre que `+.NET Library System.Formats.Asn1 v8.013+` est affecté par la CVE 2024-38095.
* *NVSHAS-9883*: [quay.io] Les filtres Wildcard ne fonctionnent pas pour le registre Docker.
* *NVSHAS-9911*: L'analyse du répertoire à l'aide de l'API REST produit un "message" incorrect.
* *NVSHAS-9930*: CVE-2018-20796 pour `+glibc/libc-bin : 2.36-9+deb12u10+` - Faux positif.
* *NVSHAS-9933*: La fonction d'adaptateur de registre (Harbor) affiche des erreurs dans le registre cible lors de l'analyse.
* *NVSHAS-9934*: Dysfonctionnement suspecté de la fonctionnalité de dérive zéro.
* *NVSHAS-9940*: NV scan JFrog Problème de mode de sous-domaine.
* *NVSHAS-9942*: Les scans d'images des clients échouent.
* *NVSHAS-9945*: Lorsque le nom du processus est trop long, il est difficile de déterminer comment créer la règle de profil de processus appropriée.
* *NVSHAS-9946*: Problème d'affichage de l'alerte de contrôle d'admission pour le type de justificatif.
* *NVSHAS-9947*: [UI-ext] Le statut "manuel" du tableau de conformité est manquant dans Rancher NeuVector.
* *NVSHAS-9948*: Après la mise à jour vers `+5.4.3+`, la configuration de NeuVector a été perdue.
* *NVSHAS-9949*: [Harbor][Incorrect user/pw] Il numérise toujours les images même en cas de saisie incorrecte de l'utilisateur/pw.
* *NVSHAS-9952*: Supprimer "signature" du rapport d'utilisation car NV n'émet ni ne vérifie plus la clé de licence.
* *NVSHAS-9953*: Pods Enforcer ne cesse de redémarrer.
* *NVSHAS-9954*: L'exportateur Prometheus de NeuVector génère des métriques dupliquées.
* *NVSHAS-9958*: L'application des règles du réseau prend beaucoup de temps.
* *NVSHAS-9960*: Les scanners ne fonctionnent pas.
* *NVSHAS-9969*: Erreur fatale : l'écriture simultanée de cartes entraîne le redémarrage du composant Enforcer.
* *NVSHAS-9971*: NV UI sur `+Get Bootstrap Password+`.
* *NVSHAS-9975*: [Manager] TypeError : `+this.mousemoveListener+` n'est pas une fonction observée dans l'interface graphique NV.
* *NVSHAS-9986*: Les règles d'accès aux processus et aux fichiers ne peuvent pas être modifiées ou supprimées dans la vue du groupe de stratégies fédérées.
* *NVSHAS-9988*: UI : Les pages des groupes n'affichent pas tous les groupes lorsque plus de 2 000 groupes sont présents.
* *NVSHAS-9991*: Le groupe `+nv.gatekeeper-controller-manager.openshift-azure-guardrails+` est absent de l'interface utilisateur.
* *NVSHAS-9993*: Remplacer MD5 par SHA256.
* *NVSHAS-9994*: Le pod Enforcer ne cesse de redémarrer.
* *NVSHAS-9996*: Le tableau de bord doit permettre le mode non privilégié des pods Enforcer.
* *NVSHAS-9998*: Impossible d'exporter un groupe à partir du maître fédéré de NeuVector.
* *NVSHAS-10000*: Mettre à jour NV vers BCI 15.7.
* *NVSHAS-10003*: Le rechargement de la page ne fonctionne pas sur une page NV autonome lorsque l'interface utilisateur de Rancher est ouverte.
* *NVSHAS-10008*: Numérisation du registre - Le menu d'affichage n'est pas disponible pour les images numérisées.
* *NVSHAS-10010*: L'inondation TCP SYN bloque l'entrée, ce qui entraîne un blocage total du trafic d'entrée.

=== 5.4.4 Mai 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9915**: Afficher les résultats du scanner Harbor dans l'interface utilisateur de NeuVector.
* **NVSHAS-9904**: Exposer `+imagePullPolicy+` à `+values.yaml+` pour chaque composant.
* **NVSHAS-9869**: UI : Déplacez les contrôles DDoS dans le volet Groupe.
* **NVSHAS-9840**: [GCP] Prise en charge du pilote automatique NeuVector pour GCP.
* **NVSHAS-9248**: Afficher les règles de processus/réseau inutilisées avec les compteurs et l'horodatage `+Last Used+`.
* **NVSHAS-8160**: [Contrôleur] Ajuster certains éléments pour le calcul du score de risque de sécurité.
* **NVSHAS-4673**: Suggestion d'ajouter un message avant d'exporter les groupes.

==== Corrections de bugs

* **NVSHAS-9931**: Ajout d'un avertissement en cas de versions incohérentes des produits NeuVector dans un cluster multiple.
* **NVSHAS-9925**: `+/v1/scan/asset/images+` sur la page du registre échoue.
* **NVSHAS-9913**: Problème avec la suppression de plusieurs règles de réseau liées aux groupes Workload:XYZ.
* **NVSHAS-9912**: Mise à jour de Helm concernant certaines permissions RBAC de K8s nécessaires au compte de service du contrôleur.
* **NVSHAS-9909**: Le message "Signed Out - Go to loading page" s'affiche lors de l'utilisation de NeuVector Rancher NavLink.
* **NVSHAS-9898**: Dans un environnement fédéré, la modification des critères d'un groupe fed.* créé par le client (par exemple fed.core-systems) ne fonctionne pas.
* **NVSHAS-9894**: [Enforcer] `+Nv.protect+` denies controller readiness probe command `+cat /tmp/ready+`.
* **NVSHAS-9886**: L'activité du réseau ne résout pas les noms de domaine pour les connexions des groupes externes personnalisés.
* **NVSHAS-9884**: [Node Scan][Container Scan] Échec de l'analyse.
* **NVSHAS-9873**: Problème de recherche dans le filtre avancé de l'interface utilisateur dans NeuVector 5.4.2.
* **NVSHAS-9865**: Les politiques de réseau exportées diffèrent selon l'ordre de sélection (mêmes groupes sélectionnés).
* **NVSHAS-9828**: [Enforcer : process] L'Enforcer NeuVector n'est pas en mesure de détecter les pods à courte durée de vie (moins de 5 secondes).
* **NVSHAS-9783**: Après avoir ajouté la politique de réseau pour refuser les paquets icmp, NeuVector ne voit pas d'alertes dans `+Security Events+`.
* **NVSHAS-9176**: Afficher une erreur de script dans la page **Risques de sécurité > Vulnérabilités** si un utilisateur autorisé à jouer le rôle d'espace de noms `+rt_scan:w+` est connecté.

=== 5.4.3 Mars 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9793**: Autoriser les rôles Fed Global dans LDAP/userinitcfg lors du déploiement de NeuVector via le ConfigMap et le Secret.
* **NVSHAS-9764**: [RFE] Ajouter la prise en charge d'Azure pour la "Configuration du référentiel à distance".
* **NVSHAS-9759**: Ajouter les détails de la date dans le rapport d'entrée et d'exposition.
* **NVSHAS-9755**: Demande d'affichage des noms des variables d'environnement avec les valeurs dans les alertes pour les secrets.
* **NVSHAS-9748**: [Helm] Mise à jour de NeuVector Helm pour la prise en charge de la référence de nom pour les groupes communs dans CRD (NVSHAS0-4717).
* **NVSHAS-9426**: Ajouter le chemin d'accès du scanner au tableau de bord.
* **NVSHAS-9326**: NeuVector - Module scanner enfichable Harbor.
* **NVSHAS-9835**: Interface utilisateur permettant de désactiver l'analyse automatique des nœuds.
* **NVSHAS-7997**: Connecteur de scanner pour ghcr.io.
* **NVSHAS-7982**: Attribuer des capteurs WAF à partir du Federation Master.

==== Corrections de bugs

* **NVSHAS-9849**: Les agents d'exécution ne s'enregistrent pas auprès des contrôleurs.
* **NVSHAS-9847**: Les filtres Wildcard ne fonctionnent pas pour le registre Docker.
* **NVSHAS-9833**: La restauration de la configuration échoue dans les déploiements Rancher.
* **NVSHAS-9832**: Problème de création de règles de réseau à l'aide du groupe Workload.
* **NVSHAS-9821**: Le nom du processus ne correspond pas à la ligne de commande pour l'alerte de règle de profit de processus.
* **NVSHAS-9817**: La création de NvClusterSecurityRule CRD indique une création réussie, mais elle n'a pas été réellement créée en raison d'entrées de règles de processus dupliquées.
* **NVSHAS-9812**: NeuVector promet des métriques erronées.
* **NVSHAS-9811**: [Manager] Impossible d'accéder à l'interface graphique lors de l'utilisation d'un certificat personnalisé (CA) avec CA racine et CA intermédiaire sur le secret.
* **NVSHAS-9801**: Le mode FIPS + `+manager.env.ssl=false+` provoque une erreur du gestionnaire.
* **NVSHAS-9792**: Échec de la synchronisation des politiques de la fédération en raison d'une taille de corps supérieure à la taille maximale de Consul.
* **NVSHAS-9784**: NeuVector renvoyant 404 lors de la numérisation du référentiel d'images Jfrog.
* **NVSHAS-9783**: Après avoir ajouté la stratégie de réseau pour refuser les paquets icmp, l'utilisateur ne voit pas d'alerte dans "Security Events".
* **NVSHAS-9780**: NeuVector single sign on ne fonctionne pas avec Rancher NavLink.
* **NVSHAS-9777**: Webhook JSON avec des clés "level" dupliquées.
* **NVSHAS-9770**: Auto-Switch after Zero-Drift mode switches incorrect policy.
* **NVSHAS-9765**: L'accès aux fichiers n'est pas totalement bloqué en mode protection.
* **NVSHAS-9756**: Enforcer a atteint le maximum de CPU et a plusieurs alertes de pression de mémoire.
* **NVSHAS-9668**: Échec du test de conformité sur RKE2.
* **NVSHAS-9265**: Résultats incomplets et incorrects de l'analyse des vulnérabilités dans l'environnement PCI du PRE.
* **NVSHAS-9227**: L'analyse du registre reste bloquée au milieu du processus d'analyse et passe à l'état "inactif".
* **NVSHAS-9729**: Un comptage incorrect des vulnérabilités est observé lorsque plusieurs statefulset ayant le "même nom" dans les namespaces sont déployés dans un projet.
* **NVSHAS-9810**: Le contrôleur NeuVector ne répond pas et l'interface utilisateur n'est pas accessible.

=== 5.4.2 Janvier 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9726**: Le moniteur passe maintenant l'URL du proxy.
* **NVSHAS-9719**: Annonce le retrait des certificats intégrés.
* **NVSHAS-9715**: Prise en charge de la valeur de la carte Helm pour le réglage du port nodal sur le contrôleur et le gestionnaire.
* **NVSHAS-9710**: Inclure une colonne triable `+feed_rating+` dans l'onglet **Vulnérabilités**.
* **NVSHAS-9669**: Score de sécurité global via l'API REST.
* **NVSHAS-9590**: Possibilité de choisir le score de vulnérabilité pour tous les actifs.
* **NVSHAS-7555**: Inclure l'option "Rafraîchissement automatique" dans les événements de sécurité.

==== Corrections de bugs

* **NVSHAS-9662**: Logique incohérente de Role/RoleBinding dans la charte Helm 2.8.2.
* **NVSHAS-9652**: Différence observée dans le format syslog dans splunk.
* **NVSHAS-9649**: Le lien du conteneur produit un code de réponse 404 dans l'événement de sécurité.
* **NVSHAS-9613**: NeuVector Manager Pod Error / NeuVector Web UI Unavailable.
* **NVSHAS-9507**: Le conteneur OCI n'est pas scanné.
* **NVSHAS-9443**: La mise à niveau/l'installation via ArgoCD échoue car elle ne peut pas créer l'objet leases.coordination.k8s.io.
* **NVSHAS-9436**: Faux négatif possible de CVE contre CVE-2024-7347.
* **NVSHAS-8386**: Les clés privées et les certificats auto-signés sont toujours expédiés sous forme d'images multiples.
* **NVSHAS-9754**: [UI] Empêcher Rancher relate SSO utilisateur désactiver l'authentification de OpenShift ou RBAC de Rancher.
* **NVSHAS-9751**: [Protection de l'exécution] Monitor Mode + Zero Drift ne génère aucune alerte lorsqu'un processus enfant est exécuté.
* **NVSHAS-9721**: L'interface utilisateur doit afficher un message d'erreur approprié lorsque l'utilisateur saisit un nom de registre erroné.
* **NVSHAS-9696**: Indication incohérente de la couleur des actifs sur la page de vulnérabilité.
* **NVSHAS-9686**: Espace de noms codé en dur pour le certificat de l'adaptateur de registre dans le diagramme Neuvector Helm.
* **NVSHAS-9678**: Traces d'erreurs excessives après le changement de filtre.
* **NVSHAS-9670**: Directeur : Problème de guillemets doubles dans la réponse au texte en clair et problème de bibliothèque java non nommée dans l'exécution de sbt.
* **NVSHAS-9667**: La définition de la variable `+CTRL_PATH_DEBUG+` env à error dans le déploiement du contrôleur ne fonctionne pas.
* **NVSHAS-9665**: Règle d'accès aux fichiers : La suppression des règles prédéfinies produit une erreur "setRowData".
* **NVSHAS-9664**: Groupe de politiques : La suppression du script personnalisé produit "setRowData" TypeError.

[NOTE]
====
Les types par défaut de gestionnaire et de service d'adaptateur de registre ont été remplacés par ClusterIP.  Les utilisateurs ont toujours la possibilité d'outrepasser ce paramètre en remplaçant les adresses `+manager.svc.type+` et `+cve.adapter.svc.type+` si NodePort est préféré.
====

Dans la version 5.4.2 de NeuVector, la prise en charge des déploiements utilisant le certificat interne intégré a été supprimée. Le certificat trouvé à l'adresse `+/etc/neuvector/certs/internal+` dans les images du conteneur NeuVector 5.4.2 sera supprimé. Pour continuer à utiliser NeuVector, les utilisateurs doivent :

==== 5.4.2 Nouvelle installation :

===== Utilisation de la barre :

- Activer les drapeaux `+internal.autoGenerateCert+` et `+internal.autoRotateCert+` dans les cartes Helm (ils seront activés par défaut à partir de la version 5.4.2). Une méthode YAML est également disponible ci-dessous.

===== Utilisation de YAML :

- Fournir un xref:internal.adoc#_replacing_certificates_used_in_internal_communications_of_suse_security[certificat interne en utilisant les méthodes existantes].

==== Mise à jour des versions précédentes vers la version 5.4.2 :

Veuillez créer et configurer des certificats internes à partir du scanner pour le contrôleur, l'exécuteur et l'adaptateur de registre afin de réaliser une mise à jour continue sans perdre de données. Il est toujours recommandé de faire une sauvegarde de votre configuration avant de procéder à la mise à jour. 

Les étapes suivantes ne sont nécessaires que si votre déploiement utilise un fichier `+.yaml+`. La mise à niveau à l'aide de Helm ne nécessite pas ces étapes supplémentaires car les certificats internes sont créés par défaut à l'aide des drapeaux suivants : `+internal.autoGenerateCert+` et `+internal.autoRotateCert+`.

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/ca.cert" > ca.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.pem" > tls.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.key" > tls.key
----

[,shell]
----
kubectl create secret generic internal-cert -n neuvector  --from-file=tls.key --from-file=tls.crt --from-file=ca.crt
----

Exemple 5.4.2 yaml avec certificat interne configuré :*https://github.com/neuvector/manifests/blob/main/kubernetes/5.4.0/neuvector-k8s.yaml* 

Informations complémentaires sur les xref:internal.adoc[certificats internes].


Dans le cas d'une configuration PVC, les utilisateurs peuvent configurer un PVC existant dans la nouvelle installation pour restaurer une configuration.


**Note supplémentaire pour le scanner :**

Pour les utilisateurs actuels des versions antérieures à 5.4.2, le certificat restera disponible sur le site `+neuvector/scanner:latest+` jusqu'au 31 mars 2025. Après cette date, il sera supprimé. Les utilisateurs doivent prévoir de fournir le même certificat interne au contrôleur, à l'exécuteur, au scanner et à l'adaptateur de registre pour continuer à utiliser le scanner.

Veuillez noter que le scanner autonome ne sera pas affecté par ces changements.

=== 5.4.1 Novembre 2024

==== Nouvelles fonctionnalités

* **NVSHAS-8583**: Définition de modes de politique granulaire pour les ensembles de règles, mode de politique de réseau séparé et mode de profil au niveau de chaque groupe.
* **NVSHAS-9440**: Prise en charge d'un mode réseau distinct et d'un mode processus et fichier dans le CRD.
* **NVSHAS-9369**: Ajout d'une catégorie de journal de débogage via la prise en charge du déploiement de helm pour le contrôleur.
* **NVSHAS-9040**: Amélioration du message syslog lorsque la règle de contrôle d'admission est refusée en mode surveillance.

==== Corrections de bugs

* **NVSHAS-9416**: [Scanner] activemq-all-5.8.0.redhat-60024.jar ne peut PAS être détecté avec un vul (mais la version précédente du scanner le peut).
* **NVSHAS-9447**: Les pods du contrôleur/scanner se bloquent - "Unsupported system Exit" (sortie de système non prise en charge).
* **NVSHAS-9278**: CVE-2024-41110 est trouvé dans la dernière image du scanner.
* **NVSHAS-9467**: Le groupe personnalisé défini par l'étiquette du pod ne propage pas ses données de profil sur les conteneurs enfants.
* **NVSHAS-9442**: Problème de déploiement sur ArgoCD.
* **NVSHAS-9436**: Faux négatif possible de CVE contre CVE-2024-7347.
* **NVSHAS-9468**: Correction de CVE-2020-26160 pour remplacer jwt-go par jwt:v5.
* **NVSHAS-9517**: Le contrôle d'admission n'est pas cohérent, ce qui entraîne des résultats incorrects.
* **NVSHAS-9532**: L'analyse de l'image est terminée, mais le déploiement n'est toujours pas autorisé.
* **NVSHAS-9558**: Rapports d'expiration du jeton JWT http.StatusRequestTimeout 408.
* **NVSHAS-9576**: Effacer le champ du mot de passe pour les données du registre lorsque l'utilisateur utilise le mode contrôleur avec Jenkins pour numériser.
* **NVSHAS-9425**: Créer un nfq lorsque le conteneur a un vxlan.
* **NVSHAS-9571**: [Registres] Le filtre pour toutes les images numérisées ne fonctionne pas correctement.
* **NVSHAS-9589**: Clusters gérés déconnectés - Mauvaise version du cluster primaire.
* **NVSHAS-8824**: L'utilisateur ne parvient pas à supprimer ses propres groupes et ne peut pas créer de groupes dans l'espace de noms.
* **NVSHAS-9605**: Un groupe d'exportation avec des valeurs invalides de mode de stratégie et de mode de profil de processus est autorisé par erreur.
* **NVSHAS-9608**: Le scanner ne signale aucune erreur alors que le contrôleur signale une erreur pour des résultats d'analyse trop importants (~23MB).
* **NVSHAS-9534**: Erreur d'affichage dans les contrôles d'admission.
* **NVSHAS-9600**: Impossible de désactiver le débogage du contrôleur.
* **NVSHAS-9631**: Réduire certaines erreurs de l'exécuteur.
* **NVSHAS-9645**: Échec du traitement du dossier CRD préexistant.
* **NVSHAS-9592**: Pas de nouvelle analyse malgré la nouvelle version de la base de données.
* **NVSHAS-9212**: Affichage d'un message d'alerte dans GET(/v1/eula) si le rôle neuvector-binding-secret est incorrect.
* **NVSHAS-9367**: Amélioration des messages d'erreur lorsque le registre ne parvient pas à se connecter.
* **NVSHAS-9475**: L'impression de la grille d'arrière-plan n'est pas entièrement couverte lorsque le menu est réduit.
* **NVSHAS-9485**: Message incorrect pour 'Network Security Policy Mode' dans l'interface utilisateur.
* **NVSHAS-9480**: L'interface utilisateur NV déployée sur le cluster aval de Rancher envoie un message HTTP/403 après la déconnexion de Rancher.
* **NVSHAS-9547**: Le tri est interrompu dans le tableau des risques de sécurité --> vulnérabilités.
* **NVSHAS-9570**: [Vulnérabilités] Modifier la description de la légende pour les différents statuts des actifs.
* **NVSHAS-9561**: Le score global de sécurité du tableau de bord doit correspondre au score réel.
* **NVSHAS-9572**: [Vulnérabilités] Les données filtrées étaient conservées même si l'utilisateur rafraîchissait la page ou s'y reconnectait.
* **NVSHAS-9597**: L'interface utilisateur ne répond à aucune erreur lorsque le contrôleur renvoie 403 pour POST(v1/group).
* **NVSHAS-8682**: Le service webhook de CRD doit être déplacé du tableau de bord crd au tableau de bord de l'application.

==== Problèmes connus

* Dans la version 2.8.3, nous avons déplacé une ressource précédemment mal allouée de crds à core. Si vous utilisez à la fois des cartes crds et des cartes core, vous risquez de rencontrer des problèmes lors de la mise à jour si vous déployez d'abord les cartes core. Pour résoudre ce problème, mettez d'abord à jour les crds, puis les core charts.

=== 5,4 septembre 2024

* **Amélioration de l'interface utilisateur**: 
** Afficher les utilisateurs SSO de Rancher.
** Gérer les jetons JWT.
** Amélioration de la navigation dans les images et des liens vers les résultats de l'analyse.
* **Renforcement de la sécurité**: 
** Nouveaux filtres de conformité.
** Prise en charge des critères de référence CIS et de la signature des images OCI.
* **Réseau et surveillance**: 
** Suivi avancé de la bande passante et de la session.
** Surveillance DDoS.
** Prise en charge de plusieurs réseaux.
* **Gestion des cercles**: 
** Nouvelles notifications pour les certificats internes arrivant à expiration, y compris les possibilités de rotation.
* **Automatisation et intégration**: 
** Automatisation de la fédération.
** Intégration du système RBAC de Rancher.
** Contrôle d'admission amélioré.
* **Performance et efficacité**: 
** Réduction de l'utilisation de la mémoire.
** Réduction des frais de transmission de données par les FAI.
** Exposition des statistiques du cache du scanner.
* **Amélioration de la convivialité**: 
** Prise en charge du mot de passe Bootstrap.
** Archivage des données de facturation dans le nuage.
** Respect des limites de l'espace de nommage.

==== Nouvelles fonctionnalités

* **NVSHAS-9012**: Affichage des utilisateurs Rancher SSO sur l'interface NV qui ont le même nom d'utilisateur.
* **NVSHAS-8939**: Fournir une option sur l'interface utilisateur NV pour que les utilisateurs de la session SSO Rancher puissent abandonner le jeton JWT actuel (c'est-à-dire se déconnecter).
* **NVSHAS-7522**: Navigation aisée des images dans les registres.
* **NVSHAS-8148**: Lien entre l'image du conteneur et les résultats de l'analyse de l'image du registre.
* **NVSHAS-9258**: Ajout d'une nouvelle notification pour les certificats expirant et les certificats internes.
* **NVSHAS-8915**: Prise en charge des nouveaux filtres de conformité et du rapport de conformité.
* **NVSHAS-9403**: Filemonitor-UI : Permet à l'utilisateur de supprimer une règle prédéfinie de surveillance des fichiers.
* **NVSHAS-8423**: Détecter la bande passante au niveau du groupe, le nombre de sessions actives et la violation du débit de session en fonction des seuils configurés.
* **NVSHAS-9218**: Prise en charge des groupes fédéraux et CRD pour la surveillance DDoS.
* **NVSHAS-8461**: Soutenir les critères de référence de la CEI pour les services k8s gérés dans le nuage.
* **NVSHAS-7664**: Réduire les frais de données des FAI lors de l'analyse du registre.
* **NVSHAS-8868**: Afficher les statistiques du cache du scanner.
* **NVSHAS-8676**: Amélioration de NV Protect pour les scripts de référence.
* **NVSHAS-9255**: Personnaliser les registres de recherche du contrôle d'admission pour les noms d'images sans FQDN.
* **NVSHAS-9144**: Un identifiant a été ajouté au profil de vulnérabilité pour faciliter l'identification.
* **NVSHAS-7687**: Prise en charge de la configuration du niveau de journalisation (debug/error/info/warn) pour l'exécuteur et le contrôleur à partir de l'interface de ligne de commande.
* **NVSHAS-7518**: Modifier les certificats internes pour les composants {product-name}.
* **NVSHAS-9287**: Permettre la rotation interne de la jambe.
* **NVSHAS-8562**: Ajout d'une notification interne d'expiration de certificat.
* **NVSHAS-8486**: Prise en charge de l'interface réseau Multus.
* **NVSHAS-7447**: Intégration de Rancher RBAC avec {product-name}.
* **NVSHAS-7822**: Automatisation de la fédération sans appel à l'API.
* **NVSHAS-8799**: Créer un cadre de conformité pour importer des modèles de conformité.
* **NVSHAS-8773**: Prise en charge du mot de passe de démarrage lors du déploiement initial.
* **NVSHAS-6740**: Amélioration du profil de référence à dérive nulle par l'application de la liste apprise en mode protection.
* **NVSHAS-8325**: Appliquer la limite de l'espace de noms du conteneur pour la règle de réseau.
* **NVSHAS-8723**: Archiver les données de facturation du cloud.
* **NVSHAS-9086**: Réduire l'utilisation de la mémoire du contrôleur en éliminant la structure de données vulTrait.
* **NVSHAS-6979**: Possibilité d'inclure le commentaire de la règle de réponse dans le contenu de l'alerte.
* **NVSHAS-8845**: Créer un APIKEY avec le rôle FedReader et FedAdmin.
* **NVSHAS-9306**: L'évaluation de la configuration du contrôle d'admission montre l'ID de la règle responsable des déploiements autorisés ou refusés.
* **NVSHAS-9078**: Prise en charge de la signature des images OCI.
* **NVSHAS-7945**: Prise en charge du benchmark DISA STIG pour Kubernetes.
* **NVSHAS-8234**: Contrôle d'admission Logique autorisant des images qui devraient être refusées.

==== Corrections de bugs

* **NVSHAS-9005**: TypeError in registries : Impossible de lire les propriétés d'une valeur indéfinie (lecture de 'total_records').
* **NVSHAS-9085**: Le rapport PDF "Assets View" montre une vulnérabilité de 0% même avec les vulnérabilités présentes.
* **NVSHAS-9084**: Le rapport PDF de Assets View affiche NaN lorsque la liste des images est vide.
* **NVSHAS-9128**: Événements liés à la sécurité : Le conteneur ne peut pas être affiché s'il n'y a pas de valeur d'espace de noms de la charge de travail.
* **NVSHAS-9025**: Champ d'application de l'acceptation de la vulnérabilité Neuvector pour les conteneurs.
* **NVSHAS-9155**: Image de numérisation du registre : nom de colonne incorrect et nom de fichier manquant
* **NVSHAS-9122**: Le Neuvector master se déconnecte à tout moment lors de l'utilisation de "Multiple Cluster" avec le login SSO de Rancher.
* **NVSHAS-9266**: Analyse du registre : Le bouton "Scan Report by Layer" devrait être caché ou désactivé lorsqu'il n'y a pas de vulnérabilité.
* **NVSHAS-9219**: Permet aux utilisateurs d'activer la validation des certificats de serveur pour les serveurs d'authentification.
* **NVSHAS-9246**: Le filtrage pour l'exportation CSV/PDF ne fonctionne pas.
* **NVSHAS-8947**: Impossible d'importer la configuration NV lorsque l'on est authentifié via Rancher SSO.
* **NVSHAS-9282**: UI : L'édition de l'entrée du registre OpenShift échoue en raison d'un jeton manquant.
* **NVSHAS-9098**: Améliorer l'expérience des utilisateurs lors du chargement des pages à risque.
* **NVSHAS-9267**: Ne pas autoriser l'interface utilisateur sur le cluster maître 5.4 à basculer vers des clusters gérés antérieurs à la version 5.4 en raison des modifications apportées à l'API REST.
* **NVSHAS-9285**: UI : Le bouton de la liste déroulante se superpose à d'autres éléments.
* **NVSHAS-9302**: Impossible de créer un APIKEY avec le rôle FedReader et FedAdmin.
* **NVSHAS-8539**: Reconfigurer la configuration du proxy perd le mot de passe.
* **NVSHAS-9293**: Suppression des détails de l'image sans rapport avec le sujet dans les rapports de vulnérabilité.
* **NVSHAS-9238**: L'interface utilisateur ne rafraîchit pas le nom du cluster affiché après qu'il ait été modifié.
* **NVSHAS-9363**: La grille Notification Configuration > Webhooks n'est pas correctement alignée.
* **NVSHAS-9362**: Le filtre Security Risk Vulnerabilities renvoie 0 résultat.
* **NVSHAS-8699**: Impossible de distinguer l'utilisateur si l'utilisateur AD de Rancher est le même.
* **NVSHAS-9062**: Affichage des utilisateurs Rancher SSO sur l'interface NV qui ont le même nom d'utilisateur (Conversion sur le contrôleur).
* **NVSHAS-9071**: Certains modules ne sont pas signalés dans l'analyse des conteneurs uniquement.
* **NVSHAS-8242**: appel gRPC pour tester si le contrôleur gère la gravité critique.
* **NVSHAS-8908**: L'analyse de X-Forwarded-Port prend correctement en compte le séparateur de virgules.
* **NVSHAS-9024**: AdmissionControl Risky Role Perf.
* **NVSHAS-9091**: Impossible de signaler tous les modules sous ol:9.1, photon:5.0, rhel:9.1, et amzn:2023 source dans le repo, le registre, et l'analyse autonome.
* **NVSHAS-8997**: Réduire considérablement le nombre de créneaux par nœud pour améliorer les performances.
* **NVSHAS-9059**: Les groupes CRD sont visibles dans les NV même après suppression des K8.
* **NVSHAS-9107**: Crash de la goroutine au niveau de rest.handlerConfigLocalCluster.
* **NVSHAS-9108**: Le port 18500 ne devrait pas être ouvert.
* **NVSHAS-9119**: Crash de la goroutine au niveau de probe.(*FileNotificationCtr).AddContainer().
* **NVSHAS-9125**: La création d'une entrée CRD dont les paramètres ne sont pas valides ne doit pas être autorisée.
* **NVSHAS-9124**: Docker : de nombreux incidents inattendus liés au processus de vérification de la santé sont signalés.
* **NVSHAS-9111**: NV devrait consulter `+--event-qps > 0+`.
* **NVSHAS-9130**: Des incidents Container.Package.Updated inattendus sont constatés après le démarrage d'un conteneur spécifique.
* **NVSHAS-9080**: L'utilisateur du lecteur Fed ne peut pas accéder à certaines API REST.
* **NVSHAS-9092**: L'utilisateur d'un espace nominatif ne doit pas voir les actifs globaux.
* **NVSHAS-9116**: La grappe de travailleurs peut quitter le site si la connexion est interrompue.
* **NVSHAS-8980**: Obtenir l'hôte et l'interface du tunnel sur le nœud avec succès dans l'oc 4.15.
* **NVSHAS-9188**: Définir l'interface mgmt-br comme interface hôte pour le nœud de moissonneur.
* **NVSHAS-4858**: Ne pas étendre le groupe de conteneurs dans le contrôleur afin d'améliorer les performances de déploiement des politiques et de réduire l'utilisation du processeur et de la mémoire.
* **NVSHAS-8700**: L'utilisateur AD de Rancher est parfois incapable de se connecter à {product-name}.
* **NVSHAS-9121**: Le réglage du seuil de surveillance du réseau du groupe ne peut pas être modifié.
* **NVSHAS-9189**: L'analyse reste bloquée dans la programmation après l'arrêt et le redémarrage du contrôleur.
* **NVSHAS-9019**: Correction de l'état des liens non synchronisés pour l'interface hôte.
* **NVSHAS-8305**: Supprimer le certificat intégré.
* **NVSHAS-9013**: Suppression du filtre BPF sur le moniteur de processus.
* **NVSHAS-7853**: EOF de la poignée de main TLS.
* **NVSHAS-9290**: La règle de profil de processus ajoutée par l'utilisateur ne prend pas effet lorsque la fonction ZD est activée.
* **NVSHAS-9301**: NV déployé sur Rancher Prime ne peut pas dire qu'il s'agit d'un arôme de Rancher.
* **NVSHAS-9289**: Autoriser la mise à niveau en l'absence de RBAC.
* **NVSHAS-7601**: Amélioration de la restauration à partir d'une sauvegarde de la configuration de PV pendant les scénarios.
* **NVSHAS-7687**: Ajout d'un paramètre de niveau syslog pour enforcer.
* **NVSHAS-9292**: Correction de l'exposition des entrées et des sorties : 0 vulnérabilité.
* **NVSHAS-9270**: Prise en charge de k3s pour le pipeline de référence CIS.
* **NVSHAS-9338**: Alerte 'Managed cluster [id] is disconnected from primary'.
* **NVSHAS-9358**: La numérisation d'images à l'aide d'un proxy échouerait.
* **NVSHAS-9337**: Envoi d'un message de journal en cas de détection d'une inondation SYN.
* **NVSHAS-9209**: Supprimer le cache du domaine lorsque l'espace de noms est supprimé de k8s.
* **NVSHAS-8985**: Les registres fédérés disparaissent après le redémarrage du contrôleur.

==== Problème connu :

* **NVSHAS-9443**: La mise à niveau/l'installation via ArgoCD échoue car elle ne peut pas créer l'objet leases.coordination.k8s.io.
* **Solution de contournement**: Créer les objets de location donnés avant de passer à la version 5.4.0 à l'aide du CD ARGO. Modifier l'espace de noms s'il est différent de neuvector.
+
--
[,bash]
----
cat <<EOF | kubectl apply -f -
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-controller
  namespace: neuvector
spec:
  leaseTransitions: 0
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-cert-upgrader
  namespace: neuvector
spec:
  leaseTransitions: 0
EOF
----
--

=== 5.3.4 juillet 2024

==== Corrections de bugs

* Les interfaces `+host+` et `+tunnel+` sont récupérées avec succès avec OpenShift CLI v4.15.
* La plage d'adresses IP 169.254.x.x est exclue des adresses IP de l'interface hôte.
* Réexaminer l'interface de l'hôte après 1 minute de démarrage de l'enforcer.
* Correction d'un problème où la regex de l'URL de l'émetteur OpenID échouait.
* Remédie aux CVE suivants :
+
|===
| CVE | S'applique à | Impact

| CVE-2023-42364
| boîte à outils
| {CVE-medium}

| CVE-2023-42365
| boîte à outils
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.2.4-s5 Juillet 2024

* Remédie aux CVE suivants :

|===
| CVE | S'applique à | Impact

| CVE-2023-42363
| boîte à outils
| {CVE-medium}

| CVE-2023-42364
| boîte à outils
| {CVE-medium}

| CVE-2023-42365
| boîte à outils
| {CVE-medium}

| CVE-2023-42366
| boîte à outils
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4603
| openssl
| {CVE-medium}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.3.3 Juin 2024

==== Améliorations

* Permettre aux utilisateurs de bloquer l'utilisation de classes de stockage spécifiques à partir de la page `+Admission Controls+`.
* Le site `+LDAP Authentication+` comporte des champs séparés pour la configuration de `+baseDN+` et `+groupDN+`.
* Le site `+Egress and Ingress chart+` comporte une nouvelle colonne "vulnérabilité" qui contient le nombre de vulnérabilités `+High+` et `+Medium+` pour chaque service.

==== Corrections de bugs

* Correction d'un bug lié à `+regex+` lors de l'utilisation d'une virgule (`+,+`) dans une entrée multiple `+Admission Control user criteria+`.
* Correction d'un bogue à cause duquel l'analyse CVE des paquets `+jar+` ne montrait pas tous les paquets affectés par une même CVE. Désormais, toutes les occurrences sont signalées.
* Remédie aux CVE suivants :

|===
| CVE | S'applique à | Impact

| CVE-2024-35195
| python:requests
| {CVE-medium}

| CVE-2024-21011
| openjdk11
| {CVE-low}

| CVE-2024-21012
| openjdk11
| {CVE-low}

| CVE-2024-21068
| openjdk11
| {CVE-low}

| CVE-2024-21085
| openjdk11
| {CVE-low}

| CVE-2024-21094
| openjdk11
| {CVE-low}
|===

==== Autres

* Permettre aux utilisateurs de définir des ressources pour `+updater-cron-job+` lors de l'installation de {product-name} avec la carte Helm.
* La version du conteneur d'exportation Prometheus a été revue et dissociée de la version du site `+controller+`.
* (Scanner) Détecter le paquetage/module `+R+` dans Ubuntu et Red Hat Enterprise Linux.
* (Scanner) Ajout de la prise en charge du scan de PHP Composer.

=== 5.2.4-s3 Avril 2024

* Remédie aux CVE suivants :

|===
| CVE | S'applique à | Impact

| CVE-2021-40633
| giflib
| {CVE-high}

| CVE-2023-48161
| giflib
| {CVE-high}

| CVE-2024-28757
| expatrié
| {CVE-high}

| CVE-2023-39742
| giflib
| {CVE-medium}

| CVE-2023-45288
| go:golang.org/x/net
| {CVE-medium}

| CVE-2024-25629
| c-ares
| {CVE-medium}

| CVE-2024-3651
| python:idna
| {CVE-medium}

| CVE-2024-2511
| openssl
| {CVE-low}
|===

=== 5.3.2 Avril 2024

==== Corrections de bugs

* Après une mise à jour vers la version 5.3.1 à partir d'une version précédente de {product-name}, les ressources personnalisées NvClusterSecurityRule préexistantes peuvent être supprimées par inadvertance. NOTE : La version 5.3.1 a été supprimée de docker hub afin d'éviter le problème de mise à jour.

=== 5.3.1 Avril 2024

[IMPORTANT]
====
La version 5.3.1 a été retirée de docker hub afin d'éviter le problème de mise à jour corrigé dans la version 5.3.2. Veuillez utiliser la version 5.3.2.
====

==== Améliorations

* Permettre aux utilisateurs de définir &apos;`+accepted+`&apos; les vulnérabilités lors de l'utilisation des actions Github afin qu'elles n'affectent pas les flux de travail.
* Ajout de filtres de gravité, de niveau de score et d'évaluation des flux à la vue Actifs > Registre > Vulnérabilités des images.
* Permet, lors de la configuration d'un registre, d'utiliser le proxy défini pour l'analyse des images du registre.

==== Corrections de bugs

* Risques de sécurité > Vulnérabilités > Le filtre avancé ne filtre pas les "CVE sans correction".
* Violation inattendue d'un conteneur vers un conteneur en mode hôte
* Acceptation du format d'image OCI lors du passage à docker api 1.24
* L'analyse du registre ne doit pas analyser les artefacts qui ne sont pas des images / ne doit pas enregistrer d'erreur.
* Permettre la vérification de la signature d'images par paires de clés sans racine, sans dépendre de l'internet ou d'un sigstore.
* Les événements de sécurité ne sont pas autorisés par les règles de réseau dans un nœud spécifique (lié aux messages d'erreur "Container Task chan full").
* Le conteneur n'est pas en mesure d'ajouter à la charge de travail avec succès (occurrences fréquentes). Résultant d'un blocage des messages du canal.

==== Autres

* Mise à jour des plugins d'analyse pour Jenkins, GitHub action, et Bamboo.
* (Scanner) Acceptation du format d'image OCI lors du passage à docker api 1.24.
* (Scanner) Registry Scan ne devrait pas analyser les artefacts non imagés / ne pas enregistrer d'erreur.
* (Scanner) Ajout de la prise en charge de l'analyse du compositeur php.

==== {product-name} UI Extension v. 1.0 pour Rancher Mars 2024

* Après l'installation de {product-name}, l xref:rancher.adoc#_suse_security_ui_extension_for_rancher['activation/installation de] l'extension {product-name} UI de Rancher affichera un tableau de bord pour le cluster, y compris des liens pour SSO vers le cluster {product-name} complet. NOTE : L'extension peut s'afficher en tant que tierce partie, ce qui sera corrigé dans une prochaine version. De plus, après l'installation, les utilisateurs de Rancher 2.7.x peuvent voir deux icônes {product-name} UI Ext dans la liste (bug). L'une des icônes indiquera Désinstaller (ce qui signifie qu'il est installé), et l'autre devrait indiquer Installer. Ce point peut être laissé tel quel, c'est-à-dire qu'il ne faut pas réinstaller l'extension si elle est déjà installée.

=== 5.2.4-s2 Février 2024

* Remédie aux CVE suivants :
* Haute cve : CVE-2023-52425 dans expat, CVE-2024-20952 et CVE-2024-20918 dans openjdk11
* Med cve : CVE-2023-52426 dans expat, CVE-2024-20926, CVE-2024-20921, CVE-2024-20945 et CVE-2024-20919 dans openjdk11, CVE-2024-0727 et CVE-2023-6237 dans openssl.

=== 5.3.0 février 2024

==== Améliorations

* Afficher les URL de destination externes (FQDN) dans le tableau de bord (sortie), les rapports PDF et CSV, ainsi que dans l'écran Activité du réseau et les listes d'événements de sécurité (violations).
* En mode découverte, l'apprentissage des sorties vers les groupes d'adresses FQDN externes se fait automatiquement. Un nouveau groupe personnalisé FQDN externe sera créé à moins que la connexion externe ne corresponde à une règle existante.
* Activer l'apprentissage ICMP (mode découverte) et le blocage (mode protection) via la nouvelle variable d'environnement du contrôleur CTRL_EN_ICMP_POLICY = 1
* Exporter les CRDs dans Github pour supporter les gitops vers un repo par défaut en utilisant la console ou l'API REST.
* Prise en charge de la déconnexion unique SAML SSO avec ADFS iDP
* Ajout de la prise en charge de la plate-forme ARM64. L'extraction à partir de plateformes basées sur ARM se fera automatiquement avec les images ARM64 {product-name} appropriées.
* Prise en charge des webhooks par l'intermédiaire d'un proxy
* Améliorer la fonction d'audit du contrôle des admissions pour y inclure les résultats de toutes les règles. Liste le résultat de chaque règle et ajoute une autre entrée pour l'action finale qui se produirait si elle était évaluée dans le cadre d'un déploiement de contrôle d'admission en temps réel.
* Appliquer les règles de contrôle d'admission désactivées via CRD ou yaml (kubectl)
* Exportation/importation du profil de vulnérabilité via la console, le CRD ou l'API REST. L'importation remplacera le profil existant. La suppression du CRD entraîne la création d'un profil vide.
* Exportation/importation de modèles de profils de conformité via la console, le CRD ou l'API REST. L'importation remplacera le modèle existant.
* Ajouter un statut "Manuel" dans les rapports de conformité pour les critères de référence CIS qui doivent être exécutés manuellement par les utilisateurs (et non par {product-name}).
* Amélioration du chargement de l'interface utilisateur et des performances de la page "Vulnérabilités".
* Unifier la connexion à la session du navigateur. Ainsi, tous les onglets du navigateur partagent la même session de connexion, l'ouverture d'un nouvel onglet à partir d'une session existante ne demande pas d'informations d'identification, et lorsqu'un onglet se déconnecte, tous les onglets sont déconnectés.
* Amélioration de la sécurité de la console (UI) : 1) ajouter des en-têtes de sécurité obligatoires (X-Content-Type-Options nosniff ; X-XSS-Protection 1 ; mode=block ; X-Frame-Options SAMEORIGIN ; Cache-Control private, no-cache, no-store, must-revalidate HTTP Strict Transport Security max-age=15724800, 2) ajouter un en-tête CSP (par exemple, définir une directive &apos;`+default-src+`&apos; ), 3) supprimer la divulgation du nom du serveur.
* Prise en charge des nouvelles versions des critères de référence de l'ECI. Kubernetes (1.8.0), Kubernetes V1.24 (1.0.0), Kubernetes V1.23 (1.0.1), RedHat OpenShift Container Platform (1.4.0)
* Afficher dans Assets -> Containers -> les détails des conteneurs qui ont été analysés dans les registres par rapport à la durée d'exécution.
* Ajouter un lien vers le groupe dans la fenêtre contextuelle Risques de sécurité -> Vulnérabilités -> Impact pour modifier facilement le mode groupe
* Prise en charge des liens profonds dans les URL vers les images et/ou les pages de vulnérabilité des conteneurs
* Ajouter l'option de réinitialisation du mot de passe pour que l'administrateur puisse réinitialiser le mot de passe de l'utilisateur dans la console Paramètres -> Utilisateurs
* Autoriser l'envoi des journaux d'événements aux journaux de pods de contrôleurs dans Settings -> Configuration -> Notification. Les événements envoyés commencent par "notification=" et ne sont enregistrés que dans le pod du contrôleur principal. Notez qu'il y a un bogue dans cette version où, pour changer le niveau d'événement, SYSLOG doit être activé (et peut être désactivé si nécessaire après avoir changé le niveau).
* Suppression de l'obligation pour le contrôleur/enforcer de monter "/host/cgroup".
* Ajout d'un menu "Obtenir de l'aide" avec des liens vers Slack, la documentation et d'autres ressources.
* Remplir le champ message dans /v1/log/activity logs

==== Corrections de bugs

* Internal Server Error in Security Risks -> Vulnérabilités avec un nombre élevé de CVEs
* SIGSEGV : violation de segmentation sur le contrôleur
* La suppression de fichiers vulnérables (par exemple jar) ne supprime pas la liste des vulnérabilités.
* Certificat Syslog non valide utilisant l'algorithme de signature SHA256withECDSA
* {product-name} indique les événements de sécurité qui doivent être autorisés par une règle de réseau
* Nœud non géré avec un enforcer "zombie" en cours d'exécution
* Le filtre avancé montre que les champs Remédiation et Impact sont vides.
* Correction de la gestion des chaînes de caractères pour éviter un redémarrage inattendu de l'Enforcer
* Violations inattendues relatives aux groupes intégrés
* Support-bundle enforcer debug RPC call for data returns error (appel RPC pour les données)
* Le groupe ne correspond pas aux événements de sécurité
* L'envoi d'événements vers Slack ne fonctionne pas - avec proxy
* Affichage des événements de sécurité pour les règles de réseau autorisées

==== Autres

* Ajout de la détection automatique du moteur de conteneurs (socket) au tableau de bord Helm
* Suppression du paramètre d'exécution du contrôleur en mode privilégié dans le tableau Helm, et de l'obligation pour le contrôleur/enforcer de monter "/host/cgroup".
* Les exemples de fichiers de déploiement kubernetes ont été supprimés de la documentation {product-name}. Vous trouverez des exemples en cliquant sur le lien.

==== Changements mis en évidence qui peuvent nécessiter des changements pour les déploiements manuels (tous les changements sont déjà reflétés dans le dernier tableau Helm pour 5.3.x)

* La détection automatique de l'exécution du conteneur (socket) supprime la nécessité de spécifier l'exécution du conteneur et le chemin du socket.
* La suppression de l'obligation d'exécuter le contrôleur en mode privilégié supprime la nécessité de monter le socket d'exécution et de monter /host/cgroup/.
* Ajout de la liaison rôle/rôle pour neuvector-binding-secret ainsi que pour neuvector-secret en yaml.
* Nouveaux comptes de service et nouveaux rôles requis pour la version 5.3
* Tous les fichiers yaml de déploiement référencés ont maintenant /5.3.0/ dans leur chemin d'accès.

=== 5.2.4-s1 Janvier 2024

==== Publication du correctif de sécurité

* Remédie à CVE-2023-6129 dans openssl, et CVE-2023-46219, CVE-2023-46218 dans curl.

=== 5.2.4 novembre 2023

==== Corrections de bugs

* Azure AKS ValidatingWebhookConfiguration changes and error logging.

=== 5.2.3 novembre 2023

==== Améliorations

* Ajout de la prise en charge de l'API NVD 2.0 dans le scanner.
* Analyser l'hôte du conteneur en mode autonome du scanner.

[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n
----

==== Corrections de bugs

* L'analyse sur un nœud échoue en raison d'un problème de blocage de docker cp / grpc.

=== 5.2.2-s1 Octobre 2023

==== Mise à jour de la sécurité

* Mise à jour des paquets pour remédier aux CVEs incluant High CVE-2023-38545 et CVE-2023-43804.

=== 5.2.2 Octobre 2023

==== Avis de sécurité pour CVE-2023-32188

* Remédier à CVE-2023-32188 &quot;`+JWT token compromise can allow malicious actions including Remote Code Execution (RCE)+`&quot; en générant automatiquement le certificat utilisé pour la signature du jeton JWT lors du déploiement et de la mise à niveau, et en générant automatiquement le certificat Manager/RESTful API lors des déploiements basés sur Helm.
 ** Le certificat pour la signature JWT est créé automatiquement par le contrôleur avec une validité de 90 jours et est renouvelé automatiquement.
 ** La génération automatique du certificat du gestionnaire, de l'API REST et de l'adaptateur de registre nécessite une installation basée sur Helm à l'aide de {product-name} helm version 2.6.3 ou ultérieure.
 ** Le certificat intégré est toujours utilisé pour les déploiements basés sur le langage yaml s'il n'est pas remplacé pendant le déploiement ; il est toutefois recommandé de le remplacer (voir la ligne suivante).
 ** Le xref:replacecert.adoc[remplacement] manuel xref:replacecert.adoc[du certificat] est toujours possible et recommandé pour les versions antérieures ou les déploiements basés sur le langage yaml. Voir l'avis de sécurité {product-name} GitHub https://github.com/neuvector/neuvector/security/advisories/GHSA-622h-h2p8-743x[ici] pour une description.
 ** L'utilisation de certificats fournis par l'utilisateur est toujours supportée comme auparavant pour les déploiements basés sur Helm et yaml.
* Ajouter des contrôles supplémentaires sur les scripts de conformité personnalisés. Par défaut, les scripts personnalisés ne sont plus autorisés à être ajoutés, à moins que la variable d'environnement CUSTOM_CHECK_CONTROL ne soit ajoutée au contrôleur et à l'Enforcer. Les valeurs sont "disable" (par défaut, non autorisé), "strict" (rôle d'administrateur uniquement) ou "loose" (rôles d'administrateur, de conformité et de politique d'exécution).
* Prévention de l'injection LDAP - le champ du nom d'utilisateur est échappé.

==== Améliorations

* Ajout de données d'analyse supplémentaires aux résultats CVE envoyés par SYSLOG pour les analyses en couches
* Prise en charge de l'API NVD 2.0 pour l'analyse de la base de données CVE
* Indiquer la date de construction de l'image du conteneur dans Assets -> Détails du conteneur
* Ajuster le tri des règles de réseau : désactiver le tri dans la vue des règles de réseau mais activer le tri des règles de réseau dans la vue des groupes.
* Activer/désactiver la détection/alerte TLS 1.0 et TLS 1.1 avec des variables d'environnement pour Enforcer THRT_SSL_TLS_1DOT0, THRT_SSL_TLS_1DOT1. Désactivé par défaut.
* Ajout d'une variable d'environnement AUTO_PROFILE_COLLECT pour Controller et Enforcer afin de faciliter la capture de l'utilisation de la mémoire lors d'enquêtes sur des événements de pression de la mémoire. Régler la valeur = 1 pour activer.
* L'évaluation de la configuration du contrôle d'admission doit faire apparaître toutes les violations en une seule analyse.
* Ajout d'options supplémentaires pour les critères du rapport CVE dans les règles de réponse. Exemple 1 - "cve-high-with-fix:X" signifie : Lorsque le nombre de (vulnérabilités élevées qui ont été corrigées) >= X, déclencher la règle de réponse. Exemple 2 - "cve-high-with-fix:X/Y" signifie : Lorsque le nombre de (vulnérabilités élevées signalées il y a Y jours et corrigées) >= X, déclencher la règle de réponse.

==== Corrections de bugs

* L'exportation d'une politique de groupe ne renvoie aucun contenu YAML réel
* Améliorer l'élagage des espaces de noms avec une fonction dédiée
* {product-name} l'utilisateur de l'espace de noms ne peut pas voir les actifs-->espaces de noms
* Ne pas traiter les demandes de CRD CREATE/UPDATE si l'espace de noms du CR est déjà supprimé.
* Fournir une solution de contournement pour une partie des groupes CRD qui ne peuvent pas être élagués avec succès après la suppression des espaces de noms.

=== 5.2.1 Août 2023

==== Améliorations

* Signaler les résultats de l'analyse en couches et les données CVE supplémentaires dans les messages SYSLOG. Cette fonction est activée par le biais d'une case à cocher dans Settings -> Configuration -> SYSLOG
* Exporter les correspondances NIST 800-53 (vers les benchmarks CIS de Docker) dans le rapport de conformité csv exporté
* Prise en charge du paramètre Proxy dans la vérification de la signature de l'image
* Inclure le résultat de l'analyse de la signature de l'image dans le rapport CVE téléchargé
* Prise en charge des annotations de pods pour les politiques de contrôle d'admission, disponibles via les critères personnalisés
* Ajout du champ Dernière modification au filtre pour l'impression du rapport sur les vulnérabilités, ainsi qu'au filtre avancé dans la vue des vulnérabilités.

==== Correction de bugs

* Ne pas créer d'administrateur par défaut avec un mot de passe par défaut dans le déploiement initial de {product-name} pour l'offre de facturation AWS (adaptateur CSP), obligeant l'utilisateur à utiliser un secret pour créer le nom d'utilisateur et le mot de passe de l'administrateur.
* Correction d'un fichier .json qui augmentait la taille et faisait planter un nœud kubernetes
* Améliorer la logique de détection des injections SQL
* Lors de l'installation de la carte helm crd avant l'installation de la carte {product-name} core, les comptes de service sont manquants.
* Le résultat de la vérification de l'image I.4.1 est incorrect
* Rapport de filtrage avancé de la vulnérabilité affichant des images provenant de tous les autres espaces de noms

=== 5.2.0 Juillet 2023

==== Améliorations

* Prise en charge des jetons pour l'accès à l'API {product-name}. Voir Paramètres -> Utilisateur, Clés API... pour créer une nouvelle clé API. Les clés peuvent être définies comme des rôles par défaut ou personnalisés.
* Prise en charge de la facturation PAYG de la place de marché AWS pour les abonnements d'assistance mensuels sur {product-name}. Les utilisateurs peuvent s'abonner au support {product-name} by SUSE, facturé mensuellement sur leur compte AWS sur la base de l'utilisation moyenne du nombre de nœuds du mois précédent. Détails https://open-docs.neuvector.com/deploying/awsmarketplace[ici.]
* Prise en charge de la signature d'images pour les contrôles d'admission. Les utilisateurs peuvent demander à {product-name} de vérifier que les images sont signées par des parties spécifiques avant qu'elles ne soient déployées dans l'environnement de production, grâce à une intégration avec Sigstore/Cosign. Voir Assets -> Sigstore Verifiers pour la création de nouveaux actifs de signature. Des règles peuvent ensuite être créées avec des critères Image Signing et/ou Image Sigstore Verifiers.
* Permettre à chaque règle de contrôle d'admission d'avoir son propre mode de surveillance ou de protection. Une action de refus en mode de surveillance alertera, et une action de refus en mode de protection bloquera. Les actions d'autorisation ne sont pas affectées.
* Ajoutez un nouvel opérateur regex dans Politique > Contrôle d'admission > Ajouter une règle pour les utilisateurs et les groupes d'utilisateurs afin de prendre en charge les regex. Prise en charge des opérateurs "match ANY regex in" et "match NONE regex in".
* Ajouter la prise en charge des critères de contrôle d'admission tels que les limites de ressources. Un nouveau critère est ajouté pour les limites de ressources, et des critères supplémentaires sont pris en charge par les paramètres des critères personnalisés.
* Prise en charge de l'invocation de {product-name} scanner à partir des registres Harbor via l'interface https://github.com/goharbor/pluggable-scanner-spec[pluggable scanner.]  Cela nécessite la configuration de la connexion au contrôleur (API exposée). L'adaptateur Harbor appelle le point de terminaison du contrôleur pour déclencher un balayage, qui peut être automatique en cas de poussée. Les services d'interrogation peuvent être utilisés pour des balayages périodiques. Les résultats de l'analyse des contrôleurs primaires de la fédération SONT propagés aux clusters distants.  NOTE : Il y a un problème avec l'erreur du point de terminaison de l'adaptateur basé sur HTTPS : veuillez ignorer l'erreur de test de connexion, elle fonctionne même si une erreur est affichée (ne pas tenir compte de la validation du certificat).
* Service SaaS consultable pour les recherches CVE. Recherche dans la dernière base de données CVE de {product-name} pour voir si un CVE spécifique existe dans la base de données. Ce service est disponible pour les clients de {product-name} Prime (abonnement d'assistance payant). Contactez le support via votre portail du CCN pour y accéder.
* Permet à l'utilisateur de désactiver la protection du réseau tout en maintenant le fonctionnement du WAF/DLP. Configurez Network Policy Enablement dans Settings -> Configuration.
* Utilisez des comptes de services moins privilégiés selon les besoins pour chaque composant de {product-name}. Une variable &quot;`+leastPrivilege+`&quot; est introduite. La valeur par défaut est false. NOTE : L'utilisation du diagramme de barre actuel avec cette variable sur une version antérieure à la 5.2.0 ne fonctionnera pas correctement.
* Lier au compte de service non par défaut pour répondre à la recommandation CIS 1.5 5.1.5.
* Permettre à l'administrateur de configurer le délai de session par défaut de l'utilisateur dans les paramètres -> Users, API Keys & Roles.
* Bannière de connexion personnalisable et texte d'en-tête d'interface utilisateur personnalisable pour les déploiements réglementés et gouvernementaux. Les exigences en matière de configuration peuvent être consultées xref:customui.adoc[ici.]
* Prise en charge par SYSLOG du transport crypté TLS. Sélectionnez TCP/TLS dans Settings -> Configuration for SYSLOG.
* Activer le déploiement du diagramme de barre du moniteur {product-name} à partir de Rancher Manager.
* Suppression de la limite supérieure du domaine de premier niveau dans le validateur d'URL pour l'analyse du registre.
* Analyser les dépendances de golang, y compris les analyses d'exécution.
* Prise en charge de l'analyse des vulnérabilités de Debian 12 (Bookworm).
* Ajout d'une exportation CSV pour Registry / Details afin d'exporter les CVE de toutes les images du registre configuré dans Assets -> Registries pour un registre sélectionné.
* Permettre à {product-name} de définir plusieurs certificats ADFS en parallèle dans le champ du certificat x.509.
* Ajouter et afficher le champ de commentaire pour les règles de réponse.
* Spécifiez ce que {product-name} considère comme des conteneurs système par le biais d'une variable d'environnement. Par exemple, pour Rancher et les espaces de noms par défaut : NV_SYSTEM_GROUPS=*cattle-system;default
* Ajout de la prise en charge de Kubernetes 1.27 et OpenShift 4.12

==== Corrections de bugs

* Réduire les enregistrements répétitifs dans les journaux de l'exécuteur/contrôleur.
* La page des clusters multiples ne s'affiche pas.
* La suppression automatique des groupes vides prend 2 heures au lieu d'une heure comme prévu.
* La règle de réseau autorisée manuellement n'est pas appliquée et entraîne une violation pour l'image de pause.
* Blocage des connexions SSL même si une règle de réseau autorise le trafic sous certaines conditions initiales.
* Avertissement d'événements de sécurité même avec des règles de réseau autorisées en raison d'un problème de synchronisation de la mise à jour de la politique.
* Les activités de réseau associent à tort le trafic des groupes personnalisés à l'extérieur.
* Le jeton du compte de service par défaut de l'espace de noms monté dans chaque pod est trop privilégié.
* Malgré la définition des règles de réseau, des violations sont enregistrées dans les événements de sécurité (faux positifs) lorsque le conteneur s'est arrêté en raison d'une erreur de mémoire insuffisante (OOM).
* Permet à l'utilisateur de désactiver/activer la détection et la protection contre les conteneurs non gérés dans le cluster. Ce paramètre peut être défini par l'intermédiaire de l'interface CLI du gestionnaire :

[,shell]
----
set system detect_unmanaged_wl status -h
Usage: cli set system detect_unmanaged_wl status [OPTIONS] {true|false}

  Enable/disable detect unmanaged container
----

==== Autres

* Ajout du paramètre "leastPrivilege" dans le diagramme de Helm. Ajouter l'option helm pour New_Service_Profile_Baseline. Une nouvelle version de la carte Helm (core) est publiée pour la version 5.2.
* Activer les paramètres d'intégration d'AWS Marketplace (adaptateur de facturation) dans le diagramme Helm.
* Mise à jour de la carte de configuration pour prendre en charge les nouvelles fonctionnalités (certificats ADFS multiples, dérive zéro, New_Service_Profile_Baseline, SYSLOG TLS, délai d'attente de l'utilisateur)
* Mise à jour des versions de Kubernetes supportées vers 1.19+, et OpenShift 4.6+ (1.19+ avec CRI-O)

=== 5.1.3 mai 2023

==== Améliorations

* Ajout d'un nouveau flux de vulnérabilités pour l'analyse du cadre Microsoft .NET.
* Les statistiques d'Enforcer sont désactivées par défaut dans l'exportateur Prometheus afin d'améliorer l'évolutivité.
* Amélioration de la convivialité : Utilisation du scanner pour numériser une seule image et imprimer le résultat (voir l'exemple ci-dessous).
* Ajouter la vérification imagePullPolicy dans les critères des règles de contrôle d'admission.
* Afficher un message d'avertissement lorsque le schéma CRD n'est pas à jour.

==== Corrections de bugs

* L'écran Activité réseau ne s'affiche pas ou mal.
* La suppression automatique des groupes vides prend 2 heures au lieu d'une heure comme prévu.
* Le profil de conformité n'apparaît pas dans la console d'interface utilisateur.
* Filtre avancé dans les événements de sécurité : niveau "erreur" manquant.
* Le mot de passe enregistré avec un caractère spécial échoue lors de la prochaine tentative d'authentification.
* La page sur les grappes multiples ne s'affiche pas correctement lorsque le nombre de demandes est élevé.
* Le volet détaillé du registre (en bas) n'est pas mis à jour.

==== Échantillon de sortie du scanner

[,shell]
----
Image: https://registry.hub.docker.comlibrary/alpine:3.4
Base OS: alpine:3.4.6
TOTAL: 6, HIGH: 1, MEDIUM: 5, LOW: 0, UNKNOWN: 0
┌─────────┬───────────────┬──────────┬───────────┬───────────────┬────────────┐
│ PACKAGE │ VULNERABILITY │ SEVERITY │ VERSION   │ FIXED VERSION │ PUBLISHED  │
├─────────┼───────────────┼──────────┼───────────┼───────────────┼────────────┤
│ openssl │ CVE-2018-0732 │ High     │ 1.0.2n-r0 │ 1.0.2o-r1     │ 2018-06-12 │
│         ├───────────────┼──────────┤           ├───────────────┼────────────┤
│         │ CVE-2018-0733 │ Medium   │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0734 │          │           │ 1.0.2q-r0     │ 2018-10-30 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0737 │          │           │ 1.0.2o-r2     │ 2018-04-16 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0739 │          │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-5407 │          │           │ 1.0.2q-r0     │ 2018-11-15 │
└─────────┴───────────────┴──────────┴───────────┴───────────────┴────────────┘
----

=== 5.1.2 Mars 2023

==== Améliorations

* Prise en charge des groupes d'adresses basés sur les hôtes virtuels et des protections de réseau correspondant aux politiques. Cela permet de résoudre un cas d'utilisation où deux adresses FQDN différentes sont résolues à la même adresse IP, mais où des règles différentes doivent être appliquées pour chaque FQDN. Un nouveau groupe personnalisé avec &apos;`+address=vh:xxx.yyy+`&apos; peut être créé à l'aide de l'indicateur &apos;`+vh:+`&apos; pour activer cette protection. Une règle de réseau peut alors utiliser le groupe personnalisé comme source &apos;`+From+`&apos; sur la base du nom d'hôte virtuel (au lieu de l'adresse IP résolue) afin d'appliquer des règles différentes pour les hôtes virtuels.
* Liste des conteneurs de conformité pour exclure les conteneurs sortis.
* Améliorer les règles DLP pour qu'elles prennent en charge les caractères génériques simples dans le modèle.
* Ajout du support pour cri-o 1.26+ et OpenShift 4.11+.
* Rendre le gravatar facultatif.
* Affichage des ressources de l'espace de noms du cluster dans la console / l'interface utilisateur.
* Affichage de la gravité/classification de la source (par exemple Red Hat, Ubuntu...) et du score de gravité de la NVD dans la console.
* Ne pas autoriser la désactivation de SSO/RBAC pour Rancher et OpenShift si l'utilisateur est authentifié par SSO.
* Ajout de l'activation du balayage automatique et de la suppression du vieillissement des groupes inutilisés dans configMap.
* Inclure l'adresse IP de la source/destination externe dans le fichier csv/pdf pour les violations de refus implicites
* Diverses optimisations des performances et de l'évolutivité pour l'utilisation du CPU et de la mémoire du contrôleur et de l'applicateur.

==== Corrections de bugs

* Correction de la lenteur des applications sur les nœuds GKE Container Optimized OS (COS) en mode Protect.
* SUSE Linux (SLES) 15.4 CVE ne correspondant pas à l'analyseur. Avec ce correctif, si la gravité est fournie dans le flux, la vulnérabilité sera ajoutée à la base de données, même si l'enregistrement NVD est manquant. Il est possible que le rapport inclue des vulnérabilités sans score CVE.

==== Autres

* Améliorer les options de contrôle d'admission CRD dans helm https://github.com/neuvector/neuvector-helm/pull/237.
* Ajout de nouvelles variables d'environnement enforcer au tableau de bord.

=== 5.1.1 Février 2023

==== Améliorations

* Ajouter &quot;`+package+`&quot; comme information à l'événement syslog pour une vulnérabilité détectée.
* Ajouter la variable d'environnement ENF_NETPOLICY_PULL_INTERVAL - Valeur en secondes (valeur recommandée 60) pour réduire le trafic réseau et la consommation de ressources qui en résulte par Enforcer en raison des mises à jour/recalculs de politiques. (Note : il s'agit d'un ajout non documenté jusqu'en août 2023).

[,yaml]
----
           - name: ENF_NETPOLICY_PULL_INTERVAL
             value: "60"   <== regulate the pulling gap by 60 seconds
----

==== Corrections de bugs

* Erreurs de suppression de groupes vides "Objet non trouvé".
* Alerte/blocage du trafic à l'intérieur d'un même conteneur
* Violations implicites inattendues pour le trafic de sortie d'istio avec une règle d'autorisation en place
* Lors de la mise à jour de {product-name} 4.x, l'appartenance incorrecte à un groupe de pods entraîne une violation inattendue de la politique.
* L'authentification OIDC échoue avec ADFS lorsque des caractères d'encodage supplémentaires apparaissent dans la requête
* Utilisation importante de la mémoire par dp lors de la création et de la suppression de pods
* Mise à jour alpine pour remédier à plusieurs CVE dont Manager : CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552
* Correction de plusieurs bugs d'interface utilisateur

==== Autres

* Mise à jour du tableau de bord pour permettre le remplacement du certificat pour les communications internes

=== 5.1.0 décembre 2022

==== Améliorations

* Base de données centralisée et multi-clusters pour l'analyse (CVE). Le cluster primaire (maître) peut analyser un registre/répo désigné comme registre fédéré. Les résultats de l'analyse de ces registres seront synchronisés avec tous les clusters gérés (à distance). Cela permet d'afficher les résultats de l'analyse dans la console du cluster géré et de les utiliser dans les règles de contrôle d'admission du cluster géré. Les registres ne doivent être analysés qu'une seule fois au lieu de l'être par chaque grappe, ce qui réduit l'utilisation de l'unité centrale, de la mémoire et de la bande passante du réseau.
* Améliorer les règles de contrôle d'admission :
 ** Critères personnalisés pour les règles de contrôle d'admission. Permet aux utilisateurs de définir des critères de ressources sur tous les champs liés aux pods et à utiliser dans les règles, par exemple item.metadata.annotationsKey contient 'neuvector', item.metadata.name='xyzzy' etc.
 ** Ajouter des critères pour vérifier les paramètres RBAC à haut risque pour les comptes de service lors du déploiement de pods. Il s'agit notamment des critères "any action of workload resources", "any action on RBAC", "create workload resources", "listing secrets" et "exec into a container".
 ** Ajouter une comparaison sémantique des versions aux modules pour les règles de contrôle d'admission. Cela permet d'appliquer les opérateurs > ou < aux numéros de version dans les règles (par exemple, ne pas autoriser le déploiement du module curl<6.2.0). Cela permet d'effectuer des contrôles de version spécifiques sur les paquets installés.
 ** Ajout d'une règle de contrôle d'admission pour Pod Security Admission (PSA) prise en charge dans Kubernetes 1.25+.
* Ajout d'une nouvelle variable env NO_DEFAULT_ADMIN qui, lorsqu'elle est activée, ne crée pas d'utilisateur "admin". Il est utilisé par défaut pour l'intégration SSO de Rancher. Si cette option n'est pas activée, un avertissement persistant est envoyé à l'utilisateur et des événements sont enregistrés afin qu'il modifie le mot de passe administrateur par défaut s'il n'est pas modifié.
* Le blocage de la connexion après des tentatives de connexion infructueuses devient maintenant la valeur par défaut. La valeur par défaut est de 5 tentatives et peut être configurée dans Settings -> Users & Roles-> Password Profile (Paramètres Utilisateurs et rôles Profil du mot de passe).
* Ajout d'une nouvelle variable env pour l'optimisation des performances ENF_NO_SYSTEM_PROFILES, value : "1". Lorsqu'elle est activée, elle désactive les moniteurs de processus et de fichiers. Aucun processus d'apprentissage, aucun mode de profil, aucun incident de processus/fichier (paquet) et aucun contrôle de l'activité des fichiers ne sera effectué. Cela permettra de réduire l'utilisation des ressources de l'unité centrale et de la mémoire, ainsi que les opérations sur les fichiers.
* Ajouter un paramètre personnalisé de mise à l'échelle automatique pour les modules de numérisation, avec les valeurs Retardé, Immédiat et Désactivé. Important : La mise à l'échelle automatique du scanner n'est pas prise en charge lorsque le scanner est déployé avec un opérateur OpenShift, car l'opérateur modifiera toujours le nombre de pods à sa valeur configurée.
 ** *_Stratégie différée :_*
  *** Lorsque le contrôleur principal voit continuellement "task count" > 0 pendant > 90 secondes, un nouveau pod scanner est démarré si maxScannerPods n'est pas encore atteint.
  *** Lorsque le contrôleur principal constate en permanence que le "nombre de tâches" est égal à 0 pendant plus de 180 secondes, il réduit d'un pod le nombre de scanners si le nombre minScannerPods n'est pas encore atteint.
 ** *_Stratégie immédiate :_*
  *** Chaque fois que le contrôleur principal voit "task count" > 0, un nouveau pod scanner est démarré si maxScannerPods n'est pas encore atteint.
  *** Lorsque le contrôleur principal constate en permanence que le "nombre de tâches" est égal à 0 pendant plus de 180 secondes, il réduit d'un pod le nombre de scanners si le nombre minScannerPods n'est pas encore atteint.
* Les groupes personnalisés peuvent désormais utiliser des étiquettes d'espace de noms, y compris les étiquettes d'espace de noms de Rancher. Il est désormais possible d'ajouter des étiquettes de pods et d'espaces de noms aux groupes personnalisés.
* Ajout de la possibilité de masquer les espaces de noms et les groupes sélectionnés dans la vue de l'activité du réseau.
* Prise en charge complète de Cilium cni.
* Prise en charge complète d'OpenShift 4.9 et 4.10.
* Des outils de construction sont désormais disponibles pour le projet {product-name}/Open Zero Trust (OZT) à l'adresse suivante https://github.com/openzerotrust/openzerotrust.io.
* {product-name} liste désormais l'identifiant de version et le résumé SHA256 pour chaque version du contrôleur, du gestionnaire, de l'agent d'exécution à l'adresse https://github.com/neuvector/manifests/tree/main/versions.
* Les données télémétriques anonymes (nombre de nœuds, groupes, règles) sont désormais transmises à un service cloud Rancher lors du déploiement afin d'aider l'équipe du projet à comprendre le comportement d'utilisation. Ceci peut être désactivé (opt-out) dans l'interface utilisateur ou avec configMap (No_Telemetry_Report) ou REST API.
* (Addendum janvier 2023). Prise en charge de la politique réseau basée sur les ServiceEntry avec Istio. La fonctionnalité d'application de la politique de réseau de sortie a été ajoutée dans la version 5.1.0 pour les pods vers les destinations ServiceEntry déclarées avec Istio. Typiquement, un ServiceEntry définit comment un service externe référencé par un nom DNS est résolu en une adresse IP de destination. Avant la version 5.1, {product-name} ne pouvait pas détecter et appliquer des règles pour les connexions à un ServiceEntry, de sorte que toutes les connexions étaient classées comme externes. Avec la version 5.1, des règles peuvent être appliquées pour des destinations ServiceEntry spécifiques. IMPORTANT : Si vous passez à la version 5.1 avec un déploiement basé sur Istio, de nouvelles règles doivent être créées pour autoriser ces connexions et éviter les alertes de violation. Après la mise à jour, les violations implicites seront signalées pour le trafic nouvellement visible si les règles d'autorisation n'existent pas. De nouvelles règles de circulation peuvent être apprises et créées automatiquement en mode découverte. Pour autoriser ce trafic, vous pouvez mettre le groupe en mode découverte ou créer un groupe personnalisé avec des adresses (ou un nom DNS) et une nouvelle règle de réseau vers cette destination pour autoriser le trafic. NOTE : Il y a un bogue dans la version 5.1.0 dans la destination rapportée par les violations de refus qui ne représentent pas la destination correcte.  Le rapport de bogue indique que le nom du serveur et le nom du client sont identiques.  Ce problème sera résolu lors d'une prochaine mise à jour.

==== Corrections de bugs

* Réduire la consommation de mémoire du contrôleur en raison des données de référence cis inutiles créées lors des mises à jour. Ce problème ne se pose pas pour les nouveaux déploiements.
* Supprimer la licence de l'écran de configuration (n'est plus nécessaire).

=== 5.0.6-s1 Mars 2023

==== Corrections de bugs

* Mise à jour des paquets alpine pour remédier aux CVE dans curl, y compris CVE-2023-23914, CVE-2023-23915, et CVE-2023-23916.

=== 5.0.6 février 2023

==== Corrections de bugs

* Utilisation importante de la mémoire dans dpMsgConnection
* Utilisation importante de la mémoire du processus dp dans enforcer s'il y a beaucoup de règles de politique apprises avec une charge de travail non gérée (fuite de mémoire).
* tcpdump ne parvient pas à démarrer correctement lors de l'analyse d'un trafic sur un conteneur
* Mise à jour alpine pour remédier à plusieurs CVE dont Manager : CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552

=== 5.0.5 novembre 2022

==== Corrections de bugs

* La mise à niveau vers la version 5.0.x génère un message d'erreur indiquant que le Manager, le Controller et l'Enforcer utilisent des versions différentes.
* Les forces de l'ordre sont prises de panique, ce qui entraîne la mort d'un policier.  L'interface WebUI n'indique pas que l'agent d'exécution est en ligne.
* Unxpected Process.Profile.Violation incident in NV.Protect group on which command on coreos.

=== 5.0.4 Octobre 2022

==== Mises à jour de la sécurité

* Mise à jour d'alpine pour supprimer la CVE-2022-40674 critique dans la bibliothèque manager expat, ainsi que d'autres CVE mineures.

==== Améliorations

* Ajout d'un support pour Antrea CNI

==== Corrections de bugs

* Correction d'un incident inattendu de type process.profile.violation dans le groupe NV.Protect.
* Lorsque SSL est désactivé pour l'accès à l'interface utilisateur du gestionnaire, le mot de passe de l'utilisateur est imprimé dans le journal du gestionnaire.

=== 5.0.3 Septembre 2022

==== Améliorations

* Ne pas afficher le CLUF après un redémarrage réussi à partir d'un volume persistant.
* Utilisez le filtre d'image dans les paramètres du profil de vulnérabilité pour ignorer les résultats de l'analyse des conteneurs.
* Support scanner dans les actions GitHub à https://github.com/neuvector/neuvector-image-scan-action.
* Ajout de variables d'environnement Enforcer pour la désactivation de l'analyse des secrets et l'exécution de tests CIS

[,yaml]
----
    env:
      - name: ENF_NO_SECRET_SCANS  (available after v4.4.4)
        value: "1"
      - name: ENF_NO_AUTO_BENCHMARK (after v5.0.3)
        value: "1"
----

==== Corrections de bugs

* L'Enforcer ne peut pas démarrer occasionnellement.
* Fuite de connexion dans les environnements de fédération à plusieurs clusters.
* La page de conformité ne se charge pas toujours dans Risques de sécurité -> Compliance

=== 5.0.2 Juillet 2022

==== Améliorations

* Les clusters Rancher durcis et SELinux sont pris en charge.

==== Corrections de bugs

* Le processus de l'agent utilise beaucoup de ressources sur les systèmes k3s.
* Les groupes AD LDAP ne fonctionnent pas correctement après la mise à jour vers la version 5.0.
* Enforcer ne cesse de se redémarrer en raison d'une erreur=too many open files (rke2/cilium).
* Le journal de support n'a pas pu être téléchargé avec succès.

=== 5.0.1 Juin 2022

==== Améliorations

* Prise en charge de l'analyse des vulnérabilités d'openSUSE Leap OS (dans l'image du scanner).
* Scanner : implémentation des attributs d'effacement lors de la reconstruction de l'image.
* Vérifier le déploiement de {product-name} et la prise en charge des hôtes SELinux. Voir ci-dessous pour plus de détails sur les correctifs provisoires jusqu'à ce que le tableau des casques soit mis à jour.
* Distinguer de manière plus visible le tableau des fonctionnalités et le tableau des partenaires dans l'interface utilisateur de Rancher + Améliorer l'annotation de l'ingress pour nginx dans le tableau des casques de Rancher. Ajouter / mettre à jour ingress.kubernetes.io/protocol : https à nginx.ingress.kubernetes.io/backend-protocol : "HTTPS".
* L'actuel OpenShift Operator prend en charge les routes passthrough pour les services d'api et de fédération. Des paramètres de valeur Helm supplémentaires ont été ajoutés pour prendre en charge les types de terminaisons d'itinéraires de type edge et re-encrypt.

==== Corrections de bugs

* Le cluster AKS pourrait ajouter une clé inattendue dans le webhook de contrôle d'admission.
* Enforcer ne devient pas opérationnel sur le cluster k8s 1.24 avec le runtime 1.64 containerd. Par ailleurs, enforcer ne démarre parfois pas.
* Tout utilisateur ayant le rôle d'administrateur (utilisateur local ou SSO) qui promeut un cluster en fed master devrait être automatiquement promu au rôle de fedAdmin.
* Lorsque sso utilise l'admin par défaut de Rancher dans {product-name} sur le cluster maître, le rôle de login de {product-name} est admin, et non fedAdmin.
* Correction de plusieurs plantages de goroutines.
* Violation implicite de l'IP de l'hôte non associé au nœud.
* Le profil de conformité n'affiche pas l'étiquette PCI.
* Le mappage des groupes LDAP n'est parfois pas affiché.
* L'outil d'examen et d'amélioration des risques génère le message d'erreur "Failed to update system config" (Échec de la mise à jour de la configuration du système) : Demande au mauvais format".
* OKD 3.11 - L'erreur Clusterrole s'affiche même si elle existe.

==== Remédiations CVE

* CVE-2022-29458 élevée trouvée sur le paquet ncurses dans toutes les images.
* CVE-2022-27778 et CVE-2022-27782 élevés trouvés sur le paquet curl dans l'image Updater.

==== Détails sur le support SELinux

{product-name} n'a besoin d'aucun paramètre supplémentaire pour que les clusters SELinux puissent être déployés et fonctionner. Déploiement testé de {product-name} sur un cluster durci RHEL 8.5 basé sur SELinux. {product-name} a été déployé avec succès si PSP est activé et si le gestionnaire de correctifs et le scanner sont déployés. La prochaine version de la carte devrait corriger le problème ci-dessous.

Vous trouverez ci-joint un exemple d'activation de psp à partir de la carte Rancher et ci-dessous les commandes pour le déploiement de patches pour le Manager et le Scanner. L'identifiant de l'utilisateur dans la commande patch peut être n'importe quel nombre.

[,shell]
----
kubectl patch deploy -ncattle-neuvector-system neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
kubectl patch deploy -ncattle-neuvector-system neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
----

Exemple d'activation de la PSP :

[,shell]
----
[neuvector@localhost nv]$ getenforce
Enforcing
[neuvector@localhost nv]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

[neuvector@localhost nv]$ kk get psp
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS                                      SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
global-restricted-psp     false                                             RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
neuvector-binding-psp     true    SYS_ADMIN,NET_ADMIN,SYS_PTRACE,IPC_LOCK   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
system-unrestricted-psp   true    *                                         RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
[neuvector@localhost nv]$ nvpo.sh
NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE                    NOMINATED NODE   READINESS GATES
neuvector-controller-pod-54f69f7f9c-6h822   1/1     Running   0          5m51s   10.42.0.29   localhost.localdomain   <none>           <none>
neuvector-enforcer-pod-jz77b                1/1     Running   0          5m51s   10.42.0.30   localhost.localdomain   <none>           <none>
neuvector-manager-pod-588488bb78-p6vf9      1/1     Running   0          111s    10.42.0.32   localhost.localdomain   <none>           <none>
neuvector-scanner-pod-87474dcff-s8vgt       1/1     Running   0          114s    10.42.0.31   localhost.localdomain   <none>           <none>
----

=== 5.0.0 General Availability (GA) Release Mai 2022

==== Améliorations

* Promotion automatisée des modes de groupe. Promouvoir le mode de protection d'un groupe en fonction du temps écoulé et de critères. Ne s'applique pas aux groupes créés par le CRD. Cette fonction permet à une nouvelle application de fonctionner en mode découverte pendant un certain temps, d'apprendre son comportement et {product-name} de créer des règles d'autorisation pour le réseau et le processus, puis de passer automatiquement en mode surveillance, puis en mode protection. Critères de découverte et de surveillance : Temps écoulé pour apprendre toute l'activité du réseau et des processus d'au moins un pod en direct dans le groupe. Critère "surveiller pour protéger" : Il n'y a pas d'événement de sécurité (réseau, processus, etc.) dans le délai fixé pour le groupe.
* Prise en charge de la carte Rancher 2.6.5 Apps and Marketplace. Déploie dans l'espace de noms cattle-neuvector-system et permet le SSO de Rancher à {product-name}. Remarque : Les déploiements précédents de Rancher (par exemple, les tableaux du catalogue des partenaires, version 1.9.x et antérieures) doivent être complètement supprimés afin de mettre à jour le nouveau tableau.
* Prise en charge de l'analyse de SUSE Linux (SLE, SLES) et de Microsoft Mariner
* Processus à dérive nulle et protection des fichiers. Il s'agit du nouveau mode par défaut pour la protection des processus et des fichiers. La dérive zéro n'autorise automatiquement que les processus provenant du processus parent qui se trouve dans l'image originale du conteneur, et ne permet pas l'installation de mises à jour de fichiers ou de nouveaux fichiers. En mode découverte ou surveillance, zero-drift émet des alertes en cas d'activité suspecte d'un processus ou d'un fichier. En mode protection, il bloque ce type d'activité. La dérive zéro n'exige pas que les processus soient appris ou ajoutés à une liste d'autorisation. La désactivation de la dérive zéro pour un groupe entraîne l'application des règles relatives aux processus et aux fichiers répertoriées pour ce groupe.
* Protection en mode fractionné pour le réseau, les processus et les fichiers. Un paramètre global est désormais disponible dans Settings -> Configuration pour définir séparément le mode de protection du réseau pour l'application des règles du réseau. L'activation de cette option (désactivée par défaut) entraîne l'application du mode de protection sélectionné (Découvrir, Surveiller, Protéger) à toutes les règles de réseau, tandis que les règles de traitement/fichier restent dans le mode de protection de ce groupe, comme indiqué dans l'écran Groupes de la stratégie ->. Ainsi, les règles de réseau peuvent être définies sur Protect (blocage), tandis que la politique en matière de processus/fichiers peut être définie sur Monitor (surveillance), ou vice versa.
* Détection des règles WAF, règles DLP améliorées (en-tête, URL, paquet complet). Utilisé pour les connexions entrantes vers les pods d'application web ainsi que pour les connexions sortantes vers les services api afin de renforcer la sécurité de l'api.
* CRD pour WAF, DLP et contrôles d'admission. REMARQUE : des liaisons/autorisations supplémentaires pour les rôles de cluster sont nécessaires. Voir les sections relatives au déploiement de Kubernetes et d'OpenShift. Importation/exportation de CRD et gestion des versions pour les contrôles d'admission pris en charge par CRD.
* Intégration SSO Rancher pour lancer la console {product-name} via Rancher Manager. Cette fonctionnalité n'est disponible que si les conteneurs {product-name} sont déployés via Rancher. Ce déploiement s'appuie sur le dépôt miroir de Rancher (par exemple, rancher/mirrored-neuvector-controller:5.0.0) et se déploie dans l'espace de noms cattle-neuvector-system. NOTE : Nécessite la mise à jour de Rancher 2.6.5 mai 2022 ou ultérieure, et seuls les rôles d'administrateur et de propriétaire de cluster sont pris en charge pour le moment.
* Prend en charge le déploiement sur RKE2.
* Prise en charge de la fédération de grappes (gestionnaire de grappes multiples) par l'intermédiaire d'un proxy. Configurez le proxy dans Paramètres -> Configuration, et activez le proxy lors de la configuration des connexions de fédération.
* Surveiller les rôles/liens de cluster de rbac requis et alerter dans les événements et l'interface utilisateur si l'un d'entre eux est manquant.
* Prise en charge des critères de limitation des ressources dans les règles de contrôle d'admission.
* Prise en charge du format Microsoft Teams pour les webhooks.
* Prise en charge des groupes imbriqués AD/LDAP sous le groupe de rôles mappé.
* Support des clusterrolebindings ou des rolebindings avec group info dans IDP for Openshift.
* Permettre aux règles de réseau et aux règles de contrôle d'admission d'être promues au rang de règles fédérées.

==== Corrections de bugs

* Correction d'un problème de sauvegarde du rôle de la fédération de travailleurs qui doit être restauré dans des clusters non fédérés.
* Améliorer les temps de chargement des pages pour un grand nombre de CVE dans Security Risks -> Vulnerabilities
* Permettre à l'utilisateur de changer de mode lorsqu'il sélectionne tous les groupes dans le menu Policy -> Groups. Avertir si le groupe Nœuds est également sélectionné.
* Réduire les éléments de contrôle de conformité portant le même nom et les rendre extensibles.
* Amélioration de la sécurité des communications gRPC.
* Correction : impossibilité d'obtenir des informations correctes sur la charge de travail privilégiée dans la configuration de rke2.
* Correction d'un problème avec le support d'openSUSE Leap 15.3 (k8s/crio).

==== Autres mises à jour

* Mise à jour de la version de l'application en 5.0.0 et de la version de la carte du gouvernail en 2.2.0
* Suppression de la fonction/menu d'analyse sans serveur.
* Suppression de la prise en charge de l'intégration des résultats de l'analyse Jfrog Xray (l'analyse du registre Artifactory est toujours prise en charge).
* La prise en charge du déploiement sur ECS n'est plus assurée. L'allinone devrait toujours pouvoir être déployé sur ECS, mais la documentation des étapes et des paramètres n'est plus prise en charge.

=== Mise à jour de {product-name} 4.x à 5.x (avant 5.2.x)

[NOTE]
====
Les instructions ci-dessous s'appliquent aux mises à jour vers les versions 5.0.x et 5.1.x. Pour la version 5.2.x, les comptes de service et les liaisons ont changé et doivent être xref:kubernetes.adoc#_deploy_suse_security[revus] pour planifier les mises à niveau.
====


Pour les utilisateurs de Helm, mettez à jour vers {product-name} Helm chart 2.0.0 ou plus récent. Si vous mettez à jour une installation Operator ou Helm sur OpenShift, voir la note ci-dessous.

. Supprimer l'ancien clusterrole neuvector-binding-customresourcedefinition

[,shell]
----
kubectl delete clusterrole neuvector-binding-customresourcedefinition
----

. Appliquer le nouveau verbe de mise à jour pour neuvector-binding-customresourcedefinition clusterrole

[,shell]
----
kubectl create clusterrole neuvector-binding-customresourcedefinition --verb=watch,create,get,update --resource=customresourcedefinitions
----

. Supprimer l'ancien schéma crd pour Kubernetes 1.19+.

[,shell]
----
kubectl delete -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/crd-k8s-1.19.yaml
----

. Créer un nouveau schéma crd pour Kubernetes 1.19+.

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/waf-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/dlp-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/admission-crd-k8s-1.19.yaml
----

. Créer un nouveau rôle de cluster et un nouveau lien de cluster pour Admission, DLP et WAF

[,shell]
----
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----

. Mise à jour des noms et chemins d'accès aux images {product-name} depuis le hub Docker (docker.io), par ex.

* neuvector/manager:5.0.0
* neuvector/controller:5.0.0
* neuvector/enforcer:5.0.0
* neuvector/scanner:latest
* neuvector/updater:latest

Optionnellement, supprimez toutes les références à la licence {product-name} et au secret de registre dans les graphiques Helm, le yaml de déploiement, le configmap, les scripts, etc., car ils ne sont plus nécessaires pour extraire les images ou pour commencer à utiliser {product-name}.

*Note sur le SCC et la mise à niveau via Operator/Helm*

Privileged SCC est ajouté au compte de service spécifié dans le yaml de déploiement par Operator version 1.3.4 et supérieure dans les nouveaux déploiements. Dans le cas d'une mise à niveau de l'Opérateur {product-name} d'une version précédente vers 1.3.4 ou de Helm vers 2.0.0, veuillez supprimer Privileged SCC avant de procéder à la mise à niveau.

[,shell]
----
oc delete rolebinding -n neuvector system:openshift:scc:privileged
----

==== Version Beta 1 publiée en avril 2022

* Fonctionnalité complète, y compris la promotion automatisée des modes de groupe. Promouvoir le mode de protection d'un groupe en fonction du temps écoulé et de critères. Ne s'applique pas aux groupes créés par le CRD. Cette fonction permet à une nouvelle application de fonctionner en mode découverte pendant un certain temps, d'apprendre son comportement et {product-name} de créer des règles d'autorisation pour le réseau et le processus, puis de passer automatiquement en mode surveillance, puis en mode protection. Critères de découverte et de surveillance : Temps écoulé pour apprendre toute l'activité du réseau et des processus d'au moins un pod en direct dans le groupe. Critère "surveiller pour protéger" : Il n'y a pas d'événement de sécurité (réseau, processus, etc.) dans le délai fixé pour le groupe.
* Prise en charge de la carte Rancher 2.6.5 Apps and Marketplace. Déploie dans l'espace de noms cattle-neuvector-system et permet le SSO de Rancher à {product-name}. Remarque : Les déploiements précédents de Rancher (par exemple, les tableaux du catalogue des partenaires, version 1.9.x et antérieures) doivent être complètement supprimés afin de mettre à jour le nouveau tableau.
* Tags pour Enforcer, Manager, Controller : 5.0.0-b1 (par exemple, neuvector/controller:5.0.0-b1)

==== Version Preview.3 publiée en mars 2022

[CAUTION]
.important
====

Pour mettre à jour les déploiements précédents pour les nouvelles fonctionnalités de CRD WAF, DLP et de contrôle d'admission, veuillez mettre à jour le CRD yaml et ajouter de nouvelles liaisons rbac/role :

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/latest/crd-k8s-1.19.yaml
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----
====


==== Améliorations

* Prise en charge de l'analyse de SUSE Linux (SLE, SLES) et de Microsoft Mariner
* Processus à dérive nulle et protection des fichiers. Il s'agit du nouveau mode par défaut pour la protection des processus et des fichiers. La dérive zéro n'autorise automatiquement que les processus provenant du processus parent qui se trouve dans l'image originale du conteneur, et ne permet pas l'installation de mises à jour de fichiers ou de nouveaux fichiers. En mode découverte ou surveillance, zero-drift émet des alertes en cas d'activité suspecte d'un processus ou d'un fichier. En mode protection, il bloque ce type d'activité. La dérive zéro n'exige pas que les processus soient appris ou ajoutés à une liste d'autorisation. La désactivation de la dérive zéro pour un groupe entraîne l'application des règles relatives aux processus et aux fichiers répertoriées pour ce groupe.
* Protection en mode fractionné pour le réseau, les processus et les fichiers. Un paramètre global est désormais disponible dans Settings -> Configuration pour définir séparément le mode de protection du réseau pour l'application des règles du réseau. L'activation de cette option (désactivée par défaut) entraîne l'application du mode de protection sélectionné (Découvrir, Surveiller, Protéger) à toutes les règles de réseau, tandis que les règles de traitement/fichier restent dans le mode de protection de ce groupe, comme indiqué dans l'écran Groupes de la stratégie ->. Ainsi, les règles de réseau peuvent être définies sur Protect (blocage), tandis que la politique en matière de processus/fichiers peut être définie sur Monitor (surveillance), ou vice versa.
* Détection des règles WAF, règles DLP améliorées (en-tête, URL, paquet complet)
* CRD pour WAF, DLP et contrôles d'admission. REMARQUE : des liaisons/autorisations supplémentaires pour les rôles de cluster sont nécessaires. Voir les sections relatives au déploiement de Kubernetes et d'OpenShift. Importation/exportation de CRD et gestion des versions pour les contrôles d'admission pris en charge par CRD.
* Intégration SSO Rancher pour lancer la console {product-name} via Rancher Manager. Cette fonctionnalité n'est disponible que si les conteneurs {product-name} sont déployés via Rancher. NOTE : Nécessite la mise à jour de Rancher (date/version à déterminer).
* Prend en charge le déploiement sur RKE2.
* Prise en charge de la fédération de grappes (gestionnaire de grappes multiples) par l'intermédiaire d'un proxy.
* Surveiller les rôles/liens de cluster de rbac requis et alerter dans les événements et l'interface utilisateur si l'un d'entre eux est manquant.
* Prise en charge des critères de limitation des ressources dans les règles de contrôle d'admission.

==== Corrections de bugs

* Correction d'un problème de sauvegarde du rôle de la fédération de travailleurs qui doit être restauré dans des clusters non fédérés.

==== Version Preview.2 publiée en février 2022

* Changements mineurs de fichiers et de licences dans les sources, aucune fonctionnalité n'a été ajoutée.

==== Prise en charge du déploiement sur AWS ECS Obsolète

La prise en charge du déploiement sur ECS n'est plus assurée. L'allinone devrait toujours pouvoir être déployé sur ECS, mais la documentation des étapes et des paramètres n'est plus prise en charge.

=== 5.0 "Tech Preview" Janvier 2022

==== Améliorations

* Première version d'une version non supportée, "tech-preview", de la version open source {product-name} 5.0.
* Ajout de la prise en charge du Top-10 de l'OWASP, des règles de type WAF pour la détection des attaques réseau dans les en-têtes ou le corps du message. Inclut la prise en charge des définitions des signatures de la CRD et l'application aux groupes appropriés.
* Supprime les fonctionnalités d'analyse sans serveur.

==== Corrections de bugs

* TBD

==== Autres

* Helm chart v1.8.9 est publié pour les déploiements 5.0.0. Si vous l'utilisez avec la version preview de 5.0.0, les modifications suivantes doivent être apportées au fichier values.yml :
 ** Mettre à jour le registre vers docker.io
 ** Mise à jour des noms d'images/étiquettes vers la version preview sur Docker hub
 ** Laisser le champ imagePullSecrets vide
