= Notes de version 5.x
:revdate: 2025-08-26
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/01.5x/01.5x.md
:page-opendocs-slug:  /notesderelease/5x

== Notes de version pour 5.x

[NOTE]
====
Pour recevoir des notifications par e-mail concernant les nouvelles versions, veuillez vous abonner à cette liste de diffusion SUSE : https://lists.suse.com/mailman/listinfo/neuvector-updates
====

=== 5.4.6 Août 2025

==== Nouvelles fonctionnalités

* *NVSHAS-6733* : Exporter les règles de réponse en tant que CRD.
* *NVSHAS-9899* : Les avertissements de profil de processus NeuVector pour les services Java contiennent des données sensibles.
* *NVSHAS-9990* : Adopter un nouvel algorithme de hachage pour les mots de passe des utilisateurs.
* *NVSHAS-9968* : Unterstützung für die Festlegung des Standardpassworts für das Standardadministratorkonto.

==== Bugs corrigés

* *NVSHAS-10062* : Le gestionnaire n'affiche pas d'ERREUR lorsque la création du mot de passe administrateur échoue lors de la première connexion.
* *NVSHAS-10041* : L'opération de fédération a échoué avec "données invalides" lorsque la fédération a été configurée via ConfigMap.
* *NVSHAS-10018*: NeuVector ne scanne pas toutes les images dans le registre GitLab.
* *NVSHAS-10017*: Alerte de sécurité de faux positif liée au processus autorisé.
* *NVSHAS-10001*: Les mesures de protection/surveillance "persistent" après la suppression du groupe.
* *NVSHAS-9985*:    NeuVector (Fed Master) cause un problème pour toutes les demandes externes.
* *NVSHAS-9981*:    Un événement de sécurité est déclenché chaque fois qu'une nouvelle "règle de profil de processus" est ajoutée ou modifiée dans un groupe.

==== Avis de sécurité

* https://github.com/neuvector/neuvector/security/advisories/GHSA-8pxw-9c75-6w56[Le compte admin a un mot de passe par défaut non sécurisé]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-8ff6-pc43-jwv3[Gestion des mots de passe non sécurisés, qui sont vulnérables aux attaques Rainbow]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-w54x-xfxg-4gxq[Le processus avec des arguments sensibles entraîne des fuites]

Voir la documentation xref:cve.adoc[Avertissements de sécurité et CVEs] pour plus d'informations.

=== 5.4.5 Juillet 2025

==== Nouvelles fonctionnalités

* *NVSHAS-9776*: Fügen Sie die etcd-Toleranz im Helm-Diagramm hinzu.

==== Corrections d'erreurs

* *NVSHAS-9507*: Le conteneur OCI n'est pas scanné.
* *NVSHAS-9787*: Supprimez le journal de gestionnaire inutile.
* *NVSHAS-9788*: Optimisez l'algorithme de création de certificats.
* *NVSHAS-9789*: Supprimez le journal de gestionnaire inutile dans la configuration du registre distant.
* *NVSHAS-9867*: NeuVector indique `+.NET Library System.Formats.Asn1 v8.013+` CVE 2024-38095 affecté.
* *NVSHAS-9883*: [quay.io] Les filtres génériques ne fonctionnent pas pour le registre Docker.
* *NVSHAS-9911*: Le scan du dépôt via l'API REST renvoie un message "faux".
* *NVSHAS-9930*: CVE-2018-20796 pour `+glibc/libc-bin : 2.36-9+deb12u10+` – Faux positif.
* *NVSHAS-9933*: La fonctionnalité de l'adaptateur de registre (Harbor) indique des erreurs dans le registre cible lors du scan.
* *NVSHAS-9934*: Une fonctionnalité de dérive zéro suspecte a échoué.
* *NVSHAS-9940*: Problème de mode sous-domaine JFrog de scan NV.
* *NVSHAS-9942*: Les analyses d'images pour les images des clients échouent.
* *NVSHAS-9945*: Si le nom du processus est trop long, il est difficile de déterminer comment la règle de profil de processus correspondante peut être créée.
* *NVSHAS-9946*: Problème d'affichage avec l'avertissement d'admission pour le type d'identifiant.
* *NVSHAS-9947*: [UI-ext] Le diagramme de conformité manque le statut "Manuel" dans Rancher NeuVector.
* *NVSHAS-9948*: Après la mise à niveau vers `+5.4.3+`, la configuration de NeuVector a été perdue.
* *NVSHAS-9949*: [Harbor][Nom d'utilisateur/Mot de passe incorrect] La recherche d'images continue, même en cas de saisie incorrecte du nom d'utilisateur/mot de passe.
* *NVSHAS-9952*: Retirez 'Signature' du rapport d'utilisation, car NV ne génère/valide plus la clé de licence.
* *NVSHAS-9953*: Les pods Enforcer continuent de redémarrer.
* *NVSHAS-9954*: L'exportateur Prometheus de NeuVector génère des métriques dupliquées.
* *NVSHAS-9958*: L'application des règles réseau prend du temps.
* *NVSHAS-9960*: Les scanners ne fonctionnent pas.
* *NVSHAS-9969*: Erreurs fatales: Des opérations d'écriture de carte simultanées entraînent le redémarrage du composant Enforcer.
* *NVSHAS-9971*: Sur NV UI `+Get Bootstrap Password+`.
* *NVSHAS-9975*: [Manager] TypeError: `+this.mousemoveListener+` n'est pas une fonction observée dans NV GUI.
* *NVSHAS-9986*: Les règles d'accès pour les processus et les fichiers ne peuvent pas être modifiées ou supprimées dans la vue du groupe de politiques fédérées.
* *NVSHAS-9988*: UI: Les pages de groupe n'affichent pas tous les groupes lorsqu'il y a plus de 2 000 groupes.
* *NVSHAS-9991*: Le groupe `+nv.gatekeeper-controller-manager.openshift-azure-guardrails+` est absent dans l'UI.
* *NVSHAS-9993*: Remplacer MD5 par SHA256.
* *NVSHAS-9994*: Le pod Enforcer continue de redémarrer.
* *NVSHAS-9996*: Le diagramme Helm devrait permettre un mode non privilégié pour les pods Enforcer.
* *NVSHAS-9998*: Impossible d'exporter le groupe du maître fédéré de NeuVector.
* *NVSHAS-10000*: Mettre à niveau NV vers BCI 15.7.
* *NVSHAS-10003*: Le rechargement de la page ne fonctionne pas sur la page NV autonome, pendant que l'interface utilisateur Rancher est ouverte.
* *NVSHAS-10008*: Analyse du registre – Le menu d'affichage est cassé pour l'image scannée.
* *NVSHAS-10010*: Le flot TCP SYN bloque l'entrée, ce qui entraîne un blocage complet du trafic entrant.

=== 5.4.4 Mai 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9915**: Afficher les résultats de l'analyse du module de scanner Harbor dans l'interface utilisateur NeuVector.
* **NVSHAS-9904**: `+imagePullPolicy+` à `+values.yaml+` pour chaque composant exposé.
* **NVSHAS-9869**: UI: Déplacer les contrôles DDoS vers le tableau de groupe.
* **NVSHAS-9840**: [GCP] Support Autopilot NeuVector pour GCP.
* **NVSHAS-9248**: Afficher les règles de processus/réseau inutilisées avec des compteurs et un horodatage `+Last Used+`.
* **NVSHAS-8160**: [Contrôleur] Ajuster certains éléments pour le calcul de la valeur de risque de sécurité.
* **NVSHAS-4673**: Proposition d'ajouter un message avant l'exportation de groupes.

==== Corrections d'erreurs

* **NVSHAS-9931**: Ajouter un avertissement si des versions incohérentes des produits NeuVector sont présentes dans un environnement multi-cluster.
* **NVSHAS-9925**: `+/v1/scan/asset/images+` L'API sur la page d'enregistrement échoue.
* **NVSHAS-9913**: Problème de suppression de plusieurs règles réseau liées aux groupes Workload:XYZ.
* **NVSHAS-9912**: Mise à jour de Helm pour certaines autorisations RBAC K8s requises pour le compte de service du contrôleur.
* **NVSHAS-9909**: Le message "Déconnecté - Aller à la page de chargement" s'affiche lorsque le lien NavLink de NeuVector Rancher est utilisé.
* **NVSHAS-9898**: Dans un environnement fédéré, changer les critères d'un groupe créé par le client fed.* (z. B. fed.core-systems) nicht.
* **NVSHAS-9894**: [Enforcer] `+Nv.protect+` refuse la commande de vérification de disponibilité du contrôleur `+cat /tmp/ready+`.
* **NVSHAS-9886**: L'activité réseau ne résout pas les noms de domaine pour les connexions de groupes externes personnalisés.
* **NVSHAS-9884**: [Analyse de nœud][Analyse de conteneur] L'analyse échouera.
* **NVSHAS-9873**: Problème de recherche avec le filtre avancé de l'UI dans NeuVector 5.4.2.
* **NVSHAS-9865**: Les politiques réseau exportées diffèrent, selon l'ordre de sélection (mêmes groupes sélectionnés).
* **NVSHAS-9828**: [Enforcer: Le NeuVector Enforcer ne peut pas détecter les Pods à courte durée de vie (moins de 5 secondes).
* **NVSHAS-9783**: Après l'ajout de la politique réseau interdisant les paquets ICMP, NeuVector ne voit aucun avertissement dans `+Security Events+`.
* **NVSHAS-9176**: Afficher une erreur de script sur la page **Risques de sécurité > Vulnérabilités** lorsque l'utilisateur avec le rôle de l'espace de noms `+rt_scan:w+` est connecté.

=== 5.4.3 Mars 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9793**: Autoriser les rôles globaux Fed dans LDAP/userinitcfg lors du déploiement de NeuVector via ConfigMap et Secret.
* **NVSHAS-9764**: [RFE] Ajouter le support d'Azure pour "Configuration de dépôt distant".
* **NVSHAS-9759**: Ajouter des détails de date dans le rapport d'exposition Ingress.
* **NVSHAS-9755**: Demande d'affichage des noms des variables d'environnement avec les valeurs dans les avertissements pour les secrets.
* **NVSHAS-9748**: [Helm] Mise à jour de NeuVector Helm pour prendre en charge la référence de nom pour les groupes partagés dans CRD (NVSHAS0-4717).
* **NVSHAS-9426**: Ajouter hostPath pour le scanner au diagramme Helm.
* **NVSHAS-9326**: NeuVector - Module de scanner Harbor pluggable.
* **NVSHAS-9835**: Interface utilisateur pour désactiver le scan automatique pour le nœud.
* **NVSHAS-7997**: Scanner-Connector pour ghcr.io.
* **NVSHAS-7982**: Affecter les capteurs WAF au maître de fédération.

==== Corrections d'erreurs

* **NVSHAS-9849**: Les agents ne s'enregistrent pas auprès des contrôleurs.
* **NVSHAS-9847**: Les filtres génériques ne fonctionnent pas pour le registre Docker.
* **NVSHAS-9833**: La restauration de la configuration échoue dans les déploiements Rancher.
* **NVSHAS-9832**: Problème de création de règles réseau en utilisant le groupe de charges de travail.
* **NVSHAS-9821**: Le nom du processus ne correspond pas à celui de la ligne de commande pour l'avertissement de règle de gain de processus.
* **NVSHAS-9817**: La création de la règle de sécurité NvClusterSecurityRule CRD indique une création réussie, mais n'a pas été réellement créée en raison d'entrées de règle de processus en double.
* **NVSHAS-9812**: Le nouvel exportateur Prometheus de NeuVector a des métriques incorrectes.
* **NVSHAS-9811**: [Manager] L'accès à l'interface graphique n'est pas possible lorsqu'un certificat personnalisé (CA) avec CA racine et CA intermédiaire est utilisé dans le secret.
* **NVSHAS-9801**: Le mode FIPS + `+manager.env.ssl=false+` provoque une erreur dans le gestionnaire.
* **NVSHAS-9792**: La synchronisation de la politique de fédération échoue car la taille du corps dépasse le maximum de Consul.
* **NVSHAS-9784**: NeuVector renvoie 404 lors de l'analyse du dépôt d'images Jfrog.
* **NVSHAS-9783**: Après l'ajout de la stratégie réseau pour rejeter les paquets ICMP, l'utilisateur ne voit aucun avertissement dans "Événements de sécurité".
* **NVSHAS-9780**: Le Single Sign-On de NeuVector ne fonctionne pas avec Rancher NavLink.
* **NVSHAS-9777**: Webhook JSON avec des clés "Level" en double.
* **NVSHAS-9770**: Le changement automatique après le mode Zero-Drift modifie la mauvaise stratégie.
* **NVSHAS-9765**: L'accès aux fichiers n'est pas complètement bloqué en mode Protect.
* **NVSHAS-9756**: L'Enforcer a atteint la CPU maximale et a plusieurs avertissements de surcharge de mémoire.
* **NVSHAS-9668**: Der Konformitätstest schlägt bei RKE2 fehl.
* **NVSHAS-9265**: Résultats incomplets et incorrects du scan de vulnérabilités dans l'environnement PRE PCI.
* **NVSHAS-9227**: Le scan du registre se bloque au milieu du processus de scan et passe à l'état "Inactif".
* **NVSHAS-9729**: Un nombre incorrect de vulnérabilités est observé lorsque plusieurs StatefulSets avec le "même nom" sont déployés dans les namespaces d'un projet.
* **NVSHAS-9810**: Le contrôleur NeuVector ne répond pas et l'interface utilisateur n'est pas accessible.

=== 5.4.2 Janvier 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9726**: Le moniteur transmet maintenant l'URL du proxy.
* **NVSHAS-9719**: Annonce de la fin de vie des certificats intégrés.
* **NVSHAS-9715**: Support pour la valeur du Helm Chart pour définir les Nodeports sur le contrôleur et le gestionnaire.
* **NVSHAS-9710**: Insérer une colonne triable `+feed_rating+` dans l'onglet **Vulnérabilités**.
* **NVSHAS-9669**: Gesamt-Sicherheitsbewertung über die REST-API.
* **NVSHAS-9590**: Capacité de sélectionner le score de vulnérabilité pour tous les actifs.
* **NVSHAS-7555**: Inclure l'option "Actualiser automatiquement" sous Événements de sécurité.

==== Corrections d'erreurs

* **NVSHAS-9662**: Logique de rôles/RoleBinding incohérente dans le diagramme Helm 2.8.2.
* **NVSHAS-9652**: Différence observée dans le format syslog dans splunk.
* **NVSHAS-9649**: Le lien du conteneur produit un code de réponse 404 dans l'événement de sécurité.
* **NVSHAS-9613**: Erreur du gestionnaire NeuVector / Interface Web NeuVector non disponible.
* **NVSHAS-9507**: Le conteneur OCI n'est pas scanné.
* **NVSHAS-9443**: La mise à niveau/l'installation via ArgoCD échoue car l'objet leases.coordination.k8s.io ne peut pas être créé.
* **NVSHAS-9436**: Faux positif possible CVE contre CVE-2024-7347.
* **NVSHAS-8386**: Les clés privées et les certificats auto-signés continuent d'être envoyés dans plusieurs images.
* **NVSHAS-9754**: [UI] Empêcher Rancher de désactiver l'authentification SSO de l'utilisateur connecté à Rancher pour OpenShift ou Rancher RBAC.
* **NVSHAS-9751**: [Protection d'exécution] Le mode de surveillance + Zero Drift ne génère pas d'alerte lorsqu'un processus enfant est en cours d'exécution.
* **NVSHAS-9721**: L'interface utilisateur doit afficher un message d'erreur approprié lorsque l'utilisateur saisit un nom d'enregistrement incorrect.
* **NVSHAS-9696**: Indication de couleur incohérente des actifs sur la page de vulnérabilité.
* **NVSHAS-9686**: Namespace codé en dur pour le certificat de l'adaptateur d'enregistrement dans le diagramme Helm de Neuvector.
* **NVSHAS-9678**: Messages d'erreur excessifs après des modifications des linters.
* **NVSHAS-9670**: Gestionnaire: Problème avec les guillemets doubles dans la réponse au format texte brut et problème avec la bibliothèque Java non nommée dans l'exécution SBT.
* **NVSHAS-9667**: Définir la variable d'environnement `+CTRL_PATH_DEBUG+` sur une erreur dans le déploiement du contrôleur ne fonctionne pas.
* **NVSHAS-9665**: Règle d'accès aux fichiers: La suppression des règles prédéfinies produit une erreur "setRowData".
* **NVSHAS-9664**: Groupe de stratégie: La suppression du script personnalisé produit une erreur de type "setRowData".

[NOTE]
====
Les types par défaut du gestionnaire et du service d'adaptateur d'enregistrement ont été modifiés en ClusterIP.  Les utilisateurs peuvent toujours remplacer les paramètres en remplaçant `+manager.svc.type+` et `+cve.adapter.svc.type+` lorsque NodePort est préféré.
====

Dans la version 5.4.2 de NeuVector, le support des déploiements utilisant le certificat interne intégré est abandonné. Le certificat trouvé à `+/etc/neuvector/certs/internal+` dans les images de conteneur NeuVector 5.4.2 sera supprimé. Pour continuer à utiliser NeuVector, les utilisateurs doivent :

==== 5.4.2 Nouvelle installation :

===== Utilisation de Helm :

- Activez les drapeaux `+internal.autoGenerateCert+` et `+internal.autoRotateCert+` dans les graphiques Helm (ceux-ci sont activés par défaut à partir de la version 5.4.2). Alternativement, une méthode YAML est liée ci-dessous.

===== Verwendung von YAML:

- Déployer un xref:internal.adoc#_replacing_certificates_used_in_internal_communications_of_suse_security[certificat interne en utilisant les méthodes existantes].

==== Mise à niveau des versions précédentes vers 5.4.2 :

Veuillez créer et configurer des certificats internes à partir du scanner pour le contrôleur, l'exécuteur et l'adaptateur de registre afin d'assurer une mise à jour continue sans perte de données. Il est toujours recommandé de faire une sauvegarde de votre configuration avant la mise à niveau. 

Les étapes suivantes ne sont nécessaires que si votre déploiement utilise un fichier `+.yaml+`. La mise à niveau via Helm ne nécessite pas ces étapes supplémentaires en raison des certificats internes créés par défaut via les drapeaux suivants : `+internal.autoGenerateCert+` et `+internal.autoRotateCert+`.

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/ca.cert" > ca.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.pem" > tls.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.key" > tls.key
----

[,shell]
----
kubectl create secret generic internal-cert -n neuvector  --from-file=tls.key --from-file=tls.crt --from-file=ca.crt
----

Exemple de yaml 5.4.2 avec certificat interne configuré :
*https://github.com/neuvector/manifests/blob/main/kubernetes/5.4.0/neuvector-k8s.yaml* 

Zusätzliche Informationen zu xref:internal.adoc[internen Zertifikaten].


En cas de configuration PVC, les utilisateurs peuvent configurer un PVC existant dans la nouvelle installation pour restaurer une configuration.


**Remarque supplémentaire pour le scanner :**

Pour les utilisateurs actuels avec des versions antérieures à 5.4.2, le certificat restera disponible jusqu'au 31. Mars 2025 dans le `+neuvector/scanner:latest+`. Après cette date, il sera supprimé. Les utilisateurs doivent s'assurer qu'ils fournissent le même certificat interne au contrôleur, à l'exécuteur, au scanner et à l'adaptateur d'enregistrement pour continuer à utiliser le scanner.

Veuillez noter que le scanner autonome ne sera pas affecté par ces changements.

=== 5.4.1 Novembre 2024

==== Nouvelles fonctionnalités

* **NVSHAS-8583**: Définissez des modes de politique granulaires pour les ensembles de règles, le mode de politique réseau séparé et le mode de profil au niveau des groupes.
* **NVSHAS-9440**: Prise en charge du mode réseau séparé ainsi que du mode processus et fichier dans CRD.
* **NVSHAS-9369**: Fügen Sie eine Debug-Protokollkategorie über die Helm-Bereitstellung für den Controller hinzu.
* **NVSHAS-9040**: Améliorez le message Syslog lorsque la règle d'admission est rejetée en mode de surveillance.

==== Corrections d'erreurs

* **NVSHAS-9416**: [Scanner] activemq-all-5.8.0.redhat-60024.jar ne peut pas être détecté avec aucune vulnérabilité (mais la version précédente du scanner peut).
* **NVSHAS-9447**: Les pods de contrôleur/scanner se bloquent - "Sortie système non prise en charge".
* **NVSHAS-9278**: CVE-2024-41110 est trouvé dans la dernière image du scanner.
* **NVSHAS-9467**: Le groupe personnalisé défini par l'étiquette du pod ne propage pas ses données de profil aux conteneurs enfants.
* **NVSHAS-9442**: Problème de déploiement sur ArgoCD.
* **NVSHAS-9436**: Faux positif possible CVE contre CVE-2024-7347.
* **NVSHAS-9468**: Fix CVE-2020-26160 to replace jwt-go with jwt:v5.
* **NVSHAS-9517**: The admission rule is inconsistent and produces incorrect results.
* **NVSHAS-9532**: The image scan is complete, but deployment is still not allowed.
* **NVSHAS-9558**: The JWT token is expiring, reports http.StatusRequestTimeout 408.
* **NVSHAS-9576**: Remove the password field for the registration data when the user uses the controller mode with Jenkins for scanning.
* **NVSHAS-9425**: Create nfq when the container has vxlan.
* **NVSHAS-9571**: [Registries] Filter for all scanned images does not work well.
* **NVSHAS-9589**: Separate managed clusters - version incompatibility with the main cluster.
* **NVSHAS-8824**: The user cannot delete their own groups and cannot create groups in the namespace.
* **NVSHAS-9605**: Exporting a group with invalid values for policy mode and process profile mode is incorrectly allowed.
* **NVSHAS-9608**: The scanner does not report an error when the controller reports an error for huge scan results ~23MB.
* **NVSHAS-9534**: Afficher les erreurs dans les tests d'admission.
* **NVSHAS-9600**: Il n'est pas possible de désactiver le débogage du contrôleur.
* **NVSHAS-9631**: Réduire certains erreurs d'exécution.
* **NVSHAS-9645**: Le traitement CRD existant échoue.
* **NVSHAS-9592**: Aucun nouveau scan malgré la nouvelle version de la base de données.
* **NVSHAS-9212**: Afficher le message d'avertissement dans GET(/v1/eula) lorsque le rôle de neuvector-binding-secret (binding) est incorrect.
* **NVSHAS-9367**: Améliorer les messages d'erreur lorsque le registre ne peut pas être connecté.
* **NVSHAS-9475**: L'impression de la grille d'arrière-plan ne couvre pas complètement lorsque le menu est minimisé.
* **NVSHAS-9485**: Message incorrect pour 'Mode de Politique de Sécurité Réseau' dans l'interface utilisateur.
* **NVSHAS-9480**: L'interface utilisateur NV déployée sur le cluster sous Rancher renvoie HTTP/403 après la déconnexion de Rancher.
* **NVSHAS-9547**: Le tri est sur le tableau des risques de sécurité --> Les vulnérabilités sont cassées.
* **NVSHAS-9570**: [Vulnérabilités] Modifier la description de la légende pour différents statuts des actifs.
* **NVSHAS-9561**: La valeur de sécurité globale du tableau de bord doit correspondre à la valeur réelle.
* **NVSHAS-9572**: [Vulnérabilités] Les données filtrées ont été conservées sur la page, indépendamment de la mise à jour par l'utilisateur ou de la reconnexion.
* **NVSHAS-9597**: L'interface utilisateur ne réagit pas aux erreurs lorsque le contrôleur 403 renvoie pour POST(v1/group).
* **NVSHAS-8682**: Le service de webhooks CRD doit être déplacé du diagramme Helm crd au diagramme Helm de l'application.

==== Problèmes connus

* Dans la version 2.8.3 des graphiques, nous avons déplacé une ressource précédemment mal attribuée des CRDs vers le noyau. Si vous utilisez à la fois les graphiques CRD et le noyau, vous pourriez rencontrer des problèmes lors de la mise à niveau si vous déployez d'abord le noyau. Pour résoudre cela, mettez d'abord à jour les CRDs puis les graphiques du noyau.

=== 5.4 Septembre 2024

* **Améliorations de l'interface utilisateur**: 
** Afficher les utilisateurs SSO de Rancher.
** JWT-Token verwalten.
** Navigation d'image améliorée et liens vers les résultats de scan.
* **Améliorations de la sécurité**: 
** Nouveaux filtres de conformité.
** Support pour les benchmarks CIS et les signatures d'images OCI.
* **Réseau & Surveillance**: 
** Surveillance avancée de la bande passante et des sessions.
** DDoS-Überwachung.
** Support pour le réseau Multus.
* **Gestion des certificats**: 
** Neue Benachrichtigungen für ablaufende interne Zertifikate, einschließlich Rotationsmöglichkeiten.
* **Automatisation & Intégration**: 
** Automatisation de la fédération.
** Intégration RBAC de Rancher.
** Amélioration du contrôle d'accès.
* **Performance & Efficacité**: 
** Réduction de l'utilisation de la mémoire.
** Réduction des frais de données ISP.
** Affichage des statistiques de cache du scanner.
* **Améliorations de l'Utilisabilité**: 
** Support pour le mot de passe de démarrage.
** Archivierung von Cloud-Abrechnungsdaten.
** Application des limites de noms d'espace.

==== Nouvelles fonctionnalités

* **NVSHAS-9012**: Affichage des utilisateurs SSO Rancher dans l'interface NV avec le même nom d'utilisateur.
* **NVSHAS-8939**: Fournir une option dans l'interface NV pour que les utilisateurs de session SSO Rancher puissent supprimer le jeton JWT actuel (c'est-à-dire se déconnecter).
* **NVSHAS-7522**: Navigation simple à travers les images dans les onglets.
* **NVSHAS-8148**: Lien de l'image du conteneur aux résultats de scan d'image du registre.
* **NVSHAS-9258**: Ajout d'une nouvelle notification pour les certificats expirants et les certificats internes.
* **NVSHAS-8915**: Support pour de nouveaux filtres de conformité et rapport de conformité.
* **NVSHAS-9403**: Interface de surveillance de fichiers: Permettre à l'utilisateur de supprimer une règle de surveillance de fichier prédéfinie.
* **NVSHAS-8423**: Détection de la bande passante au niveau des groupes, du nombre de sessions actives et de la violation du taux de session en fonction des seuils configurés.
* **NVSHAS-9218**: Support pour les groupes fédéraux et CRD pour la surveillance DDoS.
* **NVSHAS-8461**: Support pour les benchmarks CIS pour les services k8s gérés dans le cloud.
* **NVSHAS-7664**: Réduire les frais de données des fournisseurs de services Internet lors de l'analyse du registre.
* **NVSHAS-8868**: Affichage des statistiques de cache du scanner.
* **NVSHAS-8676**: Amélioration de NV Protect pour les scripts de benchmark.
* **NVSHAS-9255**: Ajustement des registres de recherche pour le contrôle d'admission des noms d'images sans FQDN.
* **NVSHAS-9144**: ID ajoutée pour le fichier de contrôle des vulnérabilités pour une identification facile.
* **NVSHAS-7687**: Support de la configuration du niveau de journalisation (Débogage/Erreur/Info/Avertissement) pour l'Exécuteur et le Contrôleur via l'interface de ligne de commande.
* **NVSHAS-7518**: Changement des certificats internes pour les composants {product-name}.
* **NVSHAS-9287**: Activation de la rotation des certificats internes.
* **NVSHAS-8562**: Ajout d'une notification sur l'expiration des certificats internes.
* **NVSHAS-8486**: Support de l'interface réseau Multus.
* **NVSHAS-7447**: Intégration Rancher RBAC avec {product-name}.
* **NVSHAS-7822**: Automatisation de la fédération sans appels API de script.
* **NVSHAS-8799**: Créer un cadre de conformité pour importer des modèles de conformité.
* **NVSHAS-8773**: Support du mot de passe de démarrage lors du premier déploiement.
* **NVSHAS-6740**: Amélioration du profil de référence à zéro dérive en appliquant la liste apprise en mode protection.
* **NVSHAS-8325**: Faire respecter la limite de l'espace de noms du conteneur pour la règle réseau.
* **NVSHAS-8723**: Archivierung von Cloud-Abrechnungsdaten.
* **NVSHAS-9086**: Réduction de la consommation de mémoire du processus de contrôleur en éliminant la structure de données vulTrait.
* **NVSHAS-6979**: Capacité d'inclure le commentaire de la règle de réponse dans le contenu de l'alerte.
* **NVSHAS-8845**: Création d'une clé API avec le rôle FedReader et FedAdmin.
* **NVSHAS-9306**: L'évaluation de la configuration du contrôle d'accès montre l'ID de règle responsable des déploiements approuvés ou rejetés.
* **NVSHAS-9078**: Support de la signature d'image pour les images OCI.
* **NVSHAS-7945**: Support de la référence STIG DISA pour Kubernetes.
* **NVSHAS-8234**: Logique de contrôle d'approbation qui permet des images qui devraient être rejetées.

==== Corrections d'erreurs

* **NVSHAS-9005**: TypeError dans les registres: Impossible de lire les propriétés de non défini (lecture de 'total_records').
* **NVSHAS-9085**: Le rapport PDF de la vue d'actif montre 0 % de vulnérabilité, même s'il y a des vulnérabilités.
* **NVSHAS-9084**: Le rapport PDF de la vue d'actif montre NaN lorsque la liste des images est vide.
* **NVSHAS-9128**: Événements de sécurité : Le conteneur ne peut pas être affiché s'il n'y a pas de valeur pour l'espace de noms de la charge de travail.
* **NVSHAS-9025**: Domaine d'acceptation des vulnérabilités Neuvector pour les conteneurs.
* **NVSHAS-9155**: Nom de colonne incorrect et nom de fichier manquant lors de l'analyse du registre d'images.
* **NVSHAS-9122**: Les journaux principaux de Neuvector se déconnectent chaque fois que "Plusieurs clusters" est utilisé avec la connexion SSO Rancher.
* **NVSHAS-9266**: Analyse du registre: Le bouton de rapport pour l'analyse par couche doit être masqué ou désactivé s'il n'y a pas de vulnérabilité.
* **NVSHAS-9219**: Permettre aux utilisateurs d'activer la validation des certificats du serveur pour les serveurs d'authentification.
* **NVSHAS-9246**: Le filtrage pour l'exportation CSV/PDF ne fonctionne pas.
* **NVSHAS-8947**: Impossible d'importer la configuration NV lorsque l'authentification se fait via Rancher SSO.
* **NVSHAS-9282**: UI: L'édition de l'entrée du registre OpenShift échoue en raison d'un jeton manquant.
* **NVSHAS-9098**: Améliorer l'expérience utilisateur lors du chargement de la page des risques.
* **NVSHAS-9267**: L'interface utilisateur sur le cluster principal 5.4 ne doit pas passer à des clusters gérés avant 5.4, en raison de modifications de l'API REST.
* **NVSHAS-9285**: INTERFACE UTILISATEUR : Le bouton déroulant chevauche d'autres éléments.
* **NVSHAS-9302** : Il n'est pas possible de créer une APIKEY avec le rôle FedReader et FedAdmin.
* **NVSHAS-8539** : La reconfiguration des paramètres de proxy perd le mot de passe.
* **NVSHAS-9293** : Suppression des détails d'image non liés dans les rapports de vulnérabilité.
* **NVSHAS-9238** : L'interface utilisateur ne rafraîchit pas le nom du cluster affiché après qu'il a été changé.
* **NVSHAS-9363** : Paramètres de notification > La grille des webhooks n'est pas correctement alignée.
* **NVSHAS-9362** : Le filtre des vulnérabilités de risque de sécurité ne renvoie aucun résultat.
* **NVSHAS-8699** : Il n'est pas possible de distinguer l'utilisateur lorsque l'utilisateur AD de Rancher est le même.
* **NVSHAS-9062** : Afficher les utilisateurs SSO de Rancher dans l'interface utilisateur NV avec le même nom d'utilisateur (conversion sur le contrôleur).
* **NVSHAS-9071** : Certains modules ne sont signalés que dans l'analyse des conteneurs.
* **NVSHAS-8242**: appel gRPC pour tester si le contrôleur gère la gravité critique.
* **NVSHAS-8908**: Analyser correctement le port X-Forwarded en tenant compte du séparateur de virgule.
* **NVSHAS-9024**: Rôle risqué de la performance du contrôle d'admission.
* **NVSHAS-9091**: Il n'est pas possible de signaler tous les modules sous ol:9.1, photon:5.0, rhel:9.1 et amzn:2023 dans le dépôt, dans la registry et dans l'analyse autonome.
* **NVSHAS-8997**: Réduire considérablement le nombre de slots de politiques par nœud pour améliorer les performances.
* **NVSHAS-9059**: Les groupes CRD sont visibles dans NV, même après la suppression de K8s.
* **NVSHAS-9107**: Crash de goroutine à rest.handlerConfigLocalCluster.
* **NVSHAS-9108**: Le port 18500 ne doit pas être ouvert.
* **NVSHAS-9119**: Crash de goroutine à probe.(*FileNotificationCtr).AddContainer().
* **NVSHAS-9125**: Une entrée CRD avec des paramètres invalides ne devrait pas pouvoir être créée.
* **NVSHAS-9124**: Docker: De nombreux incidents inattendus lors de la vérification de l'état sont signalés.
* **NVSHAS-9111** : NV doit vérifier `+--event-qps > 0+`.
* **NVSHAS-9130** : Des incidents inattendus de Container.Package.Updated sont trouvés après le démarrage d'un conteneur spécifique.
* **NVSHAS-9080** : L'utilisateur du disque Fed ne peut pas accéder à certaines API REST.
* **NVSHAS-9092** : L'espace de noms de l'utilisateur ne devrait pas voir de ressources globales.
* **NVSHAS-9116** : Le cluster de travail peut s'arrêter si la connexion est interrompue.
* **NVSHAS-8980** : Obtenez l'hôte et l'interface de tunnel sur le nœud avec succès dans oc 4.15.
* **NVSHAS-9188** : Définir l'interface mgmt-br comme interface hôte pour le nœud de récolteur.
* **NVSHAS-4858** : Ne continuez pas à développer le groupe de conteneurs dans le contrôleur pour améliorer les performances de déploiement de la stratégie et réduire l'utilisation du CPU et de la mémoire.
* **NVSHAS-8700** : L'utilisateur AD de Rancher ne peut parfois pas se connecter à {product-name}.
* **NVSHAS-9121** : Le paramètre de seuil de surveillance du réseau du groupe ne peut pas être modifié.
* **NVSHAS-9189** : Le scan se bloquera dans la planification après que le contrôleur soit arrêté et redémarré.
* **NVSHAS-9019** : Corriger l'état du lien non synchronisé pour l'interface hôte.
* **NVSHAS-8305** : Supprimer le certificat intégré.
* **NVSHAS-9013** : Supprimer le filtre BPF du moniteur de processus.
* **NVSHAS-7853** : EOF de la poignée TLS.
* **NVSHAS-9290** : La règle de profil de processus ajoutée par l'utilisateur n'a aucun effet lorsque ZD est activé.
* **NVSHAS-9301** : NV, qui est déployé sur Rancher Prime, ne peut pas afficher son goût Rancher.
* **NVSHAS-9289** : Autoriser la mise à niveau lorsque RBAC est manquant.
* **NVSHAS-7601**: Améliorer la récupération à partir de la sauvegarde de configuration PV pendant les scénarios.
* **NVSHAS-7687**: Ajouter le paramètre de niveau de journalisation Syslog pour l'appliquer.
* **NVSHAS-9292**: Corriger l'exposition Ingress Egress qui montre 0 vulnérabilités.
* **NVSHAS-9270**: Supporter k3s pour le pipeline de référence CIS.
* **NVSHAS-9338**: Alerte 'Cluster géré [id] est déconnecté du principal'.
* **NVSHAS-9358**: L'analyse d'image avec un proxy échouerait.
* **NVSHAS-9337**: Envoyer un message de journal lorsque l'attaque par SYN-Flood est détectée.
* **NVSHAS-9209**: Supprimer le cache de domaine lorsque l'espace de noms est supprimé de k8s.
* **NVSHAS-8985**: Les registres fédérés disparaissent après le redémarrage du contrôleur.

==== Problème connu:

* **NVSHAS-9443**: La mise à niveau/l'installation via ArgoCD échoue car l'objet leases.coordination.k8s.io ne peut pas être créé.
* **Solution de contournement**: Créer les objets de bail donnés avant de mettre à niveau vers 5.4.0 en utilisant ARGO CD. Changez l'espace de noms s'il est différent de neuvector.
+
--
[,bash]
----
cat <<EOF | kubectl apply -f -
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-controller
  namespace: neuvector
spec:
  leaseTransitions: 0
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-cert-upgrader
  namespace: neuvector
spec:
  leaseTransitions: 0
EOF
----
--

=== 5.3.4 Juillet 2024

==== Corrections de bogues

* Les interfaces `+host+` et `+tunnel+` ont été récupérées avec succès avec OpenShift CLI v4.15.
* Le domaine IP 169.254.x.x est exclu des IPs d'interface hôte.
* Réexaminez l'interface hôte après 1 minute de démarrage de l'enforcer.
* Correction d'un problème où l'URL du fournisseur OpenID échouait à cause de la regex.
* Corrige les CVEs suivants:
+
|===
| CVE | S'applique à | Auswirkungen

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.2.4-s5 Juillet 2024

* Corrige les CVEs suivants:

|===
| CVE | S'applique à | Auswirkungen

| CVE-2023-42363
| busybox
| {CVE-medium}

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2023-42366
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4603
| openssl
| {CVE-medium}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.3.3 Juin 2024

==== Améliorations

* Permet aux utilisateurs de bloquer l'utilisation de certaines classes de stockage depuis la page `+Admission Controls+`.
* Le `+LDAP Authentication+` a des champs séparés pour la configuration `+baseDN+` et `+groupDN+`.
* Le `+Egress and Ingress chart+` a une nouvelle colonne de vulnérabilité de sécurité qui contient le nombre de vulnérabilités de sécurité `+High+` et `+Medium+` pour chaque service.

==== Corrections de bogues

* Correction d'un bug lié à `+regex+` lors de l'utilisation d'une virgule (`+,+`) dans une entrée Multi-`+Admission Control user criteria+`.
* Correction d'un bug où le scan CVE des paquets `+jar+` n'affichait pas tous les paquets affectés par le même CVE. Tous les occurrences sont maintenant signalées.
* Corrige les CVEs suivants:

|===
| CVE | S'applique à | Auswirkungen

| CVE-2024-35195
| python:requests
| {CVE-medium}

| CVE-2024-21011
| openjdk11
| {CVE-low}

| CVE-2024-21012
| openjdk11
| {CVE-low}

| CVE-2024-21068
| openjdk11
| {CVE-low}

| CVE-2024-21085
| openjdk11
| {CVE-low}

| CVE-2024-21094
| openjdk11
| {CVE-low}
|===

==== Sonstiges

* Permettre aux utilisateurs de définir des ressources pour `+updater-cron-job+` lors de l'installation de {product-name} avec le diagramme Helm.
* Versionnage du conteneur de l'exportateur Prometheus révisé et dissocié du versionnage de `+controller+`.
* (Scanner) Détecter le paquet/module `+R+` dans Ubuntu et Red Hat Enterprise Linux.
* (Scanner) Support ajouté pour le scan PHP Composer.

=== 5.2.4-s3 Avril 2024

* Corrige les CVEs suivants:

|===
| CVE | S'applique à | Auswirkungen

| CVE-2021-40633
| giflib
| {CVE-high}

| CVE-2023-48161
| giflib
| {CVE-high}

| CVE-2024-28757
| Expat
| {CVE-high}

| CVE-2023-39742
| giflib
| {CVE-medium}

| CVE-2023-45288
| go:golang.org/x/net
| {CVE-medium}

| CVE-2024-25629
| c-ares
| {CVE-medium}

| CVE-2024-3651
| python:idna
| {CVE-medium}

| CVE-2024-2511
| openssl
| {CVE-low}
|===

=== 5.3.2 Avril 2024

==== Corrections de bogues

* Après la mise à niveau vers v5.3.1 depuis une version précédente {product-name}, les ressources NvClusterSecurityRule personnalisées existantes peuvent être supprimées par inadvertance. REMARQUE : La version 5.3.1 a été retirée du Docker Hub pour éviter le problème de mise à niveau.

=== 5.3.1 Avril 2024

[IMPORTANT]
====
La version 5.3.1 a été retirée du Docker Hub pour éviter le problème de mise à niveau qui a été corrigé dans 5.3.2. Veuillez utiliser la version 5.3.2.
====

==== Améliorations

* Permettre aux utilisateurs de définir des vulnérabilités '\`+accepted\+`' lors de l'utilisation des actions Github afin qu'elles n'affectent pas les workflows.
* Ajouter des filtres de gravité, de score et d'évaluation à Assets > Registry > Vue des vulnérabilités d'image.
* Permettre de spécifier lors de la configuration d'un registre si le proxy défini doit être utilisé pour les analyses d'images du registre.

==== Corrections de bogues

* Risques de sécurité > Vulnérabilités > Le filtre avancé ne filtre pas 'CVE sans correctif'.
* Violation inattendue de conteneur à conteneur en mode hôte.
* Accepter le format d'image OCI lors du passage à l'API Docker 1.24.
* L'analyse du registre ne doit pas analyser les artefacts non-image / ne pas enregistrer d'erreurs.
* Permettre la vérification de la signature d'image des paires de clés sans dépendance root, Internet ou sigstore.
* Événements de sécurité non autorisés par des règles réseau dans un nœud spécifique (liés aux messages d'erreur "Container Task chan full").
* Le conteneur ne peut pas être ajouté avec succès à la tâche (occurrences fréquentes). Résultant d'un blocage des messages de canal.

==== Sonstiges

* Mettre à jour les plugins de scanner pour Jenkins, l'action GitHub et Bamboo.
* (Scanner) Accepter le format d'image OCI lors du passage à l'API Docker 1.24.
* (Scanner) L'analyse du registre ne doit pas scanner les artefacts non-image / ne pas enregistrer d'erreurs.
* (Scanner) Ajouter le support pour l'analyse de PHP Composer.

==== {product-name} Extension UI v. 1.0 pour Rancher Mars 2024

* Après l'installation de {product-name}, l'xref:rancher.adoc#_suse_security_ui_extension_for_rancher[activation/installation] de l'extension UI {product-name} de Rancher affichera un tableau de bord pour le cluster, y compris des liens vers SSO pour le cluster complet {product-name}. REMARQUE : L'extension peut être affichée comme un tiers, ce qui sera corrigé dans une version future. De plus, les utilisateurs de Rancher 2.7.x peuvent voir deux icônes {product-name} UI Ext dans la liste après l'installation (erreur). Une icône indique Désinstaller (ce qui signifie qu'elle est installée), et l'autre devrait dire Installer. Cela peut rester ainsi, c'est-à-dire ne pas réinstaller si l'extension est déjà installée.

=== 5.2.4-s2 Février 2024

* Corrige les CVEs suivants:
* Haute CVE : CVE-2023-52425 dans Expat, CVE-2024-20952 et CVE-2024-20918 dans OpenJDK11
* Moyenne CVE : CVE-2023-52426 dans Expat, CVE-2024-20926, CVE-2024-20921, CVE-2024-20945 et CVE-2024-20919 dans OpenJDK11, CVE-2024-0727 et CVE-2023-6237 dans OpenSSL

=== 5.3.0 Février 2024

==== Améliorations

* Afficher les URL cibles externes (FQDN) dans le tableau de bord (Egress), dans les rapports PDF et CSV ainsi que dans l'écran d'activité réseau et les listes d'événements de sécurité (violations).
* Apprendre automatiquement les sorties vers des groupes FQDN externes en mode découverte. Un nouveau groupe FQDN externe personnalisé est créé, sauf si la connexion externe correspond à une règle existante.
* Activez l'apprentissage ICMP (mode découverte) et le blocage (mode protection) via la nouvelle variable d'environnement du contrôleur CTRL_EN_ICMP_POLICY = 1
* Exporter les CRDs vers Github pour prendre en charge gitops vers un dépôt standard via la console ou l'API REST.
* Prendre en charge la connexion unique SAML SSO avec ADFS iDP
* Ajouter la prise en charge de la plateforme ARM64. Le tirage des plateformes basées sur ARM tire automatiquement les images ARM64 correspondantes {product-name}.
* Prendre en charge les webhooks via un proxy
* Améliorer la fonction d'audit du contrôle d'admission pour inclure les résultats de toutes les règles. Écoutez le résultat de chaque règle et ajoutez une autre entrée pour l'action finale qui sera exécutée lorsqu'elle sera évaluée dans un déploiement de contrôle d'admission en direct.
* Appliquez les règles d'admission désactivées via CRD ou yaml (kubectl).
* Exporter/Importer le profil de vulnérabilité via la console, CRD ou REST-API. L'import remplace le profil existant. La suppression du CRD entraîne un profil vide.
* Exporter/Importer le modèle de profil de conformité via la console, CRD ou REST-API. L'import remplace le modèle existant.
* Ajoutez un statut 'Manuel' dans les rapports de conformité pour les benchmarks CIS qui doivent être exécutés manuellement par les utilisateurs (non exécutés par {product-name}).
* Améliorer le chargement/performance de l'interface utilisateur de la page des vulnérabilités.
* Vereinheitlichen Sie die Browsersitzungsverbindung. Ainsi, tous les onglets dans le navigateur partagent la même session de connexion, l'ouverture d'un nouvel onglet à partir d'une session existante ne nécessite pas d'identifiants, et si un onglet se déconnecte, tous les onglets se déconnectent.
* Améliorations de la sécurité de la console (UI) : 1) Ajoutez des en-têtes de sécurité requis (X-Content-Type-Options nosniff; X-XSS-Protection 1; mode=block; X-Frame-Options SAMEORIGIN; Cache-Control privé, no-cache, no-store, must-revalidate
HTTP Strict Transport Security max-age=15724800, 2) Ajoutez un en-tête CSP (z. B. eine Richtlinie '\`+default-src\+`' festlegen), 3) Entfernen Sie die Offenlegung des Servernamens.
* Support pour les versions plus récentes des benchmarks CIS. Kubernetes (1.8.0), Kubernetes V1.24 (1.0.0), Kubernetes V1.23 (1.0.1), RedHat OpenShift Container Platform (1.4.0).
* Afficher dans les actifs -> Conteneur -> Détails des conteneurs qui ont été analysés dans les registres par rapport à l'exécution.
* Ajouter un lien vers le groupe dans les risques de sécurité -> vulnérabilités -> popup impacts pour changer facilement le mode groupe.
* Support pour les liens profonds dans les URL vers la page de vulnérabilité des images et/ou des conteneurs.
* Ajouter une option de réinitialisation de mot de passe pour l'administrateur afin de réinitialiser le mot de passe de l'utilisateur dans les paramètres de la console -> utilisateur.
* L'envoi de journaux d'événements aux journaux du contrôleur de pod dans les paramètres -> Configuration -> Autoriser la notification. Les événements envoyés commencent par 'notification=' et ne sont enregistrés que dans le contrôleur de pod principal. Veuillez noter qu'il y a un bug dans cette version où SYSLOG doit être activé pour changer le niveau d'événement (et peut être désactivé après le changement de niveau si souhaité).
* Supprimer la demande pour le contrôleur/enforcer de monter "/host/cgroup".
* Ajouter le menu d'aide avec des liens vers Slack, la documentation et d'autres ressources.
* Remplir le champ de message pour /v1/log/activity logs.

==== Corrections de bogues

* Erreur interne du serveur dans les risques de sécurité -> Vulnérabilités avec un grand nombre de CVEs.
* SIGSEGV: Erreur de segmentation dans le contrôleur.
* Das Löschen von verwundbaren Dateien (z.  jar) ne les supprime pas de la liste des vulnérabilités.
* Certificat Syslog invalide avec l'algorithme de signature SHA256withECDSA.
* {product-name} montre les événements de sécurité qui devraient être autorisés par une règle réseau
* Nœud non géré avec un enforcer "zombie" en cours d'exécution.
* Le filtre avancé affiche des champs vides pour la correction et les impacts.
* Corriger la gestion des chaînes pour éviter un redémarrage inattendu de l'enforcer.
* Violations inattendues concernant les groupes intégrés.
* Appel RPC de débogage de l'enforcer de bundle de support pour les données renvoie une erreur.
* Le groupe ne correspond pas dans les événements de sécurité.
* L'envoi d'événements à Slack ne fonctionne pas - avec un proxy.
* Affichage des événements de sécurité pour les règles réseau autorisées

==== Sonstiges

* Ajouter la détection automatique de l'environnement d'exécution des conteneurs (Socket) pour l'exécution dans le diagramme Helm.
* Supprimer le paramètre pour exécuter le contrôleur en mode privilégié dans le diagramme Helm et la demande de montage du contrôleur/Enforcer, "/host/cgroup".
* Les fichiers d'exemple pour le déploiement Kubernetes ont été supprimés des documents {product-name}. Veuillez vous référer au lien pour des exemples.

==== Modifications mises en évidence qui peuvent nécessiter des changements pour les déploiements manuels (toutes les modifications sont déjà reflétées dans le dernier diagramme Helm pour 5.3.x).

* La détection automatique de l'environnement d'exécution des conteneurs (Socket) élimine la nécessité de spécifier l'environnement d'exécution des conteneurs et le chemin du socket.
* La suppression de l'exigence d'exécuter le contrôleur en mode privilégié élimine la nécessité de monter le socket d'exécution et de monter /host/cgroup/.
* Ajout de rôle/lien de rôle pour neuvector-binding-secret ainsi que neuvector-secret dans yaml.
* Nouveaux comptes de service et liaisons de rôle requises pour 5.3
* Tous les fichiers yaml de déploiement référencés ont maintenant /5.3.0/ dans leurs chemins

=== 5.2.4-s1 Janvier 2024

==== Publication de correctif de sécurité

* Remédie à CVE-2023-6129 dans openssl, et CVE-2023-46219, CVE-2023-46218 dans curl.

=== 5.2.4 Novembre 2023

==== Corrections de bogues

* Modifications à Azure AKS ValidatingWebhookConfiguration et journalisation des erreurs.

=== 5.2.3 Novembre 2023

==== Améliorations

* Ajoutez le support pour l'API NVD 2.0 dans le scanner.
* Analysez l'hôte du conteneur en mode autonome du scanner.

[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n
----

==== Corrections de bogues

* L'analyse sur un nœud échoue en raison d'un problème de blocage de docker cp / grpc.

=== 5.2.2-s1 Octobre 2023

==== Sicherheitsupdate

* Mettez à jour les paquets pour corriger les CVEs, y compris CVE-2023-38545 et CVE-2023-43804.

=== 5.2.2 Octobre 2023

==== Avis de sécurité pour CVE-2023-32188

* Corrigez CVE-2023-32188 "\`+la compromission du jeton JWT peut entraîner des actions malveillantes, y compris l'exécution de code à distance (RCE)\+`" en générant automatiquement le certificat utilisé pour signer le jeton JWT lors du déploiement et de la mise à jour, et en générant automatiquement le certificat pour le gestionnaire/API RESTful lors des déploiements basés sur Helm.
 ** Le certificat pour la signature JWT est automatiquement créé par le contrôleur avec une validité de 90 jours et est automatiquement tourné.
 ** La génération automatique du certificat du gestionnaire, de l'API REST et de l'adaptateur de registre nécessite l'utilisation d'une installation basée sur Helm avec {product-name} la version helm 2.6.3 ou supérieure.
 ** Le certificat intégré est toujours utilisé pour les déploiements basés sur yaml, sauf s'il est remplacé lors du déploiement ; il est cependant recommandé de les remplacer (voir la ligne suivante).
 ** Le xref:replacecert.adoc[remplacement manuel du certificat] est toujours pris en charge et recommandé pour les versions antérieures ou les déploiements basés sur yaml. Voir l'{product-name} avertissement de sécurité GitHub https://github.com/neuvector/neuvector/security/advisories/GHSA-622h-h2p8-743x[ici] pour une description.
 ** L'utilisation de certificats personnalisés est toujours prise en charge comme auparavant pour les déploiements basés sur Helm et yaml.
* Fügen Sie zusätzliche Kontrollen für benutzerdefinierte Compliance-Skripte hinzu. Par défaut, les scripts personnalisés ne peuvent maintenant pas être ajoutés, sauf si la variable d'environnement CUSTOM_CHECK_CONTROL est ajoutée au contrôleur et à l'enforcer. Les valeurs sont "désactiver" (par défaut non autorisé), "strict" (rôle Admin uniquement) ou "libéral" (rôles Admin, Conformité et Politiques d'exécution).
* Prévenir l'injection LDAP - le champ nom d'utilisateur est échappé.

==== Améliorations

* Ajoutez des données de scan supplémentaires aux résultats CVE envoyés par SYSLOG pour les scans de couche
* Prise en charge de l'API NVD 2.0 pour la base de données de scan CVE
* Indiquez la date de construction de l'image du conteneur dans les détails de l'actif -> Conteneur
* Ajustez le tri pour les règles réseau : Désactiver le tri dans la vue des règles réseau, mais activer le tri des règles réseau dans la vue des groupes.
* Activer/désactiver la détection/l'alerte de TLS 1.0 et TLS 1.1 avec des variables d'environnement pour l'enforcer THRT_SSL_TLS_1DOT0, THRT_SSL_TLS_1DOT1. Standardmäßig deaktiviert.
* Ajoutez la variable d'environnement AUTO_PROFILE_COLLECT pour le contrôleur et l'enforcer afin de capturer l'utilisation de la mémoire lors de la vérification des événements de mémoire. Définissez la valeur = 1 pour activer.
* Les évaluations de configuration par rapport au contrôle d'admission doivent afficher toutes les violations avec un seul scan.
* Ajoutez d'autres options pour les critères de rapport CVE dans les règles de réponse. Exemple 1 - "cve-high-with-fix:X" signifie : Si le nombre de (vulnérabilités critiques corrigées) >= X, déclencher la règle de réponse. Exemple 2 - "cve-high-with-fix:X/Y" signifie : Si le nombre de (vulnérabilités critiques signalées il y a Y jours et corrigées) >= X, déclencher la règle de réponse.

==== Corrections de bogues

* L'exportation de la stratégie de groupe ne renvoie aucun contenu YAML réel.
* Améliorez l'élagage des espaces de noms avec une fonction spéciale.
* {product-name} L'utilisateur de l'espace de noms ne peut pas voir les actifs-->Espaces de noms.
* Ignorez le traitement des demandes de CRD CREATE/UPDATE si l'espace de noms du CR a déjà été supprimé.
* Fournissez une solution de contournement pour une partie des groupes CRD qui ne peuvent pas être correctement élagués après la suppression des espaces de noms.

=== 5.2.1 Août 2023

==== Améliorations

* Rapportez les résultats des scans superposés et des données CVE supplémentaires dans les messages SYSLOG. Cela est activé par une case à cocher dans les paramètres -> Configuration -> SYSLOG.
* Exportez les correspondances NIST 800-53 (vers les benchmarks CIS-Docker) dans le rapport de conformité CSV exporté.
* Prenez en charge le paramètre proxy lors de la vérification de la signature de l'image.
* Inclure le résultat du scan de signature d'image dans le rapport CVE téléchargé.
* Prenez en charge les annotations de Pod pour les politiques d'admission disponibles via des critères personnalisés.
* Ajoutez le champ Dernière modification pour filtrer l'impression des rapports de vulnérabilités, ainsi que le filtre avancé dans la vue des vulnérabilités.

==== Corrections de bogues

* Ne créez pas d'administrateur par défaut avec un mot de passe par défaut lors du déploiement initial {product-name} pour l'offre de facturation AWS (adaptateur CSP), ce qui nécessite que l'utilisateur utilise un secret pour créer un nom d'utilisateur et un mot de passe administrateur.
* Corrigez le fichier .json qui a augmenté en taille et a fait planter un nœud Kubernetes.
* Améliorer la logique de détection des injections SQL
* Lors de l'installation du diagramme Helm-CRD d'abord, avant que le diagramme principal {product-name} ne soit installé, les comptes de service manquent.
* Le résultat de conformité de l'analyse d'image I.4.1 est incorrect
* Le rapport de filtre avancé sur les vulnérabilités montre des images de tous les autres espaces de noms.

=== 5.2.0 Juillet 2023

==== Améliorations

* Prise en charge des jetons pour accéder à l'API {product-name}. Voir les paramètres -> utilisateur, clé API ... pour créer une nouvelle clé API. Les clés peuvent être définies sur des rôles par défaut ou personnalisés.
* Prise en charge de la facturation PAYG sur le marché AWS pour les abonnements de support mensuels {product-name}. Les utilisateurs peuvent s'inscrire pour {product-name} via le support SUSE, qui est facturé mensuellement sur leur compte AWS en fonction de l'utilisation moyenne du nombre de nœuds du mois précédent. Détails https://open-docs.neuvector.com/deploying/awsmarketplace[ici].
* Prise en charge de la signature des images pour les contrôles d'admission. Les utilisateurs peuvent {product-name} demander pour vérifier que les images sont signées par certaines parties avant de pouvoir être déployées en production, grâce à une intégration avec Sigstore/Cosign. Voir les actifs -> vérificateur Sigstore pour créer de nouveaux actifs de signature. Des règles peuvent ensuite être créées avec les critères de signature d'image et/ou de vérificateur d'image Sigstore.
* Activez chaque règle pour les contrôles d'admission afin qu'elle ait son propre mode de surveillance ou de protection. Une action de rejet en mode de surveillance déclenchera une alarme, et une action de rejet en mode de protection bloquera. Les actions autorisées ne sont pas affectées.
* Ajoutez un nouvel opérateur Regex dans Politique > Contrôle d'admission > Ajouter une règle pour les utilisateurs et les groupes d'utilisateurs afin de prendre en charge Regex. Prise en charge des opérateurs "correspond à tout Regex dans" et "ne correspond à aucun Regex dans".
* Ajoutez la prise en charge des critères de contrôle d'admission tels que les limites de ressources. Un nouveau critère est ajouté pour les limites de ressources, et des critères supplémentaires sont pris en charge via les paramètres de critères personnalisés.
* Prise en charge de l'appel du {product-name} Scanner des registres Harbor via l'interface https://github.com/goharbor/pluggable-scanner-spec[scanneur pluggable]. Cela nécessite la configuration de la connexion au contrôleur (API exposée). L'adaptateur Harbor appelle le point de terminaison du contrôleur pour déclencher un scan qui peut être effectué automatiquement lors du push. Les services de requête peuvent être utilisés pour des scans réguliers. Les résultats de scan des contrôleurs principaux de la fédération sont propagés aux clusters distants.  REMARQUE : Il y a un problème avec l'erreur du point de terminaison de l'adaptateur basé sur HTTPS : Veuillez ignorer l'erreur de test de connexion, cela fonctionne même si une erreur est affichée (ignorer la validation du certificat).
* Service SaaS interrogeable pour les recherches CVE. Parcourez la dernière base de données {product-name} CVE pour voir si un CVE spécifique est présent dans la base de données. Ce service est disponible pour les clients {product-name} Prime (abonnement de support payant). Contactez le support via votre portail SCC pour l'accès.
* Permettre à l'utilisateur de désactiver la protection réseau, mais de garder WAF/DLP actif. Configurer l'activation de la politique réseau dans les paramètres de configuration ->.
* Utilisez des comptes de service moins privilégiés pour chaque composant {product-name} si nécessaire. Une variable "\`+leastPrivilege\+`" est introduite. La valeur par défaut est fausse. REMARQUE : L'utilisation du diagramme Helm actuel avec cette variable dans une version antérieure à 5.2.0 ne fonctionne pas correctement.
* Liez un compte de service non standard pour répondre à la recommandation CIS 1.5 5.1.5.
* Activez l'administrateur pour configurer le délai d'expiration de session par défaut de l'utilisateur dans les paramètres -> utilisateurs, clés API et rôles.
* Bannières de connexion personnalisables et texte d'en-tête UI personnalisable pour les déploiements réglementés et gouvernementaux. Les exigences pour la configuration se trouvent xref:customui.adoc[ici].
* Support SYSLOG pour le transport chiffré TLS. Sélectionnez TCP/TLS dans les paramètres -> Configuration pour SYSLOG.
* Activez le déploiement du {product-name} diagramme Helm de Monitor via Rancher Manager.
* Supprimez la limite supérieure pour le domaine de premier niveau dans le validateur d'URL pour le scan de registre.
* Scannez les dépendances Golang, y compris les scans en temps réel.
* Supportez le scan de vulnérabilités pour Debian 12 (Bookworm).
* Ajoutez l'exportation CSV pour le registre / détails afin d'exporter les CVEs pour toutes les images dans le registre configuré dans les actifs -> Registries pour un registre sélectionné.
* Permettez à {product-name} de définir plusieurs certificats ADFS en parallèle dans le champ de certificat x.509.
* Ajoutez le champ de commentaire pour les règles de réponse et affichez-le.
* Indiquez ce que {product-name} considère comme un conteneur système via une variable d'environnement. Par exemple pour Rancher et les espaces de noms par défaut : NV_SYSTEM_GROUPS=*cattle-system;default
* Ajouter le support pour Kubernetes 1.27 et OpenShift 4.12

==== Corrections de bogues

* Réduire les journaux répétitifs dans les journaux de l'enforcer/controller.
* La page pour plusieurs clusters n'est pas rendue.
* La suppression automatique du groupe vide prend 2 heures pour être supprimée, au lieu de 1 heure selon le calendrier.
* La règle réseau manuellement autorisée n'est pas appliquée et entraîne une violation pour l'image de pause.
* Blocage des connexions SSL, même si une règle réseau autorise le trafic sous certaines conditions initiales.
* Les événements de sécurité avertissent même avec des règles réseau autorisées en raison d'un problème de mise à jour de la politique dans la synchronisation.
* Activités réseau qui associent à tort le trafic de groupes personnalisés à l'extérieur.
* Le jeton de compte de service par défaut du namespace, monté dans chaque pod, a trop de permissions.
* Malgré la définition des règles réseau, des violations sont enregistrées parmi les événements de sécurité (faux positifs) lorsque le conteneur a été arrêté en raison d'une erreur de mémoire insuffisante (OOM).
* Permettre à l'utilisateur de désactiver/activer la détection et la protection contre les conteneurs non gérés dans le cluster. Cela peut être défini via l'interface de ligne de commande du gestionnaire :

[,shell]
----
set system detect_unmanaged_wl status -h
Usage: cli set system detect_unmanaged_wl status [OPTIONS] {true|false}

  Enable/disable detect unmanaged container
----

==== Sonstiges

* Ajoutez le paramètre "leastPrivilege" dans le diagramme Helm. Fügen Sie die Helm-Option für New_Service_Profile_Baseline hinzu. Une nouvelle version du diagramme Helm (noyau) sera publiée pour 5.2.
* Activez les paramètres d'intégration AWS Marketplace (adaptateur de facturation) dans le diagramme Helm.
* Mettez à jour le ConfigMap pour prendre en charge de nouvelles fonctionnalités (plusieurs certificats ADFS, Null-Derivation, New_Service_Profile_Baseline, SYSLOG TLS, délai d'attente utilisateur)
* Mettez à jour les versions Kubernetes prises en charge à 1.19+ et OpenShift 4.6+ (1.19+ avec CRI-O)

=== 5.1.3 Mai 2023

==== Améliorations

* Fügen Sie einen neuen Schwachstellen-Scan für das Microsoft .NET-Framework hinzu.
* Les statistiques de l'Enforcer sont désactivées par défaut dans l'exportateur Prometheus pour améliorer la scalabilité.
* Amélioration de l'utilisabilité : Utilisez le scanner pour analyser une seule image et imprimer le résultat (voir exemple ci-dessous).
* Ajouter une vérification de imagePullPolicy dans les critères des règles de contrôle d'admission.
* Affichez un message d'avertissement lorsque le schéma CRD est obsolète.

==== Corrections de bogues

* L'écran d'activité du réseau ne s'affiche pas ou s'affiche incorrectement.
* La suppression automatique du groupe vide prend 2 heures pour être supprimée, au lieu de 1 heure selon le calendrier.
* Le fichier de contrôle de conformité n'est pas affiché dans la console UI.
* Le filtre avancé dans les événements de sécurité manque le niveau "Erreur".
* Un mot de passe contenant un caractère spécial échoue lors d'une tentative d'authentification future.
* La page pour plusieurs clusters ne s'affiche pas correctement lorsque les demandes sont élevées.
* Le champ de détail du registre (en bas) ne se met pas à jour.

==== Sortie d'échantillon du scanner

[,shell]
----
Image: https://registry.hub.docker.comlibrary/alpine:3.4
Base OS: alpine:3.4.6
TOTAL: 6, HIGH: 1, MEDIUM: 5, LOW: 0, UNKNOWN: 0
┌─────────┬───────────────┬──────────┬───────────┬───────────────┬────────────┐
│ PACKAGE │ VULNERABILITY │ SEVERITY │ VERSION   │ FIXED VERSION │ PUBLISHED  │
├─────────┼───────────────┼──────────┼───────────┼───────────────┼────────────┤
│ openssl │ CVE-2018-0732 │ High     │ 1.0.2n-r0 │ 1.0.2o-r1     │ 2018-06-12 │
│         ├───────────────┼──────────┤           ├───────────────┼────────────┤
│         │ CVE-2018-0733 │ Medium   │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0734 │          │           │ 1.0.2q-r0     │ 2018-10-30 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0737 │          │           │ 1.0.2o-r2     │ 2018-04-16 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0739 │          │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-5407 │          │           │ 1.0.2q-r0     │ 2018-11-15 │
└─────────┴───────────────┴──────────┴───────────┴───────────────┴────────────┘
----

=== 5.1.2 März 2023

==== Améliorations

* Support pour le groupe d'adresses basé sur l'hôte et la stratégie de correspondance des règles de protection réseau. Cela permet un cas d'utilisation où deux adresses FQDN différentes sont résolues sur la même adresse IP, mais des règles différentes doivent être appliquées pour chaque FQDN. Un nouveau groupe personnalisé avec '\`+address=vh:xxx.yyy\+`' peut être créé en utilisant le commutateur '\`+vh:\+`' pour activer cette protection. Une règle réseau peut alors utiliser le groupe personnalisé comme source '\`+From\+`' basé sur le nom d'hôte virtuel (plutôt que l'adresse IP résolue) pour appliquer des règles différentes pour les hôtes virtuels.
* Liste des conteneurs de conformité à exclure des conteneurs émis.
* Améliorer les règles DLP pour prendre en charge le caractère générique simple dans le modèle.
* Ajouter le support pour cri-o 1.26+ et OpenShift 4.11+.
* Rendre Gravatar optionnel.
* Afficher la ressource du namespace du cluster dans la console / UI.
* La gravité/classification de la source (z. B. Red Hat, Ubuntu...) afficher avec le score de gravité NVD dans la console.
* Ne pas permettre la désactivation de SSO/RBAC pour Rancher et OpenShift lorsque l'utilisateur est authentifié via SSO.
* Ajouter l'activation de l'analyse automatique et la suppression des groupes non nécessaires dans la configMap.
* Insérer l'adresse IP pour la source/cible externe dans csv/pdf pour les violations implicites de rejet.
* Différentes optimisations de performance et de scalabilité pour l'utilisation du CPU et de la mémoire du contrôleur et de l'exécuteur.

==== Corrections de bogues

* Résoudre l'application lente sur les nœuds GKE Container Optimized OS (COS) en mode Protect.
* Le CVE SUSE Linux (SLES) 15.4 n'est pas détecté par le scanner. Avec cette correction, la vulnérabilité est ajoutée à la base de données lorsque la gravité est spécifiée dans le flux, même si l'entrée NVD est manquante. Il est possible que le rapport contienne des vulnérabilités sans scores CVE.

==== Sonstiges

* Améliorer les options CRD pour le contrôle d'admission dans helm https://github.com/neuvector/neuvector-helm/pull/237..
* Ajouter de nouvelles variables d'environnement pour l'exécuteur au diagramme Helm.

=== 5.1.1 Février 2023

==== Améliorations

* Ajouter "\`+package\+`" comme information à l'événement Syslog pour une vulnérabilité détectée.
* Ajouter la variable d'environnement de l'exécuteur ENF_NETPOLICY_PULL_INTERVAL - valeur en secondes (valeur recommandée 60) pour réduire le trafic réseau et la consommation de ressources résultante de l'exécuteur en raison des mises à jour/recalculs de la politique. (Remarque: C'était un ajout non documenté jusqu'en août 2023).

[,yaml]
----
           - name: ENF_NETPOLICY_PULL_INTERVAL
             value: "60"   <== regulate the pulling gap by 60 seconds
----

==== Corrections de bogues

* Erreur lors de la suppression du groupe vide "Objet non trouvé"
* Trafic à l'intérieur du même conteneur qui alerte/bloque.
* Violations implicites inattendues pour le trafic Egress d'Istio avec une règle d'autorisation existante.
* Lors de la mise à niveau de la version {product-name} 4.x, une mauvaise appartenance au groupe de pods entraîne une violation de politique inattendue.
* L'authentification OIDC a échoué avec ADFS lorsque des caractères d'encodage supplémentaires apparaissent dans la demande.
* Utilisation élevée de la mémoire par dp créant et supprimant des pods
* Mettre à jour Alpine pour corriger plusieurs CVE, y compris le gestionnaire : CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552
* Correction de divers bugs d'interface utilisateur

==== Sonstiges

* Diagramme Helm mis à jour pour permettre le remplacement du certificat pour les communications internes

=== 5.1.0 Décembre 2022

==== Améliorations

* Base de données de scan centralisée et multi-cluster (CVE). Le cluster principal (maître) peut scanner un registre/repo désigné comme un registre fédéré. Les résultats de scan de ces registres sont synchronisés avec tous les clusters gérés (distants). Cela permet d'afficher les résultats de scan dans la console du cluster géré et d'utiliser les résultats dans les règles d'admission du cluster géré. Les registres doivent être scannés une seule fois, au lieu de chaque cluster, réduisant ainsi l'utilisation du CPU/mémoire et de la bande passante réseau.
* Améliorer les règles de contrôle d'admission :
 ** Critères personnalisés pour les règles d'admission. Permettre aux utilisateurs de définir des critères de ressources pour tous les champs associés aux pods et de les utiliser dans les règles, par exemple item.metadata.annotationsKey contient 'neuvector', item.metadata.name='xyzzy', etc.
 ** Ajouter des critères pour vérifier les paramètres RBAC à risque pour les comptes de service lors du déploiement de pods. Cela inclut les critères 'toute action sur les ressources de charge de travail', 'toute action sur RBAC', 'créer des ressources de charge de travail', 'lister les secrets' et 'exécuter dans un conteneur'.
 ** Ajouter une comparaison de version sémantique aux modules pour les règles de contrôle d'admission. Cela permet d'appliquer les opérateurs > ou < sur les numéros de version dans les règles (par exemple, ne pas autoriser le déploiement du module curl<6.2.0). Cela permet des vérifications de version spécifiques sur les paquets installés.
 ** Ajouter une règle d'admission pour la sécurité des pods (PSA) qui est prise en charge dans Kubernetes 1.25+.
* Ajouter une nouvelle variable d'environnement NO_DEFAULT_ADMIN qui, lorsqu'elle est activée, ne crée pas d'utilisateur 'admin'. Ceci est utilisé par défaut pour l'intégration SSO de Rancher. Si non activé, avertir l'utilisateur de manière permanente et enregistrer les événements pour changer le mot de passe admin par défaut, s'il n'est pas changé par défaut.
* Le verrouillage de la connexion après des tentatives de connexion échouées est désormais la valeur par défaut. La valeur par défaut est de 5 tentatives et est configurable dans les paramètres -> Utilisateurs & Rôles-> Profil de mot de passe.
* Ajouter une nouvelle variable d'environnement pour l'optimisation des performances ENF_NO_SYSTEM_PROFILES, valeur : "1". Si activé, les moniteurs de processus et de fichiers seront désactivés. Aucun processus d'apprentissage, aucun mode de profil, aucun incident de processus/fichier (paquet) et aucune surveillance de l'activité des fichiers ne sera effectué. Cela réduira l'utilisation des ressources CPU/RAM et les opérations sur les fichiers.
* Ajouter un paramètre d'auto-scaling personnalisé pour les pods de scanner, avec les valeurs Retardé, Immédiat et Désactivé. Important : L'auto-scaling du scanner n'est pas pris en charge lorsque le scanner est déployé avec un opérateur OpenShift, car l'opérateur changera toujours le nombre de pods à la valeur configurée.
 ** *_Stratégie retardée :_*
  *** Si le contrôleur principal voit continuellement "Nombre de tâches" > 0 pendant > 90 secondes, un nouveau pod de scanner sera lancé si maxScannerPods n'est pas encore atteint.
  *** Si le contrôleur principal voit continuellement que "le nombre de tâches" est 0 pendant > 180 secondes, il réduit d'un pod de scanner, si minScannerPods n'est pas encore atteint.
 ** *_Stratégie immédiate :_*
  *** Chaque fois que le contrôleur principal voit "Nombre de tâches" > 0, un nouveau pod de scanner sera lancé si maxScannerPods n'est pas encore atteint.
  *** Si le contrôleur principal voit continuellement que "le nombre de tâches" est 0 pendant > 180 secondes, il réduit d'un pod de scanner, si minScannerPods n'est pas encore atteint.
* Les groupes personnalisés peuvent maintenant utiliser des balises de namespace, y compris les balises de namespace Rancher. En général, les balises de pod et de namespace peuvent maintenant être ajoutées aux groupes personnalisés.
* Ajoutez la possibilité de masquer des espaces de noms et des groupes sélectionnés dans la vue d'activité réseau.
* Vollständige Unterstützung für Cilium cni.
* Vollständige Unterstützung für OpenShift 4.9 und 4.10.
* Les outils de construction sont maintenant disponibles pour le projet {product-name}/Open Zero Trust (OZT) sous https://github.com/openzerotrust/openzerotrust.io...
* {product-name} répertorie maintenant l'ID de version et le hachage SHA256 pour chaque version des contrôleurs, gestionnaires, exécuteurs sous https://github.com/neuvector/manifests/tree/main/versions...
* Les données de télémétrie anonymes (nombre de nœuds, groupes, règles) sont maintenant signalées lors du déploiement à un service cloud Rancher pour aider l'équipe projet à comprendre le comportement d'utilisation. Cela peut être désactivé dans l'interface utilisateur ou avec configMap (No_Telemetry_Report) ou l'API REST (Opt-out).
* (Addendum janvier 2023). Prise en charge des stratégies basées sur le réseau avec ServiceEntry dans Istio. La fonctionnalité d'application de la stratégie réseau sortante a été ajoutée dans la version 5.1.0 pour les Pods aux cibles ServiceEntry déclarées avec Istio. Typiquement, un ServiceEntry définit comment un service externe, référencé par un nom DNS, est résolu en une adresse IP cible. Avant v5.1, {product-name} ne pouvait pas détecter et appliquer des règles pour les connexions à un ServiceEntry, de sorte que toutes les connexions étaient classées comme externes. Avec 5.1, des règles peuvent être appliquées à des cibles spécifiques de ServiceEntry. IMPORTANT : Lorsque vous mettez à jour vers v5.1 avec un déploiement basé sur Istio, de nouvelles règles doivent être créées pour permettre ces connexions et éviter les violations. Après la mise à niveau, des violations implicites seront signalées pour le trafic nouvellement visible s'il n'y a pas de règles d'autorisation. De nouvelles règles de trafic peuvent être apprises et auto-créées en mode Découverte. Pour permettre ce trafic, vous pouvez mettre le groupe en mode découverte ou créer un groupe personnalisé avec des adresses (ou un nom DNS) et une nouvelle règle réseau pour cette cible afin de permettre le trafic. REMARQUE : Il y a un bug dans 5.1.0 dans la cible signalée par les violations de rejet, qui ne représente pas la bonne cible.  L'erreur indique que server_name et client_name sont identiques.  Ce problème sera résolu dans une prochaine version de correctif.

==== Corrections d'erreurs

* Réduction de la consommation de mémoire du contrôleur en raison de données de référence inutiles créées lors des mises à jour progressives. Ce problème ne se produit pas lors de nouveaux déploiements.
* Supprimer la licence de l'écran de configuration (plus nécessaire).

=== 5.0.6-s1 Mars 2023

==== Corrections d'erreurs

* Mettre à jour les paquets Alpine pour corriger les CVE dans curl, y compris CVE-2023-23914, CVE-2023-23915 et CVE-2023-23916.

=== 5.0.6 Février 2023

==== Corrections d'erreurs

* Utilisation élevée de la mémoire dans dpMsgConnection
* Consommation de mémoire élevée dans le processus dp dans l'Enforcer, lorsque de nombreuses règles de stratégie apprises sont présentes avec une charge de travail non gérée (fuite de mémoire)
* tcpdump ne peut pas être démarré avec succès lors de l'analyse du trafic dans le conteneur
* Mettre à jour Alpine pour corriger plusieurs CVE, y compris Manager : CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552

=== 5.0.5 Novembre 2022

==== Corrections d'erreurs

* La mise à niveau vers 5.0.x entraîne un message d'erreur concernant Manager, Controller, Enforcer exécutant des versions différentes.
* Les Enforcers rencontrent une panique Go de routine, entraînant un kill dp.  WebUI ne reflète pas l'Enforcer comme étant en ligne.
* Incident inattendu de Process.Profile.Violation dans le groupe NV.Protect, où des commandes CoreOS sont exécutées.

=== 5.0.4 Octobre 2022

==== Sicherheitsupdates

* Mettre à niveau Alpine pour supprimer la CVE critique-2022-40674 dans la bibliothèque Expat du gestionnaire, ainsi que d'autres CVEs mineurs.

==== Améliorations

* Ajouter le support pour Antrea CNI

==== Corrections d'erreurs

* Corriger l'incident inattendu de process.profile.violation dans le groupe NV.Protect.
* Lorsque SSL est désactivé lors de l'accès à l'interface utilisateur du gestionnaire, le mot de passe de l'utilisateur est affiché dans le journal du gestionnaire.

=== 5.0.3 Septembre 2022

==== Améliorations

* Ne pas afficher le contrat de licence après un redémarrage réussi à partir du volume persistant.
* Utilisez le filtre d'image dans les paramètres du profil de vulnérabilité pour ignorer les résultats de scan des conteneurs.
* Support du scanner dans les actions GitHub à https://github.com/neuvector/neuvector-image-scan-action.
* Ajouter des variables d'environnement Enforcer pour désactiver le scan des secrets et exécuter les benchmarks CIS.

[,yaml]
----
    env:
      - name: ENF_NO_SECRET_SCANS  (available after v4.4.4)
        value: "1"
      - name: ENF_NO_AUTO_BENCHMARK (after v5.0.3)
        value: "1"
----

==== Corrections d'erreurs

* L'Enforcer peut parfois ne pas démarrer.
* Fuite de connexion dans des environnements de fédération multi-clusters.
* La page de conformité ne se charge parfois pas dans les risques de sécurité -> conformité.

=== 5.0.2 Juillet 2022

==== Améliorations

* Les clusters Rancher durcis et SELinux sont pris en charge.

==== Corrections d'erreurs

* Processus d'agent intensifs en CPU sur les systèmes k3s.
* Les groupes AD LDAP ne fonctionnent pas correctement après la mise à niveau vers 5.0.
* L'Enforcer redémarre en raison de l'erreur = trop de fichiers ouverts (rke2/cilium).
* Le protocole de support ne peut pas être téléchargé avec succès.

=== 5.0.1 Juin 2022

==== Améliorations

* Prise en charge du scan de vulnérabilité de l'OS openSUSE Leap (dans l'image du scanner).
* Scanner : Implementierung von Löschattributen beim Rekonstruieren des Image-Repositorys.
* Vérifiez le déploiement {product-name} et le support pour les hôtes avec SELinux activé. Voir ci-dessous pour les détails du correctif temporaire, en attendant la mise à jour du diagramme Helm.
* Différencier clairement entre le diagramme fonctionnel et les diagrammes partenaires dans l'interface utilisateur de Rancher. + Amélioration de l'annotation d'entrée pour nginx dans le diagramme Helm de Rancher. Ajouter / Mettre à jour ingress.kubernetes.io/protocol : https à nginx.ingress.kubernetes.io/backend-protocol : "HTTPS".
* L'opérateur OpenShift actuel prend en charge les routes pass-through pour les services API et de fédération. Des paramètres de valeur Helm supplémentaires sont ajoutés pour prendre en charge les types de fin de route Edge et Re-Encryption.

==== Corrections d'erreurs

* Le cluster AKS pourrait ajouter une clé inattendue dans le webhook de contrôle d'admission.
* L'enforcer ne sera pas opérationnel dans le cluster K8s 1.24 avec la runtime Containerd 1.64. Séparément, l'enforcer échoue parfois à démarrer.
* Tout utilisateur avec le rôle d'administrateur (utilisateur local ou SSO) qui promeut un cluster en un Master-Fed devrait être automatiquement promu au rôle de fedAdmin.
* Lorsque SSO utilise l'administrateur par défaut de Rancher dans {product-name} sur le cluster maître, le rôle de connexion {product-name} est admin, pas fedAdmin.
* Corriger plusieurs plantages de Goroutine.
* Violation implicite de l'IP hôte qui n'est pas liée au nœud.
* Le profil de conformité n'affiche pas le tag PCI.
* La mappage de groupe LDAP n'est parfois pas affiché.
* L'outil d'examen et d'amélioration des risques génère un message d'erreur "Erreur lors de la mise à jour de la configuration système : Demande au format incorrect".
* OKD 3.11 - L'erreur de Clusterrole est affichée, même si elle existe.

==== Remédiations CVE

* CVE-2022-29458 hautement classé, trouvé dans le paquet ncurses dans toutes les images.
* CVE-2022-27778 et CVE-2022-27782 élevés trouvés sur le paquet curl dans l'image Updater.

==== Détails sur le support SELinux

{product-name} ne nécessite aucun paramètre supplémentaire pour les clusters avec SELinux activé, pour être déployé et exploité. Déploiement de {product-name} sur un cluster RKE2, durci sur RHEL 8.5 avec SELinux activé, testé. {product-name} déployé avec succès lorsque PSP est activé et que le gestionnaire de correctifs et le scanner sont déployés. La prochaine version du graphique devrait corriger le problème suivant.

Exemple ci-joint pour activer psp à partir du graphique Rancher et ci-dessous les commandes pour patcher le déploiement du gestionnaire et du scanner. L'ID utilisateur dans la commande de patch peut être n'importe quel numéro.

[,shell]
----
kubectl patch deploy -ncattle-neuvector-system neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
kubectl patch deploy -ncattle-neuvector-system neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
----

Exemple pour activer PSP :

[,shell]
----
[neuvector@localhost nv]$ getenforce
Enforcing
[neuvector@localhost nv]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

[neuvector@localhost nv]$ kk get psp
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS                                      SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
global-restricted-psp     false                                             RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
neuvector-binding-psp     true    SYS_ADMIN,NET_ADMIN,SYS_PTRACE,IPC_LOCK   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
system-unrestricted-psp   true    *                                         RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
[neuvector@localhost nv]$ nvpo.sh
NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE                    NOMINATED NODE   READINESS GATES
neuvector-controller-pod-54f69f7f9c-6h822   1/1     Running   0          5m51s   10.42.0.29   localhost.localdomain   <none>           <none>
neuvector-enforcer-pod-jz77b                1/1     Running   0          5m51s   10.42.0.30   localhost.localdomain   <none>           <none>
neuvector-manager-pod-588488bb78-p6vf9      1/1     Running   0          111s    10.42.0.32   localhost.localdomain   <none>           <none>
neuvector-scanner-pod-87474dcff-s8vgt       1/1     Running   0          114s    10.42.0.31   localhost.localdomain   <none>           <none>
----

=== 5.0.0 Version de disponibilité générale (GA) Mai 2022

==== Améliorations

* Automatisierte Förderung von Gruppenmodi. Promeut le mode de protection d'un groupe en fonction du temps écoulé et des critères. Ne s'applique pas aux groupes créés par CRD. Cette fonction permet à une nouvelle application de fonctionner dans Discover pendant une période donnée, d'apprendre le comportement et de créer {product-name} règles pour la liste d'approbation pour le réseau et le processus, puis passe automatiquement en mode surveillance puis en mode protection. Critère de Discover à Monitor : Temps écoulé pour apprendre toutes les activités réseau et processus d'au moins un pod actif dans le groupe. Critère de Monitor à Protect : Il n'y a aucun événement de sécurité (réseau, processus, etc.) pour la période définie pour le groupe.
* Support pour les applications Rancher 2.6.5 et le diagramme Marketplace. Fourniture dans l'espace de noms cattle-neuvector-system et activation de Rancher SSO à {product-name}. Remarque : Déploiements précédents de Rancher (par ex. B. Diagrammes du catalogue des partenaires, version 1.9.x et antérieure) doivent être complètement supprimés pour mettre à jour vers le nouveau diagramme.
* Prise en charge de l'analyse de SUSE Linux (SLE, SLES) et de Microsoft Mariner.
* Protection des processus et des fichiers sans dérive. C'est le nouveau mode standard pour la protection des processus et des fichiers. La dérive zéro permet automatiquement uniquement les processus provenant du processus parent qui se trouve dans l'image de conteneur d'origine, et n'autorise pas les mises à jour de fichiers ou l'installation de nouveaux fichiers. Lorsque vous êtes en mode découverte ou surveillance, la dérive zéro alertera en cas d'activités de processus ou de fichiers suspectes. En mode protection, une telle activité est bloquée. La dérive zéro ne nécessite pas que les processus soient appris ou ajoutés à une liste d'approbation. Désactiver la dérive zéro pour un groupe garantit que les règles de processus et de fichiers énumérées pour le groupe deviennent effectives à la place.
* Protection en mode politique partagé pour le réseau, le processus/fichier. Il existe maintenant un paramètre global dans les paramètres -> Configuration, pour définir séparément le mode de protection du réseau pour l'application des règles réseau. Activer cette option (désactivée par défaut) garantit que toutes les règles réseau sont dans le mode de protection sélectionné (découverte, surveillance, protection), tandis que les règles de processus/fichiers restent en mode protection pour ce groupe, comme indiqué à l'écran Politique -> Groupes. De cette manière, les règles réseau peuvent être définies sur protection (blocage), tandis que la politique pour les processus/fichiers peut être définie sur surveillance, ou vice versa.
* Détection des règles WAF, règles DLP améliorées (en-tête, URL, paquet complet). Utilisé pour les connexions entrantes aux pods d'applications Web ainsi que pour les connexions sortantes aux services API, afin d'appliquer la sécurité API.
* CRD pour WAF, DLP et contrôles d'accès. REMARQUE : Zusätzliche Cluster-Rollenbindungen/Berechtigungen sind erforderlich. Voir les sections de déploiement Kubernetes et OpenShift. Import/Export de CRD et versionnage pour les contrôles d'accès pris en charge via CRD.
* Intégration SSO Rancher pour démarrer la console {product-name} via Rancher Manager. Cette fonction n'est disponible que si les conteneurs {product-name} sont déployés via Rancher. Ce déploiement concerne le dépôt miroir Rancher (par exemple, rancher/mirrored-neuvector-controller:5.0.0) et est déployé dans l'espace de noms cattle-neuvector-system. Nécessite une version mise à jour de Rancher 2.6.5 de mai 2022 ou ultérieure, et actuellement seules les rôles Administrateur et Propriétaire de cluster sont pris en charge. REMARQUE : Prend en charge le déploiement sur RKE2.
* Prend en charge la fédération de clusters (gestionnaire multi-clusters) via un proxy.
* Configurez le proxy dans les paramètres  Configuration et activez le proxy lors de la configuration des connexions de fédération. Surveillez les rôles/liaisons de cluster RBAC requis et alertez dans les événements et l'interface utilisateur si quelque chose manque.
* Prend en charge les exigences de limitation des ressources dans les règles de vérification d'admission.
* Unterstützen Sie die Ressourcenbeschränkungsanforderungen in den Zulassungsprüfungsregeln.
* Prend en charge les groupes AD/LDAP imbriqués sous le groupe de rôles associé.
* Prend en charge les ClusterRoleBindings ou RoleBindings avec des informations de groupe dans l'IDP pour Openshift.
* Permet aux règles réseau et aux règles de vérification d'admission d'être promues en une règle fédérée.
* Résoudre le problème de la sauvegarde du rôle de fédération des travailleurs qui devrait être restauré dans des clusters non fédérés.

==== Corrections d'erreurs

* Améliorez les temps de chargement des pages pour un grand nombre de CVEs dans les vulnérabilités de sécurité .
* Permet à l'utilisateur de changer de mode lorsqu'il sélectionne tous les groupes dans le menu -> Groupes.
* Alertez lorsque le groupe de nœuds est également sélectionné. Alertez lorsque le groupe de nœuds est également sélectionné.
* Réduire les éléments de vérification de conformité du même nom et les rendre extensibles.
* Améliorer la sécurité des communications gRPC.
* Corrigé : Il n'a pas été possible d'obtenir les bonnes informations de privilège pour la charge de travail dans la configuration rke2.
* Résoudre le problème de prise en charge d'openSUSE Leap 15.3 (k8s/crio).

==== Autres mises à jour

* Mise à jour de la version de l'application Helm à 5.0.0 et de la version du graphique à 2.2.0
* Fonction/Menu de scan sans serveur supprimé.
* Prise en charge de l'intégration des résultats de scan Jfrog Xray supprimée (le scan du registre Artifactory est toujours pris en charge).
* La prise en charge du déploiement sur ECS n'est plus fournie. L'All-in-One devrait toujours pouvoir être déployé sur ECS, mais la documentation des étapes et des paramètres n'est plus prise en charge.

=== Mise à niveau de {product-name} 4.x à 5.x (avant 5.2.x)

[NOTE]
====
Les instructions ci-dessous s'appliquent aux mises à niveau vers 5.0.x et 5.1.x. Pour 5.2.x, les comptes de service et les liaisons ont changé et doivent être xref:kubernetes.adoc#_deploy_suse_security[vérifiés] pour planifier les mises à niveau.
====


Pour les utilisateurs de Helm, mettez à jour vers {product-name} le graphique Helm 2.0.0 ou supérieur. Si vous mettez à jour un opérateur ou une installation Helm sur OpenShift, consultez la note suivante.

. Supprimez l'ancienne définition de rôle de cluster neuvector-binding-customresourcedefinition

[,shell]
----
kubectl delete clusterrole neuvector-binding-customresourcedefinition
----

. Appliquez le nouveau verbe de mise à jour pour le rôle de cluster neuvector-binding-customresourcedefinition.

[,shell]
----
kubectl create clusterrole neuvector-binding-customresourcedefinition --verb=watch,create,get,update --resource=customresourcedefinitions
----

. Supprimez l'ancien schéma crd pour Kubernetes 1.19+

[,shell]
----
kubectl delete -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/crd-k8s-1.19.yaml
----

. Créez un nouveau schéma CRD pour Kubernetes 1.19+.

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/waf-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/dlp-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/admission-crd-k8s-1.19.yaml
----

. Créez un nouveau rôle de cluster pour Admission, DLP et WAF ainsi qu'un lien de rôle de cluster.

[,shell]
----
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----

. Mettez à jour les noms et les chemins d'image pour tirer {product-name} des images de Docker Hub (docker.io), par exemple. B.

* neuvector/manager:5.0.0
* neuvector/controller:5.0.0
* neuvector/enforcer:5.0.0
* neuvector/scanner:latest
* neuvector/updater:latest

Optionnel : Supprimez toutes les références à la licence {product-name} et au secret de registre dans les Helm-Charts, le YAML de déploiement, le ConfigMap, les scripts, etc., car ils ne sont plus nécessaires pour tirer les images ou pour utiliser {product-name}.

*Note sur SCC et mise à niveau via Operator/Helm*

Le SCC privilégié est ajouté au compte de service spécifié dans le YAML de déploiement par la version de l'opérateur 1.3.4 et supérieure dans les nouvelles déploiements. En cas de mise à niveau de l'opérateur {product-name} d'une version précédente à 1.3.4 ou de Helm à 2.0.0, veuillez supprimer le SCC privilégié avant la mise à niveau.

[,shell]
----
oc delete rolebinding -n neuvector system:openshift:scc:privileged
----

==== Beta-Version 1 veröffentlicht im April 2022.

* Vollständige Funktionalität, einschließlich automatisierter Förderung von Gruppenmodi. Promeut le mode de protection d'un groupe en fonction du temps écoulé et des critères. Ne s'applique pas aux groupes créés par CRD. Cette fonction permet à une nouvelle application de fonctionner dans Discover pendant une période donnée, d'apprendre le comportement et de créer {product-name} règles pour la liste d'approbation pour le réseau et le processus, puis passe automatiquement en mode surveillance puis en mode protection. Critère de Discover à Monitor : Temps écoulé pour apprendre toutes les activités réseau et processus d'au moins un pod actif dans le groupe. Critère de Monitor à Protect : Il n'y a aucun événement de sécurité (réseau, processus, etc.) pour la période définie pour le groupe.
* Support pour les applications Rancher 2.6.5 et le diagramme Marketplace. Fourniture dans l'espace de noms cattle-neuvector-system et activation de Rancher SSO à {product-name}. Remarque : Déploiements précédents de Rancher (par ex. B. Diagrammes du catalogue des partenaires, version 1.9.x et antérieure) doivent être complètement supprimés pour mettre à jour vers le nouveau diagramme.
* Tags pour Enforcer, Manager, Controller : 5.0.0-b1 (par exemple neuvector/controller:5.0.0-b1)

==== Version Preview.3 publiée en mars 2022

[CAUTION]
.important
====

Pour mettre à jour les déploiements de prévisualisation précédents pour les nouvelles fonctionnalités CRD WAF, DLP et Admission Control, veuillez mettre à jour le YAML CRD et ajouter de nouveaux RBAC/liaisons de rôles :

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/latest/crd-k8s-1.19.yaml
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----
====


==== Améliorations

* Prise en charge de l'analyse de SUSE Linux (SLE, SLES) et de Microsoft Mariner.
* Protection des processus et des fichiers sans dérive. C'est le nouveau mode standard pour la protection des processus et des fichiers. La dérive zéro permet automatiquement uniquement les processus provenant du processus parent qui se trouve dans l'image de conteneur d'origine, et n'autorise pas les mises à jour de fichiers ou l'installation de nouveaux fichiers. Lorsque vous êtes en mode découverte ou surveillance, la dérive zéro alertera en cas d'activités de processus ou de fichiers suspectes. En mode protection, une telle activité est bloquée. La dérive zéro ne nécessite pas que les processus soient appris ou ajoutés à une liste d'approbation. Désactiver la dérive zéro pour un groupe garantit que les règles de processus et de fichiers énumérées pour le groupe deviennent effectives à la place.
* Protection en mode politique partagé pour le réseau, le processus/fichier. Il existe maintenant un paramètre global dans les paramètres -> Configuration, pour définir séparément le mode de protection du réseau pour l'application des règles réseau. Activer cette option (désactivée par défaut) garantit que toutes les règles réseau sont dans le mode de protection sélectionné (découverte, surveillance, protection), tandis que les règles de processus/fichiers restent en mode protection pour ce groupe, comme indiqué à l'écran Politique -> Groupes. De cette manière, les règles réseau peuvent être définies sur protection (blocage), tandis que la politique pour les processus/fichiers peut être définie sur surveillance, ou vice versa.
* Détection de règles WAF, règles DLP améliorées (en-tête, URL, paquet complet)
* CRD pour WAF, DLP et contrôles d'accès. REMARQUE : Zusätzliche Cluster-Rollenbindungen/Berechtigungen sind erforderlich. Voir les sections de déploiement Kubernetes et OpenShift. Import/Export de CRD et versionnage pour les contrôles d'accès pris en charge via CRD.
* Intégration SSO Rancher pour démarrer la console {product-name} via Rancher Manager. Cette fonction n'est disponible que si les conteneurs {product-name} sont déployés via Rancher. REMARQUE : Nécessite une version mise à jour de Rancher (date/version à déterminer).
* Prend en charge la fédération de clusters (gestionnaire multi-clusters) via un proxy.
* Configurez le proxy dans les paramètres  Configuration et activez le proxy lors de la configuration des connexions de fédération.
* Prend en charge les exigences de limitation des ressources dans les règles de vérification d'admission.
* Unterstützen Sie die Ressourcenbeschränkungsanforderungen in den Zulassungsprüfungsregeln.

==== Corrections d'erreurs

* Améliorez les temps de chargement des pages pour un grand nombre de CVEs dans les vulnérabilités de sécurité .

==== Version Preview.2 publiée en février 2022

* Modifications mineures de fichiers et de licences dans la source, aucune fonctionnalité ajoutée.

==== Le support pour le déploiement sur AWS ECS est obsolète

La prise en charge du déploiement sur ECS n'est plus fournie. L'All-in-One devrait toujours pouvoir être déployé sur ECS, mais la documentation des étapes et des paramètres n'est plus prise en charge.

=== 5.0 'Aperçu technique' janvier 2022

==== Améliorations

* Première version d'une version 'Aperçu technique' non prise en charge de {product-name} 5.0 version open-source.
* Ajoutez le support pour OWASP Top-10, des règles similaires à WAF pour détecter les attaques réseau dans les en-têtes ou dans le corps. Inclut le support pour les définitions de signature CRD et leur application aux groupes correspondants.
* Supprime les fonctionnalités de scan sans serveur.

==== Corrections d'erreurs

* TBD

==== Sonstiges

* Le graphique Helm v1.8.9 est publié pour les déploiements 5.0.0. Si vous utilisez cela avec la version Preview 5.0.0, les modifications suivantes doivent être apportées à values.yml :
 ** Mettez à jour le registre sur docker.io
 ** Mettez à jour les noms/étiquettes de l'image vers la version Preview sur Docker Hub
 ** Laissez les imagePullSecrets vides
