= Tester les intégrations et autres composants
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/02.other/02.other.md
:page-opendocs-slug:  /releasenotes/autres

== Tester les notes de version pour les modules d'intégration, les plug-ins et autres composants

=== Tester les actions Github

* Les actions Github pour le scan de vulnérabilités sont maintenant publiées à https://github.com/neuvector/neuvector-image-scan-action.

=== Tester le graphique Helm 1.8.9

* Le graphique Helm v1.8.9 est publié pour les déploiements 5.0.0. Si vous utilisez cela avec la version d'aperçu de 5.0.0, les modifications suivantes doivent être apportées à values.yml :
** Mettre à jour le registre vers docker.io
** Mettre à jour les noms/étiquettes d'image vers la version d'aperçu sur Docker hub
** Laisser les imagePullSecrets vides

=== Tester l'application Splunk publiée

* Nouvelle application Splunk pour \{product-name} est publiée à https://splunkbase.splunk.com/app/6205/

=== Tester la mise à jour du graphique Helm 1.8.7

* Support de la personnalisation de l'affinité et de la tolérance pour le contrôleur, le scanner et le gestionnaire.
* Ajouter le support de nodeSelector pour les pods de contrôleur, de gestionnaire, de scanner et de mise à jour.
* Support des variables d'environnement définies par l'utilisateur pour le conteneur du contrôleur.

=== Tester l'opérateur communautaire v1.2.7 pour le graphique Helm 1.8.2

* Permettre aux utilisateurs de spécifier la version de publication de \{product-name}
* Déploie la dernière version de la base de données CVE du scanner
* L'emplacement de l'image de l'opérateur de conteneur a été déplacé vers registry.neuvector.com/public
* Le nom de l'instance \{product-name} par défaut est neuvector (avant c'était example-neuvector)
* Document readme mis à jour sur la page d'installation et lien ajouté vers les notes de version

=== Tester Helm Chart 1.8.2

* Ajouter des options d'ingress et d'hôte de contrôleur.

=== Tester l'opérateur certifié v1.2.8 pour \{product-name} v4.3.1

* Prend en charge la version du graphique helm 1.8.2
* Déploie la version \{product-name} 4.3.1
* Déploie la version de la base de données du scanner 2.360
* autres changements de la version précédente 1.2.7
** Le nom de l'instance neuvector par défaut est neuvector, avant c'était example-neuvector
** document readme mis à jour sur la page d'installation
** problème d'affichage du logo \{product-name} corrigé
* Problèmes connus
** la mise à niveau de 1.2.7 à 1.2.8 ne met pas à niveau la base de données du scanner
solution de contournement : mettre à jour l'image du scanner vers registry.connect.redhat.com/neuvector/scanner@sha256:a802c012eee80444d9deea8c4402a1d977cf57d7b2b2044f90c9acc0e7ca3e06 sur le déploiement du scanner
** document readme sur la page d'installation mal aligné
** la base de données du scanner n'est pas mise à jour par l'updater

=== Tester la mise à jour du Helm Chart 1.8.0 juillet 2021

* Helm Chart v1.8.0 est mis à jour pour par défaut vers registry.neuvector.com comme le registre par défaut. REMARQUE: Doit spécifier manuellement le tag de version.
* Ajouter des paramètres configurables tels que les annotations de l'API du contrôleur dans le graphique Helm. Disponible à partir de la version 1.7.6+.
* Opérateur communautaire 1.2.6, opérateur certifié 1.2.7 mis à jour pour refléter les mises à jour du graphique Helm, y compris l'ajout de la route OpenShift lorsque controller.apisvc.type est activé.

=== Tester d'autres intégrations juillet 2021

* Ajouter un format de sortie HTML pour les résultats de scan dans les résultats de scan de pipeline Jenkins.
* Ajouter l'espace de noms de la charge de travail impactée dans les alertes de l'exportateur Prometheus. Maintenant pris en charge dans neuvector/prometheus-exporter:4.2.2 et versions ultérieures.

=== Tester la mise à jour du graphique Helm 1.7.5 mai 2021

* Support des changements requis pour le nouveau registre d'images registry.neuvector.com.  Le changement à cela entraînera des chemins d'image (c'est-à-dire supprimer neuvector du chemin de neuvector/controller à controller).

=== Tester la mise à jour du graphique Helm 1.7.2 avril 2021

* Ajouter le support pour des demandes et limites de ressources de composants séparés, par exemple, contrôleur, demandes de mémoire et de CPU de l'enforcer.

=== Tester la mise à jour du plug-in Jenkins v1.13 avril 2021

* Corriger l'erreur de scan qui existe lorsque plusieurs scanners fonctionnent en même temps.
* Afficher la note de vulnérabilité Red Hat dans le résultat du scan pour les images basées sur Red Hat.

=== Tester les mises à jour de l'opérateur avril 2021

* L'opérateur OpenShift/helm doit pouvoir remplacer les certificats auto-signés. Le graphique Helm est 1.7.1. L'opérateur communautaire est 1.2.4, et l'opérateur certifié est 1.2.3.

=== Tester le plug-in Jenkins v1.12 mars 2021

* Écraser la gravité de la vulnérabilité par score. Être capable de modifier la plage de scores de vulnérabilité (CVE) utilisée pour les classifications Élevée et Moyenne. Cela permet de personnaliser quel score peut être utilisé pour échouer les builds dans le pipeline.
* Ajouter des messages d'erreur aux exceptions JAVA hudson.AbortException. Activer un meilleur rapport de messages d'erreur depuis \{product-name} lorsqu'une erreur se produit.

=== Tester la mise à jour du Helm Chart à 1.7.1 mars 2021

* Ajouter l'IP du loadbalancer du service manager et des annotations.
* Ajouter un paramètre pour définir la capacité pvc.
* Ajouter des paramètres de socket d'exécution pour k3s et AWS bottlerocket.
* Ajouter des paramètres pour remplacer les certificats du contrôleur et du manager.

=== Tester le scanner février 2021

* Corriger CVE-2020-1938 non découvert lors du scan dans les versions du scanner 1.191 et antérieures. Mettre à jour vers la dernière version du scanner après 1.191.

=== Tester le plug-in Jenkins v1.11 février 2021

==== Tester les améliorations

* Ajouter le support pour déployer le scanner \{product-name} autonome. Cela ne nécessite pas de contrôleur et doit être déployé sur le même hôte que l'installation de Jenkins. Docker doit également être installé sur l'hôte. Actuellement, seule la version Linux de Jenkins est supportée (pas la version conteneur). Ajoutez également l'utilisateur _jenkins_ au groupe _docker_.

[,bash]
----
sudo usermod -aG docker jenkins
----

Références :
https://plugins.jenkins.io/neuvector-vulnerability-scanner/
https://github.com/jenkinsci/neuvector-vulnerability-scanner-plugin/releases/tag/neuvector-vulnerability-scanner-1.11

=== Tester les mises à jour du catalogue Rancher janvier 2021

* Mettre à jour \{product-name} dans le catalogue Rancher pour prendre en charge 4.x

=== Tester les mises à jour du graphique Helm janvier 2021

* Créer les CRDs \{product-name} requis lors du déploiement
* Corriger l'erreur lors de la définition de l'ingress du contrôleur sur vrai

=== Tester les mises à jour de l'opérateur janvier 2021

* Mettre à jour les opérateurs (communauté, certifiés) pour prendre en charge 4.x

=== Tester les changements du graphique Helm décembre 2020

* Permettre à l'utilisateur de personnaliser PriorityClass du déploiement du gestionnaire/contrôleur/appliqueur/scanner. Nous suggérons de donner aux conteneurs \{product-name} une priorité plus élevée pour s'assurer que les politiques de sécurité sont appliquées lorsque les ressources du nœud sont sous pression ou lors d'un processus de mise à niveau de cluster.

=== Tester la mise à jour importante du graphique Helm novembre 2020

[IMPORTANT]
====
Modifications de la structure du graphique Helm
====

* Le répertoire pour le graphique \{product-name} a changé de ./neuvector-helm/ à ./neuvector-helm/charts/core/

Si vous utilisez Helm pour mettre à niveau, veuillez mettre à jour l'emplacement vers le chemin ci-dessus.
