= Docker & Mirantis Kubernetes Engine
:revdate: 2025-01-10
:page-revdate: {revdate}
:page-opendocs-origin: /02.deploying/05.docker/05.docker.md
:page-opendocs-slug: /deploying/docker

== Kubernetes-Bereitstellung auf der Mirantis Kubernetes Engine

Folgen Sie den Anweisungen im xref:kubernetes.adoc[Abschnitt Kubernetes].

[NOTE]
====
{product-name} unterstützt keine gemischten Kubernetes/Swarm-Cluster.
====

== Bereitstellung von {product-name} Containern mit Docker Native oder UCP/Swarm

Beachten Sie, dass die native Docker-Bereitstellung auf der Mirantis Kubernetes Engine unter Verwendung von Swarm KEINE Bereitstellung von Diensten mit Containern im privilegierten Modus oder mit hinzugefügten seccomp-Funktionen unterstützt. Zur Bereitstellung in dieser Umgebung müssen Sie Docker Compose oder Run verwenden, um die {product-name} Container bereitzustellen. Sie können die Remote-Host-Bereitstellung (docker-compose -H HOST) verwenden, um diese Aufgabe zu erleichtern.

Hier sind die Beispielkonfigurationsdateien von docker compose. Beachten Sie, dass die Verwendung von Docker Native die Bereitstellung des Enforcers auf demselben Knoten wie der Controller nicht unterstützt, so dass die Verwendung des Allinone-Containers erforderlich ist, wenn Controller- und Enforcer-Funktionen auf einem Knoten gewünscht sind.

NOTE: Die Umgebungsvariable NV_PLATFORM_INFO=platform=Docker wird verwendet, um {product-name} mitzuteilen, dass es sich bei der Plattform um Docker/Swarm handelt, auch wenn auf einer Docker EE-Bereitstellung möglicherweise ungenutzte Kubernetes-Container vorhanden sind, die von {product-name} erkannt werden. Um diese in der Netzwerkaktivität -> Ansicht -> System anzeigen sehen zu können, fügen Sie die Umgebungsvariable für den Enforcer NV_SYSTEM_GROUPS hinzu.

=== Einsatz von Allinone für hohe Verfügbarkeit

Für HA in nativen Docker- oder EE-Produktionsumgebungen stellen Sie den Allinone-Container auf den ersten drei Produktionshosts bereit. Jeder Allinone sollte auf die IP-Adressen aller Allinone-Hosts verweisen. Zum Beispiel sind drei Allinone-Container das Minimum für HA, und die CLUSTER_JOIN_ADDR sollte die drei IP-Adressen durch Kommata getrennt auflisten. Zusätzliche HA Allinone's können in ungerader Anzahl eingesetzt werden, z.B. 5, 7. Verteilen Sie den Enforcer auf den verbleibenden Hosts im Cluster, in jedem.

=== Allinone mit docker-compose bereitstellen (privilegierter Modus)

Nachfolgend ein Beispiel für die docker-compose-Datei zur Bereitstellung des allinone-Containers auf dem ersten Knoten. Da der Allinone-Container ein Enforcer-Modul enthält, können Anwendungscontainer auf demselben Knoten gesichert werden. Sowohl der Einsatz auf der grünen als auch auf der braunen Wiese wird unterstützt.

[,yaml]
----
allinone:
    pid: host
    image: neuvector/allinone:<version>
    container_name: allinone
    privileged: true
    environment:
        - CLUSTER_JOIN_ADDR=node_ip
        - NV_PLATFORM_INFO=platform=Docker
    ports:
        - 18300:18300
        - 18301:18301
        - 18400:18400
        - 18401:18401
        - 18301:18301/udp
        - 8443:8443
    volumes:
        - /lib/modules:/lib/modules:ro
        - /var/neuvector:/var/neuvector
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc:/host/proc:ro
        - /sys/fs/cgroup:/host/cgroup:ro
----

Die wichtigste Umgebungsvariable ist die *CLUSTER_JOIN_ADDR*. Es ist die IP-Adresse, mit der sich andere Enforcer verbinden. Normalerweise sollte sie auf die IP-Adresse des Knotens gesetzt werden, auf dem der All-in-one-Container läuft.

Die Anschlüsse 18300 und 18301 sind Standardanschlüsse für die Clusterkommunikation. Sie müssen bei allen Controllern und Enforcern des Clusters identisch sein. Bitte lesen Sie im Abschnitt _"Docker-compose Details"_ nach, wie Sie die Standard-Ports ändern können.

[NOTE]
====
Um die REST-API in Allinone freizugeben, fügen Sie die Port-Map für 10443 hinzu, zum Beispiel - 10443:10443.
====

=== Hinzufügen eines Enforcer-Containers mit docker-compose (privilegierter Modus)

Dies ist ein Beispiel für eine Docker-Compose-Datei zum Beitritt eines Enforcers zum Cluster. Sowohl der Einsatz auf der grünen als auch auf der braunen Wiese wird unterstützt.

[,yaml]
----
enforcer:
    pid: host
    image: neuvector/enforcer:<version>
    container_name: enforcer
    privileged: true
    environment:
        - CLUSTER_JOIN_ADDR=controller_node_ip
        - NV_PLATFORM_INFO=platform=Docker
    ports:
        - 18301:18301
        - 18401:18401
        - 18301:18301/udp
    volumes:
        - /lib/modules:/lib/modules:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc:/host/proc:ro
        - /sys/fs/cgroup/:/host/cgroup/:ro
----

Die wichtigste Umgebungsvariable ist *CLUSTER_JOIN_ADDR*. Bei Enforcern ersetzen Sie `<controller_node_ip>` durch die Knoten-IP-Adresse des Controllers. Normalerweise haben *CLUSTER_JOIN_ADDR* in der Docker-Compose-Datei des Controllers/All-in-One und in der Docker-Compose-Datei des Enforcers denselben Wert.

=== Bereitstellen des {product-name} Scanner Containers

Ab {product-name} 4.0 muss ein separater Scanner-Container bereitgestellt werden, um Schwachstellen-Scans durchzuführen. Das ist wichtig: Verwenden Sie beim Abrufen und Ausführen des Scanner-Images immer das :latest-Tag, um sicherzustellen, dass die neueste CVE-Datenbank bereitgestellt wird.

Beispiel für einen Docker-Lauf zur Bereitstellung des Scanners auf demselben Host wie der Controller

[,shell]
----
docker run -td --name scanner -e CLUSTER_JOIN_ADDR=controller_node_ip -p 18402:18402 -v /var/run/docker.sock:/var/run/docker.sock:ro neuvector/scanner:latest
----

Und das Beispiel docker-compose

[,yaml]
----
Scanner:
   image: neuvector/scanner:latest
   container_name: scanner
   environment:
     - CLUSTER_JOIN_ADDR=controller_node_ip
   ports:
     - 18402:18402
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
----

Um den Scanner auf einem anderen Host als dem Controller einzusetzen, fügen Sie die Umgebungsvariable CLUSTER_ADVERTISED_ADDR hinzu, damit der Controller den Scanner erreichen kann.

[,shell]
----
docker run -td --name scanner -e CLUSTER_JOIN_ADDR=controller_node_ip -e CLUSTER_ADVERTISED_ADDR=scanner_host_ip -p 18402:18402 -v /var/run/docker.sock:/var/run/docker.sock:ro neuvector/scanner:latest
----

Um mehrere Scanner auf demselben Host wie der Controller einzusetzen, entfernen Sie die Portzuordnung und die Umgebungsvariable CLUSTER_ADVERTISED_ADDR.

[,shell]
----
docker run -itd --name s1  -e CLUSTER_JOIN_ADDR=controller_node_ip neuvector/scanner:latest
----

Dabei ist s1 der Scanner 1 (verwenden Sie s2, s3 usw. für jeden weiteren Scanner).

Um einen Standalone-Scanner (ohne Controller/Allinone) einzusetzen, lesen Sie bitte den Abschnitt xref:scanners.adoc[Parallele und Standalone-Scanner].

Um den Scanner zu aktualisieren, um die neuesten CVE-Datenbank-Updates von {product-name} zu erhalten, erstellen Sie einen Cron-Job, um den Scanner zu stoppen und neu zu starten, wobei die neuesten Updates gezogen werden. Einzelheiten finden Sie in xref:docker.adoc#_docker_native_updates[diesem Abschnitt].

=== Bereitstellung ohne Verwendung des privilegierten Modus

Bei einigen Plattformkonfigurationen ist es möglich, die {product-name} Container einzusetzen, ohne dass sie im privilegierten Modus laufen müssen. Die Konfiguration muss die Möglichkeit bieten, Fähigkeiten hinzuzufügen und das Scharfschaltungsprofil einzustellen. Beachten Sie, dass Docker DataCenter/UCP und Swarm dies derzeit nicht unterstützen, aber es ist immer noch möglich, {product-name} manuell mit Compose oder Run bereitzustellen.

=== Einsatz von allinone (NO privileged mode) mit docker-compose

[,yaml]
----
allinone:
    pid: host
    image: neuvector/allinone:<version>
    container_name: neuvector.allinone
    cap_add:
        - SYS_ADMIN
        - NET_ADMIN
        - SYS_PTRACE
        - IPC_LOCK
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined
        - label=disable
    environment:
        - CLUSTER_JOIN_ADDR=[AllInOne Node IP Address]
        - NV_PLATFORM_INFO=platform=Docker
    ports:
        - 18300:18300
        - 18301:18301
        - 18400:18400
        - 18401:18401
        - 18301:18301/udp
        - 8443:8443
    volumes:
        - /lib/modules:/lib/modules:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc:/host/proc:ro
        - /sys/fs/cgroup:/host/cgroup:ro
        - /var/neuvector:/var/neuvector
----

=== Einsatz von enforcer (NO privileged mode) mit docker-compose

[,yaml]
----
enforcer:
    pid: host
    image: neuvector/enforcer:<version>
    container_name: neuvector.enforcer
    cap_add:
        - SYS_ADMIN
        - NET_ADMIN
        - SYS_PTRACE
        - IPC_LOCK
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined
        - label=disable
    environment:
        - CLUSTER_JOIN_ADDR=[AllInOne Node IP Address]
        - NV_PLATFORM_INFO=platform=Docker
    ports:
        - 18301:18301
        - 18401:18401
        - 18301:18301/udp
    volumes:
        - /lib/modules:/lib/modules:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc:/host/proc:ro
        - /sys/fs/cgroup/:/host/cgroup/:ro
----

=== Bereitstellen von allinone (privilegierter Modus) mit docker run

Sie können Docker Run anstelle von Compose für die Bereitstellung verwenden. Hier sind Beispiele.

[,shell]
----
docker run -d --name allinone \
--pid=host \
--privileged \
    -e CLUSTER_JOIN_ADDR=[AllInOne Node IP Address] \
    -e NV_PLATFORM_INFO=platform=Docker \
    -p 18300:18300 \
    -p 18301:18301 \
    -p 18400:18400 \
    -p 18401:18401 \
    -p 18301:18301/udp \
    -p 8443:8443 \
    -v /lib/modules:/lib/modules:ro \
    -v /var/neuvector:/var/neuvector \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v /sys/fs/cgroup:/host/cgroup:ro \
    -v /proc:/host/proc:ro \
neuvector/allinone:<version>
----

=== Enforcer (privilegierter Modus) mit Docker Run bereitstellen

[,shell]
----
docker run -d --name enforcer \
--pid=host \
--privileged \
    -e CLUSTER_JOIN_ADDR=[AllInOne Node IP Address] \
    -e NV_PLATFORM_INFO=platform=Docker \
    -p 18301:18301 \
    -p 18401:18401 \
    -p 18301:18301/udp \
    -v /lib/modules:/lib/modules:ro \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v /sys/fs/cgroup:/host/cgroup:ro \
    -v /proc:/host/proc:ro \
neuvector/enforcer:<version>
----

=== Bereitstellen von allinone (NO privileged mode) mit docker run

Sie können Docker Run anstelle von Compose für die Bereitstellung verwenden. Hier sind Beispiele.

[,shell]
----
docker run -d --name allinone \
--pid=host \
--cap-add=SYS_ADMIN \
--cap-add=NET_ADMIN \
--cap-add=SYS_PTRACE \
--cap-add=IPC_LOCK \
--security-opt label=disable \
--security-opt apparmor=unconfined \
--security-opt seccomp=unconfined \
    -e CLUSTER_JOIN_ADDR=[AllInOne Node IP Address] \
    -e NV_PLATFORM_INFO=platform=Docker \
    -p 18300:18300 \
    -p 18301:18301 \
    -p 18400:18400 \
    -p 18401:18401 \
    -p 18301:18301/udp \
    -p 8443:8443 \
    -v /lib/modules:/lib/modules:ro \
    -v /var/neuvector:/var/neuvector \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v /sys/fs/cgroup:/host/cgroup:ro \
    -v /proc:/host/proc:ro \
neuvector/allinone:<version>
----

=== Enforcer (NO privileged mode) mit docker run bereitstellen

[,shell]
----
docker run -d --name enforcer \
--pid=host \
--cap-add=SYS_ADMIN \
--cap-add=NET_ADMIN \
--cap-add=SYS_PTRACE \
--cap-add=IPC_LOCK \
--security-opt label=disable \
--security-opt apparmor=unconfined \
--security-opt seccomp=unconfined \
    -e CLUSTER_JOIN_ADDR=[AllInOne Node IP Address]  \
    -e NV_PLATFORM_INFO=platform=Docker \
    -p 18301:18301 \
    -p 18401:18401 \
    -p 18301:18301/udp \
    -v /lib/modules:/lib/modules:ro \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v /sys/fs/cgroup:/host/cgroup:ro \
    -v /proc:/host/proc:ro \
neuvector/enforcer:<version>
----

== Separate {product-name} Komponenten auf verschiedenen Hosts bereitstellen

Wenn Sie planen, einen Docker-Host einem Controller und/oder Manager (ohne Enforcer) zuzuweisen, können diese Container einzeln anstelle des Allinone eingesetzt werden. Beachten Sie, dass Docker die Bereitstellung des Enforcers auf demselben Knoten wie den Controller als separate Komponenten nicht unterstützt, was die Verwendung des Allinone-Containers erfordert, wenn Controller- und Enforcer-Funktionen auf einem Knoten gewünscht werden.

Controller-Zusammenstellungsdatei (ersetzen Sie [Controller-IP] durch die IP des ersten Controller-Knotens)

[,yaml]
----
controller:
    image: neuvector/controller:<version>
    container_name: controller
    pid: host
    privileged: true
    environment:
      - CLUSTER_JOIN_ADDR=[controller IP]
      - NV_PLATFORM_INFO=platform=Docker
    ports:
        - 18300:18300
        - 18301:18301
        - 18400:18400
        - 18401:18401
        - 18301:18301/udp
        - 10443:10443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/cgroup:ro
      - /var/neuvector:/var/neuvector
----

Docker run kann auch verwendet werden, zum Beispiel

[,shell]
----
docker run -itd --privileged --name neuvector.controller -e CLUSTER_JOIN_ADDR=controller_ip -p 18301:18301 -p 18301:18301/udp -p 18300:18300 -p 18400:18400 -p 10443:10443 -v /var/neuvector:/var/neuvector -v /var/run/docker.sock:/var/run/docker.sock:ro -v /proc:/host/proc:ro -v /sys/fs/cgroup/:/host/cgroup/:ro neuvector/controller:<version>
----

Manager-Kompositionsdatei (ersetzen Sie [controller IP] durch die IP des Controllerknotens, mit dem eine Verbindung hergestellt werden soll). Der Docker UCP HRM-Dienst verwendet den Standardport 8443, der mit dem Konsolenport {product-name} kollidiert. Wenn Sie den Standard-HRM-Anschluss verwenden, ändern Sie die {product-name} -Anschlusszuordnung im folgenden Beispiel in einen anderen Anschluss, z. B. 9443:8443 für den Manager-Container, wie unten gezeigt.

[,yaml]
----
manager:
    image: neuvector/manager:<version>
    container_name: nvmanager
    environment:
      - CTRL_SERVER_IP=[controller IP]
    ports:
      - 9443:8443
----

Die Kompositionsdatei für den Enforcer:

[,yaml]
----
enforcer:
    image: neuvector/enforcer:<version>
    pid: host
    container_name: enforcer
    privileged: true
    environment:
        - CLUSTER_JOIN_ADDR=controller_node_ip
        - NV_PLATFORM_INFO=platform=Docker
    ports:
        - 18301:18301
        - 18401:18401
        - 18301:18301/udp
    volumes:
        - /lib/modules:/lib/modules:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc:/host/proc:ro
        - /sys/fs/cgroup/:/host/cgroup/:ro
----

== Überwachung und Neustart {product-name}

Da die {product-name} Container nicht als UCP/Swarm-Dienst bereitgestellt werden, werden sie nicht automatisch auf den Knoten gestartet/neugestartet. Sie sollten eine Alarmierung über Ihr SIEM-System für {product-name} SYSLOG-Ereignisse oder über DataCenter einrichten, um zu erkennen, ob ein {product-name} Container nicht läuft.

== Bereitstellen ohne privilegierten Modus

Im Allgemeinen müssen Sie die Einstellung privilegiert durch ersetzen:

[,yaml]
----
    cap_add:
        - SYS_ADMIN
        - NET_ADMIN
        - SYS_PTRACE
        - IPC_LOCK
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined
        - label=disable
----

Die obige Syntax gilt für Docker EE v17.06.0+. Frühere Versionen verwenden : anstelle von =, zum Beispiel apparmor:unconfined.

== Docker Native Updates

[CAUTION]
====
Verwenden Sie beim Abrufen und Ausführen des Scanner-Images immer das Tag `:latest`, um sicherzustellen, dass die neueste CVE-Datenbank bereitgestellt wird.
====

[,shell]
----
docker stop scanner
docker rm <scanner id>
docker pull neuvector/scanner:latest
<docker run command from below>
----

[NOTE]
====
`docker rm -f <scanner id>` kann auch verwendet werden, um das Anhalten und Entfernen des laufenden Scanners zu erzwingen.

Für docker-compose

[,shell]
----
docker-compose -f file.yaml down
docker-compose -f file.yaml pull        // pre-pull the image before starting the scanner
docker-compose -f file.yaml up -d
----

Beispiel für einen Docker-Lauf

[,shell]
----
docker run -td --name scanner -e CLUSTER_JOIN_ADDR=controller_node_ip -e CLUSTER_ADVERTISED_ADDR=node_ip -e SCANNER_DOCKER_URL=tcp://192.168.1.10:2376 -p 18402:18402 -v /var/run/docker.sock:/var/run/docker.sock:ro neuvector/scanner:latest
----

Und das Beispiel docker-compose

[,yaml]
----
Scanner:
   image: neuvector/scanner:latest
   container_name: scanner
   environment:
     - SCANNER_DOCKER_URL=tcp://192.168.1.10:2376
     - CLUSTER_JOIN_ADDR=controller_node_ip
     - CLUSTER_ADVERTISED_ADDR=node_ip
   ports:
     - 18402:18402
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
----
====
