= Evaluierung und Prüfung {product-name}
:revdate: 2025-05-08
:page-revdate: {revdate}
:page-opendocs-origin: /09.testing/01.testing/01.testing.md
:page-opendocs-slug:  /testing/testing

== Anwendungsbeispiele

Nachdem Sie die Komponenten von {product-name} implementiert haben, können Sie sie mit den von uns bereitgestellten Beispielanwendungen testen. Diese befinden sich im `'nvbeta`' Repository auf Docker Hub.

Eine typische Kubernetes-basierte Testumgebung besteht aus einem Master-Knoten und zwei bis drei Worker-Knoten. Sie können steuern, ob Anwendungspods und {product-name} Container auf einem Masterknoten bereitgestellt werden (standardmäßig ausgeschaltet).

== Kubernetes Test Plan

Um eine mehrschichtige Anwendung mit Nginx, Nodejs und Redis bereitzustellen, verwenden Sie die folgenden Beispiele (in der unten angegebenen Reihenfolge). Diese müssen möglicherweise für die Bereitstellung auf OpenShift, Rancher und anderen Kubernetes-basierten Tools bearbeitet werden.

Einen Demo-Namensraum erstellen

[,shell]
----
kubectl create namespace demo
----

[NOTE]
====
Das nachstehende Beispiel verwendet apiVersion: apps/v1, die von Kubernetes 1.16+ benötigt wird.
====

Erstellen Sie den Redis-Dienst und die Bereitstellung mit dieser yaml:

[,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: demo
spec:
  ports:
  - port: 6379
    protocol: "TCP"
    name: "cluster-tcp-6379"
  clusterIP: None
  selector:
    app: redis-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod
  namespace: demo
spec:
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
      - name: redis-pod
        image: redis
----

Erstellen Sie den Nodejs-Dienst und die Bereitstellung mit dieser yaml:

[,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: demo
spec:
  ports:
  - port: 8888
    protocol: "TCP"
    name: "cluster-tcp-8888"
  clusterIP: None
  selector:
    app: node-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-pod
  namespace: demo
spec:
  selector:
    matchLabels:
      app: node-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: node-pod
    spec:
      containers:
      - name: node-pod
        image: nvbeta/node
----

Erstellen Sie den Nginx-Dienst und die Bereitstellung mit dieser yaml:

[,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: nginx-webui
  namespace: demo
spec:
  ports:
    - port: 80
      name: webui
      protocol: TCP
  type: NodePort
  selector:
    app: nginx-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod
  namespace: demo
spec:
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-pod
        image: nvbeta/swarm_nginx
        ports:
        - containerPort: 80
          protocol: TCP
----

Um von außen auf den Nginx-webui-Dienst zuzugreifen, suchen Sie den zufälligen Port, der ihm durch den NodePort zugewiesen wurde (auf Port 80 abgebildet):

[,shell]
----
kubectl get svc -n demo
----

Verbinden Sie sich dann mit der öffentlichen IP-Adresse/Port für einen der Kubernetes-Knoten, z. B. `http://(public_IP):(NodePort)`

Nach der Bereitstellung von {product-name} können Sie Testdatenverkehr durch die Demoanwendungen laufen lassen, um die Whitelist-Regeln zu erstellen, und dann alle Dienste in den Überwachungs- oder Schutzmodus versetzen, um Verstöße und Angriffe zu erkennen.

=== Erzeugen von Netzwerkverletzungen in Kubernetes

Um eine Verletzung aus einem Nodejs-Pod zu erzeugen, suchen Sie einen Pod:

[,shell]
----
kubectl get pod -n demo
----

Versuchen Sie dann einige Verletzungen (ersetzen Sie node-pod-name):

[,shell]
----
kubectl exec node-pod-name curl www.google.com -n demo
----

Oder suchen Sie die interne IP-Adresse eines anderen Knotenpods, z. B. 172.30.2.21 im folgenden Beispiel, um eine Verbindung von einem Knoten zum anderen herzustellen:

[,shell]
----
kubectl exec node-pod-name curl 172.30.2.21:8888 -n demo
----

==== Erzeugen einer Bedrohung/eines Angriffs

Um einen Angriff zu simulieren, melden Sie sich in einem Container an und versuchen dann einen Ping-Angriff:

[,shell]
----
kubectl exec -it node-pod-name bash -n demo
----

Verwenden Sie die interne IP eines anderen Nodepods:

[,shell]
----
ping 172.30.2.21 -s 40000
----

Für alle oben genannten Punkte können Sie die Sicherheitsereignisse in der Netzwerkaktivitätskarte der Konsole {product-name} sowie auf der Registerkarte Benachrichtigungen anzeigen.

=== Tests zum Schutz von Prozessen und Dateien

Probieren Sie verschiedene Prozess- und Dateiaktivitäten aus, indem Sie sich in einen Container begeben und Befehle wie apt-get update, ssh, scp oder andere ausführen. Jede Prozessaktivität oder jeder Dateizugriff, der nicht erlaubt ist, führt zu Warnmeldungen in den Benachrichtigungen.

=== Registry Scanning und Zulassungskontrolle

Ein beliebter Test ist die Konfiguration der Bildsuche in einer Registrierung unter Assets -> Registries. Nachdem der Scan abgeschlossen ist, konfigurieren Sie in der Richtlinie eine Regel für die Zugangskontrolle. Stellen Sie sicher, dass Sie die Zugangskontrollen aktivieren und eine Regel auf "Verweigern" setzen, wenn ein Bild hohe Sicherheitsrisiken aufweist. Wählen Sie dann ein Image aus, das hohe Sicherheitsrisiken aufweist, und versuchen Sie, es in Kubernetes einzusetzen. Die Bereitstellung wird im Schutzmodus blockiert und Sie sehen ein Ereignis in den Benachrichtigungen -> Sicherheitsrisiken.

Fortgeschrittenere Zulassungskontrolltests können unter Verwendung verschiedener Kriterien in den Regeln oder durch Kombination von Kriterien durchgeführt werden.

==== Eine andere App bereitstellen

Die Kubernetes-Gästebuch-Demoanwendung kann auch auf Kubernetes bereitgestellt werden. Es wird empfohlen, sie in einem eigenen Namespace zu implementieren, damit Sie die Namespace-basierte Filterung in der {product-name} Konsole sehen können.

== Docker-nativer Testplan

Nachdem Sie die Komponenten von {product-name} und die Beispielanwendung(en) installiert haben, können Sie laufende Container erkennen, überwachen und schützen. Der nachstehende Testplan enthält Vorschläge zur Erzeugung von Laufzeitverletzungen des zulässigen Anwendungsverhaltens und zum Scannen von Containern auf Schwachstellen.

xref:attachment$testplan.pdf[{product-name} Prüfplan]

Wenn der obige Link nicht funktioniert, können Sie es von unserer Website http://neuvector.com/sample-applications-test-plan/[herunterladen] mit dem Passwort nv1851blvd.

{product-name} kann auch Bedrohungen für Ihre Container wie DDOS-Angriffe erkennen. Wenn Sie ein Tool ausführen, um solche Angriffe auf Ihre Container zu generieren, werden diese Ergebnisse in der Netzwerkaktivität und im Dashboard angezeigt.

Ein einfacher Ping-Befehl mit hoher Nutzlast zeigt zum Beispiel den Ping.Death-Angriff in der Konsole an. Um dies auszuprobieren, führen Sie folgende Schritte an der IP-Adresse eines der Container durch (interne IP des Containers).

[,shell]
----
ping <container_ip> -s 40000
----

In Kubernetes können Sie dies von jedem Knoten aus tun, auch vom Master. In anderen Umgebungen müssen Sie möglicherweise an dem Knoten angemeldet sein, auf dem der Container läuft.
