= 5.x Versionshinweise
:revdate: 2025-08-26
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/01.5x/01.5x.md
:page-opendocs-slug:  /releasenotes/5x

== Versionshinweise für 5.x

[NOTE]
====
Um E-Mail-Benachrichtigungen über neue Versionen zu erhalten, abonnieren Sie bitte diese SUSE-Mailingliste: https://lists.suse.com/mailman/listinfo/neuvector-updates
====

=== 5.4.6 August 2025

==== Neue Funktionen

* *NVSHAS-6733*: Antwortregeln als CRD exportieren.
* *NVSHAS-9899*: NeuVector-Profilwarnungen für Java-Dienste enthalten sensible Daten.
* *NVSHAS-9990*: Neuen Hash-Algorithmus für Benutzerpasswörter übernehmen.
* *NVSHAS-9968*: Unterstützung für die Festlegung des Standardpassworts des Standard-Admin-Kontos.

==== Behobene Fehler

* *NVSHAS-10062*: Manager zeigt keinen FEHLER an, wenn das Erstellen des Admin-Passworts beim ersten Login fehlschlägt.
* *NVSHAS-10041*: Federationsoperation fehlgeschlagen "ungültige Daten" beim Konfigurieren der Federation über ConfigMap.
* *NVSHAS-10018*: Neuvector scannt nicht alle Bilder im GitLab-Registry.
* *NVSHAS-10017*: Falsch-Positives Sicherheitswarnung im Zusammenhang mit erlaubtem Prozess.
* *NVSHAS-10001*: Schutz/Überwachung von Durchsetzungsmaßnahmen "verweilt" nach der Gruppenlöschung.
* *NVSHAS-9985*:    NeuVector (Fed Master) verursacht ein Problem für alle Anfragen von außen.
* *NVSHAS-9981*:    Sicherheitsereignis wird ausgelöst, wann immer eine neue "Prozessprofilregel" in einer Gruppe hinzugefügt oder geändert wird.

==== Sicherheitswarnungen

* https://github.com/neuvector/neuvector/security/advisories/GHSA-8pxw-9c75-6w56[Admin-Konto hat unsicheren Standardpasswort]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-8ff6-pc43-jwv3[Unsichere Passwortverwaltung anfällig für Regenbogenangriffe]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-w54x-xfxg-4gxq[Prozesse mit sensiblen Argumenten führen zu Leckagen]

Siehe die xref:cve.adoc[Sicherheitsberatung und CVEs] Dokumentation für weitere Informationen.

=== 5.4.5 Juli 2025

==== Neue Funktionen

* *NVSHAS-9776*: Fügen Sie etcd-Toleranz im Helm-Diagramm hinzu.

==== Fehlerbehebungen

* *NVSHAS-9507*: OCI-Container werden nicht gescannt.
* *NVSHAS-9787*: Entfernen Sie unnötige Managerprotokolle.
* *NVSHAS-9788*: Algorithmus zur Generierung von Zertifikaten verfeinern.
* *NVSHAS-9789*: Entfernen Sie unnötige Managerprotokolle zur Konfiguration des Remote-Registrierungsdienstes.
* *NVSHAS-9867*: NeuVector zeigt `+.NET Library System.Formats.Asn1 v8.013+` betroffene CVE 2024-38095.
* *NVSHAS-9883*: [quay.io] Wildcard-Filter funktionieren nicht für Docker-Registry.
* *NVSHAS-9911*: Das Scannen des Repos über die REST-API führt zu einer falschen "Nachricht".
* *NVSHAS-9930*: CVE-2018-20796 für `+glibc/libc-bin : 2.36-9+deb12u10+` – Falsches Positiv.
* *NVSHAS-9933*: Registry-Adapter-Funktion (Harbor) zeigt Fehler in der Ziel-Registry beim Scannen an.
* *NVSHAS-9934*: Verdacht auf Fehlfunktion der Zero-Drift-Funktionalität.
* *NVSHAS-9940*: NV-Scan JFrog Subdomain-Modus-Problem.
* *NVSHAS-9942*: Bildscans für Kundenbilder schlagen fehl.
* *NVSHAS-9945*: Wenn der Prozessname zu lang ist, ist es schwierig zu bestimmen, wie die entsprechende Prozessprofilregel erstellt werden kann.
* *NVSHAS-9946*: Anzeigeproblem mit der Admission Control-Warnung für den Credential-Typ.
* *NVSHAS-9947*: [UI-ext] Compliance-Diagramm fehlt der Status "Manuell" in Rancher NeuVector.
* *NVSHAS-9948*: Nach dem Upgrade auf `+5.4.3+` wurde die NeuVector-Konfiguration verloren.
* *NVSHAS-9949*: [Harbor][Falscher Benutzer/PW] Es scannt weiterhin Bilder, selbst bei falscher Benutzer/PW-Eingabe.
* *NVSHAS-9952*: Entfernen Sie 'Signatur' aus dem Nutzungsbericht, da NV den Lizenzschlüssel nicht mehr ausstellt/prüft.
* *NVSHAS-9953*: Pods Enforcer startet ständig neu.
* *NVSHAS-9954*: NeuVector Prometheus-Exporter erzeugt doppelte Metriken.
* *NVSHAS-9958*: Die Durchsetzung von Netzwerkregeln dauert lange.
* *NVSHAS-9960*: Scanner funktionieren nicht.
* *NVSHAS-9969*: Fatale Fehler: gleichzeitige Kartenänderungen führen zum Neustart der Enforcer-Komponente.
* *NVSHAS-9971*: NV UI über `+Get Bootstrap Password+`.
* *NVSHAS-9975*: [Manager] TypeError: `+this.mousemoveListener+` ist keine Funktion, die in der NV GUI beobachtet wurde.
* *NVSHAS-9986*: Prozess- und Datei-Zugriffsregeln können in der Ansicht der föderierten Richtliniengruppe nicht bearbeitet oder entfernt werden.
* *NVSHAS-9988*: UI: Gruppenseiten zeigen nicht alle Gruppen an, wenn mehr als 2.000 Gruppen vorhanden sind.
* *NVSHAS-9991*: Gruppe `+nv.gatekeeper-controller-manager.openshift-azure-guardrails+` fehlt in der UI.
* *NVSHAS-9993*: MD5 durch SHA256 ersetzen.
* *NVSHAS-9994*: Enforcer-Pod startet ständig neu.
* *NVSHAS-9996*: Das Helm-Diagramm sollte den nicht privilegierten Modus der Enforcer-Pods zulassen.
* *NVSHAS-9998*: Kann Gruppe nicht aus dem NeuVector-föderierten Master exportieren.
* *NVSHAS-10000*: Upgrade NV auf BCI 15.7.
* *NVSHAS-10003*: Die Seite neu laden funktioniert nicht auf der eigenständigen NV-Seite, während die Rancher-Benutzeroberfläche geöffnet ist.
* *NVSHAS-10008*: Registry-Scan – Das Ansicht-Menü ist für das gescannte Bild defekt.
* *NVSHAS-10010*: TCP SYN Flood blockiert den Eingang, was zu einem vollständigen Block des eingehenden Datenverkehrs führt.

=== 5.4.4 Mai 2025

==== Neue Funktionen

* **NVSHAS-9915**: Zeige Scanergebnisse aus dem Harbor-Scanner-Modul in der NeuVector-Benutzeroberfläche an.
* **NVSHAS-9904**: Expose `+imagePullPolicy+` zu `+values.yaml+` für jede Komponente.
* **NVSHAS-9869**: UI: Verschiebe DDoS-Kontrollen in das Gruppenfenster.
* **NVSHAS-9840**: [GCP] NeuVector Autopilot-Unterstützung für GCP.
* **NVSHAS-9248**: Zeige ungenutzte Prozess-/Netzwerkregeln mit Zählern und `+Last Used+` Zeitstempel an.
* **NVSHAS-8160**: [Controller] Einige Elemente für die Berechnung des Sicherheitsrisikowertes anpassen.
* **NVSHAS-4673**: Vorschlag, eine Nachricht vor dem Exportieren von Gruppen hinzuzufügen.

==== Fehlerbehebungen

* **NVSHAS-9931**: Füge eine Warnung hinzu, wenn inkonsistente Versionen von NeuVector-Produkten in einem Multi-Cluster vorhanden sind.
* **NVSHAS-9925**: `+/v1/scan/asset/images+` API auf der Registrierungsseite schlägt fehl.
* **NVSHAS-9913**: Problem beim Löschen mehrerer Netzwerkregeln, die mit den Workload:XYZ-Gruppen verbunden sind.
* **NVSHAS-9912**: Aktualisiere Helm über einige K8s RBAC-Berechtigungen, die vom Controller-Dienstkonto benötigt werden.
* **NVSHAS-9909**: "Abgemeldet - Gehe zur Lade-Seite" Nachricht wird angezeigt, wenn NeuVector Rancher NavLink verwendet wird.
* **NVSHAS-9898**: In einer föderierten Umgebung funktioniert das Ändern der Kriterien einer vom Kunden erstellten fed.* Gruppe (z.B. fed.core-systems) nicht.
* **NVSHAS-9894**: [Enforcer] `+Nv.protect+` verweigert den Befehl zur Bereitschaftsprüfung des Controllers `+cat /tmp/ready+`.
* **NVSHAS-9886**: Netzwerkaktivität löst keine Domainnamen für die benutzerdefinierten externen Gruppenverbindungen auf.
* **NVSHAS-9884**: [Node Scan][Container Scan] Der Scan schlägt fehl.
* **NVSHAS-9873**: UI Advanced Filter Suchproblem in NeuVector 5.4.2.
* **NVSHAS-9865**: Exportierte Netzwerkrichtlinien unterscheiden sich, abhängig von der Auswahlreihenfolge (die gleichen Gruppen ausgewählt).
* **NVSHAS-9828**: [Enforcer: Prozess] Der NeuVector Enforcer kann kurzlebige Pods (weniger als 5 Sekunden) nicht erkennen.
* **NVSHAS-9783**: Nachdem die Netzwerkrichtlinie zum Verweigern von ICMP-Paketen hinzugefügt wurde, sieht NeuVector keine Warnungen in `+Security Events+`.
* **NVSHAS-9176**: Zeige einen Skriptfehler auf der **Security Risks > Vulnerabilities** Seite an, wenn ein Benutzer mit der Berechtigung im Namespace `+rt_scan:w+` angemeldet ist.

=== 5.4.3 März 2025

==== Neue Funktionen

* **NVSHAS-9793**: Erlaube Fed Global-Rollen in LDAP/userinitcfg beim Bereitstellen von NeuVector über das ConfigMap und Secret.
* **NVSHAS-9764**: [RFE] Unterstützung für Azure für "Remote Repository Configuration" hinzufügen.
* **NVSHAS-9759**: Füge Datumsdetails im Ingress-Exposure-Bericht hinzu.
* **NVSHAS-9755**: Anfrage zur Anzeige von Umgebungsvariablennamen neben Werten in Warnungen für Geheimnisse.
* **NVSHAS-9748**: [Helm] NeuVector Helm-Update zur Unterstützung von Namensreferenzen für gemeinsame Gruppen in CRD (NVSHAS0-4717).
* **NVSHAS-9426**: Füge hostPath für Scanner zum Helm-Chart hinzu.
* **NVSHAS-9326**: NeuVector - Harbor Pluggable Scanner Modul.
* **NVSHAS-9835**: UI zum Deaktivieren des automatischen Scans für Knoten.
* **NVSHAS-7997**: Scanner-Connector für ghcr.io.
* **NVSHAS-7982**: Weise WAF-Sensoren vom Federation Master zu.

==== Fehlerbehebungen

* **NVSHAS-9849**: Enforcer registrieren sich nicht bei Controllern.
* **NVSHAS-9847**: Wildcard-Filter funktionieren nicht für Docker-Registry.
* **NVSHAS-9833**: Wiederherstellung der Konfiguration schlägt in Rancher-Bereitstellungen fehl.
* **NVSHAS-9832**: Problem beim Erstellen von Netzwerkregeln mit der Arbeitslastgruppe.
* **NVSHAS-9821**: Der Prozessname wird nicht von der Befehlszeile für die Prozessgewinnregelwarnung übereinstimmt.
* **NVSHAS-9817**: Das Erstellen der NvClusterSecurityRule CRD zeigt eine erfolgreiche Erstellung, aber sie wurde aufgrund doppelter Prozesseinträge nicht tatsächlich erstellt.
* **NVSHAS-9812**: NeuVector prometheus-exporter falsche Metriken.
* **NVSHAS-9811**: [Manager] Kann die GUI nicht aufrufen, wenn ein benutzerdefiniertes Zertifikat (CA) mit Root-CA und Zwischen-CA im Geheimnis verwendet wird.
* **NVSHAS-9801**: FIPS-Modus + `+manager.env.ssl=false+` führt dazu, dass der Manager einen Fehler ausgibt.
* **NVSHAS-9792**: Die Synchronisierung der Föderationsrichtlinie schlägt fehl, da die Körpergröße das Maximum von Consul überschreitet.
* **NVSHAS-9784**: NeuVector gibt 404 während des Scannens des Jfrog-Image-Repositorys zurück.
* **NVSHAS-9783**: Nachdem die Netzwerkpolitik hinzugefügt wurde, um ICMP-Pakete zu verweigern, sieht der Benutzer keine Warnung in "Sicherheitsereignisse".
* **NVSHAS-9780**: NeuVector Single Sign-On funktioniert nicht mit Rancher NavLink.
* **NVSHAS-9777**: Webhook-JSON mit doppelten "Level"-Schlüsseln.
* **NVSHAS-9770**: Auto-Switch nach dem Zero-Drift-Modus schaltet die falsche Richtlinie um.
* **NVSHAS-9765**: Dateizugriff wird im Schutzmodus nicht vollständig blockiert.
* **NVSHAS-9756**: Der Durchsetzer hat die maximale CPU erreicht und hat mehrere Speicher-Druckwarnungen.
* **NVSHAS-9668**: Compliance-Test schlägt bei RKE2 fehl.
* **NVSHAS-9265**: Unvollständige und falsche Ergebnisse des Schwachstellenscans in der PRE-PCI-Umgebung.
* **NVSHAS-9227**: Der Registry-Scan bleibt mitten im Scanprozess stecken und wechselt in den "Leerlauf"-Zustand.
* **NVSHAS-9729**: Eine falsche Anzahl von Schwachstellen wird beobachtet, wenn mehrere StatefulSets mit dem "gleichen Namen" in Namespaces in einem Projekt bereitgestellt werden.
* **NVSHAS-9810**: NeuVector-Controller reagiert nicht und die UI ist nicht zugänglich.

=== 5.4.2 Januar 2025

==== Neue Funktionen

* **NVSHAS-9726**: Der Monitor übergibt jetzt die Proxy-URL.
* **NVSHAS-9719**: Gibt die Stilllegung von integrierten Zertifikaten bekannt.
* **NVSHAS-9715**: Unterstützung von Helm-Chart-Werten zum Festlegen des Nodeports für Controller und Manager.
* **NVSHAS-9710**: Fügen Sie eine sortierbare `+feed_rating+` Spalte in den **Schwachstellen** Tab ein.
* **NVSHAS-9669**: Gesamtbewertung der Sicherheit über die REST-API.
* **NVSHAS-9590**: Möglichkeit, welche Schwachstellenbewertung für alle Assets auszuwählen.
* **NVSHAS-7555**: Fügen Sie die Option "Auto-Refresh" unter Sicherheitsereignisse hinzu.

==== Fehlerbehebungen

* **NVSHAS-9662**: Inkonsistente Rolle/Rollenbindung-Logik im Helm-Chart 2.8.2.
* **NVSHAS-9652**: Beobachteter Unterschied im Syslog-Format in Splunk.
* **NVSHAS-9649**: Container-Link erzeugt 404-Antwortcode im Sicherheitsereignis.
* **NVSHAS-9613**: NeuVector Manager Pod-Fehler / NeuVector Web UI nicht verfügbar.
* **NVSHAS-9507**: OCI-Container werden nicht gescannt.
* **NVSHAS-9443**: Upgrade/Installation über ArgoCD schlägt fehl, da es das Objekt leases.coordination.k8s.io nicht erstellen kann.
* **NVSHAS-9436**: Möglicher CVE-Falschnachweis gegen CVE-2024-7347.
* **NVSHAS-8386**: Private Schlüssel und selbstsignierte Zertifikate werden weiterhin in mehreren Bildern ausgeliefert.
* **NVSHAS-9754**: [UI] Verhindern Sie, dass Rancher verwandte SSO-Benutzer die Authentifizierung von OpenShift oder Ranchers RBAC deaktivieren.
* **NVSHAS-9751**: [Laufzeitschutz] Überwachungsmodus + Nulldrift erzeugt keine Warnungen, wenn ein Kindprozess ausgeführt wird.
* **NVSHAS-9721**: Die UI sollte eine geeignete Fehlermeldung anzeigen, wenn der Benutzer einen falschen Registrynamen eingibt.
* **NVSHAS-9696**: Inkonsistente Farbkennzeichnung von Assets auf der Schwachstellenseite.
* **NVSHAS-9686**: Fest codierter Namespace für das Zertifikat des Registrierungsadapters im Neuvector Helm-Chart.
* **NVSHAS-9678**: Übermäßige Fehlermeldungen nach den Änderungen des Linters.
* **NVSHAS-9670**: Manager: Problem mit einfachen Textantworten in Anführungszeichen und unbenanntem Java-Bibliotheksproblem im sbt-Lauf.
* **NVSHAS-9667**: Das Setzen der `+CTRL_PATH_DEBUG+` Umgebungsvariable auf Fehler bei der Bereitstellung des Controllers funktioniert nicht.
* **NVSHAS-9665**: Dateizugriffsregel: Das Löschen vordefinierter Regeln erzeugt einen "setRowData"-Fehler.
* **NVSHAS-9664**: Richtlinengruppe: Das Löschen des benutzerdefinierten Skripts erzeugt einen "setRowData" TypeError.

[NOTE]
====
Die Standardtypen des Manager- und Registrierungsadapterdienstes wurden auf ClusterIP geändert.  Benutzer können die Einstellung weiterhin überschreiben, indem sie `+manager.svc.type+` und `+cve.adapter.svc.type+` überschreiben, wenn NodePort bevorzugt wird.
====

In der NeuVector-Version 5.4.2 wird die Unterstützung für Bereitstellungen, die das integrierte interne Zertifikat verwenden, eingestellt. Das Zertifikat, das sich bei `+/etc/neuvector/certs/internal+` innerhalb der NeuVector 5.4.2-Containerbilder befindet, wird entfernt. Um NeuVector weiterhin zu verwenden, sollten Benutzer:

==== 5.4.2 Neue Installation:

===== Verwendung von Helm:

- Aktivieren Sie die `+internal.autoGenerateCert+` und `+internal.autoRotateCert+` Flags in den Helm-Diagrammen (diese werden ab der Version 5.4.2 standardmäßig aktiviert). Alternativ ist eine YAML-Methode unten verlinkt.

===== Verwendung von YAML:

- Stellen Sie ein xref:internal.adoc#_replacing_certificates_used_in_internal_communications_of_suse_security[internes Zertifikat mit den vorhandenen Methoden] bereit.

==== Upgrade von vorherigen Versionen auf 5.4.2:

Bitte erstellen und konfigurieren Sie interne Zertifikate vom Scanner für den Controller, den Durchsetzer und den Registrierungsadapter, um ein Rolling Update ohne Datenverlust zu erreichen. Es wird weiterhin empfohlen, eine Sicherung Ihrer Konfiguration vor dem Upgrade zu erstellen. 

Die folgenden Schritte sind nur erforderlich, wenn Ihre Bereitstellung eine `+.yaml+` Datei verwendet. Das Upgrade mit Helm benötigt diese zusätzlichen Schritte nicht, da die internen Zertifikate standardmäßig über die folgenden Flags erstellt werden: `+internal.autoGenerateCert+` und `+internal.autoRotateCert+`.

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/ca.cert" > ca.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.pem" > tls.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.key" > tls.key
----

[,shell]
----
kubectl create secret generic internal-cert -n neuvector  --from-file=tls.key --from-file=tls.crt --from-file=ca.crt
----

Beispiel 5.4.2 yaml mit internem Zertifikat konfiguriert:
*https://github.com/neuvector/manifests/blob/main/kubernetes/5.4.0/neuvector-k8s.yaml* 

Zusätzliche Informationen zu xref:internal.adoc[internen Zertifikaten].


Im Falle einer PVC-Konfiguration können Benutzer ein vorhandenes PVC in der neuen Installation konfigurieren, um eine Konfiguration wiederherzustellen.


**Zusätzlicher Hinweis für Scanner:**

Für aktuelle Benutzer mit Versionen vor 5.4.2 bleibt das Zertifikat bis zum 31. März 2025 im `+neuvector/scanner:latest+` verfügbar. Nach diesem Datum wird es entfernt. Benutzer sollten planen, dasselbe interne Zertifikat dem Controller, dem Durchsetzer, dem Scanner und dem Registrierungsadapter zur Verfügung zu stellen, um den Scanner weiterhin zu verwenden.

Bitte beachten Sie, dass der eigenständige Scanner von diesen Änderungen nicht betroffen sein wird.

=== 5.4.1 November 2024

==== Neue Funktionen

* **NVSHAS-8583**: Festlegen granularer Richtlinienmodi für Regelsets, separater Netzwerkrichtlinienmodus und Profilmodus auf Gruppenebene.
* **NVSHAS-9440**: Unterstützung für separaten Netzwerkmodus und Prozess- und Dateimodus in CRD.
* **NVSHAS-9369**: Debug-Protokollkategorie über Helm-Bereitstellungsunterstützung für den Controller hinzufügen.
* **NVSHAS-9040**: Verbessern Sie die Syslog-Nachricht, wenn die Zulassungssteuerungsregel im Überwachungsmodus abgelehnt wird.

==== Fehlerbehebungen

* **NVSHAS-9416**: [Scanner] activemq-all-5.8.0.redhat-60024.jar kann mit keinem vul erkannt werden (aber der vorherige Scanner-Build kann).
* **NVSHAS-9447**: Controller/Scanner-Pods stürzen ab - "Nicht unterstützter Systemausgang".
* **NVSHAS-9278**: CVE-2024-41110 wurde im neuesten Scanner-Image gefunden.
* **NVSHAS-9467**: Die benutzerdefinierte Gruppe, die durch das Pod-Label definiert ist, propagiert ihre Profildaten nicht auf die untergeordneten Container.
* **NVSHAS-9442**: Bereitstellungsproblem bei ArgoCD.
* **NVSHAS-9436**: Möglicher CVE-Falschnachweis gegen CVE-2024-7347.
* **NVSHAS-9468**: Behebe CVE-2020-26160, um jwt-go durch jwt:v5 zu ersetzen.
* **NVSHAS-9517**: Die Zulassungssteuerung ist inkonsistent und liefert falsche Ergebnisse.
* **NVSHAS-9532**: Der Bildscan ist abgeschlossen, aber die Bereitstellung ist weiterhin nicht erlaubt.
* **NVSHAS-9558**: JWT-Token-Ablauf meldet http.StatusRequestTimeout 408.
* **NVSHAS-9576**: Leeres Passwortfeld für Registrierungsdaten, wenn der Benutzer den Controller-Modus mit Jenkins zum Scannen verwendet.
* **NVSHAS-9425**: Erstelle nfq, wenn der Container vxlan hat.
* **NVSHAS-9571**: [Registries] Filter für alle gescannten Bilder funktioniert nicht gut.
* **NVSHAS-9589**: Verwaltete Cluster getrennt - Versionskonflikt mit dem primären Cluster.
* **NVSHAS-8824**: Benutzer kann eigene Gruppen nicht löschen, kann keine namespace-spezifischen Gruppen erstellen.
* **NVSHAS-9605**: Exportgruppe mit ungültigen Werten für den Richtlinienmodus und den Prozessprofilmodus wird fälschlicherweise erlaubt.
* **NVSHAS-9608**: Scanner meldet keinen Fehler, wenn der Controller einen Fehler für große Scan-Ergebnisse ~23MB meldet.
* **NVSHAS-9534**: Fehler in den Zulassungssteuerungen anzeigen.
* **NVSHAS-9600**: Controller-Debug kann nicht deaktiviert werden.
* **NVSHAS-9631**: Reduziere einige Durchsetzungsfehler.
* **NVSHAS-9645**: Die Verarbeitung von bereits vorhandenen CRDs schlägt fehl.
* **NVSHAS-9592**: Kein neuer Scan trotz neuer DB-Version.
* **NVSHAS-9212**: Zeige Warnmeldung in GET(/v1/eula) an, wenn die Rolle (Binding) neuvector-binding-secret falsch ist.
* **NVSHAS-9367**: Verbessere Fehlermeldungen, wenn die Registrierung nicht verbunden werden kann.
* **NVSHAS-9475**: Der Hintergrundrasterdruck deckt nicht vollständig ab, wenn das Menü minimiert ist.
* **NVSHAS-9485**: Falsche Nachricht für 'Netzwerksicherheitsrichtlinienmodus' in der Benutzeroberfläche.
* **NVSHAS-9480**: Die NV-Benutzeroberfläche, die im Rancher-Downstream-Cluster bereitgestellt wird, gibt nach dem Abmelden von Rancher HTTP/403 zurück.
* **NVSHAS-9547**: Die Sortierung ist auf der Tabelle der Sicherheitsrisiken --> Schwachstellen defekt.
* **NVSHAS-9570**: [Schwachstellen] Ändern Sie die Legendenbeschreibung für verschiedene Status bei Vermögenswerten.
* **NVSHAS-9561**: Die Gesamtbewertung der Sicherheitsanzeige sollte mit der tatsächlichen Bewertung übereinstimmen.
* **NVSHAS-9572**: [Schwachstellen] Die gefilterten Daten wurden unabhängig von der Benutzeraktualisierung oder dem erneuten Anmelden auf der Seite beibehalten.
* **NVSHAS-9597**: Die Benutzeroberfläche reagiert nicht auf einen Fehler, wenn der Controller 403 für POST(v1/group) zurückgibt.
* **NVSHAS-8682**: Der CRD-Webhook-Dienst muss vom CRD-Helm-Diagramm in das Anwendungs-Helm-Diagramm verschoben werden.

==== Bekannte Probleme

* In der Version 2.8.3 des Diagramms haben wir eine zuvor falsch zugewiesene Ressource von crds zu core verschoben. Wenn Sie sowohl crds- als auch core-Diagramme verwenden, können während des Upgrades Probleme auftreten, wenn Sie zuerst core bereitstellen. Um dies zu beheben, aktualisieren Sie zuerst die crds und dann die core-Diagramme.

=== 5.4 September 2024

* **UI-Verbesserungen**: 
** Rancher SSO-Benutzer anzeigen.
** JWT-Token verwalten.
** Erweiterte Bildnavigation und Links zu Scanergebnissen.
* **Sicherheitsverbesserungen**: 
** Neue Compliance-Filter.
** Unterstützung für CIS-Benchmarks und OCI-Image-Signierung.
* **Netzwerk & Überwachung**: 
** Erweiterte Bandbreiten- und Sitzungsverfolgung.
** DDoS-Überwachung.
** Multus-Netzwerkunterstützung.
* **Zertifikatsverwaltung**: 
** Neue Benachrichtigungen für ablaufende interne Zertifikate, einschließlich Rotationsmöglichkeiten.
* **Automatisierung & Integration**: 
** Automatisierung der Föderation.
** Rancher RBAC-Integration.
** Verbesserte Zugangssteuerung.
* **Leistung & Effizienz**: 
** Reduzierter Speicherverbrauch.
** Reduzierung der ISP-Datenkosten.
** Offenlegung der Scanner-Cache-Statistiken.
* **Benutzerfreundlichkeitsverbesserungen**: 
** Unterstützung für Bootstrap-Passwörter.
** Archivierung von Cloud-Abrechnungsdaten.
** Durchsetzung von Namespace-Grenzen.

==== Neue Funktionen

* **NVSHAS-9012**: Anzeige von Rancher SSO-Benutzern in der NV-Benutzeroberfläche, die denselben Benutzernamen haben.
* **NVSHAS-8939**: Bereitstellung einer Option in der NV-Benutzeroberfläche, damit Rancher SSO-Sitzungsbenutzer das aktuelle JWT-Token (d.h. Abmeldung) ablegen können.
* **NVSHAS-7522**: Einfache Bildnavigation durch Registrierungen.
* **NVSHAS-8148**: Link vom Containerbild zu den Scanergebnissen des Registrierungsbildes.
* **NVSHAS-9258**: Fügen Sie eine neue Benachrichtigung für ablaufende Zertifikate und interne Zertifikate hinzu.
* **NVSHAS-8915**: Unterstützung für neue Compliance-Filter und Compliance-Bericht.
* **NVSHAS-9403**: Filemonitor-UI: Erlauben Sie dem Benutzer, vordefinierte Dateiüberwachungsregeln zu löschen.
* **NVSHAS-8423**: Erkennung von Bandbreite auf Gruppenebene, aktiver Sitzungsanzahl und Sitzungsratenverletzungen basierend auf konfigurierten Schwellenwerten.
* **NVSHAS-9218**: Unterstützung für Bundes- und CRD-Gruppen zur DDoS-Überwachung.
* **NVSHAS-8461**: Unterstützung von CIS-Benchmarks für verwaltete k8s-Dienste in der Cloud.
* **NVSHAS-7664**: Reduzierung der ISP-Datengebühren während des Scannens von Registrierungen.
* **NVSHAS-8868**: Statistiken zum Scanner-Cache offenlegen.
* **NVSHAS-8676**: Verbesserung von NV Protect für Benchmark-Skripte.
* **NVSHAS-9255**: Anpassung der Suchregistrierungen für die Zulassungssteuerung für Bildnamen ohne FQDN.
* **NVSHAS-9144**: ID hinzugefügt für das Schwachstellenprofil zur einfachen Identifizierung.
* **NVSHAS-7687**: Unterstützung der Konfiguration des Protokollniveaus (debug/error/info/warn) für Durchsetzer und Controller über die CLI.
* **NVSHAS-7518**: Ändern Sie interne Zertifikate für {product-name} Komponenten.
* **NVSHAS-9287**: Aktivieren Sie die Rotation interner Zertifikate.
* **NVSHAS-8562**: Fügen Sie eine Benachrichtigung über das Ablaufdatum interner Zertifikate hinzu.
* **NVSHAS-8486**: Unterstützung der Multus-Netzwerkschnittstelle.
* **NVSHAS-7447**: Rancher RBAC-Integration mit {product-name}.
* **NVSHAS-7822**: Föderationsautomatisierung ohne Skripting-API-Aufrufe.
* **NVSHAS-8799**: Erstellen Sie ein Compliance-Rahmenwerk für den Import von Compliance-Vorlagen.
* **NVSHAS-8773**: Bootstrap-Passwortunterstützung während der ersten Bereitstellung.
* **NVSHAS-6740**: Verbesserung des Null-Drift-Baseline-Profils durch Durchsetzung der gelernten Liste im Schutzmodus.
* **NVSHAS-8325**: Durchsetzung der Container-Namensraumgrenze für Netzwerkregeln.
* **NVSHAS-8723**: Archivieren von Cloud-Abrechnungsdaten.
* **NVSHAS-9086**: Reduzierung des Speicherverbrauchs des Controller-Prozesses durch Eliminierung der vulTrait-Datenstruktur.
* **NVSHAS-6979**: Möglichkeit, den Kommentar der Antwortregel im Alarminhalt einzuschließen.
* **NVSHAS-8845**: APIKEY mit der Rolle FedReader und FedAdmin erstellen.
* **NVSHAS-9306**: Die Bewertung der Admission Control-Konfiguration zeigt die Regel-ID, die für erlaubte oder abgelehnte Bereitstellungen verantwortlich ist.
* **NVSHAS-9078**: Unterstützung für die Bildsignierung für OCI-Bilder.
* **NVSHAS-7945**: Unterstützung des DISA STIG-Benchmarks für Kubernetes.
* **NVSHAS-8234**: Admission Control-Logik, die Bilder zulässt, die abgelehnt werden sollten.

==== Fehlerbehebungen

* **NVSHAS-9005**: TypeError in Registries: Kann Eigenschaften von undefiniertem Wert nicht lesen (lesen von 'total_records').
* **NVSHAS-9085**: Der PDF-Bericht der Vermögenswerte zeigt 0% Verwundbarkeit, selbst bei vorhandenen Verwundbarkeiten.
* **NVSHAS-9084**: Der PDF-Bericht der Vermögenswerte zeigt NaN, wenn die Bildliste leer ist.
* **NVSHAS-9128**: Sicherheitsereignisse: Container können nicht angezeigt werden, wenn kein Namespace-Wert für die Arbeitslast vorhanden ist.
* **NVSHAS-9025**: Neuvector-Vulnerabilitätsakzeptanzbereich für Container.
* **NVSHAS-9155**: Registry-Scan-Bild falscher Spaltenname und fehlender Dateiname.
* **NVSHAS-9122**: Neuvector-Masterprotokolle melden sich jederzeit ab, wenn "Multiple Cluster" mit Rancher SSO-Login verwendet wird.
* **NVSHAS-9266**: Registry-Scan: Die Schaltfläche "Scanbericht nach Schicht" sollte ausgeblendet oder deaktiviert sein, wenn keine Schwachstelle vorhanden ist.
* **NVSHAS-9219**: Benutzern erlauben, die Serverzertifikatsvalidierung für Authentifizierungsserver zu aktivieren.
* **NVSHAS-9246**: Die Filterung für den CSV/PDF-Export funktioniert nicht.
* **NVSHAS-8947**: NV-Konfiguration kann nicht importiert werden, wenn über Rancher SSO authentifiziert wird.
* **NVSHAS-9282**: UI: Das Bearbeiten des OpenShift-Registry-Eintrags schlägt aufgrund eines fehlenden Tokens fehl.
* **NVSHAS-9098**: Verbessern Sie die Benutzererfahrung beim Laden der Risikoseite.
* **NVSHAS-9267**: Erlauben Sie der Benutzeroberfläche im 5.4-Master-Cluster nicht, zu verwalteten Clustern vor 5.4 zu wechseln, aufgrund von Änderungen an der REST-API.
* **NVSHAS-9285**: UI: Der Dropdown-Listen-Button überlappt sich mit anderen Elementen.
* **NVSHAS-9302**: APIKEY kann nicht mit der Rolle FedReader und FedAdmin erstellt werden.
* **NVSHAS-8539**: Die Neukonfiguration der Proxy-Einstellungen verliert das Passwort.
* **NVSHAS-9293**: Entfernung von nicht verwandten Bilddetails in den Sicherheitsberichten.
* **NVSHAS-9238**: Die UI aktualisiert den angezeigten Clusternamen nach der Änderung nicht.
* **NVSHAS-9363**: Benachrichtigungskonfiguration > Webhooks-Raster sind nicht richtig ausgerichtet.
* **NVSHAS-9362**: Der Sicherheitsrisiko-Schwachstellenfilter gibt 0 Ergebnisse zurück.
* **NVSHAS-8699**: Kann den Benutzer nicht unterscheiden, wenn der Rancher AD-Benutzer derselbe ist.
* **NVSHAS-9062**: Anzeige von Rancher SSO-Benutzern in der NV-UI, die denselben Benutzernamen haben (Konvertierung auf dem Controller).
* **NVSHAS-9071**: Einige Module werden nur im Container-Scan nicht gemeldet.
* **NVSHAS-8242**: gRPC-Aufruf, um zu testen, ob der Controller kritische Schweregrade behandelt.
* **NVSHAS-8908**: X-Forwarded-Port korrekt analysieren unter Berücksichtigung des Komma-Trennzeichens.
* **NVSHAS-9024**: AdmissionControl Riskante Rolle Perf.
* **NVSHAS-9091**: Kann nicht alle Module unter ol:9.1, photon:5.0, rhel:9.1 und amzn:2023 in Repo, Registry und Standalone-Scan melden.
* **NVSHAS-8997**: Die Anzahl der Richtlinien-Slots pro Knoten erheblich reduzieren, um die Leistung zu verbessern.
* **NVSHAS-9059**: CRD-Gruppen sind in NV sichtbar, selbst nach der Löschung aus K8s.
* **NVSHAS-9107**: Goroutine-Absturz bei rest.handlerConfigLocalCluster.
* **NVSHAS-9108**: Port 18500 sollte nicht offen sein.
* **NVSHAS-9119**: Goroutine-Absturz bei probe.(*FileNotificationCtr).AddContainer().
* **NVSHAS-9125**: CRD-Eintrag mit ungültigen Einstellungen sollte nicht erstellt werden dürfen.
* **NVSHAS-9124**: Docker: Viele unerwartete Vorfälle im Gesundheitscheck-Prozess werden gemeldet.
* **NVSHAS-9111**: NV sollte `+--event-qps > 0+` überprüfen.
* **NVSHAS-9130**: Unerwartete Container.Package.Updated-Vorfälle werden gefunden, nachdem ein bestimmter Container gestartet wurde.
* **NVSHAS-9080**: Der Benutzer des Fed Readers kann auf einige REST-APIs nicht zugreifen.
* **NVSHAS-9092**: Benutzer mit Namensraum sollte keine globalen Assets sehen.
* **NVSHAS-9116**: Der Arbeitscluster kann verlassen werden, wenn die Verbindung unterbrochen wird.
* **NVSHAS-8980**: Host- und Tunnel-Schnittstelle auf dem Knoten erfolgreich in oc 4.15 abrufen.
* **NVSHAS-9188**: Setze die mgmt-br-Schnittstelle als Hostschnittstelle für den Ernteknoten.
* **NVSHAS-4858**: Containergruppen im Controller nicht erweitern, um die Leistung der Richtlinienbereitstellung zu verbessern und CPU- sowie Speicherauslastung zu reduzieren.
* **NVSHAS-8700**: Rancher AD-Benutzer kann sich manchmal nicht bei {product-name} anmelden.
* **NVSHAS-9121**: Die Netzüberwachungs-Schwellenwerteinstellung der Gruppe kann nicht bearbeitet werden.
* **NVSHAS-9189**: Der Scan wird nach dem Herunterfahren und Neustarten des Controllers im Zeitplan stecken bleiben.
* **NVSHAS-9019**: Unsynchronisierten Linkzustand für die Hostschnittstelle beheben.
* **NVSHAS-8305**: Integriertes Zertifikat entfernen.
* **NVSHAS-9013**: BPF-Filter im Prozessmonitor entfernen.
* **NVSHAS-7853**: TLS-Handshake EOF.
* **NVSHAS-9290**: Benutzerhinzugefügte Prozessprofilregel hat mit aktiviertem ZD keine Wirkung.
* **NVSHAS-9301**: NV, das auf Rancher Prime bereitgestellt wurde, kann nicht erkennen, dass es sich um die Rancher-Version handelt.
* **NVSHAS-9289**: Upgrade erlauben, wenn RBAC fehlt.
* **NVSHAS-7601**: Verbessern Sie die Wiederherstellung aus der PV-Konfigurationssicherung während der Szenarien.
* **NVSHAS-7687**: Fügen Sie die Syslog-Level-Einstellung für den Durchsetzer hinzu.
* **NVSHAS-9292**: Beheben Sie die Anzeige von 0 Sicherheitsanfälligkeiten bei Ingress Egress.
* **NVSHAS-9270**: Unterstützung von k3s für die CIS-Benchmark-Pipeline.
* **NVSHAS-9338**: Warnung: 'Verwalteter Cluster [id] ist vom Primärsystem getrennt'.
* **NVSHAS-9358**: Bildscan über Proxy würde fehlschlagen.
* **NVSHAS-9337**: Senden Sie eine Protokollnachricht, wenn ein SYN-Flood erkannt wird.
* **NVSHAS-9209**: Löschen Sie den Domain-Cache, wenn der Namespace aus k8s gelöscht wird.
* **NVSHAS-8985**: Föderierte Registrierungen verschwinden nach dem Neustart des Controllers.

==== Bekanntes Problem:

* **NVSHAS-9443**: Upgrade/Installation über ArgoCD schlägt fehl, da es das Objekt leases.coordination.k8s.io nicht erstellen kann.
* **Workaround**: Erstellen Sie die angegebenen Lease-Objekte, bevor Sie auf 5.4.0 mit ARGO CD aktualisieren. Ändern Sie den Namespace, wenn er sich von neuvector unterscheidet.
+
--
[,bash]
----
cat <<EOF | kubectl apply -f -
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-controller
  namespace: neuvector
spec:
  leaseTransitions: 0
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-cert-upgrader
  namespace: neuvector
spec:
  leaseTransitions: 0
EOF
----
--

=== 5.3.4 Juli 2024

==== Fehlerbehebungen

* Die `+host+` und `+tunnel+` Schnittstelle werden erfolgreich mit OpenShift CLI v4.15 abgerufen.
* Der IP-Bereich 169.254.x.x ist von den Host-Schnittstellen-IPs ausgeschlossen.
* Überprüfen Sie die Host-Schnittstelle nach 1 Minute nach dem Start des Durchsetzers.
* Ein Problem wurde behoben, bei dem die OpenID-Issuer-URL-Reguläre-Ausdruck fehlgeschlagen ist.
* Behebt folgende CVEs:
+
|===
| CVE | Gilt für | Auswirkung

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.2.4-s5 Juli 2024

* Behebt folgende CVEs:

|===
| CVE | Gilt für | Auswirkung

| CVE-2023-42363
| busybox
| {CVE-medium}

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2023-42366
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4603
| openssl
| {CVE-medium}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.3.3 Juni 2024

==== Verbesserungen

* Erlaubt Benutzern, die Verwendung bestimmter Speicherklassen von der `+Admission Controls+` Seite zu blockieren.
* Die `+LDAP Authentication+` hat separate Felder für `+baseDN+` und `+groupDN+` Konfiguration.
* Die `+Egress and Ingress chart+` hat eine neue Sicherheitsanfälligkeits-Spalte, die die `+High+` und `+Medium+` Sicherheitsanfälligkeitsanzahl für jeden Dienst enthält.

==== Fehlerbehebungen

* Fehler behoben, der mit `+regex+` auftrat, wenn ein Komma (`+,+`) in einem Multi-Eintrag `+Admission Control user criteria+` verwendet wurde.
* Fehler behoben, bei dem der CVE-Scan von `+jar+` Paketen nicht alle von demselben CVE betroffenen Pakete anzeigte. Jetzt werden alle Vorkommen gemeldet.
* Behebt folgende CVEs:

|===
| CVE | Gilt für | Auswirkung

| CVE-2024-35195
| python:requests
| {CVE-medium}

| CVE-2024-21011
| openjdk11
| {CVE-low}

| CVE-2024-21012
| openjdk11
| {CVE-low}

| CVE-2024-21068
| openjdk11
| {CVE-low}

| CVE-2024-21085
| openjdk11
| {CVE-low}

| CVE-2024-21094
| openjdk11
| {CVE-low}
|===

==== Andere

* Erlaubt Benutzern, Ressourcen für `+updater-cron-job+` festzulegen, wenn {product-name} mit dem Helm-Chart installiert wird.
* Prometheus-Exporter-Container-Versionierung überprüft und von der `+controller+` Versionierung dissociiert.
* (Scanner) Erkennen Sie das `+R+` Paket/Modul in Ubuntu und Red Hat Enterprise Linux.
* (Scanner) Unterstützung für den PHP Composer-Scan hinzugefügt.

=== 5.2.4-s3 April 2024

* Behebt folgende CVEs:

|===
| CVE | Gilt für | Auswirkung

| CVE-2021-40633
| giflib
| {CVE-high}

| CVE-2023-48161
| giflib
| {CVE-high}

| CVE-2024-28757
| expat
| {CVE-high}

| CVE-2023-39742
| giflib
| {CVE-medium}

| CVE-2023-45288
| go:golang.org/x/net
| {CVE-medium}

| CVE-2024-25629
| c-ares
| {CVE-medium}

| CVE-2024-3651
| python:idna
| {CVE-medium}

| CVE-2024-2511
| openssl
| {CVE-low}
|===

=== 5.3.2 April 2024

==== Fehlerbehebungen

* Nach dem Upgrade auf v5.3.1 von einer vorherigen {product-name} Version können vorhandene benutzerdefinierte Ressourcen von NvClusterSecurityRule versehentlich gelöscht werden. HINWEIS: Die Version 5.3.1 wurde aus dem Docker Hub entfernt, um das Upgrade-Problem zu verhindern.

=== 5.3.1 April 2024

[IMPORTANT]
====
Die Version 5.3.1 wurde aus dem Docker Hub entfernt, um das Upgrade-Problem zu verhindern, das in 5.3.2 behoben wurde. Bitte verwenden Sie die Version 5.3.2.
====

==== Verbesserungen

* Erlauben Sie Benutzern, &apos;`+accepted+`&apos; Schwachstellen bei der Verwendung von Github-Aktionen zu definieren, damit sie die Workflows nicht beeinträchtigen.
* Fügen Sie Schweregrad-, Punktzahl- und Feed-Bewertungsfilter zu Assets > Registry > Bildschwachstellenansicht hinzu.
* Erlauben Sie bei der Konfiguration eines Registrys, ob der definierte Proxy für die Registrierungsbildscans verwendet werden soll.

==== Fehlerbehebungen

* Sicherheitsrisiken > Schwachstellen > Erweiterter Filter filtert 'CVE ohne Fix' nicht.
* Unerwarteter Verstoß vom Container zum Hostmode-Container
* Akzeptieren Sie das OCI-Bildformat beim Wechsel zu Docker API 1.24
* Registry-Scan sollte keine Nicht-Bild-Artefakte scannen / keinen Fehler protokollieren.
* Ermöglichen Sie die signaturverifizierung von schlüsselpaare ohne internet oder sigstore abhängigkeit.
* Sicherheitsereignisse, die durch netzwerkrichtlinien in einem bestimmten Knoten nicht erlaubt werden (bezogen auf "Container Task chan full" Fehlermeldungen)
* Container kann nicht erfolgreich zur arbeitslast hinzugefügt werden (häufige vorkommen). Resultierend aus einem totenpunkt von kanalnachrichten.

==== Andere

* Aktualisieren Sie die scanner-plugins für Jenkins, GitHub-Aktion und Bamboo.
* (Scanner) Akzeptieren Sie das OCI-Bildformat beim Wechsel zu docker api 1.24.
* (Scanner) Das Registry-Scan sollte keine Nicht-Bild-Artefakte scannen / keinen Fehler protokollieren.
* (Scanner) Unterstützung für php composer scan hinzufügen.

==== {product-name} UI-Erweiterung v. 1.0 für Rancher März 2024

* Nach der installation von {product-name}, xref:rancher.adoc#_suse_security_ui_extension_for_rancher[aktivieren/installieren] wird die {product-name} UI-Erweiterung von Rancher ein Dashboard für den Cluster anzeigen, einschließlich Links zu SSO zum vollständigen {product-name} Cluster. HINWEIS: Die Erweiterung kann als Drittanbieter angezeigt werden, was in einer zukünftigen Version behoben wird. Außerdem können Rancher 2.7.x-Benutzer nach der installation zwei {product-name} UI Ext-Icons in der Liste sehen (Fehler). Ein Icon wird Deinstallieren sagen (was bedeutet, dass es installiert ist), und das andere sollte Installieren sagen. Dies kann so belassen werden, d.h. nicht erneut installieren, wenn die Erweiterung bereits installiert ist.

=== 5.2.4-s2 Februar 2024

* Behebt folgende CVEs:
* Hohe cve: CVE-2023-52425 in expat, CVE-2024-20952 und CVE-2024-20918 in openjdk11
* Mittlere cve: CVE-2023-52426 in expat, CVE-2024-20926, CVE-2024-20921, CVE-2024-20945 und CVE-2024-20919 in openjdk11, CVE-2024-0727 und CVE-2023-6237 in openssl

=== 5.3.0 Februar 2024

==== Verbesserungen

* Externe Ziel-URLs (FQDN) im Dashboard (Egress), PDF- und CSV-Berichten sowie im Netzwerkaktivitätsbildschirm und in den Sicherheitsereignislisten (Verstöße) anzeigen
* Im Entdeckungsmodus lernen, Egresses zu externen FQDN-Adressgruppen automatisch. Eine neue benutzerdefinierte Gruppe für externe FQDN wird erstellt, es sei denn, die externe Verbindung entspricht einer bestehenden Regel.
* Aktivieren Sie das ICMP-Lernen (Entdeckungsmodus) und die Blockierung (Schutzmodus) über die neue Controller-Umgebungsvariable CTRL_EN_ICMP_POLICY = 1
* Exportieren Sie CRDs in Github, um gitops in ein Standard-Repo über die Konsole oder die REST-API zu unterstützen.
* Unterstützung für SAML SSO-Einzelabmeldung mit ADFS iDP
* Unterstützung für die ARM64-Plattform hinzufügen. Das Abrufen von ARM-basierten Plattformen zieht automatisch die entsprechenden ARM64 {product-name} Bilder.
* Unterstützung von Webhooks über einen Proxy
* Verbessern Sie die Funktion zur Überprüfung der Zulassungskontrolle, um die Ergebnisse aller Regeln einzuschließen. Listen Sie das Ergebnis jeder Regel auf und fügen Sie einen weiteren Eintrag für die endgültige Aktion hinzu, die bei der Auswertung in einer Live-Zulassungskontrollbereitstellung auftreten würde.
* Deaktivierte Zulassungskontrollregeln über CRD oder yaml (kubectl) anwenden
* Export / Import von Schwachstellenprofilen über die Konsole, CRD oder REST-API. Das Importieren ersetzt das vorhandene Profil. Das Löschen der CRD führt zu einem leeren Profil.
* Export / Import von Compliance-Profilvorlagen über die Konsole, CRD oder REST-API. Das Importieren ersetzt die vorhandene Vorlage.
* Fügen Sie einen 'Manuellen' Status in den Compliance-Berichten für CIS-Benchmarks hinzu, die manuell von Benutzern ausgeführt werden müssen (nicht ausgeführt von {product-name}).
* Verbessern Sie das Laden/ die Leistung der Benutzeroberfläche der Schwachstellenseite
* Browser-Sitzungsanmeldung vereinheitlichen. Damit teilen sich alle Tabs im Browser dieselbe Anmeldesitzung, das Öffnen eines neuen Tabs aus einer bestehenden Sitzung erfordert keine Anmeldeinformationen, und wenn sich ein Tab abmeldet, werden alle Tabs abgemeldet.
* Verbesserungen der Sicherheit der Konsole (UI): 1) Fügen Sie obligatorische Sicherheitsheader hinzu (X-Content-Type-Options nosniff; X-XSS-Protection 1; mode=block; X-Frame-Options SAMEORIGIN; Cache-Control private, no-cache, no-store, must-revalidate
HTTP Strict Transport Security max-age=15724800, 2) Fügen Sie den CSP-Header hinzu (z. B. setzen Sie eine &apos;`+default-src+`&apos; Direktive), 3) Entfernen Sie die Offenlegung des Servernamens.
* Unterstützung neuerer Versionen der CIS-Benchmarks. Kubernetes (1.8.0), Kubernetes V1.24 (1.0.0), Kubernetes V1.23 (1.0.1), RedHat OpenShift Container Platform (1.4.0)
* Zeigen Sie in Assets -> Containern -> Containerdetails an, die in Registrierungen im Vergleich zur Laufzeit gescannt wurden.
* Fügen Sie einen Link zur Gruppe in Sicherheitsrisiken -> Schwachstellen -> Auswirkungen Popup hinzu, um den Gruppenmodus einfach zu bearbeiten.
* Unterstützung von Deep Linking in URLs zur Bild- und/oder Container-Schwachstellenseite.
* Fügen Sie die Option zum Zurücksetzen des Passworts für den Administrator hinzu, um das Benutzerpasswort in den Konsoleneinstellungen -> Benutzer zurückzusetzen.
* Erlauben Sie das Senden von Ereignisprotokollen an die Protokolle des Controller-Pods in den Einstellungen -> Konfiguration -> Benachrichtigung. Die gesendeten Ereignisse beginnen mit 'notification=' und werden nur im führenden Controller-Pod gespeichert. Beachten Sie, dass es in dieser Version einen Fehler gibt, bei dem zur Änderung des Ereignisniveaus SYSLOG aktiviert sein muss (und nach der Änderung des Niveaus deaktiviert werden kann, wenn gewünscht).
* Entfernen Sie die Anforderung, dass der Controller/Enforcer "/host/cgroup" einhängt.
* Fügen Sie das Menü 'Support erhalten' mit Links zu Slack, Dokumentation und anderen Ressourcen hinzu.
* Füllen Sie das Nachrichtenfeld zu /v1/log/activity logs aus.

==== Fehlerbehebungen

* Interner Serverfehler in Sicherheitsrisiken -> Schwachstellen mit einer hohen Anzahl von CVEs.
* SIGSEGV: Segmentierungsverletzung im Controller.
* Das Löschen anfälliger Dateien (z. B. jar) entfernt sie nicht aus der Schwachstellenliste.
* Ungültiges Syslog-Zertifikat mit dem Signaturalgorithmus SHA256withECDSA.
* {product-name} zeigt Sicherheitsereignisse, die durch eine Netzwerkregel erlaubt sein sollten
* Unverwalteter Knoten mit "Zombie"-Durchsetzer läuft
* Erweiterter Filter zeigt die Felder Behebung und Auswirkungen leer an
* Behandeln von Zeichenfolgen anpassen, um unerwartete Neustarts des Durchsetzers zu verhindern
* Unerwartete Verstöße in Bezug auf integrierte Gruppen
* Support-Bundle-Durchsetzer-Debug-RPC-Aufruf für Daten gibt Fehler zurück
* Gruppe stimmt nicht mit Sicherheitsereignissen überein
* Ereignisse an Slack senden funktioniert nicht - mit Proxy
* Zeigt Sicherheitsereignisse für erlaubte Netzwerkregeln an

==== Andere

* Fügen Sie die automatische Erkennung der Laufzeit-Container-Engine (Socket) zum Helm-Diagramm hinzu
* Entfernen Sie die Einstellung für den Betrieb des Controllers im privilegierten Modus im Helm-Diagramm und die Anforderung, dass der Controller/Durchsetzer "/host/cgroup" einhängt.
* Die Beispiel-Kubernetes-Bereitstellungsdateien wurden aus den {product-name}-Dokumenten entfernt. Bitte beziehen Sie sich auf den Link für Beispiele.

==== Hervorgehobene Änderungen, die möglicherweise Änderungen für manuelle Bereitstellungen erfordern (alle Änderungen sind bereits im neuesten Helm-Diagramm für 5.3.x enthalten)

* Die automatische Erkennung der Containerlaufzeit (Socket) beseitigt die Notwendigkeit, die Containerlaufzeit und den Socket-Pfad anzugeben.
* Die Entfernung der Anforderung, den Controller im privilegierten Modus auszuführen, beseitigt die Notwendigkeit, den Laufzeitsocket und /host/cgroup/ einzuhängen.
* Rolle/Rollenbindung für neuvector-binding-secret sowie neuvector-secret in yaml hinzugefügt.
* Neue Dienstkonten und Rollenbindungen erforderlich für 5.3
* Alle referenzierten Bereitstellungs-yaml-Dateien haben jetzt /5.3.0/ in ihren Pfaden

=== 5.2.4-s1 Januar 2024

==== Sicherheits-Patch-Veröffentlichung

* Behebt CVE-2023-6129 in openssl und CVE-2023-46219, CVE-2023-46218 in curl.

=== 5.2.4 November 2023

==== Fehlerbehebungen

* Änderungen an Azure AKS ValidatingWebhookConfiguration und Fehlerprotokollierung.

=== 5.2.3 November 2023

==== Verbesserungen

* Unterstützung für NVD API 2.0 im Scanner hinzufügen.
* Scannen des Container-Hosts im Standalone-Modus des Scanners.

[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n
----

==== Fehlerbehebungen

* Scan auf einem Knoten schlägt aufgrund eines blockierten docker cp / grpc-Problems fehl.

=== 5.2.2-s1 Oktober 2023

==== Sicherheitsupdate

* Pakete aktualisieren, um CVEs zu beheben, einschließlich Hoch CVE-2023-38545 und CVE-2023-43804.

=== 5.2.2 Oktober 2023

==== Sicherheitsberatung für CVE-2023-32188

* Beheben von CVE-2023-32188 &quot;`+JWT token compromise can allow malicious actions including Remote Code Execution (RCE)+`&quot; durch automatische Generierung des Zertifikats, das zum Signieren des JWT-Tokens bei Bereitstellung und Upgrade verwendet wird, sowie automatische Generierung des Manager/RESTful API-Zertifikats während der Helm-basierten Bereitstellungen.
 ** Zertifikat für JWT-Signierung wird automatisch vom Controller mit einer Gültigkeit von 90 Tagen erstellt und automatisch rotiert.
 ** Die automatische Generierung des Manager-, REST-API- und Registry-Adapterzertifikats erfordert die Verwendung einer Helm-basierten Installation mit {product-name} Helm-Version 2.6.3 oder höher.
 ** Das integrierte Zertifikat wird weiterhin für yaml-basierte Bereitstellungen verwendet, wenn es während der Bereitstellung nicht ersetzt wird; es wird jedoch empfohlen, diese zu ersetzen (siehe nächste Zeile).
 ** Manuelle xref:replacecert.adoc[Ersetzung des Zertifikats] wird weiterhin unterstützt und für frühere Versionen oder yaml-basierte Bereitstellungen empfohlen. Siehe die {product-name} GitHub-Sicherheitsberatung https://github.com/neuvector/neuvector/security/advisories/GHSA-622h-h2p8-743x[hier] für eine Beschreibung.
 ** Die Verwendung von benutzerdefinierten Zertifikaten wird wie zuvor sowohl für Helm- als auch für yaml-basierte Bereitstellungen weiterhin unterstützt.
* Fügen Sie zusätzliche Steuerungen für benutzerdefinierte Compliance-Skripte hinzu. Standardmäßig dürfen benutzerdefinierte Skripte jetzt nicht hinzugefügt werden, es sei denn, die Umgebungsvariable CUSTOM_CHECK_CONTROL wird zu Controller und Enforcer hinzugefügt. Die Werte sind "deaktivieren" (Standard, nicht erlaubt), "streng" (nur Admin-Rolle) oder "locker" (Admin-, Compliance- und Runtime-Policy-Rollen).
* Verhindern Sie LDAP-Injection - das Benutzernamenfeld wird escaped.

==== Verbesserungen

* Fügen Sie zusätzliche Scandaten zu den von SYSLOG für geschichtete Scans gesendeten CVE-Ergebnissen hinzu.
* Unterstützung für NVD API 2.0 für Scans der CVE-Datenbank.
* Geben Sie das Erstellungsdatum des Container-Images in den Assets -> Containerdetails an.
* Passen Sie die Sortierung für Netzwerkregeln an: Deaktivieren Sie die Sortierung in der Ansicht der Netzwerkregeln, aktivieren Sie jedoch die Sortierung der Netzwerkregeln in der Gruppenansicht.
* Aktivieren/deaktivieren Sie die Erkennung/Alarmierung von TLS 1.0 und TLS 1.1 mit Umgebungsvariablen für Enforcer THRT_SSL_TLS_1DOT0, THRT_SSL_TLS_1DOT1. Standardmäßig deaktiviert.
* Fügen Sie die Umgebungsvariable AUTO_PROFILE_COLLECT für Controller und Enforcer hinzu, um bei der Erfassung des Speicherverbrauchs bei der Untersuchung von Speicherbelastungsereignissen zu helfen. Setzen Sie den Wert = 1, um zu aktivieren.
* Konfigurationsbewertungen gegen Admission Control sollten alle Verstöße mit einem Scan anzeigen.
* Fügen Sie weitere Optionen für die CVE-Berichtskriterien in den Reaktionsregeln hinzu. Beispiel 1 - "cve-high-with-fix:X" bedeutet: Wenn die Anzahl der (hochgefährlichen Schwachstellen, die behoben wurden) >= X, lösen Sie die Reaktionsregel aus. Beispiel 2 - "cve-high-with-fix:X/Y" bedeutet: Wenn die Anzahl der (hochgefährlichen Schwachstellen, die vor Y Tagen gemeldet wurden und behoben wurden) >= X, lösen Sie die Reaktionsregel aus.

==== Fehlerbehebungen

* Der Export der Gruppenrichtlinie gibt keinen tatsächlichen YAML-Inhalt zurück.
* Verbessern Sie das Beschneiden von Namespaces mit einer speziellen Funktion.
* {product-name} Namespace-Benutzer können keine Assets sehen-->Namespaces
* Überspringen Sie die Verarbeitung der CRD CREATE/UPDATE-Anfragen, wenn der Namespace des CR bereits gelöscht ist
* Bieten Sie einen Workaround für einen Teil der CRD-Gruppen, die nach dem Löschen von Namespaces nicht erfolgreich beschnitten werden können.

=== 5.2.1 August 2023

==== Verbesserungen

* Berichten Sie über geschichtete Scanergebnisse und zusätzliche CVE-Daten in SYSLOG-Nachrichten. Dies wird über ein Kontrollkästchen in den Einstellungen -> Konfiguration -> SYSLOG aktiviert
* Exportieren Sie NIST 800-53-Zuordnungen (zu Docker CIS-Benchmarks) im exportierten CSV-Compliance-Bericht
* Unterstützen Sie die Proxy-Einstellung bei der Überprüfung von Bildsignaturen
* Fügen Sie das Ergebnis des Bildsignatur-Scans im heruntergeladenen CVE-Bericht hinzu
* Unterstützen Sie Pod-Anmerkungen für Zulassungskontrollrichtlinien, die über die benutzerdefinierten Kriterien verfügbar sind
* Fügen Sie das Feld "Zuletzt geändert" hinzu, um nach Schwachstellenberichten zu filtern, sowie einen erweiterten Filter in der Schwachstellenansicht

==== Fehlerbehebungen

* Erstellen Sie keinen Standard-Admin mit dem Standardpasswort in der initialen {product-name} Bereitstellung für das AWS-Abrechnungsangebot (CSP-Adapter), wodurch der Benutzer gezwungen wird, ein Geheimnis zu verwenden, um den Admin-Benutzernamen und das Passwort zu erstellen
* Beheben Sie die .json-Datei, die die Größe erhöht hat und einen Kubernetes-Knoten zum Absturz brachte
* Verbessern Sie die Logik zur Erkennung von SQL-Injection
* Wenn das Helm-CRD-Diagramm zuerst installiert wird, bevor das {product-name} Core-Diagramm installiert wird, fehlen Dienstkonten
* Das Compliance-Ergebnis des Bildscans I.4.1 ist falsch
* Der erweiterte Schwachstellenfilterbericht zeigt Bilder aus allen anderen Namespaces an

=== 5.2.0 Juli 2023

==== Verbesserungen

* Unterstützen Sie Tokens für den {product-name} API-Zugriff. Siehe Einstellungen -> Benutzer, API-Schlüssel..., um einen neuen API-Schlüssel zu erstellen. Schlüssel können auf Standard- oder benutzerdefinierte Rollen gesetzt werden.
* Unterstützung für AWS Marketplace PAYG-Abrechnung für {product-name} monatliche Support-Abonnements. Benutzer können sich für {product-name} durch SUSE-Support anmelden, der monatlich auf ihr AWS-Konto basierend auf dem durchschnittlichen Knotenverbrauch des vorherigen Monats abgerechnet wird. Details https://open-docs.neuvector.com/deploying/awsmarketplace[hier].
* Unterstützung für die Signierung von Bildern für Zulassungssteuerungen. Benutzer können {product-name} verlangen, um zu überprüfen, dass Bilder von bestimmten Parteien signiert sind, bevor sie in die Produktionsumgebung bereitgestellt werden, durch eine Integration mit Sigstore/Cosign. Siehe Assets -> Sigstore-Überprüfer zur Erstellung neuer Signatur-Assets. Regeln können dann mit den Kriterien Bildsignierung und/oder Bild-Sigstore-Überprüfer erstellt werden.
* Aktivieren Sie, dass jede Zulassungssteuerungsregel ihren eigenen Modus von Überwachen oder Schützen hat. Eine Verweigerungsaktion im Überwachungsmodus wird alarmieren, und eine Verweigerungsaktion im Schutzmodus wird blockieren. Erlaubte Aktionen sind nicht betroffen.
* Fügen Sie einen neuen Regex-Operator in Richtlinie > Zulassungssteuerung > Regel hinzufügen für Benutzer und Benutzergruppen hinzu, um Regex zu unterstützen. Unterstützen Sie die Operatoren "entspricht JEDER Regex in" und "entspricht KEINER Regex in".
* Fügen Sie Unterstützung für Zulassungssteuerungskriterien wie Ressourcenlimits hinzu. Ein neues Kriterium wird für Ressourcenlimits hinzugefügt, und zusätzliche Kriterien werden über die Einstellungen für benutzerdefinierte Kriterien unterstützt.
* Unterstützung für das Aufrufen des {product-name} Scanners von Harbor-Registrierungen über die https://github.com/goharbor/pluggable-scanner-spec[pluggable scanner] Schnittstelle. Dies erfordert die Konfiguration der Verbindung zum Controller (exponierte API). Der Harbor-Adapter ruft den Controller-Endpunkt auf, um einen Scan auszulösen, der automatisch beim Pushen scannen kann. Interrogationsdienste können für regelmäßige Scans verwendet werden. Scanergebnisse von den primären Controllern der Föderation werden an entfernte Cluster propagiert.  HINWEIS: Es gibt ein Problem mit dem HTTPS-basierten Adapterendpunktfehler: Bitte ignorieren Sie den Testverbindungsfehler, es funktioniert, auch wenn ein Fehler angezeigt wird (Zertifikatsvalidierung überspringen).
* Durchsuchbarer SaaS-Dienst für CVE-Abfragen. Durchsuchen Sie die neueste {product-name} CVE-Datenbank, um zu sehen, ob ein bestimmter CVE in der Datenbank vorhanden ist. Dieser Dienst ist für {product-name} Prime (kostenpflichtiges Support-Abonnement) Kunden verfügbar. Kontaktieren Sie den Support über Ihr SCC-Portal für den Zugriff.
* Erlauben Sie dem Benutzer, den Netzwerkschutz zu deaktivieren, aber WAF/DLP funktionsfähig zu halten. Konfigurieren Sie die Aktivierung der Netzwerkpolitik in den Einstellungen -> Konfiguration.
* Verwenden Sie weniger privilegierte Dienstkonten, wie für jede {product-name} Komponente erforderlich. Eine Variable &quot;`+leastPrivilege+`&quot; wird eingeführt. Der Standardwert ist falsch. HINWEIS: Die Verwendung des aktuellen Helm-Diagramms mit dieser Variablen bei einer Version vor 5.2.0 funktioniert nicht richtig.
* Binden Sie an ein nicht standardmäßiges Dienstkonto, um die CIS 1.5 5.1.5-Empfehlung zu erfüllen.
* Ermöglichen Sie dem Administrator, die standardmäßige Sitzungszeitüberschreitung für Benutzer in den Einstellungen -> Benutzer, API-Schlüssel und Rollen zu konfigurieren.
* Anpassbares Anmeldebanner und anpassbarer UI-Headertext für regulierte und staatliche Bereitstellungen. Die Anforderungen für die Konfiguration finden Sie xref:customui.adoc[hier].
* SYSLOG-Unterstützung für TLS-verschlüsselten Transport. Wählen Sie TCP/TLS in den Einstellungen -> Konfiguration für SYSLOG.
* Aktivieren Sie die Bereitstellung des {product-name} Monitor-Helfer-Diagramms von Rancher Manager.
* Entfernen Sie die obere Grenze für die oberste Domain im URL-Validator für die Registrierungsscans.
* Scannen Sie Golang-Abhängigkeiten, einschließlich Laufzeitscans.
* Unterstützung für den Schwachstellenscan von Debian 12 (Bookworm).
* CSV-Export für Registry / Details hinzufügen, um CVEs für alle Bilder im konfigurierten Registry in Assets -> Registries für eine ausgewählte Registry zu exportieren.
* Erlauben Sie {product-name}, mehrere ADFS-Zertifikate parallel im x.509-Zertifikatfeld festzulegen.
* Fügen Sie das Kommentarfeld für Antwortregeln hinzu und zeigen Sie es an.
* Geben Sie an, was {product-name} als Systemcontainer über die Umgebungsvariable betrachtet. Zum Beispiel für Rancher und Standard-Namensräume: NV_SYSTEM_GROUPS=*cattle-system;default
* Unterstützung für Kubernetes 1.27 und OpenShift 4.12 hinzufügen.

==== Fehlerbehebungen

* Wiederholende Protokolle in den Protokollen des Durchsetzungs-/Steuerungssystems reduzieren.
* Die Seite mit mehreren Clustern wird nicht gerendert.
* Die automatische Entfernung leerer Gruppen dauert 2 Stunden zum Löschen anstelle von 1 Stunde gemäß Zeitplan.
* Manuell erlaubte Netzwerkregel wird nicht angewendet und führt zu einer Verletzung für das Pause-Image.
* SSL-Verbindungen blockieren, auch wenn eine Netzwerkregel den Datenverkehr unter bestimmten Anfangsbedingungen erlaubt.
* Sicherheitsereignisse warnen, selbst bei erlaubten Netzwerkregeln aufgrund eines Problems mit der Richtlinienaktualisierung in der Synchronisierung.
* Netzwerkaktivitäten, die den Datenverkehr benutzerdefinierter Gruppen fälschlicherweise extern zuordnen.
* Das Standarddienstkontotoken des Namensraums, das in jedem Pod gemountet ist, hat zu hohe Berechtigungen.
* Trotz der Definition der Netzwerkregeln werden Verstöße in Sicherheitsereignissen protokolliert (falsche Positiven), wenn der Container aufgrund eines Speichermangels (OOM) gestoppt wurde.
* Erlauben Sie dem Benutzer, die Erkennung und den Schutz gegen nicht verwaltete Container im Cluster zu deaktivieren/aktivieren. Dies kann über die Manager-CLI festgelegt werden:

[,shell]
----
set system detect_unmanaged_wl status -h
Usage: cli set system detect_unmanaged_wl status [OPTIONS] {true|false}

  Enable/disable detect unmanaged container
----

==== Andere

* Fügen Sie die Einstellung "leastPrivilege" im Helm-Diagramm hinzu. Fügen Sie die Helm-Option für New_Service_Profile_Baseline hinzu. Eine neue Helm-Chart (Kern) Version wird für 5.2 veröffentlicht.
* Aktivieren Sie die Integrationsoptionen für den AWS Marketplace (Abrechnungsadapter) im Helm-Chart.
* Aktualisieren Sie das ConfigMap, um neue Funktionen zu unterstützen (mehrere ADFS-Zertifikate, null Drift, New_Service_Profile_Baseline, SYSLOG TLS, Benutzer-Timeout)
* Aktualisieren Sie die unterstützten Kubernetes-Versionen auf 1.19+ und OpenShift 4.6+ (1.19+ mit CRI-O)

=== 5.1.3 Mai 2023

==== Verbesserungen

* Fügen Sie einen neuen Schwachstellen-Feed zum Scannen des Microsoft .NET-Frameworks hinzu.
* Enforcer-Statistiken sind standardmäßig im Prometheus-Exporter deaktiviert, um die Skalierbarkeit zu verbessern.
* Usability-Verbesserung: Verwenden Sie den Scanner, um ein einzelnes Bild zu scannen und das Ergebnis auszudrucken (siehe Beispiel unten).
* Fügen Sie die Überprüfung der imagePullPolicy in die Kriterien der Zulassungssteuerungsregeln ein.
* Zeigen Sie eine Warnmeldung an, wenn das CRD-Schema veraltet ist.

==== Fehlerbehebungen

* Der Bildschirm für Netzwerkaktivitäten wird nicht gerendert oder wird falsch gerendert.
* Die automatische Entfernung leerer Gruppen dauert 2 Stunden zum Löschen anstelle von 1 Stunde gemäß Zeitplan.
* Das Compliance-Profil wird nicht in der UI-Konsole angezeigt.
* Erweiterter Filter in Sicherheitsereignissen fehlt "Fehler"-Level.
* Gespeichertes Passwort mit Sonderzeichen schlägt bei zukünftigen Authentifizierungsversuchen fehl.
* Die Seite mit mehreren Clustern wird nicht richtig gerendert, wenn die Anfragen hoch sind.
* Das Detailfeld (unten) des Registrierungsbereichs wird nicht aktualisiert.

==== Scanner-Beispielausgabe

[,shell]
----
Image: https://registry.hub.docker.comlibrary/alpine:3.4
Base OS: alpine:3.4.6
TOTAL: 6, HIGH: 1, MEDIUM: 5, LOW: 0, UNKNOWN: 0
┌─────────┬───────────────┬──────────┬───────────┬───────────────┬────────────┐
│ PACKAGE │ VULNERABILITY │ SEVERITY │ VERSION   │ FIXED VERSION │ PUBLISHED  │
├─────────┼───────────────┼──────────┼───────────┼───────────────┼────────────┤
│ openssl │ CVE-2018-0732 │ High     │ 1.0.2n-r0 │ 1.0.2o-r1     │ 2018-06-12 │
│         ├───────────────┼──────────┤           ├───────────────┼────────────┤
│         │ CVE-2018-0733 │ Medium   │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0734 │          │           │ 1.0.2q-r0     │ 2018-10-30 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0737 │          │           │ 1.0.2o-r2     │ 2018-04-16 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0739 │          │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-5407 │          │           │ 1.0.2q-r0     │ 2018-11-15 │
└─────────┴───────────────┴──────────┴───────────┴───────────────┴────────────┘
----

=== 5.1.2 März 2023

==== Verbesserungen

* Unterstützung für virtualisierte hostbasierte Adressgruppen und Richtlinien zur Übereinstimmung von Netzwerkschutzmaßnahmen. Dies ermöglicht einen Anwendungsfall, bei dem zwei verschiedene FQDN-Adressen auf dieselbe IP-Adresse aufgelöst werden, aber unterschiedliche Regeln für jede FQDN durchgesetzt werden sollten. Eine neue benutzerdefinierte Gruppe mit &apos;`+address=vh:xxx.yyy+`&apos; kann unter Verwendung des &apos;`+vh:+`&apos; Indikators erstellt werden, um diesen Schutz zu aktivieren. Eine Netzwerkregel kann dann die benutzerdefinierte Gruppe als &apos;`+From+`&apos; Quelle basierend auf dem virtuellen Hostnamen (anstatt der aufgelösten IP-Adresse) verwenden, um unterschiedliche Regeln für virtuelle Hosts durchzusetzen.
* Compliance-Containerliste zum Ausschließen beendeter Container.
* Verbesserung der DLP-Regeln zur Unterstützung einfacher Wildcards im Muster.
* Unterstützung für cri-o 1.26+ und OpenShift 4.11+ hinzufügen.
* Gravatar optional machen.
* Cluster-Namespace-Ressource in Konsole / UI anzeigen.
* Quellschweregrad/Klassifizierung (z.B. Red Hat, Ubuntu...) zusammen mit dem NVD-Schweregradwert in der Konsole anzeigen.
* SSO/RBAC-Deaktivierung für Rancher und OpenShift nicht zulassen, wenn der Benutzer über SSO authentifiziert ist.
* Aktivierung der automatischen Überprüfung und Löschung von nicht verwendeten Gruppenalter zu configMap hinzufügen.
* IP-Adresse für externe Quelle/Ziel in csv/pdf für implizite Verstoßverletzungen einbeziehen.
* Verschiedene Leistungs- und Skalierbarkeitsoptimierungen für CPU- und Speicherverbrauch von Controller und Durchsetzer.

==== Fehlerbehebungen

* Anwendungs-Verlangsamung auf GKE Container Optimized OS (COS) Knoten im Schutzmodus beheben.
* SUSE Linux (SLES) 15.4 CVE stimmt nicht im Scanner überein. Mit diesem Fix wird, wenn die Schwere in dem Feed angegeben ist, die Schwachstelle zur Datenbank hinzugefügt, auch wenn der NVD-Eintrag fehlt. Es ist möglich, dass der Bericht Schwachstellen ohne CVE-Werte enthält.

==== Andere

* Verbesserung der Optionen für Admission Control CRD in helm https://github.com/neuvector/neuvector-helm/pull/237.
* Neue Durchsetzer-Umgebungsvariablen zum Helm-Chart hinzufügen.

=== 5.1.1 Februar 2023

==== Verbesserungen

* Fügen Sie &quot;`+package+`&quot; als Informationen zum Syslog-Ereignis für eine erkannte Schwachstelle hinzu.
* Fügen Sie die Enforcer-Umgebungsvariable ENF_NETPOLICY_PULL_INTERVAL hinzu - Wert in Sekunden (empfohlener Wert 60), um den Netzwerkverkehr und den resultierenden Ressourcenverbrauch durch den Enforcer aufgrund von Richtlinienaktualisierungen/-neuberechnungen zu reduzieren. (Hinweis: Dies war bis August 2023 eine nicht dokumentierte Ergänzung).

[,yaml]
----
           - name: ENF_NETPOLICY_PULL_INTERVAL
             value: "60"   <== regulate the pulling gap by 60 seconds
----

==== Fehlerbehebungen

* Fehler beim Löschen leerer Gruppen "Objekt nicht gefunden"
* Verkehr innerhalb desselben Containers alarmieren/blockieren
* Unerwartete implizite Verstöße für Istio Egress-Verkehr mit vorhandener Erlauben-Regel
* Beim Upgrade von {product-name} 4.x-Version verursacht eine falsche Pod-Gruppenmitgliedschaft unerwartete Richtlinienverletzungen
* OIDC-Authentifizierung fehlgeschlagen mit ADFS, wenn zusätzliche Kodierungszeichen in der Anfrage erscheinen
* Hoher Speicherverbrauch durch dp, das Pods erstellt und löscht
* Aktualisieren Sie Alpine, um mehrere CVEs, einschließlich Manager, zu beheben: CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552
* Verschiedene UI-Fehler behoben

==== Andere

* Helm-Chart aktualisiert, um den Austausch des Zertifikats für interne Kommunikation zu ermöglichen

=== 5.1.0 Dezember 2022

==== Verbesserungen

* Zentralisierte, Multi-Cluster-Scanning (CVE) Datenbank. Der primäre (Master-)Cluster kann ein als föderiertes Registry bezeichnetes Registry/Repo scannen. Die Scanergebnisse aus diesen Registrierungen werden mit allen verwalteten (remote) Clustern synchronisiert. Dies ermöglicht die Anzeige der Scanergebnisse in der Konsole des verwalteten Clusters sowie die Verwendung der Ergebnisse in den Zulassungssteuerungsregeln des verwalteten Clusters. Registrierungen müssen nur einmal gescannt werden, anstatt von jedem Cluster, wodurch CPU-/Speicher- und Netzwerkbandbreitennutzung reduziert wird.
* Verbessern Sie die Zulassungssteuerungsregeln:
 ** Benutzerdefinierte Kriterien für Zulassungssteuerungsregeln. Erlauben Sie Benutzern, Ressourcen-Kriterien für alle podbezogenen Felder zu definieren und in Regeln zu verwenden, z. B. item.metadata.annotationsKey enthält 'neuvector', item.metadata.name='xyzzy' usw.
 ** Fügen Sie Kriterien hinzu, um hochriskante RBAC-Einstellungen für Dienstkonten beim Bereitstellen von Pods zu überprüfen. Diese umfassen Kriterien 'jede Aktion von Arbeitslastressourcen', 'jede Aktion auf RBAC', 'Arbeitslastressourcen erstellen', 'Geheimnisse auflisten' und 'in einen Container ausführen'.
 ** Fügen Sie einen semantischen Versionsvergleich zu Modulen für Zulassungssteuerungsregeln hinzu. Dies ermöglicht die Anwendung von > oder < Operatoren auf Versionsnummern in Regeln (z. B. nicht zulassen, dass das Modul curl<6.2.0 bereitgestellt wird). Dies ermöglicht spezifische Versionsprüfungen für installierte Pakete.
 ** Fügen Sie eine Zulassungssteuerungsregel für die Pod-Sicherheitszulassung (PSA) hinzu, die in Kubernetes 1.25+ unterstützt wird.
* Fügen Sie eine neue Umgebungsvariable NO_DEFAULT_ADMIN hinzu, die, wenn aktiviert, keinen 'admin'-Benutzer erstellt. Dies wird standardmäßig für die Rancher SSO-Integration verwendet. Wenn nicht aktiviert, warnen Sie den Benutzer dauerhaft und protokollieren Sie Ereignisse, um das Standard-Admin-Passwort zu ändern, wenn es nicht vom Standard geändert wird.
* Das Blockieren des Logins nach fehlgeschlagenen Anmeldeversuchen wird nun zur Standardoption. Der Standardwert beträgt 5 Versuche und kann in den Einstellungen -> Benutzer & Rollen-> Passwortprofil konfiguriert werden.
* Fügen Sie eine neue Umgebungsvariable zur Leistungsoptimierung ENF_NO_SYSTEM_PROFILES hinzu, Wert: "1". Wenn aktiviert, werden die Prozess- und Dateimonitoren deaktiviert. Keine Lernprozesse, keine Profilmodi, keine Prozess-/Dateivorfälle (Paket) und kein Dateiaktivitätsmonitor werden durchgeführt. Dies wird die CPU-/Speicherressourcennutzung und Dateioperationen reduzieren.
* Fügen Sie eine benutzerdefinierte Auto-Scaling-Einstellung für Scanner-Pods hinzu, mit den Werten Verzögert, Sofort und Deaktiviert. Wichtig: Das Auto-Scaling von Scannern wird nicht unterstützt, wenn der Scanner mit einem OpenShift-Operator bereitgestellt wird, da der Operator die Anzahl der Pods immer auf den konfigurierten Wert ändert.
 ** *_Verzögerte Strategie:_*
  *** Wenn der Hauptcontroller kontinuierlich "Aufgabenanzahl" > 0 für > 90 Sekunden sieht, wird ein neuer Scanner-Pod gestartet, wenn maxScannerPods noch nicht erreicht ist.
  *** Wenn der Hauptcontroller kontinuierlich sieht, dass die "Aufgabenanzahl" 0 für > 180 Sekunden beträgt, wird ein Scanner-Pod heruntergefahren, wenn minScannerPods noch nicht erreicht ist.
 ** *_Sofortige Strategie:_*
  *** Jedes Mal, wenn der Hauptcontroller sieht, dass die "Aufgabenanzahl" > 0 ist, wird ein neuer Scanner-Pod gestartet, wenn maxScannerPods noch nicht erreicht ist.
  *** Wenn der Hauptcontroller kontinuierlich sieht, dass die "Aufgabenanzahl" 0 für > 180 Sekunden beträgt, wird ein Scanner-Pod heruntergefahren, wenn minScannerPods noch nicht erreicht ist.
* Benutzerdefinierte Gruppen können jetzt Namensraum-Labels verwenden, einschließlich der Namensraum-Labels von Rancher. Im Allgemeinen können jetzt Pod- und Namensraum-Labels zu benutzerdefinierten Gruppen hinzugefügt werden.
* Fügen Sie die Möglichkeit hinzu, ausgewählte Namensräume und Gruppen in der Netzwerkaktivitätsansicht auszublenden.
* Vollständige Unterstützung für Cilium cni.
* Vollständige Unterstützung für OpenShift 4.9 und 4.10.
* Build-Tools sind jetzt für das {product-name}/Open Zero Trust (OZT)-Projekt unter https://github.com/openzerotrust/openzerotrust.io. verfügbar.
* {product-name} listet jetzt die Versions-ID und den SHA256-Hash für jede Version des Controllers, Managers, Durchsetzers unter https://github.com/neuvector/manifests/tree/main/versions. auf.
* Anonyme Telemetriedaten (Anzahl der Knoten, Gruppen, Regeln) werden jetzt bei der Bereitstellung an einen Rancher-Cloud-Dienst gemeldet, um dem Projektteam zu helfen, das Nutzungsverhalten zu verstehen. Dies kann in der Benutzeroberfläche oder mit configMap (No_Telemetry_Report) oder REST-API deaktiviert werden (Opt-out).
* (Nachtrag Januar 2023). Unterstützung für netzwerkbasierte Richtlinien mit ServiceEntry und Istio. Die Durchsetzung von Egress-Netzwerkrichtlinien wurde in Version 5.1.0 für Pods zu ServiceEntry-Zielen, die mit Istio deklariert sind, hinzugefügt. Typischerweise definiert ein ServiceEntry, wie ein externes Dienst, das über den DNS-Namen angesprochen wird, zu einer Ziel-IP aufgelöst wird. Vor v5.1 konnte {product-name} keine Regeln für Verbindungen zu einem ServiceEntry erkennen und durchsetzen, sodass alle Verbindungen als extern klassifiziert wurden. Mit 5.1 können Regeln für spezifische ServiceEntry-Ziele durchgesetzt werden. WICHTIG: Wenn Sie auf v5.1 mit einer auf Istio basierenden Bereitstellung aktualisieren, müssen neue Regeln erstellt werden, um diese Verbindungen zuzulassen und Verletzungswarnungen zu vermeiden. Nach dem Upgrade werden implizite Verstöße für neu sichtbaren Verkehr gemeldet, wenn keine Erlaubungsregeln existieren. Neue Verkehrsregeln können im Entdeckungsmodus gelernt und automatisch erstellt werden. Um diesen Verkehr zuzulassen, können Sie die Gruppe in den Entdeckungsmodus versetzen oder eine benutzerdefinierte Gruppe mit Adressen (oder DNS-Namen) und einer neuen Netzwerkrichtlinie zu diesem Ziel erstellen, um den Verkehr zuzulassen. HINWEIS: Es gibt einen Fehler in 5.1.0 im Ziel, das von den Verweigerungsverstößen gemeldet wird, die nicht das korrekte Ziel darstellen.  Der Fehler berichtet, dass sowohl server_name als auch client_name gleich sind.  Dieses Problem wird in einem kommenden Patch-Release behoben.

==== Fehlerbehebungen

* Reduzieren Sie den Speicherverbrauch des Controllers durch unnötige cis-Benchmarkdaten, die während der Rolling-Updates erstellt wurden. Dieses Problem tritt bei neuen Bereitstellungen nicht auf.
* Lizenz von der Konfigurationsoberfläche entfernen (nicht mehr erforderlich).

=== 5.0.6-s1 März 2023

==== Fehlerbehebungen

* Aktualisieren Sie die Alpine-Pakete, um CVEs in curl zu beheben, einschließlich CVE-2023-23914, CVE-2023-23915 und CVE-2023-23916.

=== 5.0.6 Februar 2023

==== Fehlerbehebungen

* Hoher Speicherverbrauch in dpMsgConnection
* Hoher Speicherverbrauch im dp-Prozess im Enforcer, wenn viele erlernte Richtlinienregeln mit nicht verwaltetem Arbeitsaufwand vorhanden sind (Speicherleck)
* tcpdump kann nicht erfolgreich gestartet werden, wenn der Datenverkehr auf dem Container gesnifft wird
* Alpine aktualisieren, um mehrere CVEs einschließlich Manager zu beheben: CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552

=== 5.0.5 November 2022

==== Fehlerbehebungen

* Das Upgrade auf 5.0.x führt zu einer Fehlermeldung über Manager, Controller, Enforcer, die unterschiedliche Versionen ausführen.
* Enforcer erleben Go-Routine-Panik, was zu dp kill führt.  WebUI zeigt den Enforcer nicht als online an.
* Unerwarteter Process.Profile.Violation Vorfall in der NV.Protect-Gruppe, auf dem Befehl auf CoreOS.

=== 5.0.4 Oktober 2022

==== Sicherheitsupdates

* Alpine aktualisieren, um die kritische CVE-2022-40674 in der Manager-Expat-Bibliothek zu entfernen, sowie andere kleinere CVEs.

==== Verbesserungen

* Unterstützung für Antrea CNI hinzufügen

==== Fehlerbehebungen

* Unerwarteten Process.Profile.Violation Vorfall in der NV.Protect-Gruppe beheben.
* Wenn SSL im Manager-UI-Zugriff deaktiviert ist, wird das Benutzerpasswort im Manager-Log ausgegeben.

=== 5.0.3 September 2022

==== Verbesserungen

* EULA nach erfolgreichem Neustart vom persistenten Volume nicht anzeigen.
* Verwenden Sie den Bildfilter in den Einstellungen des Schwachstellenprofils, um die Ergebnisse des Container-Scans zu überspringen.
* Unterstützung des Scanners in GitHub-Aktionen bei https://github.com/neuvector/neuvector-image-scan-action.
* Umgebungsvariablen für den Enforcer hinzufügen, um das Scannen von Geheimnissen zu deaktivieren und CIS-Benchmarks auszuführen

[,yaml]
----
    env:
      - name: ENF_NO_SECRET_SCANS  (available after v4.4.4)
        value: "1"
      - name: ENF_NO_AUTO_BENCHMARK (after v5.0.3)
        value: "1"
----

==== Fehlerbehebungen

* Enforcer kann gelegentlich nicht gestartet werden.
* Verbindungsleck in Multi-Cluster-Föderationsumgebungen.
* Compliance-Seite lädt manchmal nicht in Sicherheitsrisiken -> Compliance

=== 5.0.2 Juli 2022

==== Verbesserungen

* Härtete Rancher und SELinux-Cluster werden unterstützt.

==== Fehlerbehebungen

* Agent-Prozess hat hohe CPU-Auslastung auf k3s-Systemen.
* AD LDAP-Gruppen funktionieren nach dem Upgrade auf 5.0 nicht richtig.
* Enforcer wird aufgrund von Fehler=zu viele offene Dateien (rke2/cilium) ständig neu gestartet.
* Support-Protokoll kann nicht erfolgreich heruntergeladen werden.

=== 5.0.1 Juni 2022

==== Verbesserungen

* Unterstützung des Schwachstellenscans von openSUSE Leap OS (im Scanner-Image).
* Scanner: Implementierung von Wipe-Out-Attributen während der Rekonstruktion des Image-Repos.
* Überprüfen Sie {product-name} Bereitstellung und Unterstützung für Hosts mit aktiviertem SELinux. Siehe unten für Details zu vorübergehenden Patches, bis das Helm-Diagramm aktualisiert wird.
* Unterscheidung zwischen Feature-Diagramm und Partner-Diagrammen in der Rancher-Benutzeroberfläche deutlicher.+ Verbesserung der Ingress-Annotation für Nginx im Rancher-Helm-Diagramm. Hinzufügen / Aktualisieren
ingress.kubernetes.io/protocol: https zu nginx.ingress.kubernetes.io/backend-protocol: "HTTPS".
* Der aktuelle OpenShift-Operator unterstützt Passthrough-Routen für API- und Föderationsdienste. Zusätzliche Helm-Wertparameter werden hinzugefügt, um Edge- und Re-Encrypt-Routenbeendigungstypen zu unterstützen.

==== Fehlerbehebungen

* Der AKS-Cluster könnte einen unerwarteten Schlüssel im Admission-Control-WebHook hinzufügen.
* Der Enforcer wird im k8s 1.24-Cluster mit dem 1.64 Containerd-Runtime nicht betriebsbereit. Außerdem startet der Enforcer manchmal nicht.
* Jeder Benutzer mit Admin-Rolle (lokaler Benutzer oder SSO), der einen Cluster zum fed master befördert, sollte automatisch zur fedAdmin-Rolle befördert werden.
* Wenn SSO den standardmäßigen Rancher-Admin in {product-name} im Master-Cluster verwendet, ist die {product-name}-Anmelderolle admin, nicht fedAdmin.
* Behebe mehrere Goroutine-Abstürze.
* Implizite Verletzung von Host-IP, die nicht mit dem Knoten verbunden ist.
* ComplianceProfile zeigt kein PCI-Tag an.
* LDAP-Gruppenzuordnung wird manchmal nicht angezeigt.
* Das Risikoüberprüfungs- und Verbesserungstool führt zu einer Fehlermeldung "Fehler beim Aktualisieren der Systemkonfiguration: Anfrage im falschen Format".
* OKD 3.11 - Clusterrole-Fehler wird angezeigt, auch wenn sie existiert.

==== CVE-Beseitigungen

* Hohe CVE-2022-29458 cve im ncurses-Paket in allen Bildern gefunden.
* Hohe CVE-2022-27778 und CVE-2022-27782 im curl-Paket im Updater-Bild gefunden.

==== Details zur SELinux-Unterstützung

{product-name} benötigt keine zusätzlichen Einstellungen für SELinux-aktivierte Cluster, um bereitgestellt und betrieben zu werden. Bereitstellung von {product-name} auf einem RHEL 8.5-basierten SELinux-aktivierten RKE2-härteten Cluster getestet. {product-name} wurde erfolgreich bereitgestellt, wenn PSP aktiviert ist und das Patch-Manager- und Scanner-Deployment. Die nächste Chart-Version sollte das untenstehende Problem beheben.

Beigefügtes Beispiel zur Aktivierung von PSP aus dem Rancher-Chart und die unten angegebenen Befehle zum Patchen der Manager- und Scanner-Bereitstellung. Die Benutzer-ID im Patch-Befehl kann jede Zahl sein.

[,shell]
----
kubectl patch deploy -ncattle-neuvector-system neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
kubectl patch deploy -ncattle-neuvector-system neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
----

Beispiel zur Aktivierung von PSP:

[,shell]
----
[neuvector@localhost nv]$ getenforce
Enforcing
[neuvector@localhost nv]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

[neuvector@localhost nv]$ kk get psp
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS                                      SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
global-restricted-psp     false                                             RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
neuvector-binding-psp     true    SYS_ADMIN,NET_ADMIN,SYS_PTRACE,IPC_LOCK   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
system-unrestricted-psp   true    *                                         RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
[neuvector@localhost nv]$ nvpo.sh
NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE                    NOMINATED NODE   READINESS GATES
neuvector-controller-pod-54f69f7f9c-6h822   1/1     Running   0          5m51s   10.42.0.29   localhost.localdomain   <none>           <none>
neuvector-enforcer-pod-jz77b                1/1     Running   0          5m51s   10.42.0.30   localhost.localdomain   <none>           <none>
neuvector-manager-pod-588488bb78-p6vf9      1/1     Running   0          111s    10.42.0.32   localhost.localdomain   <none>           <none>
neuvector-scanner-pod-87474dcff-s8vgt       1/1     Running   0          114s    10.42.0.31   localhost.localdomain   <none>           <none>
----

=== 5.0.0 Allgemeine Verfügbarkeit (GA) Veröffentlichung Mai 2022

==== Verbesserungen

* Automatisierte Förderung von Gruppenmodi. Fördert den Schutzmodus einer Gruppe basierend auf verstrichener Zeit und Kriterien. Gilt nicht für CRD-erstellte Gruppen. Dieses Feature ermöglicht es einer neuen Anwendung, für einen bestimmten Zeitraum in Discover zu laufen, das Verhalten zu lernen und {product-name} Erlauben-Listen-Regeln für Netzwerk und Prozess zu erstellen, bevor sie automatisch in den Überwachungs- und dann in den Schutzmodus wechselt. Kriterium von Discover zu Monitor: Verstrichene Zeit zum Lernen aller Netzwerk- und Prozessaktivitäten von mindestens einem aktiven Pod in der Gruppe. Kriterium von Monitor zu Protect: Es gibt keine Sicherheitsereignisse (Netzwerk, Prozess usw.) für den festgelegten Zeitraum der Gruppe.
* Unterstützung für Rancher 2.6.5 Apps und Marketplace-Chart. Wird in den Namespace cattle-neuvector-system bereitgestellt und aktiviert SSO von Rancher zu {product-name}. Hinweis: Frühere Bereitstellungen von Rancher (z. B. Partnerkatalog-Charts, Version 1.9.x und früher) müssen vollständig entfernt werden, um auf das neue Chart zu aktualisieren.
* Unterstützt das Scannen von SUSE Linux (SLE, SLES) und Microsoft Mariner.
* Null-Drift-Prozess- und Dateischutz. Dies ist der neue Standardmodus für Prozess- und Dateischutz. Null-Drift erlaubt automatisch nur Prozesse, die vom übergeordneten Prozess stammen, der im ursprünglichen Container-Image enthalten ist, und erlaubt keine Dateiaktualisierungen oder die Installation neuer Dateien. Im Entdeckungs- oder Überwachungsmodus wird Zero-Drift bei verdächtigen Prozessen oder Dateiaktivitäten alarmieren. Im Schutzmodus wird es solche Aktivitäten blockieren. Zero-Drift erfordert keine Prozesse, die gelernt oder zu einer Erlaubenliste hinzugefügt werden müssen. Das Deaktivieren von Zero-Drift für eine Gruppe bewirkt, dass die für die Gruppe aufgeführten Prozess- und Dateiregeln wirksam werden.
* Geteilte Richtlinienmodus-Schutz für Netzwerk, Prozess/Datei. Es gibt jetzt eine globale Einstellung in den Einstellungen -> Konfiguration, um den Netzwerk-Schutzmodus separat für die Durchsetzung von Netzwerkrichtlinien festzulegen. Das Aktivieren dieser Funktion (Standard ist deaktiviert) bewirkt, dass alle Netzwerkrichtlinien im ausgewählten Schutzmodus (Entdecken, Überwachen, Schützen) sind, während die Prozess-/Dateiregeln im Schutzmodus für diese Gruppe bleiben, wie im Richtlinien -> Gruppenbildschirm angezeigt. Auf diese Weise können Netzwerkrichtlinien auf Schützen (blockieren) eingestellt werden, während die Prozess-/Dateirichtlinien auf Überwachen oder umgekehrt eingestellt werden können.
* WAF-Regelerkennung, verbesserte DLP-Regeln (Header, URL, vollständiges Paket). Verwendet für eingehende Verbindungen zu Webanwendungs-Pods sowie für ausgehende Verbindungen zu API-Diensten zur Durchsetzung der API-Sicherheit.
* CRD für WAF, DLP und Zulassungssteuerungen. HINWEIS: Zusätzliche Clusterrollenbindungen/Berechtigungen erforderlich. Siehe die Abschnitte zur Bereitstellung von Kubernetes und OpenShift. CRD-Import/Export und Versionierung für Zulassungssteuerungen, die durch CRD unterstützt werden.
* Rancher SSO-Integration zum Starten der {product-name} Konsole über Rancher Manager. Dieses Feature ist nur verfügbar, wenn die {product-name} Container über Rancher bereitgestellt werden. Diese Bereitstellung zieht aus dem gespiegelten Rancher-Repository (z.B. rancher/mirrored-neuvector-controller:5.0.0) und wird im Namespace cattle-neuvector-system bereitgestellt. HINWEIS: Erfordert die aktualisierte Rancher-Version 2.6.5 Mai 2022 oder später, und nur Admin- und Clusterbesitzerrollen werden derzeit unterstützt.
* Unterstützt die Bereitstellung auf RKE2.
* Unterstützung für die Föderation von Clustern (Multi-Cluster-Manager) über einen Proxy. Proxy in den Einstellungen -> Konfiguration konfigurieren und Proxy aktivieren, wenn Föderationsverbindungen konfiguriert werden.
* Überwachen Sie die erforderlichen RBAC-Clusterrollen/-bindungen und warnen Sie in Ereignissen und der Benutzeroberfläche, wenn welche fehlen.
* Unterstützen Sie die Kriterien für Ressourcenbeschränkungen in den Zulassungssteuerungsregeln.
* Unterstützen Sie das Microsoft Teams-Format für Webhooks.
* Unterstützen Sie verschachtelte AD/LDAP-Gruppen unter der zugeordneten Rollengruppe.
* Unterstützen Sie Clusterrollenbindungen oder Rollenbindungen mit Gruppeninformationen in IDP für Openshift.
* Erlauben Sie Netzwerkregeln und Zulassungssteuerungsregeln, zu einer föderierten Regel befördert zu werden.

==== Fehlerbehebungen

* Beheben Sie das Problem, dass das Backup der Worker-Föderationsrolle in nicht-föderierte Cluster wiederhergestellt werden sollte.
* Verbessern Sie die Ladezeiten der Seite für eine große Anzahl von CVEs in Sicherheitsrisiken -> Verwundbarkeiten.
* Erlauben Sie dem Benutzer, den Modus zu wechseln, wenn er alle Gruppen im Menü Richtlinien -> Gruppen auswählt. Warnen Sie, wenn die Gruppe der Knoten ebenfalls ausgewählt ist.
* Falten Sie die Compliance-Prüfposten mit demselben Namen zusammen und machen Sie sie erweiterbar.
* Verbessern Sie die Sicherheit der gRPC-Kommunikation.
* Behoben: konnte keine korrekten privilegierten Informationen zur Arbeitslast in der rke2-Installation abrufen.
* Beheben Sie das Problem mit der Unterstützung von openSUSE Leap 15.3 (k8s/crio).

==== Weitere Updates

* Helm-Chart-Update appVersion auf 5.0.0 und Chart-Version auf 2.2.0
* Serverless-Scanning-Funktion/-menü entfernt.
* Unterstützung für die Integration von Jfrog Xray-Scanergebnissen entfernt (Artifactory-Registry-Scan wird weiterhin unterstützt).
* Die Unterstützung für die Bereitstellung auf ECS wird nicht mehr bereitgestellt. Der All-in-One sollte weiterhin auf ECS bereitgestellt werden können, jedoch wird die Dokumentation der Schritte und Einstellungen nicht mehr unterstützt.

=== Upgrade von {product-name} 4.x auf 5.x (vor 5.2.x)

[NOTE]
====
Die folgenden Anweisungen gelten für Upgrades auf 5.0.x und 5.1.x. Für 5.2.x haben sich Dienstkonten und Bindungen geändert und sollten xref:kubernetes.adoc#_deploy_suse_security[überprüft] werden, um Upgrades zu planen.
====


Für Helm-Benutzer, aktualisieren Sie auf {product-name} Helm-Chart 2.0.0 oder später. Wenn Sie einen Operator oder eine Helm-Installation auf OpenShift aktualisieren, siehe die folgende Anmerkung.

. Löschen Sie die alte neuvector-binding-customresourcedefinition-Clusterrolle

[,shell]
----
kubectl delete clusterrole neuvector-binding-customresourcedefinition
----

. Wenden Sie das neue Update-Verb für die neuvector-binding-customresourcedefinition-Clusterrolle an

[,shell]
----
kubectl create clusterrole neuvector-binding-customresourcedefinition --verb=watch,create,get,update --resource=customresourcedefinitions
----

. Löschen Sie das alte CRD-Schema für Kubernetes 1.19+

[,shell]
----
kubectl delete -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/crd-k8s-1.19.yaml
----

. Erstellen Sie ein neues CRD-Schema für Kubernetes 1.19+

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/waf-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/dlp-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/admission-crd-k8s-1.19.yaml
----

. Erstellen Sie eine neue Admission-, DLP- und WAF-Clusterrolle sowie eine Clusterrollenbindung

[,shell]
----
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----

. Aktualisieren Sie die Bildnamen und -pfade zum Abrufen von {product-name} Bildern vom Docker-Hub (docker.io), z.B.

* neuvector/manager:5.0.0
* neuvector/controller:5.0.0
* neuvector/enforcer:5.0.0
* neuvector/scanner:latest
* neuvector/updater:latest

Optional können Sie alle Verweise auf die {product-name} Lizenz und das Registrierungsgeheimnis in Helm-Charts, Bereitstellungs-YAML, ConfigMap, Skripten usw. entfernen, da diese nicht mehr erforderlich sind, um die Bilder abzurufen oder {product-name} zu verwenden.

*Hinweis zu SCC und Upgrade über Operator/Helm*

Privileged SCC wird dem Dienstkonto hinzugefügt, das in der Bereitstellungs-YAML von Operator-Version 1.3.4 und höher in neuen Bereitstellungen angegeben ist. Im Falle eines Upgrades des {product-name} Operators von einer vorherigen Version auf 1.3.4 oder Helm auf 2.0.0, bitte Privileged SCC vor dem Upgrade löschen.

[,shell]
----
oc delete rolebinding -n neuvector system:openshift:scc:privileged
----

==== Beta 1-Version veröffentlicht im April 2022

* Funktional vollständig, einschließlich automatisierter Förderung von Gruppenmodi. Fördert den Schutzmodus einer Gruppe basierend auf verstrichener Zeit und Kriterien. Gilt nicht für CRD-erstellte Gruppen. Dieses Feature ermöglicht es einer neuen Anwendung, für einen bestimmten Zeitraum in Discover zu laufen, das Verhalten zu lernen und {product-name} Erlauben-Listen-Regeln für Netzwerk und Prozess zu erstellen, bevor sie automatisch in den Überwachungs- und dann in den Schutzmodus wechselt. Kriterium von Discover zu Monitor: Verstrichene Zeit zum Lernen aller Netzwerk- und Prozessaktivitäten von mindestens einem aktiven Pod in der Gruppe. Kriterium von Monitor zu Protect: Es gibt keine Sicherheitsereignisse (Netzwerk, Prozess usw.) für den festgelegten Zeitraum der Gruppe.
* Unterstützung für Rancher 2.6.5 Apps und Marketplace-Chart. Wird in den Namespace cattle-neuvector-system bereitgestellt und aktiviert SSO von Rancher zu {product-name}. Hinweis: Frühere Bereitstellungen von Rancher (z. B. Partnerkatalog-Charts, Version 1.9.x und früher) müssen vollständig entfernt werden, um auf das neue Chart zu aktualisieren.
* Tags für Vollstrecker, Manager, Controller: 5.0.0-b1 (z.B. neuvector/controller:5.0.0-b1)

==== Vorschau.3-Version veröffentlicht im März 2022

[CAUTION]
.wichtig
====

Um frühere Vorschau-Bereitstellungen für neue CRD WAF, DLP und Admission-Control-Funktionen zu aktualisieren, bitte die CRD-YAML aktualisieren und neue rbac/role-Bindungen hinzufügen:

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/latest/crd-k8s-1.19.yaml
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----
====


==== Verbesserungen

* Unterstützt das Scannen von SUSE Linux (SLE, SLES) und Microsoft Mariner.
* Null-Drift-Prozess- und Dateischutz. Dies ist der neue Standardmodus für Prozess- und Dateischutz. Null-Drift erlaubt automatisch nur Prozesse, die vom übergeordneten Prozess stammen, der im ursprünglichen Container-Image enthalten ist, und erlaubt keine Dateiaktualisierungen oder die Installation neuer Dateien. Im Entdeckungs- oder Überwachungsmodus wird Zero-Drift bei verdächtigen Prozessen oder Dateiaktivitäten alarmieren. Im Schutzmodus wird es solche Aktivitäten blockieren. Zero-Drift erfordert keine Prozesse, die gelernt oder zu einer Erlaubenliste hinzugefügt werden müssen. Das Deaktivieren von Zero-Drift für eine Gruppe bewirkt, dass die für die Gruppe aufgeführten Prozess- und Dateiregeln wirksam werden.
* Geteilte Richtlinienmodus-Schutz für Netzwerk, Prozess/Datei. Es gibt jetzt eine globale Einstellung in den Einstellungen -> Konfiguration, um den Netzwerk-Schutzmodus separat für die Durchsetzung von Netzwerkrichtlinien festzulegen. Das Aktivieren dieser Funktion (Standard ist deaktiviert) bewirkt, dass alle Netzwerkrichtlinien im ausgewählten Schutzmodus (Entdecken, Überwachen, Schützen) sind, während die Prozess-/Dateiregeln im Schutzmodus für diese Gruppe bleiben, wie im Richtlinien -> Gruppenbildschirm angezeigt. Auf diese Weise können Netzwerkrichtlinien auf Schützen (blockieren) eingestellt werden, während die Prozess-/Dateirichtlinien auf Überwachen oder umgekehrt eingestellt werden können.
* WAF-Regelerkennung, verbesserte DLP-Regeln (Header, URL, vollständiges Paket)
* CRD für WAF, DLP und Zulassungssteuerungen. HINWEIS: Zusätzliche Clusterrollenbindungen/Berechtigungen erforderlich. Siehe die Abschnitte zur Bereitstellung von Kubernetes und OpenShift. CRD-Import/Export und Versionierung für Zulassungssteuerungen, die durch CRD unterstützt werden.
* Rancher SSO-Integration zum Starten der {product-name} Konsole über Rancher Manager. Dieses Feature ist nur verfügbar, wenn die {product-name} Container über Rancher bereitgestellt werden. HINWEIS: Benötigt aktualisierte Rancher-Version (Datum/Version TBD).
* Unterstützt die Bereitstellung auf RKE2.
* Unterstützung für die Föderation von Clustern (Multi-Cluster-Manager) über einen Proxy.
* Überwachen Sie die erforderlichen RBAC-Clusterrollen/-bindungen und warnen Sie in Ereignissen und der Benutzeroberfläche, wenn welche fehlen.
* Unterstützen Sie die Kriterien für Ressourcenbeschränkungen in den Zulassungssteuerungsregeln.

==== Fehlerbehebungen

* Beheben Sie das Problem, dass das Backup der Worker-Föderationsrolle in nicht-föderierte Cluster wiederhergestellt werden sollte.

==== Vorschau.2-Version veröffentlicht im Februar 2022

* Kleine Datei- und Lizenzänderungen im Quellcode, keine neuen Funktionen hinzugefügt.

==== Unterstützung für Bereitstellung auf AWS ECS eingestellt

Die Unterstützung für die Bereitstellung auf ECS wird nicht mehr bereitgestellt. Der All-in-One sollte weiterhin auf ECS bereitgestellt werden können, jedoch wird die Dokumentation der Schritte und Einstellungen nicht mehr unterstützt.

=== 5.0 'Technische Vorschau' Januar 2022

==== Verbesserungen

* Erste Veröffentlichung einer nicht unterstützten, 'technischen Vorschau'-Version von {product-name} 5.0 Open-Source-Version.
* Unterstützung für OWASP Top-10, WAF-ähnliche Regeln zum Erkennen von Netzwerkangriffen in Headern oder im Body hinzufügen. Beinhaltet Unterstützung für CRD-Definitionen von Signaturen und Anwendung auf geeignete Gruppen.
* Entfernt serverlose Scanfunktionen.

==== Fehlerbehebungen

* TBD

==== Sonstiges

* Helm-Chart v1.8.9 wird für 5.0.0-Bereitstellungen veröffentlicht. Wenn dies mit der Vorschau-Version von 5.0.0 verwendet wird, sollten die folgenden Änderungen an values.yml vorgenommen werden:
 ** Aktualisieren Sie das Register auf docker.io
 ** Aktualisieren Sie die Bildnamen/-tags auf die Vorschauversion im Docker Hub
 ** Lassen Sie die imagePullSecrets leer
