= Versionshinweise 5.x
:revdate: 2025-08-26
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/01.5x/01.5x.md
:page-opendocs-slug:  /releasenotes/5x

== Versionshinweise für 5.x

[NOTE]
====
Um E-Mail-Benachrichtigungen über neue Versionen zu erhalten, abonnieren Sie bitte diese SUSE-Newsletterliste: https://lists.suse.com/mailman/listinfo/neuvector-updates
====

=== 5.4.6 August 2025

==== Nouvelles fonctionnalités

* *NVSHAS-6733* : Regeln für Antworten als CRD exportieren.
* *NVSHAS-9899* : Die NeuVector-Prozessprofilwarnungen für Java-Dienste enthalten sensible Daten.
* *NVSHAS-9990* : Ein neues Hash-Algorithmus für Benutzerpasswörter übernehmen.
* *NVSHAS-9968* : Unterstützung für die Festlegung des Standardpassworts für das Standardadministratorkonto.

==== Behobene Fehler

* *NVSHAS-10062* : Der Manager zeigt keinen FEHLER an, wenn die Erstellung des Administratorkennworts beim ersten Anmelden fehlschlägt.
* *NVSHAS-10041* : Die Föderationsoperation schlug mit "ungültigen Daten" fehl, als die Föderation über ConfigMap konfiguriert wurde.
* *NVSHAS-10018*: NeuVector scannt nicht alle Images im GitLab-Registry.
* *NVSHAS-10017*: Alerte de sécurité de faux positif liée au processus autorisé.
* *NVSHAS-10001*: Die Schutz-/Überwachungsmaßnahmen "bestehen" nach der Löschung der Gruppe fort.
* *NVSHAS-9985*:    NeuVector (Fed Master) verursacht ein Problem für alle Anfragen von außen.
* *NVSHAS-9981*:    Ein Sicherheitsereignis wird jedes Mal ausgelöst, wenn eine neue "Prozessprofilregel" zu einer Gruppe hinzugefügt oder geändert wird.

==== Avis de sécurité

* https://github.com/neuvector/neuvector/security/advisories/GHSA-8pxw-9c75-6w56[Das Admin-Konto hat ein unsicheres Standardpasswort]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-8ff6-pc43-jwv3[Verwaltung unsicherer Passwörter, die anfällig für Rainbow-Angriffe sind]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-w54x-xfxg-4gxq[Der Prozess mit sensiblen Argumenten führt zu Leaks]

Siehe die Dokumentation xref:cve.adoc[Sicherheitswarnungen und CVEs] für weitere Informationen.

=== 5.4.5 Juli 2025

==== Nouvelles fonctionnalités

* *NVSHAS-9776*: Fügen Sie die etcd-Toleranz im Helm-Diagramm hinzu.

==== Fehlerbehebungen

* *NVSHAS-9507*: Der OCI-Container wird nicht gescannt.
* *NVSHAS-9787*: Löschen Sie das unnötige Manager-Log.
* *NVSHAS-9788*: Optimieren Sie den Algorithmus zur Zertifikatserstellung.
* *NVSHAS-9789*: Löschen Sie das unnötige Manager-Log in der Konfiguration des Remote-Registers.
* *NVSHAS-9867*: NeuVector zeigt `.NET Library System.Formats.Asn1 v8.013` CVE 2024-38095 betroffen an.
* *NVSHAS-9883*: [quay.io] Die generischen Filter funktionieren nicht für das Docker-Register.
* *NVSHAS-9911*: Das Scannen des Repositories über die REST-API gibt eine "falsche" Nachricht zurück.
* *NVSHAS-9930*: CVE-2018-20796 für `glibc/libc-bin : 2.36-9+deb12u10` – Falscher Alarm.
* *NVSHAS-9933*: Die Funktionalität des Registeradapters (Harbor) zeigt Fehler im Zielregister während des Scans an.
* *NVSHAS-9934*: Verdächtige Zero-Drift-Funktionalität ist ausgefallen.
* *NVSHAS-9940*: Problème de mode sous-domaine JFrog de scan NV.
* *NVSHAS-9942*: Die Bildanalysen für die Kundenbilder schlagen fehl.
* *NVSHAS-9945*: Wenn der Prozessname zu lang ist, ist es schwierig zu bestimmen, wie die entsprechende Prozessprofilregel erstellt werden kann.
* *NVSHAS-9946*: Anzeigeproblem mit der Zulassungswarnung für den Credential-Typ.
* *NVSHAS-9947*: [UI-ext] Das Compliance-Diagramm fehlt den Status "Manuell" in Rancher NeuVector.
* *NVSHAS-9948*: Nach dem Upgrade auf `5.4.3` wurde die NeuVector-Konfiguration verloren.
* *NVSHAS-9949*: [Harbor][Benutzer/Passwort falsch] Es wird weiterhin nach Bildern gesucht, selbst bei falscher Benutzer-/Passworteingabe.
* *NVSHAS-9952*: Entfernen Sie 'Signatur' aus dem Nutzungsbericht, da NV den Lizenzschlüssel nicht mehr ausgibt/prüft.
* *NVSHAS-9953*: Die Enforcer-Pods starten weiterhin neu.
* *NVSHAS-9954*: L'exportateur Prometheus de NeuVector génère des métriques dupliquées.
* *NVSHAS-9958*: Die Anwendung der Netzwerkregeln dauert lange.
* *NVSHAS-9960*: Die Scanner funktionieren nicht.
* *NVSHAS-9969*: Fatale Fehler: Gleichzeitige Kartenschreibvorgänge führen zum Neustart der Enforcer-Komponente.
* *NVSHAS-9971*: Über NV UI `Get Bootstrap Password`.
* *NVSHAS-9975*: [Manager] TypeError: `this.mousemoveListener` ist keine in NV GUI beobachtete Funktion.
* *NVSHAS-9986*: Zugriffsregeln für Prozesse und Dateien können in der Ansicht der föderierten Richtliniengruppe nicht geändert oder gelöscht werden.
* *NVSHAS-9988*: UI: Die Gruppenseiten zeigen nicht alle Gruppen an, wenn mehr als 2.000 Gruppen vorhanden sind.
* *NVSHAS-9991*: Die Gruppe `nv.gatekeeper-controller-manager.openshift-azure-guardrails` fehlt in der UI.
* *NVSHAS-9993*: MD5 durch SHA256 ersetzen.
* *NVSHAS-9994*: Der Enforcer-Pod startet weiterhin neu.
* *NVSHAS-9996*: Das Helm-Diagramm sollte einen nicht privilegierten Modus für die Enforcer-Pods ermöglichen.
* *NVSHAS-9998*: Impossible d'exporter le groupe du maître fédéré de NeuVector.
* *NVSHAS-10000*: Upgrade NV zu BCI 15.7.
* *NVSHAS-10003*: Das Neuladen der Seite funktioniert nicht auf der eigenständigen NV-Seite, während die Rancher-Benutzeroberfläche geöffnet ist.
* *NVSHAS-10008*: Analyse du registre – Le menu d'affichage est cassé pour l'image scannée.
* *NVSHAS-10010*: Die TCP SYN-Flut blockiert den Eingang, was zu einer vollständigen Blockade des eingehenden Verkehrs führt.

=== 5.4.4 Mai 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9915**: Die Ergebnisse der Analyse des Harbor-Scanner-Moduls in der NeuVector-Benutzeroberfläche anzeigen.
* **NVSHAS-9904**: `imagePullPolicy` an `values.yaml` für jede Komponente exponieren.
* **NVSHAS-9869**: UI: DDoS-Kontrollen zum Gruppentafel verschieben.
* **NVSHAS-9840**: [GCP] NeuVector Autopilot Unterstützung für GCP.
* **NVSHAS-9248**: Unbenutzte Prozess-/Netzwerkregeln mit Zählern und einem Zeitstempel `Last Used` anzeigen.
* **NVSHAS-8160**: [Controller] Einige Elemente für die Berechnung des Sicherheitsrisikowertes anpassen.
* **NVSHAS-4673**: Vorschlag, eine Nachricht vor dem Export von Gruppen hinzuzufügen.

==== Fehlerbehebungen

* **NVSHAS-9931**: Eine Warnung hinzufügen, wenn inkonsistente Versionen von NeuVector-Produkten in einem Multi-Cluster vorhanden sind.
* **NVSHAS-9925**: `/v1/scan/asset/images` Die API auf der Registrierungsseite schlägt fehl.
* **NVSHAS-9913**: Problème de suppression de plusieurs règles réseau liées aux groupes Workload:XYZ.
* **NVSHAS-9912**: Helm-Update zu bestimmten erforderlichen K8s RBAC-Berechtigungen für das Dienstkonto des Controllers.
* **NVSHAS-9909**: Nachricht "Getrennt - Gehe zur Lade-Seite" wird angezeigt, wenn NeuVector Rancher NavLink verwendet wird.
* **NVSHAS-9898**: In einer föderierten Umgebung funktioniert das Ändern der Kriterien einer vom Kunden erstellten Gruppe fed.* (z. B. fed.core-systems) nicht.
* **NVSHAS-9894**: [Enforcer] `Nv.protect` verweigert den Verfügbarkeitsprüfungsbefehl des Controllers `cat /tmp/ready`.
* **NVSHAS-9886**: Die Netzwerkaktivität löst keine Domainnamen für benutzerdefinierte externe Gruppenverbindungen auf.
* **NVSHAS-9884**: [Analyse de nœud][Analyse de conteneur] L'analyse échouera.
* **NVSHAS-9873**: Problème de recherche avec le filtre avancé de l'UI dans NeuVector 5.4.2.
* **NVSHAS-9865**: Les politiques réseau exportées diffèrent, selon l'ordre de sélection (mêmes groupes sélectionnés).
* **NVSHAS-9828**: [Enforcer: Prozess] Der NeuVector Enforcer kann Pods mit kurzer Lebensdauer (weniger als 5 Sekunden) nicht erkennen.
* **NVSHAS-9783**: Nachdem die Netzwerkrichtlinie zum Verbot von ICMP-Paketen hinzugefügt wurde, sieht NeuVector keine Warnung in `Security Events`.
* **NVSHAS-9176**: Eine Skriptfehler auf der Seite **Risiken von Sicherheit > Schwachstellen** anzeigen, wenn ein Benutzer mit der Rolle des Namensraums `rt_scan:w` angemeldet ist.

=== 5.4.3 März 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9793**: Erlaube Fed Global-Rollen in LDAP/userinitcfg beim Bereitstellen von NeuVector über das ConfigMap und Secret.
* **NVSHAS-9764**: [RFE] Unterstützung für Azure für "Remote Repository-Konfiguration" hinzufügen.
* **NVSHAS-9759**: Fügen Sie Datumsdetails im Ingress Exposure Report hinzu.
* **NVSHAS-9755**: Anfrage zur Anzeige der Namen der Umgebungsvariablen mit den Werten in den Warnungen für die Geheimnisse.
* **NVSHAS-9748**: [Helm] Aktualisierung von NeuVector Helm zur Unterstützung der Namensreferenz für gemeinsame Gruppen in CRD (NVSHAS0-4717).
* **NVSHAS-9426**: Fügen Sie hostPath für Scanner zum Helm-Diagramm hinzu.
* **NVSHAS-9326**: NeuVector - Pluggable Harbor Scanner-Modul.
* **NVSHAS-9835**: Benutzeroberfläche zum Deaktivieren des automatischen Scans für den Knoten.
* **NVSHAS-7997**: Scanner-Connector für ghcr.io.
* **NVSHAS-7982**: WAF-Sensoren vom Föderationsmaster zuweisen.

==== Fehlerbehebungen

* **NVSHAS-9849**: Die Agenten registrieren sich nicht bei den Controllern.
* **NVSHAS-9847**: Die generischen Filter funktionieren nicht für das Docker-Registry.
* **NVSHAS-9833**: La restauration de la configuration échoue dans les déploiements Rancher.
* **NVSHAS-9832**: Problème de création de règles réseau en utilisant le groupe de charges de travail.
* **NVSHAS-9821**: Der Prozessname stimmt nicht mit dem von der Befehlszeile für die Regelwarnung des Prozessgewinns überein.
* **NVSHAS-9817**: Die Erstellung der Sicherheitsregel NvClusterSecurityRule CRD zeigt eine erfolgreiche Erstellung an, wurde jedoch aufgrund doppelter Prozessregel-Einträge nicht tatsächlich erstellt.
* **NVSHAS-9812**: NeuVector Prometheus-Exporter hat falsche Metriken.
* **NVSHAS-9811**: [Manager] Zugriff auf die grafische Benutzeroberfläche ist nicht möglich, wenn ein benutzerdefiniertes Zertifikat (CA) mit Wurzel-CA und Zwischen-CA im Geheimnis verwendet wird.
* **NVSHAS-9801**: Der FIPS + `manager.env.ssl=false` Modus verursacht einen Fehler im Manager.
* **NVSHAS-9792**: Die Synchronisierung der Föderationsrichtlinie schlägt fehl, da die Körpergröße das Maximum von Consul überschreitet.
* **NVSHAS-9784**: NeuVector renvoie 404 lors de l'analyse du dépôt d'images Jfrog.
* **NVSHAS-9783**: Nachdem die Netzwerkstrategie hinzugefügt wurde, um ICMP-Pakete abzulehnen, sieht der Benutzer keine Warnungen in "Sicherheitsereignisse".
* **NVSHAS-9780**: Die NeuVector Single Sign-On funktioniert nicht mit Rancher NavLink.
* **NVSHAS-9777**: JSON-Webhook mit doppelten "Level"-Schlüsseln.
* **NVSHAS-9770**: Der automatische Wechsel nach dem Zero-Drift-Modus ändert die falsche Strategie.
* **NVSHAS-9765**: Der Zugriff auf Dateien ist im Protect-Modus nicht vollständig blockiert.
* **NVSHAS-9756**: Der Enforcer hat die maximale CPU erreicht und hat mehrere Speicherbelastungswarnungen.
* **NVSHAS-9668**: Der Konformitätstest schlägt bei RKE2 fehl.
* **NVSHAS-9265**: Unvollständige und falsche Ergebnisse des Schwachstellenscans in der PRE PCI-Umgebung.
* **NVSHAS-9227**: Le scan du registre se bloque au milieu du processus de scan et passe à l'état "Inactif".
* **NVSHAS-9729**: Eine falsche Anzahl von Schwachstellen wird beobachtet, wenn mehrere StatefulSets mit dem "gleichen Namen" in den Namespaces in einem Projekt bereitgestellt werden.
* **NVSHAS-9810**: Der NeuVector-Controller reagiert nicht und die Benutzeroberfläche ist nicht zugänglich.

=== 5.4.2 Januar 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9726**: Der Monitor übergibt jetzt die URL des Proxys.
* **NVSHAS-9719**: Ankündigung der Abkündigung der integrierten Zertifikate.
* **NVSHAS-9715**: Unterstützung für Helm Chart-Wert zur Festlegung des Nodeports auf dem Controller und dem Manager.
* **NVSHAS-9710**: Eine sortierbare Spalte `feed_rating` im Tab **Schwachstellen** einfügen.
* **NVSHAS-9669**: Gesamt-Sicherheitsbewertung über die REST-API.
* **NVSHAS-9590**: Fähigkeit, den Schwachstellenscore für alle Assets auszuwählen.
* **NVSHAS-7555**: Inclure l'option "Actualiser automatiquement" sous Événements de sécurité.

==== Fehlerbehebungen

* **NVSHAS-9662**: Inkonsistente Rollen-/RoleBinding-Logik im Helm-Diagramm 2.8.2.
* **NVSHAS-9652**: Différence observée dans le format syslog dans splunk.
* **NVSHAS-9649**: Le lien du conteneur produit un code de réponse 404 dans l'événement de sécurité.
* **NVSHAS-9613**: Fehler des NeuVector Managers / NeuVector Web-Interface nicht verfügbar.
* **NVSHAS-9507**: Der OCI-Container wird nicht gescannt.
* **NVSHAS-9443**: Das Upgrade/Die Installation über ArgoCD schlägt fehl, da das Objekt leases.coordination.k8s.io nicht erstellt werden kann.
* **NVSHAS-9436**: Möglicher Fehlalarm CVE gegen CVE-2024-7347.
* **NVSHAS-8386**: Private Schlüssel und selbstsignierte Zertifikate werden weiterhin in mehreren Images versendet.
* **NVSHAS-9754**: [UI] Verhindern, dass Rancher die SSO-Authentifizierung des mit Rancher verbundenen Benutzers für OpenShift oder Rancher RBAC deaktiviert.
* **NVSHAS-9751**: [Ausführungs-Schutz] Der Überwachungsmodus + Zero Drift erzeugt keine Warnung, wenn ein Kindprozess ausgeführt wird.
* **NVSHAS-9721**: Die Benutzeroberfläche sollte eine geeignete Fehlermeldung anzeigen, wenn der Benutzer einen falschen Registrynamen eingibt.
* **NVSHAS-9696**: Indication de couleur incohérente des actifs sur la page de vulnérabilité.
* **NVSHAS-9686**: Fest codierter Namespace für das Zertifikat des Registrierungsadapters im Helm-Diagramm von Neuvector.
* **NVSHAS-9678**: Übermäßige Fehlermeldungen nach Änderungen des Linters.
* **NVSHAS-9670**: Manager: Problem mit doppelten Anführungszeichen in der Antwort im Nur-Text-Format und Problem mit nicht benannter Java-Bibliothek in der SBT-Ausführung.
* **NVSHAS-9667**: Das Setzen der Umgebungsvariable `CTRL_PATH_DEBUG` auf einen Fehler im Deployment des Controllers funktioniert nicht.
* **NVSHAS-9665**: Dateizugriffsregel: La suppression des règles prédéfinies produit une erreur "setRowData".
* **NVSHAS-9664**: Groupe de stratégie: La suppression du script personnalisé produit une erreur de type "setRowData".

[NOTE]
====
Die Standardtypen des Managers und des Registrierungsadapterdienstes wurden in ClusterIP geändert.  Benutzer können das Parameter immer ersetzen, indem sie `manager.svc.type` und `cve.adapter.svc.type` ersetzen, wenn NodePort bevorzugt wird.
====

In der Version 5.4.2 von NeuVector wird die Unterstützung für Deployments, die das integrierte interne Zertifikat verwenden, eingestellt. Le certificat trouvé à `/etc/neuvector/certs/internal` dans les images de conteneur NeuVector 5.4.2 sera supprimé. Um NeuVector weiterhin zu verwenden, müssen die Benutzer:

==== 5.4.2 Neue Installation:

===== Verwendung von Helm:

- Aktivieren Sie die Flags `internal.autoGenerateCert` und `internal.autoRotateCert` in den Helm-Charts (diese werden ab Version 5.4.2 standardmäßig aktiviert). Alternativ ist eine YAML-Methode unten verlinkt.

===== Verwendung von YAML:

- Ein xref:internal.adoc#_replacing_certificates_used_in_internal_communications_of_suse_security[internes Zertifikat unter Verwendung der vorhandenen Methoden bereitstellen].

==== Upgrade von vorherigen Versionen auf 5.4.2:

Bitte erstellen und konfigurieren Sie interne Zertifikate vom Scanner für den Controller, den Executor und den Registry-Adapter, um ein kontinuierliches Update ohne Datenverlust zu gewährleisten. Es wird immer empfohlen, eine Sicherung Ihrer Konfiguration vor dem Upgrade zu erstellen. 

Die folgenden Schritte sind nur erforderlich, wenn Ihr Deployment eine `.yaml` Datei verwendet. Das Upgrade über Helm benötigt diese zusätzlichen Schritte nicht aufgrund der standardmäßig über die folgenden Flags erstellten internen Zertifikate: `internal.autoGenerateCert` und `internal.autoRotateCert`.

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/ca.cert" > ca.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.pem" > tls.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.key" > tls.key
----

[,shell]
----
kubectl create secret generic internal-cert -n neuvector  --from-file=tls.key --from-file=tls.crt --from-file=ca.crt
----

Beispiel für yaml 5.4.2 mit konfiguriertem internem Zertifikat:
*https://github.com/neuvector/manifests/blob/main/kubernetes/5.4.0/neuvector-k8s.yaml* 

Zusätzliche Informationen zu xref:internal.adoc[internen Zertifikaten].


Im Falle einer PVC-Konfiguration können Benutzer ein vorhandenes PVC in der neuen Installation konfigurieren, um eine Konfiguration wiederherzustellen.


**Zusätzliche Anmerkung für den Scanner:**

Für aktuelle Benutzer mit Versionen vor 5.4.2 bleibt das Zertifikat bis zum 31. März 2025 im `neuvector/scanner:latest` verfügbar. Nach diesem Datum wird es gelöscht. Die Benutzer müssen sicherstellen, dass sie dasselbe interne Zertifikat dem Controller, dem Executor, dem Scanner und dem Registrierungsadapter zur Verfügung stellen, um den Scanner weiterhin nutzen zu können.

Bitte beachten Sie, dass der autonome Scanner von diesen Änderungen nicht betroffen sein wird.

=== 5.4.1 November 2024

==== Nouvelles fonctionnalités

* **NVSHAS-8583**: Definieren Sie granulare Richtlinienmodi für Regelsets, separaten Netzwerkrichtlinienmodus und Profilmodus auf Gruppenebene.
* **NVSHAS-9440**: Unterstützen Sie den separaten Netzwerkmodus sowie den Prozess- und Dateimodus in CRD.
* **NVSHAS-9369**: Fügen Sie eine Debug-Protokollkategorie über die Helm-Bereitstellung für den Controller hinzu.
* **NVSHAS-9040**: Verbessern Sie die Syslog-Nachricht, wenn die Zulassungsregel im Überwachungsmodus abgelehnt wird.

==== Fehlerbehebungen

* **NVSHAS-9416**: [Scanner] activemq-all-5.8.0.redhat-60024.jar kann mit keiner Schwachstelle erkannt werden (aber die vorherige Version des Scanners kann).
* **NVSHAS-9447**: Die Controller/Scanner-Pods stürzen ab - "Nicht unterstützte Systemausgabe".
* **NVSHAS-9278**: CVE-2024-41110 est trouvé dans la dernière image du scanner.
* **NVSHAS-9467**: Die benutzerdefinierte Gruppe, die durch das Pod-Label definiert ist, propagiert ihre Profildaten nicht auf die untergeordneten Container.
* **NVSHAS-9442**: Bereitstellungsproblem auf ArgoCD.
* **NVSHAS-9436**: Möglicher Fehlalarm CVE gegen CVE-2024-7347.
* **NVSHAS-9468**: Beheben Sie CVE-2020-26160, um jwt-go durch jwt:v5 zu ersetzen.
* **NVSHAS-9517**: Die Zulassungsregel ist inkonsistent und liefert falsche Ergebnisse.
* **NVSHAS-9532**: Der Bildscan ist abgeschlossen, aber die Bereitstellung ist weiterhin nicht erlaubt.
* **NVSHAS-9558**: Das JWT-Token läuft ab, berichtet http.StatusRequestTimeout 408.
* **NVSHAS-9576**: Löschen Sie das Passwortfeld für die Registrierungsdaten, wenn der Benutzer den Controller-Modus mit Jenkins zum Scannen verwendet.
* **NVSHAS-9425**: Erstellen Sie nfq, wenn der Container vxlan hat.
* **NVSHAS-9571**: [Registries] Filter für alle gescannten Bilder funktioniert nicht gut.
* **NVSHAS-9589**: Getrennte verwaltete Cluster - Versionsinkompatibilität mit dem Hauptcluster.
* **NVSHAS-8824**: Der Benutzer kann seine eigenen Gruppen nicht löschen und kann keine Gruppen im Namensraum erstellen.
* **NVSHAS-9605**: Das Exportieren einer Gruppe mit ungültigen Werten für den Richtlinienmodus und den Prozessprofilmodus ist fälschlicherweise erlaubt.
* **NVSHAS-9608**: Der Scanner meldet keinen Fehler, wenn der Controller einen Fehler für riesige Scanergebnisse ~23MB meldet.
* **NVSHAS-9534**: Fehler in den Zulassungsprüfungen anzeigen.
* **NVSHAS-9600**: Das Deaktivieren des Debuggings des Controllers ist nicht möglich.
* **NVSHAS-9631**: Einige Laufzeitfehler reduzieren.
* **NVSHAS-9645**: Die vorhandene CRD-Verarbeitung schlägt fehl.
* **NVSHAS-9592**: Kein neuer Scan trotz der neuen Version der Datenbank.
* **NVSHAS-9212**: Die Warnmeldung in GET(/v1/eula) anzeigen, wenn die Rolle von neuvector-binding-secret (binding) falsch ist.
* **NVSHAS-9367**: Die Fehlermeldungen verbessern, wenn das Register nicht verbunden werden kann.
* **NVSHAS-9475**: Der Druck des Hintergrundrasters deckt nicht vollständig ab, wenn das Menü minimiert ist.
* **NVSHAS-9485**: Message incorrect pour 'Mode de Politique de Sécurité Réseau' dans l'interface utilisateur.
* **NVSHAS-9480**: Die auf dem Cluster unter Rancher bereitgestellte NV-Benutzeroberfläche gibt HTTP/403 zurück, nachdem die Verbindung zu Rancher getrennt wurde.
* **NVSHAS-9547**: Die Sortierung ist auf der Sicherheitsrisiko-Tabelle --> Schwachstellen kaputt.
* **NVSHAS-9570**: [Schwachstellen] Die Beschreibung der Legende für verschiedene Status bei den Assets ändern.
* **NVSHAS-9561**: Der Gesamtsicherheitswert des Dashboards sollte mit dem tatsächlichen Wert übereinstimmen.
* **NVSHAS-9572**: [Schwachstellen] Die gefilterten Daten wurden unabhängig von der Benutzeraktualisierung oder der erneuten Verbindung auf der Seite beibehalten.
* **NVSHAS-9597**: Die Benutzeroberfläche reagiert nicht auf Fehler, wenn der Controller 403 für POST(v1/group) zurückgibt.
* **NVSHAS-8682**: Der CRD-Webhooks-Dienst muss vom Helm-Diagramm crd in das Helm-Diagramm der Anwendung verschoben werden.

==== Problèmes connus

* In der Version 2.8.3 des Grafiks haben wir eine zuvor falsch zugewiesene Ressource von den CRDs zum Kern verschoben. Wenn Sie sowohl die CRD- als auch die Kern-Grafiken verwenden, könnten Sie beim Upgrade auf Probleme stoßen, wenn Sie zuerst den Kern bereitstellen. Um dies zu lösen, aktualisieren Sie zuerst die CRDs und dann die Kern-Grafiken.

=== 5.4 September 2024

* **Améliorations de l'interface utilisateur**: 
** SSO-Benutzer von Rancher anzeigen.
** JWT-Token verwalten.
** Navigation d'image améliorée et liens vers les résultats de scan.
* **Améliorations de la sécurité**: 
** Nouveaux filtres de conformité.
** Unterstützung für CIS-Benchmarks und OCI-Image-Signaturen.
* **Réseau & Surveillance**: 
** Erweiterte Überwachung der Bandbreite und der Sitzungen.
** DDoS-Überwachung.
** Unterstützung für das Multus-Netzwerk.
* **Zertifikatsverwaltung**: 
** Neue Benachrichtigungen für ablaufende interne Zertifikate, einschließlich Rotationsmöglichkeiten.
* **Automatisierung & Integration**: 
** Automatisation de la fédération.
** Intégration RBAC de Rancher.
** Verbesserung der Zugriffssteuerung.
* **Performance & Efficacité**: 
** Réduction de l'utilisation de la mémoire.
** Reduzierung der ISP-Datengebühren.
** Anzeige der Cache-Statistiken des Scanners.
* **Améliorations de l'Utilisabilité**: 
** Unterstützung für das Startpasswort.
** Archivierung von Cloud-Abrechnungsdaten.
** Durchsetzung der Namensraumgrenzen.

==== Nouvelles fonctionnalités

* **NVSHAS-9012**: Anzeige der SSO Rancher-Benutzer in der NV-Oberfläche mit demselben Benutzernamen.
* **NVSHAS-8939**: Bereitstellung einer Option in der NV-Oberfläche, damit SSO Rancher-Sitzungsbenutzer das aktuelle JWT-Token (d.h. sich abmelden) löschen können.
* **NVSHAS-7522**: Einfache Navigation durch die Bilder in den Registern.
* **NVSHAS-8148**: Lien de l'image du conteneur aux résultats de scan d'image du registre.
* **NVSHAS-9258**: Hinzufügen einer neuen Benachrichtigung für ablaufende Zertifikate und interne Zertifikate.
* **NVSHAS-8915**: Support pour de nouveaux filtres de conformité et rapport de conformité.
* **NVSHAS-9403**: Filemonitor-UI: Permettre à l'utilisateur de supprimer une règle de surveillance de fichier prédéfinie.
* **NVSHAS-8423**: Erkennung der Bandbreite auf Gruppenebene, der Anzahl aktiver Sitzungen und der Verletzung der Sitzungsrate basierend auf den konfigurierten Schwellenwerten.
* **NVSHAS-9218**: Support pour les groupes fédéraux et CRD pour la surveillance DDoS.
* **NVSHAS-8461**: Unterstützung für CIS-Benchmarks für verwaltete k8s-Dienste in der Cloud.
* **NVSHAS-7664**: Réduire les frais de données des fournisseurs de services Internet lors de l'analyse du registre.
* **NVSHAS-8868**: Anzeige der Cache-Statistiken des Scanners.
* **NVSHAS-8676**: Verbesserung von NV Protect für Benchmark-Skripte.
* **NVSHAS-9255**: Anpassung der Suchregister für die Zulassungssteuerung für Bildnamen ohne FQDN.
* **NVSHAS-9144**: Hinzugefügte ID für die Schwachstellenkontrolldatei zur einfachen Identifizierung.
* **NVSHAS-7687**: Unterstützung der Konfiguration des Protokollierungsniveaus (Debug/Fehler/Info/Warnung) für den Executor und den Controller über die Befehlszeilenschnittstelle.
* **NVSHAS-7518**: Ändern der internen Zertifikate für die Komponenten {product-name}.
* **NVSHAS-9287**: Aktivierung der Rotation interner Zertifikate.
* **NVSHAS-8562**: Hinzufügen einer Benachrichtigung über das Ablaufen interner Zertifikate.
* **NVSHAS-8486**: Support de l'interface réseau Multus.
* **NVSHAS-7447**: RBAC Rancher-Integration mit {product-name}.
* **NVSHAS-7822**: Automatisation de la fédération sans appels API de script.
* **NVSHAS-8799**: Créer un cadre de conformité pour importer des modèles de conformité.
* **NVSHAS-8773**: Unterstützung des Startpassworts während der Erstbereitstellung.
* **NVSHAS-6740**: Amélioration du profil de référence à zéro dérive en appliquant la liste apprise en mode protection.
* **NVSHAS-8325**: Faire respecter la limite de l'espace de noms du conteneur pour la règle réseau.
* **NVSHAS-8723**: Archivierung von Cloud-Abrechnungsdaten.
* **NVSHAS-9086**: Reduzierung des Speicherverbrauchs des Controller-Prozesses durch Eliminierung der Datenstruktur vulTrait.
* **NVSHAS-6979**: Capacité d'inclure le commentaire de la règle de réponse dans le contenu de l'alerte.
* **NVSHAS-8845**: Erstellen eines API-Schlüssels mit der Rolle FedReader und FedAdmin.
* **NVSHAS-9306**: Die Bewertung der Konfiguration der Zulassungssteuerung zeigt die Regel-ID, die für genehmigte oder abgelehnte Bereitstellungen verantwortlich ist.
* **NVSHAS-9078**: Unterstützung der Bildsignatur für OCI-Bilder.
* **NVSHAS-7945**: Prise en charge de la référence STIG DISA pour Kubernetes.
* **NVSHAS-8234**: Zulassungssteuerungslogik, die Bilder zulässt, die abgelehnt werden sollten.

==== Fehlerbehebungen

* **NVSHAS-9005**: TypeError in den Registern: Impossible de lire les propriétés de non défini (lecture de 'total_records').
* **NVSHAS-9085**: Der PDF-Bericht der Asset-Ansicht zeigt 0 % Verwundbarkeit, selbst wenn Verwundbarkeiten vorhanden sind.
* **NVSHAS-9084**: Der PDF-Bericht der Asset-Ansicht zeigt NaN, wenn die Liste der Images leer ist.
* **NVSHAS-9128**: Événements de sécurité : Der Container kann nicht angezeigt werden, wenn kein Wert für den Namespace der Arbeitslast vorhanden ist.
* **NVSHAS-9025**: Akzeptanzbereich der Neuvector-Verwundbarkeiten für Container.
* **NVSHAS-9155**: Falscher Spaltenname und fehlender Dateiname beim Analysieren des Image-Registers.
* **NVSHAS-9122**: Die Hauptprotokolle von Neuvector trennen sich jedes Mal, wenn "Mehrere Cluster" mit der SSO-Rancher-Verbindung verwendet wird.
* **NVSHAS-9266**: Analyse des Registers: Die Schaltfläche Bericht zur Analyse nach Schicht sollte ausgeblendet oder deaktiviert werden, wenn keine Verwundbarkeit vorhanden ist.
* **NVSHAS-9219**: Benutzern erlauben, die Zertifikatsvalidierung des Servers für Authentifizierungsserver zu aktivieren.
* **NVSHAS-9246**: Die Filterung für den CSV/PDF-Export funktioniert nicht.
* **NVSHAS-8947**: Kann die NV-Konfiguration nicht importieren, wenn die Authentifizierung über Rancher SSO erfolgt.
* **NVSHAS-9282**: UI: L'édition de l'entrée du registre OpenShift échoue en raison d'un jeton manquant.
* **NVSHAS-9098**: Verbessern Sie die Benutzererfahrung beim Laden der Risikoseite.
* **NVSHAS-9267**: Die Benutzeroberfläche auf dem Hauptcluster 5.4 darf nicht auf verwaltete Cluster vor 5.4 wechseln, aufgrund von Änderungen an der REST-API.
* **NVSHAS-9285**: UI : Der Dropdown-Button überlappt andere Elemente.
* **NVSHAS-9302** : Es ist nicht möglich, einen APIKEY mit der Rolle FedReader und FedAdmin zu erstellen.
* **NVSHAS-8539** : Die Neukonfiguration der Proxy-Einstellungen verliert das Passwort.
* **NVSHAS-9293** : Suppression des détails d'image non liés dans les rapports de vulnérabilité.
* **NVSHAS-9238** : L'interface utilisateur ne rafraîchit pas le nom du cluster affiché après qu'il a été changé.
* **NVSHAS-9363** : Benachrichtigungseinstellungen > Das Gitter der Webhooks ist nicht richtig ausgerichtet.
* **NVSHAS-9362** : Le filtre des vulnérabilités de risque de sécurité ne renvoie aucun résultat.
* **NVSHAS-8699** : Es ist nicht möglich, den Benutzer zu unterscheiden, wenn der AD-Benutzer von Rancher derselbe ist.
* **NVSHAS-9062** : Anzeigen der SSO-Benutzer von Rancher in der NV-Benutzeroberfläche mit demselben Benutzernamen (Konvertierung auf dem Controller).
* **NVSHAS-9071** : Einige Module werden nur in der Containeranalyse gemeldet.
* **NVSHAS-8242**: gRPC-Aufruf zum Testen, ob der Controller die kritische Schwere verwaltet.
* **NVSHAS-8908**: Den X-Forwarded-Port unter Berücksichtigung des Komma-Trennzeichens korrekt analysieren.
* **NVSHAS-9024**: Riskante Rolle der Admission Control Performance.
* **NVSHAS-9091**: Es ist nicht möglich, alle Module unter ol:9.1, photon:5.0, rhel:9.1 und amzn:2023 im Repository, im Registry und in der autonomen Analyse zu melden.
* **NVSHAS-8997**: Die Anzahl der Richtlinien-Slots pro Knoten erheblich reduzieren, um die Leistung zu verbessern.
* **NVSHAS-9059**: CRD-Gruppen sind in NV sichtbar, selbst nach der Löschung von K8s.
* **NVSHAS-9107**: Crash de goroutine à rest.handlerConfigLocalCluster.
* **NVSHAS-9108**: Der Port 18500 sollte nicht geöffnet sein.
* **NVSHAS-9119**: Crash de goroutine à probe.(*FileNotificationCtr).AddContainer().
* **NVSHAS-9125**: Ein CRD-Eintrag mit ungültigen Parametern sollte nicht erstellt werden dürfen.
* **NVSHAS-9124**: Docker: Viele unerwartete Vorfälle bei der Statusüberprüfung werden gemeldet.
* **NVSHAS-9111** : NV muss `--event-qps > 0` überprüfen.
* **NVSHAS-9130** : Unerwartete Vorfälle von Container.Package.Updated werden nach dem Start eines bestimmten Containers gefunden.
* **NVSHAS-9080** : Der Benutzer des Fed-Laufwerks kann auf bestimmte REST-APIs nicht zugreifen.
* **NVSHAS-9092** : Der Benutzer-Namespace sollte keine globalen Ressourcen sehen.
* **NVSHAS-9116** : Der Arbeitscluster kann abfahren, wenn die Verbindung unterbrochen wird.
* **NVSHAS-8980** : Obtenez l'hôte et l'interface de tunnel sur le nœud avec succès dans oc 4.15.
* **NVSHAS-9188** : Définir l'interface mgmt-br comme interface hôte pour le nœud de récolteur.
* **NVSHAS-4858** : Entwickeln Sie die Containergruppe im Controller nicht weiter, um die Bereitstellungsleistung der Strategie zu verbessern und die CPU- und Speicherauslastung zu reduzieren.
* **NVSHAS-8700** : Der AD-Benutzer von Rancher kann sich manchmal nicht bei {product-name} anmelden.
* **NVSHAS-9121** : Le paramètre de seuil de surveillance du réseau du groupe ne peut pas être modifié.
* **NVSHAS-9189**: Le scan se bloquera dans la planification après que le contrôleur soit arrêté et redémarré.
* **NVSHAS-9019**: Den nicht synchronisierten Linkstatus für die Hostschnittstelle beheben.
* **NVSHAS-8305**: Das integrierte Zertifikat entfernen.
* **NVSHAS-9013**: BPF-Filter vom Prozessmonitor entfernen.
* **NVSHAS-7853**: EOF des TLS-Handschlags.
* **NVSHAS-9290**: Die vom Benutzer hinzugefügte Prozessprofilregel hat keine Wirkung, wenn ZD aktiviert ist.
* **NVSHAS-9301**: NV, das auf Rancher Prime bereitgestellt wird, kann seinen Rancher-Geschmack nicht anzeigen.
* **NVSHAS-9289**: Upgrade erlauben, wenn RBAC fehlt.
* **NVSHAS-7601**: Die Wiederherstellung aus der PV-Konfigurationssicherung während der Szenarien verbessern.
* **NVSHAS-7687**: Fügen Sie den Syslog-Protokollierungsebene-Parameter hinzu, um ihn durchzusetzen.
* **NVSHAS-9292**: Korrigieren Sie die Ingress Egress-Exposition, die 0 Schwachstellen zeigt.
* **NVSHAS-9270**: Supporter k3s pour le pipeline de référence CIS.
* **NVSHAS-9338**: Alerte 'Cluster géré [id] est déconnecté du principal'.
* **NVSHAS-9358**: Die Bildanalyse mit einem Proxy würde fehlschlagen.
* **NVSHAS-9337**: Senden Sie eine Protokollnachricht, wenn der SYN-Flood-Angriff erkannt wird.
* **NVSHAS-9209**: Löschen Sie den Domain-Cache, wenn der Namespace aus k8s entfernt wird.
* **NVSHAS-8985**: Les registres fédérés disparaissent après le redémarrage du contrôleur.

==== Problème connu:

* **NVSHAS-9443**: Das Upgrade/Installation über ArgoCD schlägt fehl, da das Objekt leases.coordination.k8s.io nicht erstellt werden kann.
* **Workaround**: Créer les objets de bail donnés avant de mettre à niveau vers 5.4.0 en utilisant ARGO CD. Changez l'espace de noms s'il est différent de neuvector.
+
--
[,bash]
----
cat <<EOF | kubectl apply -f -
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-controller
  namespace: neuvector
spec:
  leaseTransitions: 0
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-cert-upgrader
  namespace: neuvector
spec:
  leaseTransitions: 0
EOF
----
--

=== 5.3.4 Juli 2024

==== Fehlerbehebungen

* Die Schnittstellen `host` und `tunnel` wurden erfolgreich mit OpenShift CLI v4.15 abgerufen.
* Der IP-Bereich 169.254.x.x ist von den Host-Interface-IPs ausgeschlossen.
* Réexaminez l'interface hôte après 1 minute de démarrage de l'enforcer.
* Correction d'un problème où l'URL du fournisseur OpenID échouait à cause de la regex.
* Behebt die folgenden CVEs:
+
|===
| CVE | S'applique à | Auswirkungen

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.2.4-s5 Juli 2024

* Behebt die folgenden CVEs:

|===
| CVE | S'applique à | Auswirkungen

| CVE-2023-42363
| busybox
| {CVE-medium}

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2023-42366
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4603
| openssl
| {CVE-medium}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.3.3 Juni 2024

==== Améliorations

* Ermöglicht Benutzern, die Verwendung bestimmter Speicherklassen von der Seite `Admission Controls` zu blockieren.
* Die `LDAP Authentication` hat separate Felder für die Konfiguration `baseDN` und `groupDN`.
* Die `Egress and Ingress chart` hat eine neue Sicherheitsanfälligkeitsspalte, die die Anzahl der Sicherheitsanfälligkeiten `High` und `Medium` für jeden Dienst enthält.

==== Fehlerbehebungen

* Behebung eines Fehlers im Zusammenhang mit `regex` bei der Verwendung eines Kommas (`,`) in einem Multi-`Admission Control user criteria`-Eintrag.
* Behebung eines Fehlers, bei dem der CVE-Scan der Pakete `jar` nicht alle von demselben CVE betroffenen Pakete anzeigte. Jetzt werden alle Vorkommen gemeldet.
* Behebt die folgenden CVEs:

|===
| CVE | S'applique à | Auswirkungen

| CVE-2024-35195
| python:requests
| {CVE-medium}

| CVE-2024-21011
| openjdk11
| {CVE-low}

| CVE-2024-21012
| openjdk11
| {CVE-low}

| CVE-2024-21068
| openjdk11
| {CVE-low}

| CVE-2024-21085
| openjdk11
| {CVE-low}

| CVE-2024-21094
| openjdk11
| {CVE-low}
|===

==== Sonstiges

* Benutzern ermöglichen, Ressourcen für `updater-cron-job` bei der Installation von {product-name} mit dem Helm-Diagramm festzulegen.
* Versionnage du conteneur de l'exportateur Prometheus révisé et dissocié du versionnage de `controller`.
* (Scanner) Paket/Modul `R` in Ubuntu und Red Hat Enterprise Linux erkennen.
* (Scanner) Unterstützung für den PHP Composer-Scan hinzugefügt.

=== 5.2.4-s3 April 2024

* Behebt die folgenden CVEs:

|===
| CVE | S'applique à | Auswirkungen

| CVE-2021-40633
| giflib
| {CVE-high}

| CVE-2023-48161
| giflib
| {CVE-high}

| CVE-2024-28757
| Expat
| {CVE-high}

| CVE-2023-39742
| giflib
| {CVE-medium}

| CVE-2023-45288
| go:golang.org/x/net
| {CVE-medium}

| CVE-2024-25629
| c-ares
| {CVE-medium}

| CVE-2024-3651
| python:idna
| {CVE-medium}

| CVE-2024-2511
| openssl
| {CVE-low}
|===

=== 5.3.2 April 2024

==== Fehlerbehebungen

* Nach dem Upgrade auf v5.3.1 von einer vorherigen Version {product-name} können vorhandene benutzerdefinierte NvClusterSecurityRule-Ressourcen versehentlich gelöscht werden. HINWEIS: Die Version 5.3.1 wurde aus dem Docker Hub entfernt, um das Upgrade-Problem zu verhindern.

=== 5.3.1 April 2024

[IMPORTANT]
====
Die Version 5.3.1 wurde aus dem Docker Hub entfernt, um das Upgrade-Problem zu verhindern, das in 5.3.2 behoben wurde. Veuillez utiliser la version 5.3.2.
====

==== Améliorations

* Benutzern erlauben, '\`accepted\`' Schwachstellen bei der Verwendung von Github-Aktionen festzulegen, damit sie die Workflows nicht beeinträchtigen.
* Schweregrad-, Punktzahl- und Bewertungsfilter zu Assets > Registry > Bildschwachstellenansicht hinzufügen.
* Erlauben, bei der Konfiguration eines Registrys anzugeben, ob der definierte Proxy für die Bildanalysen des Registrys verwendet werden soll.

==== Fehlerbehebungen

* Sicherheitsrisiken > Schwachstellen > Der erweiterte Filter filtert 'CVE ohne Fix' nicht.
* Unerwartete Container-zu-Container-Verletzung im Host-Modus
* Das OCI-Bildformat beim Wechsel zur Docker-API 1.24 akzeptieren.
* Die Registrierungsanalyse sollte keine Nicht-Bild-Artefakte analysieren / keine Fehler protokollieren.
* Ermöglichen Sie die Überprüfung der Bildsignatur von Schlüsselpaaren ohne Root ohne Internet- oder sigstore-Abhängigkeit.
* Nicht autorisierte Sicherheitsereignisse durch Netzwerkregeln in einem bestimmten Knoten (verbunden mit den Fehlermeldungen "Container Task chan full").
* Der Container kann nicht erfolgreich zur Aufgabe hinzugefügt werden (häufige Vorkommen). Resultierend aus einer Blockade der Kanalnachrichten.

==== Sonstiges

* Aktualisieren Sie die Scanner-Plugins für Jenkins, die GitHub-Aktion und Bamboo.
* (Scanner) Akzeptieren Sie das OCI-Bildformat beim Wechsel zur Docker-API 1.24.
* (Scanner) Der Registryscan sollte keine Nicht-Image-Artefakte scannen / keine Fehler protokollieren.
* (Scanner) Unterstützung für die Analyse von PHP Composer hinzufügen.

==== {product-name} UI-Erweiterung v. 1.0 für Rancher Mars 2024

* Nach der Installation von {product-name} wird die xref:rancher.adoc#_suse_security_ui_extension_for_rancher[Aktivierung/Installation] der UI-Erweiterung {product-name} von Rancher ein Dashboard für den Cluster anzeigen, einschließlich Links zu SSO zum vollständigen Cluster {product-name}. HINWEIS: Die Erweiterung kann als Drittanbieter angezeigt werden, was in einer zukünftigen Version behoben wird. Darüber hinaus können Benutzer von Rancher 2.7.x nach der Installation zwei Symbole {product-name} UI Ext in der Liste sehen (Fehler). Ein Symbol zeigt Deinstallieren an (was bedeutet, dass es installiert ist), und das andere sollte Installieren sagen. Dies kann so bleiben, das heißt, nicht erneut installieren, wenn die Erweiterung bereits installiert ist.

=== 5.2.4-s2 Février 2024

* Behebt die folgenden CVEs:
* Hohe CVE: CVE-2023-52425 in Expat, CVE-2024-20952 und CVE-2024-20918 in OpenJDK11
* Mittlere CVE: CVE-2023-52426 in Expat, CVE-2024-20926, CVE-2024-20921, CVE-2024-20945 und CVE-2024-20919 in OpenJDK11, CVE-2024-0727 und CVE-2023-6237 in OpenSSL

=== 5.3.0 Februar 2024

==== Améliorations

* Externe Ziel-URLs (FQDN) im Dashboard (Egress), in PDF- und CSV-Berichten sowie im Netzwerkaktivitätsbildschirm und in den Sicherheitsereignislisten (Verstöße) anzeigen.
* Im Entdeckungsmodus automatisch Ausgaben an externe FQDN-Gruppen lernen. Eine neue benutzerdefinierte externe FQDN-Gruppe wird erstellt, es sei denn, die externe Verbindung entspricht einer bestehenden Regel.
* Aktivieren Sie das ICMP-Lernen (Entdeckungsmodus) und die Blockierung (Schutzmodus) über die neue Umgebungsvariable des Controllers CTRL_EN_ICMP_POLICY = 1
* Exportieren Sie die CRDs nach Github, um gitops zu einem Standard-Repository über die Konsole oder die REST-API zu unterstützen.
* Unterstützen Sie die SAML SSO-Einmalanmeldung mit ADFS iDP
* Fügen Sie die Unterstützung für die ARM64-Plattform hinzu. Das Abrufen von ARM-basierten Plattformen zieht automatisch die entsprechenden ARM64-Bilder {product-name} an.
* Unterstützen Sie Webhooks über einen Proxy
* Verbessern Sie die Audit-Funktion der Zulassungssteuerung, um die Ergebnisse aller Regeln einzuschließen. Listen Sie das Ergebnis jeder Regel auf und fügen Sie einen weiteren Eintrag für die endgültige Aktion hinzu, die ausgeführt wird, wenn sie in einer Live-Zulassungssteuerungsbereitstellung bewertet wird.
* Wenden Sie deaktivierte Zulassungsregeln über CRD oder yaml (kubectl) an
* Exportieren/Importieren des Schwachstellenprofils über die Konsole, CRD oder REST-API. Der Import ersetzt das vorhandene Profil. Das Löschen des CRD führt zu einem leeren Profil.
* Exportieren/Importieren des Compliance-Profilmodells über die Konsole, CRD oder REST-API. Der Import ersetzt das vorhandene Modell.
* Fügen Sie einen Status 'Manuell' in den Compliance-Berichten für die CIS-Benchmarks hinzu, die manuell von den Benutzern ausgeführt werden müssen (nicht ausgeführt von {product-name}).
* Améliorer le chargement/performance de l'interface utilisateur de la page des vulnérabilités
* Vereinheitlichen Sie die Browsersitzungsverbindung. Damit teilen sich alle Tabs im Browser dieselbe Anmeldesitzung, das Öffnen eines neuen Tabs aus einer bestehenden Sitzung erfordert keine Anmeldeinformationen, und wenn sich ein Tab abmeldet, melden sich alle Tabs ab.
* Améliorations de la sécurité de la console (UI) : 1) Fügen Sie erforderliche Sicherheitsheader hinzu (X-Content-Type-Options nosniff; X-XSS-Protection 1; mode=block; X-Frame-Options SAMEORIGIN; Cache-Control privat, no-cache, no-store, must-revalidate
HTTP Strict Transport Security max-age=15724800, 2) Fügen Sie einen CSP-Header hinzu (z. B. eine Richtlinie '\`default-src\`' festlegen), 3) Entfernen Sie die Offenlegung des Servernamens
* Unterstützung für neuere Versionen der CIS-Benchmarks. Kubernetes (1.8.0), Kubernetes V1.24 (1.0.0), Kubernetes V1.23 (1.0.1), RedHat OpenShift Container Platform (1.4.0)
* Anzeigen in den Assets -> Container -> Details der Container, die in den Registern im Vergleich zur Ausführung analysiert wurden
* Einen Link zur Gruppe in den Sicherheitsrisiken -> Schwachstellen -> Popup-Auswirkungen hinzufügen, um den Gruppenmodus einfach zu ändern
* Unterstützung für Deep Links in URLs zur Seite der Schwachstelle von Bildern und/oder Containern
* Eine Passwort-Reset-Option für den Administrator hinzufügen, um das Passwort des Benutzers in den Konsoleneinstellungen -> Benutzer zurückzusetzen
* Das Senden von Ereignisprotokollen an die Protokolle des Pod-Controllers in den Einstellungen -> Konfiguration -> Benachrichtigung erlauben. Die gesendeten Ereignisse beginnen mit 'notification=' und werden nur im führenden Pod-Controller protokolliert. Bitte beachten Sie, dass es einen Fehler in dieser Version gibt, bei dem SYSLOG aktiviert sein muss, um das Ereignisniveau zu ändern (und nach der Änderung des Niveaus deaktiviert werden kann, wenn gewünscht).
* Die Anforderung für den Controller/Enforcer, "/host/cgroup" zu mounten, entfernen.
* Das Menü Hilfe erhalten hinzufügen mit Links zu Slack, der Dokumentation und anderen Ressourcen
* Das Nachrichtenfeld für /v1/log/activity logs ausfüllen

==== Fehlerbehebungen

* Interner Serverfehler in den Sicherheitsrisiken -> Schwachstellen mit einer großen Anzahl von CVEs
* SIGSEGV: Segmentierungsfehler im Controller
* Das Löschen von verwundbaren Dateien (z. B. jar) entfernt sie nicht aus der Liste der Schwachstellen
* Ungültiges Syslog-Zertifikat mit dem Signaturalgorithmus SHA256withECDSA
* {product-name} montre les événements de sécurité qui devraient être autorisés par une règle réseau
* Nicht verwalteter Knoten mit einem "Zombie"-Enforcer, der läuft
* Der erweiterte Filter zeigt leere Felder für Behebung und Auswirkungen an
* Corriger la gestion des chaînes pour éviter un redémarrage inattendu de l'enforcer
* Unerwartete Verstöße bezüglich integrierter Gruppen
* Appel RPC de débogage de l'enforcer de bundle de support pour les données renvoie une erreur
* Le groupe ne correspond pas dans les événements de sécurité
* Das Senden von Ereignissen an Slack funktioniert nicht - mit Proxy
* Affichage des événements de sécurité pour les règles réseau autorisées

==== Sonstiges

* Automatische Erkennung der Containerlaufzeit (Socket) zur Ausführung im Helm-Diagramm hinzufügen
* Parameter zum Ausführen des Controllers im privilegierten Modus im Helm-Diagramm entfernen und die Anforderung für den Controller/Enforcer, "/host/cgroup" zu mounten.
* Beispieldateien für die Kubernetes-Bereitstellung wurden aus den Dokumenten {product-name} entfernt. Bitte beziehen Sie sich auf den Link für Beispiele.

==== Hervorgehobene Änderungen, die möglicherweise Änderungen für manuelle Bereitstellungen erfordern (alle Änderungen sind bereits im letzten Helm-Diagramm für 5.3.x reflektiert)

* Die automatische Erkennung der Containerlaufzeit (Socket) beseitigt die Notwendigkeit, die Containerlaufzeit und den Socket-Pfad anzugeben.
* Die Entfernung der Anforderung, den Controller im privilegierten Modus auszuführen, beseitigt die Notwendigkeit, den Ausführungssocket zu mounten und /host/cgroup/ zu mounten.
* Hinzufügen von Rolle/Rollenbindung für neuvector-binding-secret sowie neuvector-secret in yaml.
* Neue Dienstkonten und erforderliche Rollenbindungen für 5.3
* Tous les fichiers yaml de déploiement référencés ont maintenant /5.3.0/ dans leurs chemins

=== 5.2.4-s1 Januar 2024

==== Publication de correctif de sécurité

* Remédie à CVE-2023-6129 dans openssl, et CVE-2023-46219, CVE-2023-46218 dans curl.

=== 5.2.4 November 2023

==== Fehlerbehebungen

* Änderungen an Azure AKS ValidatingWebhookConfiguration und Fehlerprotokollierung.

=== 5.2.3 November 2023

==== Améliorations

* Fügen Sie die Unterstützung für die NVD 2.0 API in den Scanner hinzu.
* Analysieren Sie den Host des Containers im autonomen Modus des Scanners.

[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n
----

==== Fehlerbehebungen

* L'analyse sur un nœud échoue en raison d'un problème de blocage de docker cp / grpc.

=== 5.2.2-s1 Oktober 2023

==== Sicherheitsupdate

* Aktualisieren Sie die Pakete, um die CVEs zu beheben, einschließlich CVE-2023-38545 und CVE-2023-43804.

=== 5.2.2 Oktober 2023

==== Avis de sécurité pour CVE-2023-32188

* Beheben Sie CVE-2023-32188 "\`JWT-Token-Kompromittierung kann böswillige Aktionen einschließlich Remote Code Execution (RCE)\`" durch automatisches Generieren des Zertifikats, das zum Signieren des JWT-Tokens während der Bereitstellung und Aktualisierung verwendet wird, und durch automatisches Generieren des Zertifikats für Manager/RESTful API während der Bereitstellungen basierend auf Helm.
 ** Das Zertifikat für die JWT-Signatur wird automatisch vom Controller mit einer Gültigkeit von 90 Tagen erstellt und automatisch rotiert.
 ** Die automatische Generierung des Manager-Zertifikats, der REST API und des Registry-Adapters erfordert die Verwendung einer Helm-basierten Installation mit {product-name} der Version helm 2.6.3 oder höher.
 ** Das integrierte Zertifikat wird immer für Bereitstellungen basierend auf yaml verwendet, es sei denn, es wird während der Bereitstellung ersetzt; es wird jedoch empfohlen, diese zu ersetzen (siehe die folgende Zeile).
 ** Der xref:replacecert.adoc[manuelle Zertifikatsersatz] wird immer unterstützt und für frühere Versionen oder Bereitstellungen basierend auf yaml empfohlen. Siehe das {product-name} Sicherheitswarnung GitHub https://github.com/neuvector/neuvector/security/advisories/GHSA-622h-h2p8-743x[hier] für eine Beschreibung.
 ** Die Verwendung von benutzerdefinierten Zertifikaten wird wie zuvor für Bereitstellungen basierend auf Helm und yaml weiterhin unterstützt.
* Fügen Sie zusätzliche Kontrollen für benutzerdefinierte Compliance-Skripte hinzu. Standardmäßig dürfen benutzerdefinierte Skripte jetzt nicht hinzugefügt werden, es sei denn, die Umgebungsvariable CUSTOM_CHECK_CONTROL wird dem Controller und dem Enforcer hinzugefügt. Die Werte sind "deaktivieren" (standardmäßig nicht erlaubt), "streng" (nur Admin-Rolle) oder "liberal" (Admin-, Compliance- und Ausführungsrichtlinienrollen).
* Verhindern Sie LDAP-Injection - das Benutzernamefeld wird escaped.

==== Améliorations

* Fügen Sie zusätzliche Scan-Daten zu den von SYSLOG gesendeten CVE-Ergebnissen für Schichtscans hinzu
* Unterstützung der NVD-API 2.0 für die CVE-Scan-Datenbank
* Das Baudatum des Container-Images in den Asset-Details -> Container angeben
* Die Sortierung für Netzwerkregeln anpassen: Sortierung in der Ansicht der Netzwerkregeln deaktivieren, aber die Sortierung der Netzwerkregeln in der Gruppenansicht aktivieren.
* Aktivieren/deaktivieren Sie die Erkennung/Alarmierung von TLS 1.0 und TLS 1.1 mit Umgebungsvariablen für den Enforcer THRT_SSL_TLS_1DOT0, THRT_SSL_TLS_1DOT1. Standardmäßig deaktiviert.
* Fügen Sie die Umgebungsvariable AUTO_PROFILE_COLLECT für den Controller und den Enforcer hinzu, um die Speichernutzung bei der Überprüfung von Speicherereignissen zu erfassen. Setzen Sie den Wert = 1, um zu aktivieren.
* Die Konfigurationsbewertungen im Vergleich zur Zulassungskontrolle sollten alle Verstöße mit einem einzigen Scan anzeigen.
* Fügen Sie weitere Optionen für die CVE-Berichtskriterien in den Antwortregeln hinzu. Beispiel 1 - "cve-high-with-fix:X" bedeutet: Wenn die Anzahl der (hochgradigen Schwachstellen, die behoben wurden) >= X, die Antwortregel auslösen. Beispiel 2 - "cve-high-with-fix:X/Y" bedeutet: Wenn die Anzahl der (hochgradigen Schwachstellen, die vor Y Tagen gemeldet wurden und behoben wurden) >= X, die Antwortregel auslösen.

==== Fehlerbehebungen

* L'exportation de la stratégie de groupe ne renvoie aucun contenu YAML réel.
* Verbessern Sie das Pruning von Namespaces mit einer speziellen Funktion.
* {product-name} Der Benutzer des Namespaces kann die Assets-->Namespaces nicht sehen
* Ignorieren Sie die Verarbeitung von CRD CREATE/UPDATE-Anfragen, wenn der Namespace des CR bereits gelöscht wurde.
* Bieten Sie eine Workaround-Lösung für einen Teil der CRD-Gruppen an, die nach der Löschung der Namespaces nicht erfolgreich beschnitten werden können.

=== 5.2.1 August 2023

==== Améliorations

* Berichten Sie über die Ergebnisse von überlagerten Scans und zusätzliche CVE-Daten in SYSLOG-Nachrichten. Dies wird durch ein Kontrollkästchen in den Einstellungen -> Konfiguration -> SYSLOG aktiviert.
* Exportieren Sie die NIST 800-53-Zuordnungen (zu den CIS-Docker-Benchmarks) in den exportierten CSV-Konformitätsbericht.
* Unterstützen Sie die Proxy-Einstellung bei der Überprüfung der Bildsignatur.
* Inclure le résultat du scan de signature d'image dans le rapport CVE téléchargé.
* Unterstützen Sie Pod-Anmerkungen für die Zulassungspolitiken, die über benutzerdefinierte Kriterien verfügbar sind.
* Fügen Sie das Feld Letzte Änderung hinzu, um den Druck von Schwachstellenberichten zu filtern, sowie den erweiterten Filter in der Schwachstellensicht.

==== Fehlerbehebungen

* Erstellen Sie keinen Standardadministrator mit einem Standardpasswort in der anfänglichen Bereitstellung {product-name} für das AWS-Abrechnungsangebot (CSP-Adapter), was erfordert, dass der Benutzer ein Geheimnis verwendet, um einen Benutzernamen und ein Administratorkennwort zu erstellen.
* Corriger le fichier .json qui a augmenté en taille et a fait planter un nœud kubernetes
* Améliorer la logique de détection des injections SQL
* Beim Installieren des Helm-CRD-Diagramms zuerst, bevor das Kern-Diagramm {product-name} installiert wird, fehlen die Dienstkonten.
* Le résultat de conformité de l'analyse d'image I.4.1 est incorrect
* Der erweiterte Filterbericht über Schwachstellen zeigt Bilder aus allen anderen Namensräumen.

=== 5.2.0 Juli 2023

==== Améliorations

* Unterstützung von Tokens für den Zugriff auf die API {product-name}. Siehe Einstellungen -> Benutzer, API-Schlüssel... um einen neuen API-Schlüssel zu erstellen. Die Schlüssel können auf Standard- oder benutzerdefinierte Rollen festgelegt werden.
* Unterstützung der PAYG-Abrechnung im AWS Marketplace für monatliche Support-Abonnements {product-name}. Benutzer können sich für {product-name} über den SUSE-Support anmelden, der monatlich auf ihrem AWS-Konto basierend auf der durchschnittlichen Nutzung der Knotenanzahl des vorherigen Monats abgerechnet wird. Détails https://open-docs.neuvector.com/deploying/awsmarketplace[ici].
* Unterstützung für die Signatur von Bildern für Admission Controls. Benutzer können {product-name} verlangen, um zu überprüfen, dass die Bilder von bestimmten Parteien signiert sind, bevor sie in der Produktionsumgebung bereitgestellt werden können, dank einer Integration mit Sigstore/Cosign. Siehe Assets -> Sigstore-Überprüfer, um neue Signatur-Assets zu erstellen. Regeln können dann mit den Kriterien Bildsignatur und/oder Bild-Sigstore-Überprüfer erstellt werden.
* Aktivieren Sie jede Regel für Admission Controls, um ihren eigenen Überwachungs- oder Schutzmodus zu haben. Eine Ablehnungsaktion im Überwachungsmodus wird alarmieren, und eine Ablehnungsaktion im Schutzmodus wird blockieren. Erlaubte Aktionen sind nicht betroffen.
* Fügen Sie einen neuen Regex-Operator in Policy > Admission Control > Regel hinzufügen für Benutzer und Benutzergruppen hinzu, um Regex zu unterstützen. Unterstützung für die Operatoren "entspricht jedem Regex in" und "entspricht keinem Regex in".
* Ajoutez la prise en charge des critères de contrôle d'admission tels que les limites de ressources. Ein neues Kriterium wird für Ressourcengrenzen hinzugefügt, und zusätzliche Kriterien werden über die benutzerdefinierten Kriterienparameter unterstützt.
* Unterstützung für den Aufruf des {product-name} Scanners von Harbor-Registries über die https://github.com/goharbor/pluggable-scanner-spec[pluggable scanner] Schnittstelle. Dies erfordert die Konfiguration der Verbindung zum Controller (exponierte API). Der Harbor-Adapter ruft den Endpunkt des Controllers auf, um einen Scan auszulösen, der automatisch beim Pushen durchgeführt werden kann. Abfrage-Dienste können für regelmäßige Scans verwendet werden. Die Scan-Ergebnisse der Hauptcontroller der Föderation werden an die entfernten Cluster propagiert.  HINWEIS: Es gibt ein Problem mit dem Fehler des HTTPS-basierten Adapterendpunkts: Bitte ignorieren Sie den Verbindungs-Testfehler, es funktioniert, auch wenn ein Fehler angezeigt wird (Zertifikatsvalidierung ignorieren).
* Abfragbarer SaaS-Dienst für CVE-Suchen. Durchsuchen Sie die neueste {product-name} CVE-Datenbank, um zu sehen, ob ein bestimmtes CVE in der Datenbank vorhanden ist. Dieser Dienst ist für {product-name} Prime-Kunden (kostenpflichtiges Support-Abonnement) verfügbar. Kontaktieren Sie den Support über Ihr SCC-Portal für den Zugriff.
* Erlauben Sie dem Benutzer, den Netzwerkschutz zu deaktivieren, aber WAF/DLP aktiv zu halten. Konfigurieren Sie die Aktivierung der Netzwerkrichtlinie in den Einstellungen -> Konfiguration.
* Verwenden Sie nach Bedarf weniger privilegierte Dienstkonten für jede Komponente {product-name}. Eine Variable "\`leastPrivilege\`" wird eingeführt. Der Standardwert ist falsch. HINWEIS: Die Verwendung des aktuellen Helm-Diagramms mit dieser Variablen in einer Version vor 5.2.0 funktioniert nicht richtig.
* Verknüpfen Sie ein nicht standardmäßiges Dienstkonto, um die CIS-Empfehlung 1.5 5.1.5 zu erfüllen.
* Aktivieren Sie den Administrator, um die standardmäßige Sitzungsablaufzeit des Benutzers in den Einstellungen -> Benutzer, API-Schlüssel und Rollen zu konfigurieren.
* Anpassbare Anmeldebanner und anpassbarer UI-Headertext für regulierte und staatliche Bereitstellungen. Die Anforderungen für die Konfiguration finden Sie xref:customui.adoc[hier].
* SYSLOG-Unterstützung für den verschlüsselten Transport TLS. Wählen Sie TCP/TLS in den Einstellungen -> Konfiguration für SYSLOG aus.
* Aktivieren Sie die Bereitstellung des {product-name} Helm-Diagramms von Monitor über Rancher Manager.
* Entfernen Sie die obere Grenze für die Top-Level-Domain im URL-Validator für den Registryscan.
* Scannen Sie die Golang-Abhängigkeiten, einschließlich Echtzeitscans.
* Unterstützen Sie den Schwachstellenscan für Debian 12 (Bookworm).
* Fügen Sie den CSV-Export für das Register / Details hinzu, um die CVEs für alle Bilder im konfigurierten Register in den Assets -> Registries für ein ausgewähltes Register zu exportieren.
* Erlauben Sie {product-name}, mehrere ADFS-Zertifikate parallel im x.509-Zertifikatfeld festzulegen.
* Fügen Sie das Kommentarfeld für die Antwortregeln hinzu und zeigen Sie es an.
* Geben Sie an, was {product-name} als Systemcontainer über eine Umgebungsvariable betrachtet. Zum Beispiel für Rancher und die Standard-Namensräume: NV_SYSTEM_GROUPS=*cattle-system;default
* Unterstützung für Kubernetes 1.27 und OpenShift 4.12 hinzufügen

==== Fehlerbehebungen

* Réduire les journaux répétitifs dans les journaux de l'enforcer/controller.
* Die Seite für mehrere Cluster wird nicht gerendert.
* Die automatische Löschung der leeren Gruppe dauert 2 Stunden, um gelöscht zu werden, anstatt 1 Stunde gemäß dem Zeitplan.
* Die manuell erlaubte Netzwerkregel wird nicht angewendet und führt zu einem Verstoß für das Pause-Image.
* Blockierung von SSL-Verbindungen, auch wenn eine Netzwerkregel den Verkehr unter bestimmten Anfangsbedingungen erlaubt.
* Sicherheitsereignisse warnen selbst bei erlaubten Netzwerkregeln aufgrund eines Problems mit der Aktualisierung der Richtlinie in der Synchronisation.
* Netzwerkaktivitäten, die fälschlicherweise den Verkehr von benutzerdefinierten Gruppen extern zuordnen.
* Das Standard-Servicekonto-Token des Namensraums, das in jedem Pod gemountet ist, hat zu viele Berechtigungen.
* Trotz der Definition von Netzwerkregeln werden Verstöße unter den Sicherheitsereignissen (falsche Positivmeldungen) protokolliert, wenn der Container aufgrund eines Fehlers bei unzureichendem Speicher (OOM) gestoppt wurde.
* Ermöglichen Sie dem Benutzer, die Erkennung und den Schutz vor nicht verwalteten Containern im Cluster zu deaktivieren/aktivieren. Cela peut être défini via l'interface de ligne de commande du gestionnaire :

[,shell]
----
set system detect_unmanaged_wl status -h
Usage: cli set system detect_unmanaged_wl status [OPTIONS] {true|false}

  Enable/disable detect unmanaged container
----

==== Sonstiges

* Fügen Sie den Parameter "leastPrivilege" im Helm-Diagramm hinzu. Fügen Sie die Helm-Option für New_Service_Profile_Baseline hinzu. Eine neue Version des Helm-Diagramms (Kern) wird für 5.2 veröffentlicht.
* Aktivieren Sie die AWS Marketplace-Integrationsparameter (Abrechnungsadapter) im Helm-Diagramm.
* Aktualisieren Sie das ConfigMap, um neue Funktionen zu unterstützen (mehrere ADFS-Zertifikate, Null-Derivation, New_Service_Profile_Baseline, SYSLOG TLS, Benutzer-Timeout)
* Aktualisieren Sie die unterstützten Kubernetes-Versionen auf 1.19+ und OpenShift 4.6+ (1.19+ mit CRI-O)

=== 5.1.3 Mai 2023

==== Améliorations

* Fügen Sie einen neuen Schwachstellen-Scan für das Microsoft .NET-Framework hinzu.
* Die Statistiken des Enforcers sind standardmäßig im Prometheus-Exporter deaktiviert, um die Skalierbarkeit zu verbessern.
* Amélioration de l'utilisabilité : Verwenden Sie den Scanner, um ein einzelnes Bild zu analysieren und das Ergebnis auszudrucken (siehe Beispiel unten).
* Ajouter une vérification de imagePullPolicy dans les critères des règles de contrôle d'admission.
* Zeigen Sie eine Warnmeldung an, wenn das CRD-Schema veraltet ist.

==== Fehlerbehebungen

* L'écran d'activité du réseau ne s'affiche pas ou s'affiche incorrectement.
* Die automatische Löschung der leeren Gruppe dauert 2 Stunden, um gelöscht zu werden, anstatt 1 Stunde gemäß dem Zeitplan.
* Die Compliance-Kontrolldatei wird nicht in der UI-Konsole angezeigt.
* Le filtre avancé dans les événements de sécurité manque le niveau "Erreur".
* Das Passwort, das ein Sonderzeichen enthält, schlägt bei einem zukünftigen Authentifizierungsversuch fehl.
* Die Seite für mehrere Cluster wird nicht korrekt angezeigt, wenn die Anfragen hoch sind.
* Das Detailfeld des Registers (unten) wird nicht aktualisiert.

==== Sortie d'échantillon du scanner

[,shell]
----
Image: https://registry.hub.docker.comlibrary/alpine:3.4
Base OS: alpine:3.4.6
TOTAL: 6, HIGH: 1, MEDIUM: 5, LOW: 0, UNKNOWN: 0
┌─────────┬───────────────┬──────────┬───────────┬───────────────┬────────────┐
│ PACKAGE │ VULNERABILITY │ SEVERITY │ VERSION   │ FIXED VERSION │ PUBLISHED  │
├─────────┼───────────────┼──────────┼───────────┼───────────────┼────────────┤
│ openssl │ CVE-2018-0732 │ High     │ 1.0.2n-r0 │ 1.0.2o-r1     │ 2018-06-12 │
│         ├───────────────┼──────────┤           ├───────────────┼────────────┤
│         │ CVE-2018-0733 │ Medium   │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0734 │          │           │ 1.0.2q-r0     │ 2018-10-30 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0737 │          │           │ 1.0.2o-r2     │ 2018-04-16 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0739 │          │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-5407 │          │           │ 1.0.2q-r0     │ 2018-11-15 │
└─────────┴───────────────┴──────────┴───────────┴───────────────┴────────────┘
----

=== 5.1.2 März 2023

==== Améliorations

* Unterstützung für die hostbasierte Adressgruppe und die Netzwerk-Schutzregel-Matching-Strategie. Dies ermöglicht einen Anwendungsfall, bei dem zwei verschiedene FQDN-Adressen auf dieselbe IP-Adresse aufgelöst werden, aber unterschiedliche Regeln für jeden FQDN angewendet werden müssen. Eine neue benutzerdefinierte Gruppe mit '\`address=vh:xxx.yyy\`' kann erstellt werden, indem der Schalter '\`vh:\`' verwendet wird, um diesen Schutz zu aktivieren. Eine Netzwerkregel kann dann die benutzerdefinierte Gruppe als Quelle '\`From\`' basierend auf dem virtuellen Hostnamen (anstatt der aufgelösten IP-Adresse) verwenden, um unterschiedliche Regeln für virtuelle Hosts anzuwenden.
* Liste der Compliance-Container zum Ausschließen der ausgegebenen Container.
* Améliorer les règles DLP pour prendre en charge le caractère générique simple dans le modèle.
* Fügen Sie die Unterstützung für cri-o 1.26+ und OpenShift 4.11+ hinzu.
* Gravatar optional machen.
* Ressource des Namensraums des Clusters in der Konsole / UI anzeigen.
* Die Schwere/Klassifizierung der Quelle (z. B. Red Hat, Ubuntu...) mit dem Schweregrad-Score NVD in der Konsole anzeigen.
* Die Deaktivierung von SSO/RBAC für Rancher und OpenShift nicht zulassen, wenn der Benutzer über SSO authentifiziert ist.
* Die Aktivierung des automatischen Scans und die Entfernung von nicht mehr benötigten Gruppen in die configMap hinzufügen.
* Die IP-Adresse für die externe Quelle/Ziel in csv/pdf für implizite Ablehnungsverletzungen einfügen.
* Verschiedene Leistungs- und Skalierbarkeitsoptimierungen für die CPU- und Speicherauslastung des Controllers und des Executors.

==== Fehlerbehebungen

* Die langsame Anwendung auf GKE Container Optimized OS (COS) Knoten im Protect-Modus beheben.
* SUSE Linux (SLES) 15.4 CVE wird im Scanner nicht erkannt. Mit dieser Korrektur wird die Schwachstelle zur Datenbank hinzugefügt, wenn die Schwere im Stream angegeben ist, auch wenn der NVD-Eintrag fehlt. Es ist möglich, dass der Bericht Schwachstellen ohne CVE-Scores enthält.

==== Sonstiges

* Die CRD-Optionen für die Zulassungskontrolle in helm https://github.com/neuvector/neuvector-helm/pull/237. verbessern.
* Neue Umgebungsvariablen für den Executor zum Helm-Diagramm hinzufügen.

=== 5.1.1 Februar 2023

==== Améliorations

* "\`package\`" als Information zum Syslog-Ereignis für eine erkannte Schwachstelle hinzufügen.
* Die Umgebungsvariable des Executors ENF_NETPOLICY_PULL_INTERVAL - Wert in Sekunden (empfohlener Wert 60) hinzufügen, um den Netzwerkverkehr und den resultierenden Ressourcenverbrauch des Executors aufgrund von Updates/Neuberechnungen der Richtlinie zu reduzieren. (Hinweis: Dies war bis August 2023 eine nicht dokumentierte Ergänzung).

[,yaml]
----
           - name: ENF_NETPOLICY_PULL_INTERVAL
             value: "60"   <== regulate the pulling gap by 60 seconds
----

==== Fehlerbehebungen

* Fehler beim Löschen der leeren Gruppe "Objekt nicht gefunden"
* Verkehr innerhalb desselben Containers, der alarmiert/blockiert.
* Unerwartete implizite Verstöße für den Egress-Verkehr von Istio mit vorhandener Berechtigungsregel.
* Beim Upgrade von Version {product-name} 4.x führt eine falsche Pod-Gruppenmitgliedschaft zu einem unerwarteten Richtlinienverstoß.
* Die OIDC-Authentifizierung ist mit ADFS fehlgeschlagen, wenn zusätzliche Kodierungszeichen in der Anfrage erscheinen.
* Utilisation élevée de la mémoire par dp créant et supprimant des pods
* Alpine aktualisieren, um mehrere CVE zu beheben, einschließlich Manager: CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552
* Verschiedene Benutzeroberflächenfehler behoben

==== Sonstiges

* Aktualisiertes Helm-Diagramm, um den Austausch des Zertifikats für interne Kommunikationen zu ermöglichen

=== 5.1.0 Décembre 2022

==== Améliorations

* Base de données de scan centralisée et multi-cluster (CVE). Le cluster principal (maître) peut scanner un registre/repo désigné comme un registre fédéré. Die Scanergebnisse dieser Register werden mit allen verwalteten (entfernten) Clustern synchronisiert. Dies ermöglicht es, die Scanergebnisse in der Konsole des verwalteten Clusters anzuzeigen und die Ergebnisse in den Zulassungsregeln des verwalteten Clusters zu verwenden. Die Register müssen nur einmal gescannt werden, anstatt von jedem Cluster, wodurch die CPU-/Speicher- und Netzwerkbandbreitennutzung reduziert wird.
* Améliorer les règles de contrôle d'admission :
 ** Benutzerdefinierte Kriterien für die Zulassungsregeln. Benutzern ermöglichen, Ressourcen Kriterien für alle mit Pods verbundenen Felder zu definieren und in den Regeln zu verwenden, z.B. item.metadata.annotationsKey enthält 'neuvector', item.metadata.name='xyzzy' usw.
 ** Kriterien hinzufügen, um risikobehaftete RBAC-Parameter für Dienstkonten beim Bereitstellen von Pods zu überprüfen. Dies umfasst die Kriterien 'jede Aktion auf Arbeitslastressourcen', 'jede Aktion auf RBAC', 'Arbeitslastressourcen erstellen', 'Secrets auflisten' und 'in einem Container ausführen'.
 ** Ajouter une comparaison de version sémantique aux modules pour les règles de contrôle d'admission. Dies ermöglicht die Anwendung der Operatoren > oder < auf Versionsnummern in den Regeln (z.B. das Bereitstellen des Moduls curl<6.2.0 nicht zuzulassen). Cela permet des vérifications de version spécifiques sur les paquets installés.
 ** Eine Zulassungsregel für die Sicherheit der Pods (PSA) hinzufügen, die in Kubernetes 1.25+ unterstützt wird.
* Eine neue Umgebungsvariable NO_DEFAULT_ADMIN hinzufügen, die, wenn aktiviert, keinen 'admin'-Benutzer erstellt. Dies wird standardmäßig für die SSO-Integration von Rancher verwendet. Wenn nicht aktiviert, den Benutzer dauerhaft warnen und Ereignisse protokollieren, um das Standard-Admin-Passwort zu ändern, falls es nicht standardmäßig geändert wird.
* Das Sperren der Verbindung nach fehlgeschlagenen Anmeldeversuchen wird nun zur Standardeinstellung. Der Standardwert beträgt 5 Versuche und ist in den Einstellungen -> Benutzer & Rollen-> Passwortprofil konfigurierbar.
* Eine neue Umgebungsvariable zur Leistungsoptimierung ENF_NO_SYSTEM_PROFILES hinzufügen, Wert: "1". Wenn aktiviert, werden die Prozess- und Dateimonitoren deaktiviert. Es wird kein Lernprozess, kein Profilmodus, kein Vorfall von Prozess/Datei (Paket) und keine Überwachung der Dateiaktivität durchgeführt. Dies wird die Nutzung von CPU/RAM-Ressourcen und die Dateioperationen reduzieren.
* Fügen Sie einen benutzerdefinierten Auto-Scaling-Parameter für die Scanner-Pods hinzu, mit den Werten Verzögert, Sofort und Deaktiviert. Wichtig: Das Auto-Scaling des Scanners wird nicht unterstützt, wenn der Scanner mit einem OpenShift-Operator bereitgestellt wird, da der Operator die Anzahl der Pods immer auf den konfigurierten Wert ändern wird.
 ** *_Stratégie retardée :_*
  *** Wenn der Hauptcontroller kontinuierlich "Anzahl der Aufgaben" > 0 für > 90 Sekunden sieht, wird ein neuer Scanner-Pod gestartet, wenn maxScannerPods noch nicht erreicht ist.
  *** Wenn der Hauptcontroller kontinuierlich sieht, dass "die Anzahl der Aufgaben" 0 für > 180 Sekunden ist, reduziert er um einen Scanner-Pod, wenn minScannerPods noch nicht erreicht ist.
 ** *_Stratégie immédiate :_*
  *** Jedes Mal, wenn der Hauptcontroller "Anzahl der Aufgaben" > 0 sieht, wird ein neuer Scanner-Pod gestartet, wenn maxScannerPods noch nicht erreicht ist.
  *** Wenn der Hauptcontroller kontinuierlich sieht, dass "die Anzahl der Aufgaben" 0 für > 180 Sekunden ist, reduziert er um einen Scanner-Pod, wenn minScannerPods noch nicht erreicht ist.
* Benutzerdefinierte Gruppen können jetzt Namespace-Tags verwenden, einschließlich Rancher-Namespace-Tags. Im Allgemeinen können jetzt Pod- und Namespace-Tags zu benutzerdefinierten Gruppen hinzugefügt werden.
* Fügen Sie die Möglichkeit hinzu, ausgewählte Namespaces und Gruppen in der Netzwerkaktivitätsansicht auszublenden.
* Vollständige Unterstützung für Cilium cni.
* Vollständige Unterstützung für OpenShift 4.9 und 4.10.
* Build-Tools sind jetzt für das Projekt {product-name}/Open Zero Trust (OZT) unter https://github.com/openzerotrust/openzerotrust.io.. verfügbar.
* {product-name} listet jetzt die Versions-ID und den SHA256-Hash für jede Version des Controllers, Managers, Executors unter https://github.com/neuvector/manifests/tree/main/versions.. auf.
* Anonyme Telemetriedaten (Anzahl der Knoten, Gruppen, Regeln) werden jetzt bei der Bereitstellung an einen Rancher-Cloud-Service gemeldet, um dem Projektteam zu helfen, das Nutzungsverhalten zu verstehen. Dies kann in der Benutzeroberfläche oder mit configMap (No_Telemetry_Report) oder REST API deaktiviert werden (Opt-out).
* (Addendum Januar 2023). Unterstützung für netzwerkbasierte Strategien mit ServiceEntry in Istio. Die Funktion zur Anwendung der ausgehenden Netzwerkstrategie wurde in Version 5.1.0 für Pods zu den mit Istio deklarierten ServiceEntry-Zielen hinzugefügt. Typischerweise definiert ein ServiceEntry, wie ein externer Dienst, der durch einen DNS-Namen referenziert wird, in eine Ziel-IP-Adresse aufgelöst wird. Vor v5.1 konnte {product-name} keine Regeln für Verbindungen zu einem ServiceEntry erkennen und anwenden, sodass alle Verbindungen als extern eingestuft wurden. Mit 5.1 können Regeln für spezifische Ziele von ServiceEntry angewendet werden. WICHTIG: Wenn Sie auf v5.1 mit einem auf Istio basierenden Deployment aktualisieren, müssen neue Regeln erstellt werden, um diese Verbindungen zu ermöglichen und Verstöße zu vermeiden. Nach dem Upgrade werden implizite Verstöße für den neu sichtbaren Datenverkehr gemeldet, wenn keine Berechtigungsregeln vorhanden sind. De nouvelles règles de trafic peuvent être apprises et auto-créées en mode Découverte. Um diesen Datenverkehr zu ermöglichen, können Sie die Gruppe in den Entdeckungsmodus versetzen oder eine benutzerdefinierte Gruppe mit Adressen (oder einem DNS-Namen) und einer neuen Netzwerkregel zu diesem Ziel erstellen, um den Datenverkehr zu ermöglichen. HINWEIS: Es gibt einen Fehler in 5.1.0 im Ziel, das durch die Ablehnungsverstöße gemeldet wird, das nicht das richtige Ziel darstellt.  Der Fehler meldet, dass server_name und client_name identisch sind.  Ce problème sera résolu dans une prochaine version de correctif.

==== Fehlerbehebungen

* Reduzierung des Speicherverbrauchs des Controllers aufgrund unnötiger Referenzdaten, die während der schrittweisen Updates erstellt wurden. Dieses Problem tritt bei neuen Deployments nicht auf.
* Supprimer la licence de l'écran de configuration (plus nécessaire).

=== 5.0.6-s1 März 2023

==== Fehlerbehebungen

* Aktualisieren Sie die Alpine-Pakete, um die CVEs in curl zu beheben, einschließlich CVE-2023-23914, CVE-2023-23915 und CVE-2023-23916.

=== 5.0.6 Februar 2023

==== Fehlerbehebungen

* Utilisation élevée de la mémoire dans dpMsgConnection
* Hoher Speicherverbrauch im dp-Prozess im Enforcer, wenn viele erlernte Strategieregeln mit einer nicht verwalteten Arbeitslast vorhanden sind (Speicherleck)
* tcpdump kann nicht erfolgreich gestartet werden, wenn der Datenverkehr im Container analysiert wird
* Alpine aktualisieren, um mehrere CVEs zu beheben, einschließlich Manager: CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552

=== 5.0.5 November 2022

==== Fehlerbehebungen

* Das Upgrade auf 5.0.x führt zu einer Fehlermeldung bezüglich Manager, Controller, Enforcer, die unterschiedliche Versionen ausführen.
* Die Enforcer erleben eine routinemäßige Go-Panik, die zu einem dp-Kill führt.  WebUI spiegelt den Enforcer nicht als online wider.
* Unerwarteter Vorfall von Process.Profile.Violation in der NV.Protect-Gruppe, auf der CoreOS-Befehle ausgeführt werden.

=== 5.0.4 Oktober 2022

==== Sicherheitsupdates

* Alpine aktualisieren, um die kritische CVE-2022-40674 in der Expat-Bibliothek des Managers zu entfernen, sowie andere kleinere CVEs.

==== Améliorations

* Unterstützung für Antrea CNI hinzufügen

==== Fehlerbehebungen

* Unerwarteten Vorfall von process.profile.violation in der NV.Protect-Gruppe beheben.
* Wenn SSL beim UI-Zugriff des Managers deaktiviert ist, wird das Benutzerpasswort im Manager-Log ausgegeben.

=== 5.0.3 September 2022

==== Améliorations

* Den Lizenzvertrag nach einem erfolgreichen Neustart vom persistenten Volume nicht anzeigen.
* Verwenden Sie den Bildfilter in den Einstellungen des Schwachstellenprofils, um die Scanergebnisse von Containern zu ignorieren.
* Unterstützung des Scanners in GitHub-Aktionen bei https://github.com/neuvector/neuvector-image-scan-action.
* Fügen Sie Enforcer-Umgebungsvariablen hinzu, um das Scannen von Geheimnissen zu deaktivieren und die CIS-Benchmarks auszuführen.

[,yaml]
----
    env:
      - name: ENF_NO_SECRET_SCANS  (available after v4.4.4)
        value: "1"
      - name: ENF_NO_AUTO_BENCHMARK (after v5.0.3)
        value: "1"
----

==== Fehlerbehebungen

* Enforcer kann gelegentlich nicht starten.
* Verbindungsleck in Multi-Cluster-Föderationsumgebungen.
* Die Compliance-Seite lädt manchmal nicht in den Sicherheitsrisiken -> Compliance.

=== 5.0.2 Juli 2022

==== Améliorations

* Härtete Rancher-Cluster und SELinux werden unterstützt.

==== Fehlerbehebungen

* CPU-intensive Agent-Prozesse auf k3s-Systemen.
* AD LDAP-Gruppen funktionieren nach dem Upgrade auf 5.0 nicht richtig.
* Enforcer startet aufgrund des Fehlers = zu viele offene Dateien (rke2/cilium) weiterhin neu.
* Das Support-Protokoll kann nicht erfolgreich heruntergeladen werden.

=== 5.0.1 Juni 2022

==== Améliorations

* Prise en charge du scan de vulnérabilité de l'OS openSUSE Leap (dans l'image du scanner).
* Scanner: Implementierung von Löschattributen beim Rekonstruieren des Image-Repositorys.
* Überprüfen Sie das Deployment {product-name} und den Support für Hosts mit aktiviertem SELinux. Siehe unten für Details zum vorübergehenden Patch, bis das Helm-Diagramm aktualisiert wird.
* Deutlicher zwischen dem Funktionsdiagramm und den Partnerdiagrammen in der Rancher-Benutzeroberfläche unterscheiden. + Verbesserung der Eingangsannotation für nginx im Rancher-Helm-Diagramm. Hinzufügen / Aktualisieren
ingress.kubernetes.io/protocol : https zu nginx.ingress.kubernetes.io/backend-protocol : "HTTPS".
* Der aktuelle OpenShift-Operator unterstützt Pass-Through-Routen für API- und Föderationsdienste. Zusätzliche Helm-Wertparameter werden hinzugefügt, um die Edge- und Re-Encryption-Routenendtypen zu unterstützen.

==== Fehlerbehebungen

* Der AKS-Cluster könnte einen unerwarteten Schlüssel im Admission Control Webhook hinzufügen.
* Der Enforcer wird im K8s-Cluster 1.24 mit dem Containerd-Runtime 1.64 nicht betriebsbereit. Séparément, l'enforcer échoue parfois à démarrer.
* Jeder Benutzer mit der Rolle Administrator (lokaler Benutzer oder SSO), der einen Cluster zu einem Master-Fed befördert, sollte automatisch zur Rolle fedAdmin befördert werden.
* Wenn SSO den Standardadministrator von Rancher in {product-name} auf dem Master-Cluster verwendet, ist die Anmelderolle {product-name} admin, nicht fedAdmin.
* Mehrere Goroutine-Abstürze beheben.
* Implizite Verletzung der Host-IP, die nicht mit dem Knoten verknüpft ist.
* Das Compliance-Profil zeigt nicht das PCI-Tag an.
* Die LDAP-Gruppenzuordnung wird manchmal nicht angezeigt.
* Das Risiko-Review- und Verbesserungstool führt zu einer Fehlermeldung "Fehler beim Aktualisieren der Systemkonfiguration: Anfrage im falschen Format".
* OKD 3.11 - Der Fehler von Clusterrole wird angezeigt, auch wenn er existiert.

==== Remédiations CVE

* CVE-2022-29458 hoch eingestuft, gefunden im Paket ncurses in allen Images.
* CVE-2022-27778 et CVE-2022-27782 élevés trouvés sur le paquet curl dans l'image Updater.

==== Details zur SELinux-Unterstützung

{product-name} benötigt keine zusätzlichen Parameter für Cluster mit aktiviertem SELinux, um bereitgestellt und betrieben zu werden. Bereitstellung von {product-name} auf einem RKE2-Cluster, der auf RHEL 8.5 mit aktiviertem SELinux gehärtet ist, getestet. {product-name} erfolgreich bereitgestellt, wenn PSP aktiviert ist und der Patch-Manager und der Scanner bereitgestellt werden. Die nächste Version des Charts sollte das folgende Problem beheben.

Beigefügtes Beispiel zur Aktivierung von psp aus dem Rancher-Chart und unten die Befehle zum Patchen der Bereitstellung des Managers und des Scanners. L'ID utilisateur dans la commande de patch peut être n'importe quel numéro.

[,shell]
----
kubectl patch deploy -ncattle-neuvector-system neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
kubectl patch deploy -ncattle-neuvector-system neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
----

Beispiel zur Aktivierung von PSP:

[,shell]
----
[neuvector@localhost nv]$ getenforce
Enforcing
[neuvector@localhost nv]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

[neuvector@localhost nv]$ kk get psp
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS                                      SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
global-restricted-psp     false                                             RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
neuvector-binding-psp     true    SYS_ADMIN,NET_ADMIN,SYS_PTRACE,IPC_LOCK   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
system-unrestricted-psp   true    *                                         RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
[neuvector@localhost nv]$ nvpo.sh
NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE                    NOMINATED NODE   READINESS GATES
neuvector-controller-pod-54f69f7f9c-6h822   1/1     Running   0          5m51s   10.42.0.29   localhost.localdomain   <none>           <none>
neuvector-enforcer-pod-jz77b                1/1     Running   0          5m51s   10.42.0.30   localhost.localdomain   <none>           <none>
neuvector-manager-pod-588488bb78-p6vf9      1/1     Running   0          111s    10.42.0.32   localhost.localdomain   <none>           <none>
neuvector-scanner-pod-87474dcff-s8vgt       1/1     Running   0          114s    10.42.0.31   localhost.localdomain   <none>           <none>
----

=== 5.0.0 Version de disponibilité générale (GA) Mai 2022

==== Améliorations

* Automatisierte Förderung von Gruppenmodi. Promeut le mode de protection d'un groupe en fonction du temps écoulé et des critères. Gilt nicht für von CRD erstellte Gruppen. Diese Funktion ermöglicht es einer neuen Anwendung, während eines bestimmten Zeitraums in Discover zu laufen, das Verhalten zu lernen und {product-name} Regeln für die Genehmigungsliste für das Netzwerk und den Prozess zu erstellen, und wechselt dann automatisch in den Überwachungsmodus und dann in den Schutzmodus. Kriterium von Discover zu Monitor: Verstrichene Zeit, um alle Netzwerk- und Prozessaktivitäten von mindestens einem aktiven Pod in der Gruppe zu lernen. Kriterium von Monitor zu Protect: Es gibt keine Sicherheitsereignisse (Netzwerk, Prozess usw.) für den festgelegten Zeitraum für die Gruppe.
* Unterstützung für Rancher-Anwendungen 2.6.5 und das Marketplace-Diagramm. Bereitstellung im Namespace cattle-neuvector-system und Aktivierung von Rancher SSO bei {product-name}. Hinweis: Frühere Bereitstellungen von Rancher (z. B. Partnerkatalog-Diagramme, Version 1.9.x und früher) müssen vollständig entfernt werden, um auf das neue Diagramm zu aktualisieren.
* Unterstützung für den Scan von SUSE Linux (SLE, SLES) und Microsoft Mariner
* Schutz von Prozessen und Dateien ohne Drift. Dies ist der neue Standardmodus für den Schutz von Prozessen und Dateien. Zero-Drift erlaubt automatisch nur die Prozesse, die vom übergeordneten Prozess stammen, der sich im ursprünglichen Container-Image befindet, und erlaubt keine Dateiaktualisierungen oder die Installation neuer Dateien. Wenn Sie sich im Entdeckungs- oder Überwachungsmodus befinden, wird Zero-Drift bei verdächtigen Prozess- oder Dateiaktivitäten alarmieren. Im Schutzmodus wird eine solche Aktivität blockiert. Die Null-Abweichung erfordert nicht, dass die Prozesse gelernt oder zu einer Genehmigungsliste hinzugefügt werden. Die Deaktivierung der Null-Abweichung für eine Gruppe sorgt dafür, dass die für die Gruppe aufgelisteten Prozess- und Dateiregeln anstelle dessen wirksam werden.
* Schutz im geteilten Politikmodus für das Netzwerk, den Prozess/Datei. Es gibt jetzt eine globale Einstellung in den Einstellungen -> Konfiguration, um den Schutzmodus des Netzwerks für die Anwendung der Netzwerkregeln separat festzulegen. Das Aktivieren dieser Option (standardmäßig deaktiviert) sorgt dafür, dass alle Netzwerkregeln im ausgewählten Schutzmodus (Entdeckung, Überwachung, Schutz) sind, während die Prozess-/Dateiregeln im Schutzmodus für diese Gruppe bleiben, wie im Bildschirm Politik -> Gruppen angezeigt. Auf diese Weise können die Netzwerkregeln auf Schutz (Blockierung) festgelegt werden, während die Politik für Prozesse/Dateien auf Überwachung festgelegt werden kann, oder umgekehrt.
* Erkennung von WAF-Regeln, verbesserte DLP-Regeln (Header, URL, vollständiges Paket). Verwendet für eingehende Verbindungen zu Webanwendungs-Pods sowie für ausgehende Verbindungen zu API-Diensten, um die API-Sicherheit anzuwenden.
* CRD für WAF, DLP und Zugangssteuerungen. HINWEIS: Zusätzliche Cluster-Rollenbindungen/Berechtigungen sind erforderlich. Voir les sections de déploiement Kubernetes et OpenShift. Import/Export von CRD und Versionierung für die unterstützten Zugangssteuerungen über CRD.
* SSO-Integration Rancher zum Starten der {product-name} Konsole über Rancher Manager. Diese Funktion ist nur verfügbar, wenn die Container {product-name} über Rancher bereitgestellt werden. Diese Bereitstellung bezieht sich auf das Rancher-Mirror-Repository (z. B. rancher/mirrored-neuvector-controller:5.0.0) und wird im Namespace cattle-neuvector-system bereitgestellt. HINWEIS: Erfordert eine aktualisierte Version von Rancher 2.6.5 Mai 2022 oder später, und derzeit werden nur die Rollen Administrator und Clusterbesitzer unterstützt.
* Unterstützt die Bereitstellung auf RKE2.
* Unterstützt die Cluster-Föderation (Multi-Cluster-Manager) über einen Proxy. Konfigurieren Sie den Proxy in den Einstellungen -> Konfiguration und aktivieren Sie den Proxy bei der Konfiguration der Föderationsverbindungen.
* Überwachen Sie die erforderlichen Cluster-Rollen/Bindungen rbac und alarmieren Sie in den Ereignissen und der Benutzeroberfläche, wenn etwas fehlt.
* Unterstützen Sie die Ressourcenbeschränkungsanforderungen in den Zulassungsprüfungsregeln.
* Unterstützen Sie das Microsoft Teams-Format für Webhooks.
* Unterstützen Sie verschachtelte AD/LDAP-Gruppen unter der zugeordneten Rollengruppe.
* Unterstützen Sie ClusterRoleBindings oder RoleBindings mit Gruppeninformationen im IDP für Openshift.
* Erlauben Sie Netzwerkregeln und Zulassungsprüfungsregeln, in eine föderierte Regel befördert zu werden.

==== Fehlerbehebungen

* Beheben Sie das Problem mit der Sicherung der Föderationsrolle von Arbeitern, die in nicht-föderierten Clustern wiederhergestellt werden sollte.
* Verbessern Sie die Ladezeiten von Seiten für eine große Anzahl von CVEs in den Sicherheitsrisiken -> Verwundbarkeiten.
* Ermöglichen Sie dem Benutzer, den Modus zu ändern, wenn er alle Gruppen im -> Gruppenmenü auswählt. Warnen Sie, wenn die Knoten-Gruppe ebenfalls ausgewählt ist.
* Réduire les éléments de vérification de conformité du même nom et les rendre extensibles.
* Améliorer la sécurité des communications gRPC.
* Behoben: Es war nicht möglich, die richtigen Privileginformationen für die Arbeitslast in der rke2-Konfiguration zu erhalten.
* Beheben Sie das Problem mit der Unterstützung von openSUSE Leap 15.3 (k8s/crio).

==== Weitere Updates

* Aktualisierung der Helm-Chart appVersion auf 5.0.0 und der Chart-Version auf 2.2.0
* Funktion/Serverloser Scan-Menü entfernt.
* Unterstützung für die Integration der Jfrog Xray-Scanergebnisse entfernt (der Scan des Artifactory-Registers wird weiterhin unterstützt).
* Die Unterstützung für die Bereitstellung auf ECS wird nicht mehr bereitgestellt. Das All-in-One sollte weiterhin auf ECS bereitgestellt werden können, jedoch wird die Dokumentation der Schritte und Parameter nicht mehr unterstützt.

=== Upgrade von {product-name} 4.x auf 5.x (vor 5.2.x)

[NOTE]
====
Les instructions ci-dessous s'appliquent aux mises à niveau vers 5.0.x et 5.1.x. Für 5.2.x haben sich die Dienstkonten und Bindungen geändert und müssen xref:kubernetes.adoc#_deploy_suse_security[überprüft] werden, um Upgrades zu planen.
====


Für Helm-Benutzer aktualisieren Sie auf {product-name} das Helm-Chart 2.0.0 oder höher. Wenn Sie einen Operator oder eine Helm-Installation auf OpenShift aktualisieren, siehe die folgende Anmerkung.

. Supprimez l'ancienne définition de rôle de cluster neuvector-binding-customresourcedefinition

[,shell]
----
kubectl delete clusterrole neuvector-binding-customresourcedefinition
----

. Wenden Sie das neue Aktualisierungsverb für die Cluster-Rolle neuvector-binding-customresourcedefinition an.

[,shell]
----
kubectl create clusterrole neuvector-binding-customresourcedefinition --verb=watch,create,get,update --resource=customresourcedefinitions
----

. Supprimez l'ancien schéma crd pour Kubernetes 1.19+

[,shell]
----
kubectl delete -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/crd-k8s-1.19.yaml
----

. Erstellen Sie ein neues CRD-Schema für Kubernetes 1.19+.

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/waf-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/dlp-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/admission-crd-k8s-1.19.yaml
----

. Erstellen Sie eine neue Cluster-Rolle für Admission, DLP und WAF sowie eine Cluster-Rollenbindung.

[,shell]
----
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----

. Aktualisieren Sie die Namen und Bildpfade, um {product-name} Bilder von Docker Hub (docker.io) zu ziehen, z. B.

* neuvector/manager:5.0.0
* neuvector/controller:5.0.0
* neuvector/enforcer:5.0.0
* neuvector/scanner:latest
* neuvector/updater:latest

Optional: Entfernen Sie alle Verweise auf die {product-name} Lizenz und das Registry-Secret in den Helm-Charts, der Deployment-YAML, dem ConfigMap, den Skripten usw., da diese nicht mehr erforderlich sind, um die Bilder zu ziehen oder um {product-name} zu verwenden.

*Hinweis zu SCC und Upgrade über Operator/Helm*

Der privilegierte SCC wird dem im Deployment-YAML angegebenen Dienstkonto durch die Operator-Version 1.3.4 und höher in neuen Bereitstellungen hinzugefügt. Im Falle eines Upgrades des Operators {product-name} von einer vorherigen Version auf 1.3.4 oder von Helm auf 2.0.0, entfernen Sie bitte den privilegierten SCC vor dem Upgrade.

[,shell]
----
oc delete rolebinding -n neuvector system:openshift:scc:privileged
----

==== Beta-Version 1 veröffentlicht im April 2022.

* Vollständige Funktionalität, einschließlich automatisierter Förderung von Gruppenmodi. Promeut le mode de protection d'un groupe en fonction du temps écoulé et des critères. Gilt nicht für von CRD erstellte Gruppen. Diese Funktion ermöglicht es einer neuen Anwendung, während eines bestimmten Zeitraums in Discover zu laufen, das Verhalten zu lernen und {product-name} Regeln für die Genehmigungsliste für das Netzwerk und den Prozess zu erstellen, und wechselt dann automatisch in den Überwachungsmodus und dann in den Schutzmodus. Kriterium von Discover zu Monitor: Verstrichene Zeit, um alle Netzwerk- und Prozessaktivitäten von mindestens einem aktiven Pod in der Gruppe zu lernen. Kriterium von Monitor zu Protect: Es gibt keine Sicherheitsereignisse (Netzwerk, Prozess usw.) für den festgelegten Zeitraum für die Gruppe.
* Unterstützung für Rancher-Anwendungen 2.6.5 und das Marketplace-Diagramm. Bereitstellung im Namespace cattle-neuvector-system und Aktivierung von Rancher SSO bei {product-name}. Hinweis: Frühere Bereitstellungen von Rancher (z. B. Partnerkatalog-Diagramme, Version 1.9.x und früher) müssen vollständig entfernt werden, um auf das neue Diagramm zu aktualisieren.
* Tags für Enforcer, Manager, Controller : 5.0.0-b1 (zum Beispiel neuvector/controller:5.0.0-b1)

==== Version Preview.3 veröffentlicht im März 2022

[CAUTION]
.wichtig
====

Um frühere Preview-Deployments für die neuen CRD WAF-, DLP- und Admission Control-Funktionen zu aktualisieren, aktualisieren Sie bitte die YAML-CRD und fügen Sie neue RBAC/Rollenbindungen hinzu :

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/latest/crd-k8s-1.19.yaml
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----
====


==== Améliorations

* Unterstützung für den Scan von SUSE Linux (SLE, SLES) und Microsoft Mariner
* Schutz von Prozessen und Dateien ohne Drift. Dies ist der neue Standardmodus für den Schutz von Prozessen und Dateien. Zero-Drift erlaubt automatisch nur die Prozesse, die vom übergeordneten Prozess stammen, der sich im ursprünglichen Container-Image befindet, und erlaubt keine Dateiaktualisierungen oder die Installation neuer Dateien. Wenn Sie sich im Entdeckungs- oder Überwachungsmodus befinden, wird Zero-Drift bei verdächtigen Prozess- oder Dateiaktivitäten alarmieren. Im Schutzmodus wird eine solche Aktivität blockiert. Die Null-Abweichung erfordert nicht, dass die Prozesse gelernt oder zu einer Genehmigungsliste hinzugefügt werden. Die Deaktivierung der Null-Abweichung für eine Gruppe sorgt dafür, dass die für die Gruppe aufgelisteten Prozess- und Dateiregeln anstelle dessen wirksam werden.
* Schutz im geteilten Politikmodus für das Netzwerk, den Prozess/Datei. Es gibt jetzt eine globale Einstellung in den Einstellungen -> Konfiguration, um den Schutzmodus des Netzwerks für die Anwendung der Netzwerkregeln separat festzulegen. Das Aktivieren dieser Option (standardmäßig deaktiviert) sorgt dafür, dass alle Netzwerkregeln im ausgewählten Schutzmodus (Entdeckung, Überwachung, Schutz) sind, während die Prozess-/Dateiregeln im Schutzmodus für diese Gruppe bleiben, wie im Bildschirm Politik -> Gruppen angezeigt. Auf diese Weise können die Netzwerkregeln auf Schutz (Blockierung) festgelegt werden, während die Politik für Prozesse/Dateien auf Überwachung festgelegt werden kann, oder umgekehrt.
* WAF-Regelerkennung, verbesserte DLP-Regeln (Header, URL, vollständiges Paket)
* CRD für WAF, DLP und Zugangssteuerungen. HINWEIS: Zusätzliche Cluster-Rollenbindungen/Berechtigungen sind erforderlich. Voir les sections de déploiement Kubernetes et OpenShift. Import/Export von CRD und Versionierung für die unterstützten Zugangssteuerungen über CRD.
* SSO-Integration Rancher zum Starten der {product-name} Konsole über Rancher Manager. Diese Funktion ist nur verfügbar, wenn die Container {product-name} über Rancher bereitgestellt werden. HINWEIS: Benötigt eine aktualisierte Version von Rancher (Datum/version noch festzulegen).
* Unterstützt die Bereitstellung auf RKE2.
* Unterstützt die Cluster-Föderation (Multi-Cluster-Manager) über einen Proxy.
* Überwachen Sie die erforderlichen Cluster-Rollen/Bindungen rbac und alarmieren Sie in den Ereignissen und der Benutzeroberfläche, wenn etwas fehlt.
* Unterstützen Sie die Ressourcenbeschränkungsanforderungen in den Zulassungsprüfungsregeln.

==== Fehlerbehebungen

* Beheben Sie das Problem mit der Sicherung der Föderationsrolle von Arbeitern, die in nicht-föderierten Clustern wiederhergestellt werden sollte.

==== Version Preview.2 veröffentlicht im Februar 2022

* Modifications mineures de fichiers et de licences dans la source, aucune fonctionnalité ajoutée.

==== Unterstützung für die Bereitstellung auf AWS ECS veraltet

Die Unterstützung für die Bereitstellung auf ECS wird nicht mehr bereitgestellt. Das All-in-One sollte weiterhin auf ECS bereitgestellt werden können, jedoch wird die Dokumentation der Schritte und Parameter nicht mehr unterstützt.

=== 5.0 'Tech Preview' Januar 2022

==== Améliorations

* Erste Version einer nicht unterstützten 'Tech-Preview'-Version von {product-name} 5.0 Open-Source-Version.
* Fügen Sie Unterstützung für OWASP Top-10 hinzu, ähnliche Regeln wie WAF zur Erkennung von Netzwerkangriffen in Headern oder im Body. Beinhaltet Unterstützung für CRD-Signaturdefinitionen und deren Anwendung auf die entsprechenden Gruppen.
* Entfernt die Funktionen des Serverless-Scans.

==== Fehlerbehebungen

* TBD

==== Sonstiges

* Le graphique Helm v1.8.9 est publié pour les déploiements 5.0.0. Wenn Sie dies mit der Preview-Version 5.0.0 verwenden, müssen die folgenden Änderungen an values.yml vorgenommen werden :
 ** Aktualisieren Sie das Registry auf docker.io
 ** Aktualisieren Sie die Namen/Tags des Images auf die Preview-Version auf Docker Hub
 ** Laissez les imagePullSecrets vides
