= Directives générales
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /13.special/01.general/01.general.md
:page-opendocs-slug:  /spécial/général

== Test {product-name} en utilisant le conteneur Allinone

Les exemples dans cette section déploient les conteneurs Allinone et Enforcer. Ceci est utile pour essayer {product-name}, en particulier dans des environnements non-Kubernetes (par exemple, natif docker). Pour les déploiements basés sur Kubernetes, il est recommandé d'utiliser le dernier chart Helm {product-name}. Veuillez consulter la section Déploiement de {product-name}.

== Directives générales pour le déploiement

Préparez votre environnement hôte pour une installation correcte. Assurez-vous que les conteneurs {product-name} peuvent communiquer entre eux entre les hôtes. Ensuite, examinez et modifiez les fichiers d'exemple pour votre environnement.

En général, il est important de faire ce qui suit :

. Étiquetez les nœuds de manière appropriée. Si vous utilisez des étiquettes de nœud pour contrôler où l'allinone ou le contrôleur est déployé, étiquetez-les avant le déploiement.
. Assurez-vous que les volumes peuvent être mappés correctement. Par exemple
+
[,yaml]
----
volumes:
        - /var/neuvector:/var/neuvector
        - /var/run/docker.sock:/var/run/docker.sock
        - /proc:/host/proc:ro
        - /sys/fs/cgroup:/host/cgroup:ro
----

. Ouvrez les ports requis sur les hôtes. Assurez-vous que les ports requis sont correctement mappés et ouverts sur l'hôte. L'allinone nécessite 8443 (si vous utilisez la console), 18300, 18301, 18400 et 18401. L'Enforcer nécessite 18301 et 18401.
. Modifier le CLUSTER_JOIN_ADDR. Trouvez l'adresse IP du nœud, le nom du nœud (si vous utilisez un serveur de noms), ou la variable de nœud (si vous utilisez des outils d'orchestration) pour le tout-en-un (contrôleur) à utiliser pour le "`node IP`" dans les fichiers d'exemple pour le tout-en-un et l'enforcer.

== Accéder à la Console

Veuillez consulter la première section Bases -> Connexion au Gestionnaire pour les options permettant de désactiver https ou d'accéder à la console via une passerelle de périmètre de sécurité qui n'autorise pas le port 8443 pour l'accès à la console.
