= Parallelscanner und Standalone-Scanner
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /06.scanning/06.scanners/06.scanners.md
:page-opendocs-slug:  /Scannen/Scanner

== Erhöhen Sie die Skalierbarkeit von Scannern mit mehreren Scannern

Um die Leistung und Skalierbarkeit des Scanners zu erhöhen, unterstützt {product-name} den Einsatz mehrerer Scanner-Pods, die parallel Bilder in Registern scannen können. Die Steuerung weist jedem verfügbaren Scanner-Pod Scan-Aufgaben zu. Scanner-Pods können mit Kubernetes je nach Bedarf einfach nach oben oder unten skaliert werden.

Scanner-Pods sollten auf separaten Knoten bereitgestellt werden, um die Arbeitslast auf verschiedene Host-Ressourcen zu verteilen. Denken Sie daran, dass ein Scanner genügend Speicherplatz benötigt, um das Bild zu ziehen und zu vergrößern, also sollte er mehr als die größte zu scannende Bildgröße zur Verfügung haben. Bei Bedarf können Scanner auf bestimmten Knoten platziert werden, oder es kann vermieden werden, mehrere Pods auf einem Knoten zu platzieren, indem Standard-Kubernetes-Knoten-Labels, Taints/Toleranzen oder Knoten-Affinitätskonfigurationen verwendet werden.

Standardmäßig stellt {product-name} 2 Scanner-Pods bereit, die Teil der Beispielbereitstellungen im Abschnitt Bereitstellen von {product-name} sind. Diese Replikatsätze können je nach Bedarf nach oben oder unten skaliert werden.

Der Scanner enthält die neueste CVE-Datenbank und wird regelmäßig (mit dem Tag "latest") von {product-name} aktualisiert. Der Updater setzt den Scanner neu ein und erzwingt einen Abruf des neuesten Scanner-Images, um die neueste CVE-Datenbank zu erhalten. Im Abschnitt xref:updating.adoc[Aktualisierung der CVE-Datenbank] finden Sie weitere Einzelheiten zum Updater.

Bitte beachten Sie, dass in den ersten Versionen das Vorhandensein und der Status von mehreren Scannern nur in Kubernetes mit 'kubectl get pods -n neuvector' sichtbar ist und nicht in der Webkonsole angezeigt wird.

Die Suchergebnisse aller Scanner werden im Menü Assets -> Register angezeigt. Weitere Funktionen zur Scannerüberwachung werden in zukünftigen Versionen hinzugefügt.

=== Automatische Skalierung von Scanner-Pods

Scanner-Pods können so konfiguriert werden, dass sie anhand bestimmter Kriterien automatisch skaliert werden. So wird sichergestellt, dass Scanaufträge schnell und effizient abgewickelt werden, insbesondere wenn Tausende von Bildern gescannt oder erneut gescannt werden müssen. Es gibt drei mögliche Einstellungen: verzögert, sofort und deaktiviert. Wenn Bilder zum Scannen in eine Warteschlange gestellt werden, führt das Steuergerät einen "Task-Count" über die Größe der Warteschlange.

* Verspätete Strategie:
** Wenn der Lead Controller für > 90 Sekunden kontinuierlich "task count" > 0 sieht, wird ein neuer Scanner-Pod gestartet, wenn maxScannerPods noch nicht erreicht ist
** Wenn der Lead Controller für mehr als 180 Sekunden kontinuierlich sieht, dass "task count" 0 ist, wird ein Scanner-Pod verkleinert, wenn minScannerPods noch nicht erreicht ist
* Unmittelbare Strategie:
** Jedes Mal, wenn der Lead Controller "task count" > 0 sieht, wird ein neuer Scanner-Pod gestartet, wenn maxScannerPods noch nicht erreicht ist
** Wenn der Lead Controller für mehr als 180 Sekunden kontinuierlich sieht, dass "task count" 0 ist, wird ein Scanner-Pod verkleinert, wenn minScannerPods noch nicht erreicht ist

Die automatische Skalierung des Scanners wird unter Einstellungen -> Konfiguration konfiguriert. Die Einstellung minimumScannerPods legt die minimale Anzahl von Scanner-Pods fest, die zu einem beliebigen Zeitpunkt laufen, während maxScannerPods die maximale Anzahl von Pods festlegt, auf die die automatische Skalierungsstrategie skalieren kann. HINWEIS: Wenn Sie einen Mindestwert festlegen, wird der Wert für die Replikate des ursprünglichen Scannereinsatzes nicht angepasst. Der Mindestwert wird beim ersten Hoch- bzw. Runterschalten angewendet.

[IMPORTANT]
====
Die automatische Skalierung des Scanners wird nicht unterstützt, wenn der Scanner mit einem OpenShift-Operator bereitgestellt wird, da der Operator die Anzahl der Pods immer auf den konfigurierten Wert ändert.
====

=== Betrieb und Fehlersuche

Jeder Scanner-Pod fragt die zu scannenden Register ab, um die vollständige Liste der verfügbaren Bilder und anderer Daten zu erhalten. Jedem Scanner wird dann ein Bild zugewiesen, das er aus der Registrierung ziehen und scannen soll.

Um das Verhalten des Scanners zu untersuchen, können die Protokolle der einzelnen Scanner-Pods mit

[,shell]
----
kubectl logs <scanner-pod-name> -n neuvector
----

== Leistungsplanung

Experimentieren Sie mit einer unterschiedlichen Anzahl von Scannern auf Registern mit einer großen Anzahl von Bildern, um das Verhalten der Scan-Abschlusszeit in Ihrer Umgebung zu beobachten. 2-5 Scanner als Replikationseinstellung sollten für die meisten Fälle ausreichend sein.

Wenn eine Scanaufgabe einem Scanner zugewiesen wird, zieht dieser das Bild aus der Registrierung (nachdem er die Registrierung nach der Liste der verfügbaren Bilder abgefragt hat). Die meiste Zeit wird in der Regel für das Abrufen des Bildes (Download) benötigt. Mehrere Scanner können parallel Bilder aus derselben Registrierung abrufen, so dass die Leistung durch die Registrierung oder die Netzwerkbandbreite begrenzt sein kann.

Große Bilder benötigen mehr Zeit zum Abrufen und müssen zum Scannen vergrößert werden, was mehr Speicherplatz beansprucht. Vergewissern Sie sich, dass jedem Scanner genügend Speicherplatz zugewiesen ist, um mehr als das größte erwartete Bild zu verarbeiten (mindestens 10 % mehr).

Es können mehrere Scanner-Pods auf demselben Host/Knoten bereitgestellt werden, es sollte jedoch darauf geachtet werden, dass der Host über genügend Arbeitsspeicher, CPU und Netzwerkbandbreite verfügt, um die Scannerleistung zu maximieren.

== Eigenständiger Scanner für lokales Scannen

{product-name} unterstützt Standalone-Scanner-Einsätze für lokales Scannen von Bildern (für die kein Controller erforderlich ist). In dem unten aufgeführten Beispiel für einen Docker-Lauf wird das lokale Image gescannt und die Ergebnisse lokal in /var/neuvector gespeichert. Beim lokalen Scannen muss der Zugriff auf das Image über die gemountete docker.sock möglich sein, andernfalls kann eine Registry angegeben werden.

[,bash]
----
docker run --name neuvector.scanner --rm -e SCANNER_REPOSITORY=ubuntu -e SCANNER_TAG=16.04 -e SCANNER_ON_DEMAND=true -v /var/run/docker.sock:/var/run/docker.sock -v /var/neuvector:/var/neuvector  neuvector/scanner
----

Die folgenden Umgebungsvariablen des Scanners können im Befehl docker run verwendet werden:

* SCANNER_REGISTRY= Url der Registrierung (optional anstelle von lokalem Scan)
* SCANNER_REPOSITORY= zu scannendes Repository
* SCANNER_TAG= Versions-Tag
* SCANNER_REGISTRY_USERNAME= user (optional anstelle von local scan)
* SCANNER_REGISTRY_PASSWORD= Kennwort (optional anstelle von Local Scan)
* SCANNER_SCAN_LAYERS= true oder false (um geschichtete Scanergebnisse zurückzugeben)
* SCANNER_ON_DEMAND=true (erforderlich)
* CLUSTER_JOIN_ADDR (optional), CLUSTER_JOIN_PORT (optional) - zum Senden der Ergebnisse an den Controller zur Verwendung in den Regeln für die Zulassungskontrolle (in Kubernetes eingesetzter Controller).
* CLUSTER_ADVERTISED_ADDR (optional) - wenn sich der Scanner auf einem anderen Host als der Controller befindet, um die Ergebnisse für die Verwendung in den Regeln für die Zulassungskontrolle zu senden (Controller mit Kubernetes-Einsatz).

=== Host-Scannen im Standalone-Modus

Verwenden Sie den folgenden Befehl, um den Host zu scannen.

[CAUTION]
====
Erfordert den privilegierten Modus!
====


[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n neuvector
----

=== Manuelle Bereitstellung von mehreren Scannern in Kubernetes

Um Scanner manuell als Teil einer bestehenden Kubernetes-Bereitstellung bereitzustellen, erstellen Sie eine neue Rollenbindung:

[,shell]
----
kubectl create rolebinding neuvector-admin --clusterrole=admin --serviceaccount=neuvector:default -n neuvector
----

Oder für OpenShift

[,shell]
----
oc adm policy add-role-to-user admin system:serviceaccount:neuvector:default -n neuvector
----

Verwenden Sie die folgende Datei, um mehrere Scanner einzusetzen. Bearbeiten Sie die Replikate, um die Anzahl der parallel laufenden Scanner zu erhöhen oder zu verringern.

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-scanner-pod
  namespace: neuvector
spec:
  selector:
    matchLabels:
      app: neuvector-scanner-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  template:
    metadata:
      labels:
        app: neuvector-scanner-pod
    spec:
      containers:
        - name: neuvector-scanner-pod
          image: neuvector/scanner
          imagePullPolicy: Always
          env:
            - name: CLUSTER_JOIN_ADDR
              value: neuvector-svc-controller.neuvector
# Commented out sections are required only for local build-phase scanning
#            - name: SCANNER_DOCKER_URL
#              value: tcp://192.168.1.10:2376
#          volumeMounts:
#            - mountPath: /var/run/docker.sock
#              name: docker-sock
#              readOnly: true
#      volumes:
#        - name: docker-sock
#          hostPath:
#            path: /var/run/docker.sock
      restartPolicy: Always
----

Als nächstes erstellen oder aktualisieren Sie den CVE-Datenbank-Updater-Cron-Job. Dadurch wird die CVE-Datenbank jede Nacht aktualisiert.

[,yaml]
----
apiVersion: batch/v1
kind: CronJob
metadata:
  name: neuvector-updater-pod
  namespace: neuvector
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: neuvector-updater-pod
        spec:
          containers:
          - name: neuvector-updater-pod
            image: neuvector/updater
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - TOKEN=`+cat /var/run/secrets/kubernetes.io/serviceaccount/token+`; /usr/bin/curl -kv -X PATCH -H "Authorization:Bearer $TOKEN" -H "Content-Type:application/strategic-merge-patch+json" -d '{"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"&apos;`+date +%Y-%m-%dT%H:%M:%S%z+`&apos;"}}}}}' 'https://kubernetes.default/apis/apps/v1/namespaces/neuvector/deployments/neuvector-scanner-pod'
          restartPolicy: Never
----
