= Fehlersuche
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /12.troubleshooting/01.troubleshooting/01.troubleshooting.md
:page-opendocs-slug:  /fehlersuche/problembehebung

== Fehlerbehebung {product-name} Einsätze

Die Container von {product-name} werden mit demselben Orchestrierungstool bereitgestellt, verwaltet und aktualisiert, das auch für die Anwendungs-Workloads verwendet wird. Bitte lesen Sie unbedingt die Online-Dokumentation zu den einzelnen Schritten, die während der Bereitstellung erforderlich sind. Oft werden Bereitstellungen versucht, indem einfach die yaml-Beispieldateien kopiert und bereitgestellt werden, ohne die vorhergehenden Schritte zu überprüfen, wie z. B. die ordnungsgemäße Konfiguration von Registrierungen, Geheimnissen oder RBACs/Rolebindings.

=== Ersteinsatz

* Prüfen Sie, ob die {product-name} Container mit korrekter Authentifizierung gezogen werden können. Überprüfen Sie das verwendete Geheimnis und stellen Sie sicher, dass der Cluster auf die entsprechende Registrierung zugreifen kann.
* Vergewissern Sie sich, dass die erforderlichen Änderungen an der yaml (z. B. NodePort oder LoadBalancer) oder an den Helm-Werte-Einstellungen entsprechend vorgenommen wurden.
* Überprüfen Sie die Plattform und die Container-Laufzeit und nehmen Sie ggf. Änderungen vor (z. B. PKS, containerd, CRI-O).

=== Anmeldung und Erstkonfiguration

* Stellen Sie sicher, dass der Zugriff auf den Manager (IP-Adresse, Port, Route) durch Firewalls erlaubt ist.

=== Laufender Betrieb

* Verzeichnisintegration. {product-name} unterstützt spezifische Konfigurationen für LDAP/AD und andere Integrationen für Gruppen und Rollen. Wenden Sie sich an {product-name}, um weitere Schritte zur Fehlerbehebung und ein Tool zur AD-Fehlerbehebung zu erhalten.
* Scannen der Registry. Die meisten Probleme stehen im Zusammenhang mit Authentifizierungsfehlern in der Registrierung oder der Unfähigkeit des Controllers, vom Cluster aus auf die Registrierung zuzugreifen.
* Vergewissern Sie sich bei Leistungsproblemen, dass dem Scanner genügend Speicher für das Scannen großer Bilder zugewiesen ist. Außerdem können in der Pod-Richtlinie Mindestanforderungen für CPU und Arbeitsspeicher festgelegt werden, um eine angemessene Leistung bei der Skalierung zu gewährleisten.
* Zulassungskontrolle. Siehe den Abschnitt Fehlerbehebung im Abschnitt Sicherheitsrisiken... -> Zulassungskontrollen.

=== Aktualisierung von

* Verwenden Sie rollende Updates für den Controller. Wenn Sie Hosts neu starten, überwachen Sie die Controller, wenn sie auf andere Hosts verschoben werden, oder stellen Sie sie auf den neu gestarteten Hosts neu bereit, um sicherzustellen, dass sie starten, dem Controller-Cluster beitreten und sich stabilisieren/synchronisieren können. Wenn alle Hosts auf einmal oder zu schnell neu gestartet werden, kann dies zu unbekannten Zuständen bei den Controllern führen.
* Verwenden Sie einen persistenten Volume-Anspruch, um die Konfiguration von {product-name} für den Fall zu speichern, dass alle Controller/Knoten im Cluster ausfallen.
* Wenn Sie auf eine neue Version aktualisieren, lesen Sie die Online-Dokumentation, um die erforderlichen Änderungen/Ergänzungen in der yaml-Datei sowie andere Änderungen wie z. B. Rollenverknüpfungen oder neue Dienste (z. B. Webhook für die Zulassungskontrolle, persistenter Volumenanspruch usw.) zu ermitteln.

== Debug-Protokolle

So zeigen Sie die Protokolle eines {product-name} Containers an, zum Beispiel eines Controller-Pods

[,shell]
----
kubectl logs neuvector-controller-pod-777fdc5668-4jkjn -n neuvector
----

Diese Protokolle können Probleme mit der Cluster-Konnektivität, Verwaltungsaktionen, Scan-Aktivitäten und andere nützliche Einträge enthalten. Wenn mehrere Steuergeräte in Betrieb sind, kann es notwendig sein, jedes einzelne zu überprüfen. Diese Protokolle können über eine Pipeline in eine Datei geleitet werden, die an den {product-name} Support gesendet wird.

=== Einschalten des Debug-Modus für {product-name} Steuerungen

Bei Problemen, die eine eingehende Untersuchung erfordern, kann der Debug-Modus für die Controller/Allinone aktiviert werden, der detaillierte Informationen protokolliert. Dies kann die Größe der Protokolldateien stark erhöhen, weshalb empfohlen wird, sie nach dem Sammeln der Daten zu deaktivieren.

=== Kubernetes, OpenShift und andere Orchestrierungsprotokolle

Es kann hilfreich sein, die Protokolle von Orchestrierungswerkzeugen zu prüfen, um alle Bereitstellungsaktivitäten zu sehen, einschließlich Zeitstempel und Status der Pod-Erstellung, Bereitstellungen, Daemonsets und andere Verwaltungsaktionen der {product-name} Container, die vom Orchestrierungswerkzeug durchgeführt werden.

[,shell]
----
kubectl get events -n neuvector
----

== Support-Protokoll

Das Supportprotokoll enthält zusätzliche Informationen, die für den {product-name} Support nützlich sind, einschließlich Systemkonfiguration, Container, Richtlinien, Benachrichtigungen und {product-name} Containerdetails.

Um das Support-Protokoll herunterzuladen, gehen Sie zu Einstellungen -> Konfiguration und wählen Sie Protokoll sammeln.

== Verwenden der CLI zum Einschalten des Debug-Modus

Melden Sie sich beim {product-name} manager pod mit Benutzer und Passwort an (empfohlen in einem separaten Terminalfenster).

[,shell]
----
kubectl exec -it neuvector-manager-pod-5bb76b6754-rlmnp -n neuvector -- cli
----

[,shell]
----
#neuvector-svc-controller.neuvector> login
----

Abrufen der Liste der Steuergeräte. Suchen Sie den Controller mit der Einstellung Leader = True.

[,shell]
----
show controller
----

Schalten Sie den Debug-Modus in der führenden Steuerung ein, indem Sie die ID oder den Namen der Steuerung verwenden

[,shell]
----
set controller 4fce427cf963 debug -c all
----

So aktivieren Sie den Debug-Modus auf allen Controllern

[,shell]
----
set system controller_debug -c all
----

Führen Sie die Aktivität in {product-name} aus, die Sie debuggen möchten. Zeigen Sie dann die Controller-Protokolle an (in einem separaten Terminalfenster).

[,shell]
----
kubectl logs <leader_controller_pod_name> -n neuvector
----

Erfassen Sie bei Bedarf die Protokolle und senden Sie sie an {product-name}.

Schalten Sie den Debug-Modus auf dem Controller aus (zurück im CLI-Fenster).

[,shell]
----
set controller 4fce427cf963 debug
exit
----

Prüfen Sie den Debug-Status des Controllers.

[,shell]
----
show controller setting 289d67396fcb
----

== Verwenden der REST-API zum Einschalten des Debug-Modus

Legen Sie ein Zugangstoken mit Ihrer IP, Ihrem Benutzer und Ihrem Passwort fest:

[,shell]
----
_controllerIP_="<your_controller_ip>"
_controllerRESTAPIPort_="10443"
_neuvectorUsername_="admin"
_neuvectorPassword_="admin"
----

[NOTE]
====
Für Kubernetes-basierte Bereitstellungen können Sie die Controller-IP in der folgenden Befehlsausgabe abrufen:
====

[,shell]
----
kubectl get pod -n neuvector -o wide | grep controller
----

[NOTE]
====
Wenn Sie von außerhalb des Clusters auf die REST-API zugreifen, lesen Sie die Anweisungen im Abschnitt Automatisierung.
====

Abrufen des Authentifizierungstokens

[,shell]
----
curl -k -H "Content-Type: application/json" -d '{"password": {"username": "'$_neuvectorUsername_'", "password": "'$_neuvectorPassword_'"}}' "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/auth" > /dev/null 2>&1 > token.json
_TOKEN_=`+cat token.json | jq -r '.token.token'+`
----

[NOTE]
====
Möglicherweise müssen Sie jq installieren ($sudo yum install jq)
====

Debug-Modus einschalten

[,shell]
----
curl -X PATCH -k -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_" -d '{"config": {"controller_debug": ["cpath", "conn"]}}' "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/system/config"  > /dev/null 2>&1   > set_debug.json
#debug options - cpath, conn, mutex, scan, cluster , all
----

Debuggen auf allen Controllern eines Clusters deaktivieren

[,shell]
----
curl -X PATCH -k -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_" -d '{"config": {"controller_debug": []}}' "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/system/config"  > /dev/null 2>&1   > set_debug.json
----

Prüfen des Debug-Status des Controllers in einem Cluster

[,bash]
----
curl  -k -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_"  "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/system/config"  > /dev/null 2>&1   > system_setting.json

cat system_setting.json | jq .config.controller_debug
----

Abmeldung

[,shell]
----
echo `+date +%Y%m%d_%H%M%S+` log out
curl -k -X 'DELETE' -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_" "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/auth" > /dev/null 2>&1
----
