= Notes de version 5.x
:revdate: 2025-08-26
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/01.5x/01.5x.md
:page-opendocs-slug:  /notesdeversion/5x

== Notes de version pour 5.x

[NOTE]
====
Pour recevoir des notifications par e-mail sur les nouvelles versions, veuillez vous abonner à cette liste de diffusion SUSE : https://lists.suse.com/mailman/listinfo/neuvector-updates
====

=== 5.4.6 Août 2025

==== Nouvelles fonctionnalités

* *NVSHAS-6733*: Exporter les règles de réponse en tant que CRD.
* *NVSHAS-9899*: Les alertes de profil NeuVector pour les services Java contiennent des données sensibles.
* *NVSHAS-9990*: Adopter un nouvel algorithme de hachage pour les mots de passe des utilisateurs.
* *NVSHAS-9968*: Support pour définir le mot de passe par défaut du compte admin par défaut.

==== Bugs corrigés

* *NVSHAS-10062*: Le gestionnaire n'affiche pas d'ERREUR lorsque la création du mot de passe admin échoue au 1. La connexion échoue.
* *NVSHAS-10041*: Échec de l'opération de fédération "données invalides" lors de la configuration de la fédération via ConfigMap.
* *NVSHAS-10018*: Neuvector ne scanne pas toutes les images dans le registre GitLab.
* *NVSHAS-10017*: Alerte de sécurité faussement positive liée à un processus autorisé.
* *NVSHAS-10001*: Les protections/contrôles de surveillance "persistent" après la suppression du groupe.
* *NVSHAS-9985*:    NeuVector (Fed Master) cause un problème pour toutes les demandes externes.
* *NVSHAS-9981*:    Un événement de sécurité est déclenché lorsqu'une nouvelle "règle de profil de processus" est ajoutée ou modifiée dans un groupe.

==== Sicherheitswarnungen

* https://github.com/neuvector/neuvector/security/advisories/GHSA-8pxw-9c75-6w56[Le compte admin a un mot de passe par défaut non sécurisé]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-8ff6-pc43-jwv3[Gestion des mots de passe non sécurisée vulnérable aux attaques par rainbow table]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-w54x-xfxg-4gxq[Le processus avec des arguments sensibles entraîne des fuites de données]

Voir la documentation xref:cve.adoc[conseils de sécurité et CVEs] pour plus d'informations.

=== 5.4.5 Juillet 2025

==== Nouvelles fonctionnalités

* *NVSHAS-9776*: Fügen Sie etcd-Toleranz im Helm-Diagramm hinzu.

==== Corrections de bogues

* *NVSHAS-9507*: Les conteneurs OCI ne sont pas scannés.
* *NVSHAS-9787*: Supprimez les journaux de gestion inutiles.
* *NVSHAS-9788*: Affiner l'algorithme de génération de certificats.
* *NVSHAS-9789*: Supprimez les journaux de gestion inutiles lors de la configuration du service d'enregistrement à distance.
* *NVSHAS-9867*: NeuVector affiche `+.NET Library System.Formats.Asn1 v8.013+` CVE 2024-38095 affectés.
* *NVSHAS-9883*: [quay.io] Les filtres wildcard ne fonctionnent pas pour Docker Registry.
* *NVSHAS-9911*: Le scan du dépôt via l'API REST entraîne un message "incorrect".
* *NVSHAS-9930*: CVE-2018-20796 pour `+glibc/libc-bin : 2.36-9+deb12u10+` – Faux positif.
* *NVSHAS-9933*: La fonction d'adaptateur de registre (Harbor) affiche des erreurs dans le registre cible lors du scan.
* *NVSHAS-9934*: Suspicion de dysfonctionnement de la fonctionnalité Zero-Drift.
* *NVSHAS-9940*: Problème de mode de sous-domaine NV-Scan JFrog.
* *NVSHAS-9942*: Les analyses d'images pour les images des clients échouent.
* *NVSHAS-9945*: Lorsque le nom du processus est trop long, il est difficile de déterminer comment la règle de profil de processus correspondante peut être créée.
* *NVSHAS-9946*: Problème d'affichage avec l'avertissement de contrôle d'admission pour le type de connexion.
* *NVSHAS-9947*: [UI-ext] Le diagramme de conformité manque de l'état "Manuel" dans Rancher NeuVector.
* *NVSHAS-9948*: Après la mise à niveau vers `+5.4.3+`, la configuration de NeuVector a été perdue.
* *NVSHAS-9949*: [Harbor][Mauvais utilisateur/Mot de passe] Il continue de scanner les images, même en cas de saisie incorrecte de l'utilisateur/mot de passe.
* *NVSHAS-9952*: Retirez 'Signature' du rapport d'utilisation, car NV ne délivre/valide plus la clé de licence.
* *NVSHAS-9953*: Les pods Enforcer redémarrent constamment.
* *NVSHAS-9954*: L'exportateur Prometheus de NeuVector génère des métriques en double.
* *NVSHAS-9958*: L'application des règles réseau prend du temps.
* *NVSHAS-9960*: Les scanners ne fonctionnent pas.
* *NVSHAS-9969*: Erreurs fatales : les modifications simultanées des cartes entraînent le redémarrage du composant Enforcer.
* *NVSHAS-9971*: NV UI via `+Get Bootstrap Password+`.
* *NVSHAS-9975*: [Manager] TypeError : `+this.mousemoveListener+` n'est pas une fonction observée dans l'interface utilisateur NV.
* *NVSHAS-9986*: Les règles d'accès aux processus et aux fichiers ne peuvent pas être modifiées ou supprimées dans la vue du groupe de politiques fédérées.
* *NVSHAS-9988*: UI : Les pages de groupe n'affichent pas tous les groupes lorsqu'il y a plus de 2 000 groupes.
* *NVSHAS-9991*: Le groupe `+nv.gatekeeper-controller-manager.openshift-azure-guardrails+` est manquant dans l'interface utilisateur.
* *NVSHAS-9993*: Remplacer MD5 par SHA256.
* *NVSHAS-9994*: Le pod Enforcer redémarre constamment.
* *NVSHAS-9996*: Le diagramme Helm doit permettre le mode non privilégié des pods Enforcer.
* *NVSHAS-9998*: Impossible d'exporter le groupe depuis le maître de fédération NeuVector.
* *NVSHAS-10000*: Mettre à niveau NV vers BCI 15.7.
* *NVSHAS-10003*: Le rechargement de la page ne fonctionne pas sur la page autonome de NV pendant que l'interface utilisateur Rancher est ouverte.
* *NVSHAS-10008*: Analyse du registre – Le menu d'affichage est défectueux pour l'image scannée.
* *NVSHAS-10010*: Le flood TCP SYN bloque l'entrée, ce qui entraîne un blocage complet du trafic entrant.

=== 5.4.4 Mai 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9915**: Afficher les résultats de l'analyse du module scanner Harbor dans l'interface utilisateur NeuVector.
* **NVSHAS-9904**: Exposer `+imagePullPolicy+` à `+values.yaml+` pour chaque composant.
* **NVSHAS-9869**: UI : Déplacer les contrôles DDoS dans la fenêtre de groupe.
* **NVSHAS-9840**: [GCP] Support Autopilot NeuVector pour GCP.
* **NVSHAS-9248**: Afficher les règles de processus/réseau inutilisées avec des compteurs et un horodatage `+Last Used+`.
* **NVSHAS-8160**: [Contrôleur] Ajustez certains éléments pour le calcul de la valeur de risque de sécurité.
* **NVSHAS-4673**: Proposition d'ajouter un message avant d'exporter des groupes.

==== Corrections de bogues

* **NVSHAS-9931**: Ajoutez un avertissement lorsque des versions incohérentes des produits NeuVector sont présentes dans un multi-cluster.
* **NVSHAS-9925**: Échec de l'API `+/v1/scan/asset/images+` sur la page d'enregistrement.
* **NVSHAS-9913**: Problème lors de la suppression de plusieurs règles réseau associées aux groupes Workload:XYZ.
* **NVSHAS-9912**: Mettez à jour Helm via certaines autorisations RBAC K8s requises par le compte de service du contrôleur.
* **NVSHAS-9909**: Le message "Déconnecté - Aller à la page de chargement" s'affiche lorsque le lien NavLink de NeuVector Rancher est utilisé.
* **NVSHAS-9898**: Dans un environnement fédéré, changer les critères d'un groupe fed.* créé par le client (par exemple, fed.core-systems) ne fonctionne pas.
* **NVSHAS-9894**: [Enforcer] `+Nv.protect+` refuse la commande de vérification de disponibilité du contrôleur `+cat /tmp/ready+`.
* **NVSHAS-9886**: L'activité réseau ne résout pas les noms de domaine pour les connexions de groupes externes personnalisés.
* **NVSHAS-9884**: [Scan de nœud][Scan de conteneur] L'analyse a échoué.
* **NVSHAS-9873**: Problème de recherche de filtre avancé de l'UI dans NeuVector 5.4.2.
* **NVSHAS-9865**: Les politiques réseau exportées diffèrent en fonction de l'ordre de sélection (les mêmes groupes sélectionnés).
* **NVSHAS-9828**: [Enforcer: Processus] Le NeuVector Enforcer ne peut pas détecter les Pods éphémères (moins de 5 secondes).
* **NVSHAS-9783**: Après l'ajout de la politique réseau pour refuser les paquets ICMP, NeuVector ne voit pas d'avertissements dans `+Security Events+`.
* **NVSHAS-9176**: Affiche une erreur de script sur la **Risques de sécurité > Vulnérabilités** page, lorsque l'utilisateur avec la permission dans l'espace de noms `+rt_scan:w+` est connecté.

=== 5.4.3 Mars 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9793**: Autoriser les rôles globaux Fed dans LDAP/userinitcfg lors du déploiement de NeuVector via le ConfigMap et Secret.
* **NVSHAS-9764**: [RFE] Ajouter le support pour Azure pour "Configuration de dépôt à distance".
* **NVSHAS-9759**: Ajouter des détails de date dans le rapport d'exposition Ingress.
* **NVSHAS-9755**: Demande d'affichage des noms des variables d'environnement à côté des valeurs dans les avertissements pour les secrets.
* **NVSHAS-9748**: [Helm] Mise à jour de NeuVector Helm pour prendre en charge les références de noms pour les groupes partagés dans CRD (NVSHAS0-4717).
* **NVSHAS-9426**: Ajouter hostPath pour le scanner au diagramme Helm.
* **NVSHAS-9326**: NeuVector - Module de scanner pluggable Harbor.
* **NVSHAS-9835**: Interface pour désactiver le scan automatique pour les nœuds.
* **NVSHAS-7997**: Connecteur de scanner pour ghcr.io.
* **NVSHAS-7982**: Attribuer des capteurs WAF depuis le maître de fédération.

==== Corrections de bogues

* **NVSHAS-9849**: Les enforceurs ne s'enregistrent pas auprès des contrôleurs.
* **NVSHAS-9847**: Les filtres wildcard ne fonctionnent pas pour Docker Registry.
* **NVSHAS-9833**: La restauration de la configuration échoue dans les déploiements Rancher.
* **NVSHAS-9832**: Problème lors de la création de règles réseau avec le groupe de charges de travail.
* **NVSHAS-9821**: Le nom du processus ne correspond pas à la ligne de commande pour l'avertissement de règle de gain de processus.
* **NVSHAS-9817**: La création de la CRD NvClusterSecurityRule montre une création réussie, mais elle n'a pas été réellement créée en raison d'entrées de processus en double.
* **NVSHAS-9812**: NeuVector prometheus-exporter renvoie de fausses métriques.
* **NVSHAS-9811**: [Manager] Impossible d'accéder à l'interface graphique lorsque un certificat personnalisé (CA) avec Root-CA et Intermediate-CA est utilisé dans le secret.
* **NVSHAS-9801**: Le mode FIPS + `+manager.env.ssl=false+` entraîne une erreur dans le Manager.
* **NVSHAS-9792**: La synchronisation de la politique de fédération échoue car la taille du corps dépasse le maximum de Consul.
* **NVSHAS-9784**: NeuVector renvoie 404 lors de l'analyse du dépôt d'images Jfrog.
* **NVSHAS-9783**: Après l'ajout de la politique réseau pour refuser les paquets ICMP, l'utilisateur ne voit aucun avertissement dans "Événements de sécurité".
* **NVSHAS-9780**: NeuVector Single Sign-On ne fonctionne pas avec Rancher NavLink.
* **NVSHAS-9777**: Webhook-JSON avec des clés "Level" en double.
* **NVSHAS-9770**: Le commutateur automatique après le mode Zero-Drift active la mauvaise politique.
* **NVSHAS-9765**: L'accès aux fichiers n'est pas complètement bloqué en mode protection.
* **NVSHAS-9756**: Le contrôleur a atteint l'utilisation maximale du CPU et a plusieurs avertissements de pression mémoire.
* **NVSHAS-9668**: Le test de conformité échoue sur RKE2.
* **NVSHAS-9265**: Résultats incomplets et incorrects du scan de vulnérabilités dans l'environnement PRE-PCI.
* **NVSHAS-9227**: Le scan du registre se bloque au milieu du processus de scan et passe en état "inactif".
* **NVSHAS-9729**: Un nombre incorrect de vulnérabilités est observé lorsque plusieurs StatefulSets avec le "même nom" sont déployés dans des namespaces d'un projet.
* **NVSHAS-9810**: Le contrôleur NeuVector ne répond pas et l'interface utilisateur n'est pas accessible.

=== 5.4.2 Janvier 2025

==== Nouvelles fonctionnalités

* **NVSHAS-9726**: Le moniteur transmet maintenant l'URL du proxy.
* **NVSHAS-9719**: Gibt die Stilllegung von integrierten Zertifikaten bekannt.
* **NVSHAS-9715**: Support des valeurs de Helm Chart pour définir le Nodeport pour le contrôleur et le gestionnaire.
* **NVSHAS-9710**: Ajoutez une colonne `+feed_rating+` triable dans l'onglet **Vulnérabilités**.
* **NVSHAS-9669**: Gesamtbewertung der Sicherheit über die REST-API.
* **NVSHAS-9590**: Möglichkeit, welche Schwachstellenbewertung für alle Assets auszuwählen.
* **NVSHAS-7555**: Ajoutez l'option "Mise à jour automatique" sous Événements de sécurité.

==== Corrections de bogues

* **NVSHAS-9662**: Logique de liaison de rôle/rôles incohérente dans le Helm Chart 2.8.2.
* **NVSHAS-9652**: Différence observée dans le format Syslog dans Splunk.
* **NVSHAS-9649**: Le lien du conteneur génère un code de réponse 404 dans l'événement de sécurité.
* **NVSHAS-9613**: Erreur du pod du gestionnaire NeuVector / Interface Web NeuVector non disponible.
* **NVSHAS-9507**: Les conteneurs OCI ne sont pas scannés.
* **NVSHAS-9443**: La mise à niveau/l'installation via ArgoCD échoue car elle ne peut pas créer l'objet leases.coordination.k8s.io.
* **NVSHAS-9436**: Faux positif CVE possible contre CVE-2024-7347.
* **NVSHAS-8386**: Les clés privées et les certificats auto-signés continuent d'être livrés dans plusieurs images.
* **NVSHAS-9754**: [UI] Empêcher les utilisateurs SSO liés à Rancher de désactiver l'authentification d'OpenShift ou le RBAC de Rancher.
* **NVSHAS-9751**: [Protection à l'exécution] Le mode de surveillance + le drift nul ne génère pas d'alertes lorsqu'un processus enfant est en cours d'exécution.
* **NVSHAS-9721**: L'interface utilisateur doit afficher un message d'erreur approprié lorsque l'utilisateur saisit un nom d'enregistrement incorrect.
* **NVSHAS-9696**: Affichage des couleurs incohérentes des actifs sur la page des vulnérabilités.
* **NVSHAS-9686**: Espace de noms codé en dur pour le certificat de l'adaptateur d'enregistrement dans le graphique Helm de Neuvector.
* **NVSHAS-9678**: Messages d'erreur excessifs après les modifications du linter.
* **NVSHAS-9670**: Gestionnaire: Problème avec les guillemets doubles dans la réponse et problème de bibliothèque Java sans nom dans l'exécution sbt.
* **NVSHAS-9667**: Définir la variable d'environnement `+CTRL_PATH_DEBUG+` sur des erreurs dans le déploiement du contrôleur ne fonctionne pas.
* **NVSHAS-9665**: Règle d'accès aux fichiers: La suppression des règles prédéfinies génère une erreur "setRowData".
* **NVSHAS-9664**: Groupe de politiques: La suppression du script personnalisé génère une erreur de type "setRowData".

[NOTE]
====
Les types par défaut du service Manager et de l'adaptateur de registre ont été modifiés en ClusterIP.  Les utilisateurs peuvent toujours remplacer le paramètre en remplaçant `+manager.svc.type+` et `+cve.adapter.svc.type+` lorsque NodePort est préféré.
====

Dans la version 5.4.2 de NeuVector, le support pour les déploiements utilisant le certificat interne intégré sera arrêté. Le certificat situé à `+/etc/neuvector/certs/internal+` dans les images de conteneur NeuVector 5.4.2 sera supprimé. Pour continuer à utiliser NeuVector, les utilisateurs doivent :

==== 5.4.2 Nouvelle installation :

===== Utilisation de Helm :

- Activez les drapeaux `+internal.autoGenerateCert+` et `+internal.autoRotateCert+` dans les diagrammes Helm (ceux-ci seront activés par défaut à partir de la version 5.4.2). Alternativement, une méthode YAML est liée ci-dessous.

===== Verwendung von YAML:

- Déployez un xref:internal.adoc#_replacing_certificates_used_in_internal_communications_of_suse_security[certificat interne avec les méthodes existantes].

==== Mise à niveau des versions précédentes vers 5.4.2 :

Il est toujours recommandé de faire une sauvegarde de votre configuration avant la mise à niveau. Les étapes suivantes ne sont nécessaires que si votre déploiement utilise un fichier . 

La mise à niveau avec Helm ne nécessite pas ces étapes supplémentaires, car les certificats internes sont créés par défaut via les drapeaux suivants :  et . Exemple 5.4.2 yaml configuré avec certificat interne :
*

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/ca.cert" > ca.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.pem" > tls.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.key" > tls.key
----

[,shell]
----
kubectl create secret generic internal-cert -n neuvector  --from-file=tls.key --from-file=tls.crt --from-file=ca.crt
----

Informations supplémentaires sur https://github.com/neuvector/manifests/blob/main/kubernetes/5.4.0/neuvector-k8s.yaml*certificats internes*. 

Zusätzliche Informationen zu xref:internal.adoc[internen Zertifikaten].


Remarque supplémentaire pour le scanner :


Pour les utilisateurs actuels avec des versions antérieures à 5.4.2, le certificat restera valable jusqu'au 31.

. Disponible en mars 2025 dans `+neuvector/scanner:latest+`. Après cette date, il sera supprimé. Les utilisateurs doivent prévoir de fournir le même certificat interne au contrôleur, à l'exécuteur, au scanner et à l'adaptateur d'enregistrement pour continuer à utiliser le scanner.

Veuillez noter que le scanner autonome ne sera pas affecté par ces changements.

=== 5.4.1 Novembre 2024

==== Nouvelles fonctionnalités

* **NVSHAS-8583**: Définir des modes de politique granulaires pour les ensembles de règles, le mode de politique réseau séparé et le mode de profil au niveau des groupes.
* **NVSHAS-9440**: Support du mode réseau séparé et du mode processus et fichier dans CRD.
* **NVSHAS-9369**: Debug-Protokollkategorie über Helm-Bereitstellungsunterstützung für den Controller hinzufügen.
* **NVSHAS-9040**: Améliorer le message Syslog lorsque la règle de contrôle d'admission est rejetée en mode de surveillance.

==== Corrections de bogues

* **NVSHAS-9416**: [Scanner] activemq-all-5.8.0.redhat-60024.jar ne peut pas être reconnu par aucun vul (mais la version précédente du scanner peut).
* **NVSHAS-9447**: Les pods contrôleur/scanner se bloquent - "Sortie système non prise en charge".
* **NVSHAS-9278**: CVE-2024-41110 a été trouvé dans la dernière image du scanner.
* **NVSHAS-9467**: Le groupe personnalisé défini par l'étiquette du pod ne propage pas ses données de profil aux conteneurs enfants.
* **NVSHAS-9442**: Bereitstellungsproblem bei ArgoCD.
* **NVSHAS-9436**: Faux positif CVE possible contre CVE-2024-7347.
* **NVSHAS-9468**: Corrigez CVE-2020-26160 pour remplacer jwt-go par jwt:v5.
* **NVSHAS-9517**: Le contrôle d'admission est incohérent et renvoie des résultats incorrects.
* **NVSHAS-9532**: Le scan d'image est terminé, mais le déploiement n'est toujours pas autorisé.
* **NVSHAS-9558**: JWT-Token-Ablauf meldet http.StatusRequestTimeout 408.
* **NVSHAS-9576**: Supprimez le champ de mot de passe pour les données d'inscription lorsque l'utilisateur utilise le mode contrôleur avec Jenkins pour le scan.
* **NVSHAS-9425**: Créez nfq si le conteneur a vxlan.
* **NVSHAS-9571**: [Registres] Le filtre pour toutes les images scannées ne fonctionne pas bien.
* **NVSHAS-9589**: Clusters gérés séparément - Conflit de version avec le cluster principal.
* **NVSHAS-8824**: L'utilisateur ne peut pas supprimer ses propres groupes, ne peut pas créer de groupes spécifiques à l'espace de noms.
* **NVSHAS-9605**: Le groupe d'exportation avec des valeurs non valides pour le mode de politique et le mode de profil de processus est incorrectement autorisé.
* **NVSHAS-9608**: Le scanner ne signale pas d'erreur lorsque le contrôleur signale une erreur pour de grands résultats de scan ~23MB.
* **NVSHAS-9534**: Afficher les erreurs dans les contrôles d'admission.
* **NVSHAS-9600**: Le débogage du contrôleur ne peut pas être désactivé.
* **NVSHAS-9631**: Réduisez certaines erreurs d'application.
* **NVSHAS-9645**: Le traitement des CRDs existants échoue.
* **NVSHAS-9592**: Aucun nouveau scan malgré la nouvelle version de la base de données.
* **NVSHAS-9212**: Afficher un message d'avertissement dans GET(/v1/eula) lorsque le rôle (Binding) du neuvector-binding-secret est incorrect.
* **NVSHAS-9367**: Améliorez les messages d'erreur lorsque l'enregistrement ne peut pas être connecté.
* **NVSHAS-9475**: L'impression de la grille d'arrière-plan ne couvre pas complètement lorsque le menu est minimisé.
* **NVSHAS-9485**: Message incorrecte pour 'Mode de politique de sécurité réseau' dans l'interface utilisateur.
* **NVSHAS-9480**: L'interface utilisateur NV déployée dans le cluster en aval de Rancher renvoie HTTP/403 après la déconnexion de Rancher.
* **NVSHAS-9547**: Le tri est défectueux dans le tableau des risques de sécurité --> Vulnérabilités.
* **NVSHAS-9570**: [Vulnérabilités] Modifiez la description de la légende pour différents statuts des actifs.
* **NVSHAS-9561**: L'évaluation globale de l'affichage de sécurité doit correspondre à l'évaluation réelle.
* **NVSHAS-9572**: [Vulnérabilités] Les données filtrées ont été conservées indépendamment de la mise à jour par l'utilisateur ou de la reconnexion sur la page.
* **NVSHAS-9597**: L'interface utilisateur ne réagit pas aux erreurs lorsque le contrôleur renvoie 403 pour POST(v1/group).
* **NVSHAS-8682**: Le service Webhook CRD doit être déplacé du diagramme Helm CRD vers le diagramme Helm de l'application.

==== Problèmes connus

* Dans la version 2.8.3 du diagramme, nous avons déplacé une ressource précédemment mal attribuée de crds à noyau. Si vous utilisez à la fois des diagrammes crds et noyau, des problèmes peuvent survenir lors de la mise à niveau si vous déployez d'abord le noyau. Pour résoudre cela, mettez d'abord à jour les crds puis les diagrammes noyau.

=== 5.4 Septembre 2024

* **Améliorations de l'UI**: 
** Afficher les utilisateurs SSO de Rancher.
** JWT-Token verwalten.
** Navigation d'image avancée et liens vers les résultats de scan.
* **Améliorations de la sécurité**: 
** Nouveaux filtres de conformité.
** Support pour les benchmarks CIS et la signature d'images OCI.
* **Réseau & Surveillance**: 
** Suivi avancé de la bande passante et des sessions.
** DDoS-Überwachung.
** Multus-Netzwerkunterstützung.
* **Gestion des certificats**: 
** Neue Benachrichtigungen für ablaufende interne Zertifikate, einschließlich Rotationsmöglichkeiten.
* **Automatisation & Intégration**: 
** Automatisation de la fédération.
** Intégration RBAC de Rancher.
** Amélioration du contrôle d'accès.
* **Performance & Efficacité**: 
** Réduction de la consommation de mémoire.
** Réduction des coûts de données ISP.
** Divulgation des statistiques de cache du scanner.
* **Benutzerfreundlichkeitsverbesserungen**: 
** Support pour les mots de passe Bootstrap.
** Archivierung von Cloud-Abrechnungsdaten.
** Application des limites d'espace de noms.

==== Nouvelles fonctionnalités

* **NVSHAS-9012**: Affichage des utilisateurs SSO Rancher dans l'interface utilisateur NV avec le même nom d'utilisateur.
* **NVSHAS-8939**: Fournir une option dans l'interface utilisateur NV pour que les utilisateurs de session SSO Rancher puissent déposer le jeton JWT actuel (c'est-à-dire. déconnexion).
* **NVSHAS-7522**: Navigation d'image simple à travers les enregistrements.
* **NVSHAS-8148**: Lien de l'image du conteneur vers les résultats de scan de l'image d'enregistrement.
* **NVSHAS-9258**: Fügen Sie eine neue Benachrichtigung für ablaufende Zertifikate und interne Zertifikate hinzu.
* **NVSHAS-8915**: Support pour de nouveaux filtres de conformité et rapport de conformité.
* **NVSHAS-9403**: Interface utilisateur de Filemonitor: Erlauben Sie dem Benutzer, eine vordefinierte Dateiüberwachungsregel zu löschen.
* **NVSHAS-8423**: Détection de la bande passante au niveau des groupes, nombre de sessions actives et violations des taux de session basées sur des seuils configurés.
* **NVSHAS-9218**: Support pour les groupes fédéraux et CRD pour la surveillance DDoS.
* **NVSHAS-8461**: Support des benchmarks CIS pour les services k8s gérés dans le cloud.
* **NVSHAS-7664**: Réduction des frais de données ISP pendant le scan d'enregistrement.
* **NVSHAS-8868**: Dévoiler les statistiques du cache du scanner.
* **NVSHAS-8676**: Amélioration de NV Protect pour les scripts de benchmark.
* **NVSHAS-9255**: Ajustement des enregistrements de recherche pour le contrôle d'admission pour les noms d'images sans FQDN.
* **NVSHAS-9144**: ID ajoutée pour le profil de vulnérabilité pour une identification facile.
* **NVSHAS-7687**: Support de la configuration du niveau de journal (déboguer/erreur/info/avertir) pour le contrôleur et le moteur via l'interface de ligne de commande.
* **NVSHAS-7518**: Modifier les certificats internes pour les composants {product-name}.
* **NVSHAS-9287**: Activer la rotation des certificats internes.
* **NVSHAS-8562**: Fügen Sie eine Benachrichtigung über das Ablaufdatum interner Zertifikate hinzu.
* **NVSHAS-8486**: Support de l'interface réseau Multus.
* **NVSHAS-7447**: Intégration RBAC Rancher avec {product-name}.
* **NVSHAS-7822**: Automatisation de la fédération sans appels d'API de script.
* **NVSHAS-8799**: Créer un cadre de conformité pour l'importation de modèles de conformité.
* **NVSHAS-8773**: Support du mot de passe Bootstrap lors du premier déploiement.
* **NVSHAS-6740**: Amélioration du profil de référence de dérive nulle en appliquant la liste apprise en mode protection.
* **NVSHAS-8325**: Application de la limite de l'espace de noms des conteneurs pour les règles réseau.
* **NVSHAS-8723**: Archivieren von Cloud-Abrechnungsdaten.
* **NVSHAS-9086**: Réduction de la consommation de mémoire du processus de contrôleur en éliminant la structure de données vulTrait.
* **NVSHAS-6979**: Möglichkeit, den Kommentar der Antwortregel im Alarminhalt einzuschließen.
* **NVSHAS-8845**: Créer une clé API avec le rôle FedReader et FedAdmin.
* **NVSHAS-9306**: L'évaluation de la configuration du contrôle d'admission montre l'ID de règle responsable des déploiements autorisés ou refusés.
* **NVSHAS-9078**: Support pour la signature d'images pour les images OCI.
* **NVSHAS-7945**: Support du benchmark DISA STIG pour Kubernetes.
* **NVSHAS-8234**: Logique de contrôle d'admission qui permet des images qui devraient être refusées.

==== Corrections de bogues

* **NVSHAS-9005**: TypeError dans les registres : Impossible de lire les propriétés d'une valeur indéfinie (lecture de 'total_records').
* **NVSHAS-9085**: Le rapport PDF sur la vue des actifs montre 0 % de vulnérabilité, même en présence de vulnérabilités.
* **NVSHAS-9084**: Le rapport PDF sur la vue des actifs montre NaN lorsque la liste des images est vide.
* **NVSHAS-9128**: Événements de sécurité : Les conteneurs ne peuvent pas être affichés s'il n'y a pas de valeur pour l'espace de noms de la charge de travail.
* **NVSHAS-9025**: Domaine d'acceptation des vulnérabilités Neuvector pour les conteneurs.
* **NVSHAS-9155**: Nom de colonne incorrect et nom de fichier manquant pour l'image de scan du registre.
* **NVSHAS-9122**: Les journaux principaux de Neuvector se déconnectent à tout moment lorsque "Multiple Cluster" est utilisé avec la connexion SSO de Rancher.
* **NVSHAS-9266**: Scan du registre: Le bouton "Rapport de scan par couche" doit être masqué ou désactivé s'il n'y a pas de vulnérabilité.
* **NVSHAS-9219**: Permettre aux utilisateurs d'activer la validation des certificats de serveur pour les serveurs d'authentification.
* **NVSHAS-9246**: Le filtrage pour l'exportation CSV/PDF ne fonctionne pas.
* **NVSHAS-8947**: La configuration NV ne peut pas être importée lorsqu'elle est authentifiée via Rancher SSO.
* **NVSHAS-9282**: UI : La modification de l'entrée du registre OpenShift échoue en raison d'un jeton manquant.
* **NVSHAS-9098**: Améliorez l'expérience utilisateur lors du chargement de la page de risque.
* **NVSHAS-9267**: Ne permettez pas à l'interface utilisateur dans le cluster maître 5.4 de passer à des clusters gérés avant 5.4, en raison de modifications de l'API REST.
* **NVSHAS-9285**: UI: Le bouton de la liste déroulante se chevauche avec d'autres éléments.
* **NVSHAS-9302**: Impossible de créer une clé API avec le rôle FedReader et FedAdmin.
* **NVSHAS-8539**: La reconfiguration des paramètres proxy perd le mot de passe.
* **NVSHAS-9293**: Suppression des détails d'image non pertinents dans les rapports de sécurité.
* **NVSHAS-9238**: L'interface utilisateur ne met pas à jour le nom du cluster affiché après le changement.
* **NVSHAS-9363**: Configuration des notifications > La grille des webhooks n'est pas correctement alignée.
* **NVSHAS-9362**: Le filtre de vulnérabilités de risque de sécurité renvoie 0 résultats.
* **NVSHAS-8699**: Impossible de distinguer l'utilisateur lorsque l'utilisateur AD Rancher est le même.
* **NVSHAS-9062**: Affichage des utilisateurs SSO Rancher dans l'interface NV, ayant le même nom d'utilisateur (conversion sur le contrôleur).
* **NVSHAS-9071**: Certains modules ne sont pas signalés uniquement dans le scan du conteneur.
* **NVSHAS-8242**: appel gRPC pour tester si le contrôleur gère les niveaux de gravité critiques.
* **NVSHAS-8908**: Analyser correctement le X-Forwarded-Port en tenant compte du séparateur de virgule.
* **NVSHAS-9024**: Risque de rôle AdmissionControl Perf.
* **NVSHAS-9091**: Impossible de signaler tous les modules sous ol:9.1, photon:5.0, rhel:9.1 et amzn:2023 dans le scan Repo, Registry et Standalone.
* **NVSHAS-8997**: Réduire considérablement le nombre de slots de politiques par nœud pour améliorer les performances.
* **NVSHAS-9059**: Les groupes CRD sont visibles dans NV, même après leur suppression de K8s.
* **NVSHAS-9107**: Goroutine-Absturz bei rest.handlerConfigLocalCluster.
* **NVSHAS-9108**: Le port 18500 ne doit pas être ouvert.
* **NVSHAS-9119**: Goroutine-Absturz bei probe.(*FileNotificationCtr).AddContainer().
* **NVSHAS-9125**: L'entrée CRD avec des paramètres invalides ne devrait pas être créée.
* **NVSHAS-9124**: Docker: De nombreux incidents inattendus dans le processus de vérification de la santé sont signalés.
* **NVSHAS-9111**: NV devrait vérifier `+--event-qps > 0+`.
* **NVSHAS-9130**: Des incidents inattendus de Container.Package.Updated sont trouvés après le démarrage d'un certain conteneur.
* **NVSHAS-9080**: L'utilisateur du lecteur Fed ne peut pas accéder à certaines API REST.
* **NVSHAS-9092**: L'utilisateur avec un espace de noms ne devrait pas voir d'actifs globaux.
* **NVSHAS-9116**: Le cluster de travail peut être quitté si la connexion est interrompue.
* **NVSHAS-8980**: Interface hôte et tunnel sur le nœud récupérée avec succès dans oc 4.15.
* **NVSHAS-9188**: Définir l'interface mgmt-br comme interface hôte pour le nœud de récolte.
* **NVSHAS-4858**: Ne pas étendre les groupes de conteneurs dans le contrôleur pour améliorer les performances de déploiement des politiques et réduire l'utilisation du CPU et de la mémoire.
* **NVSHAS-8700**: L'utilisateur AD Rancher ne peut parfois pas se connecter à {product-name}.
* **NVSHAS-9121**: Le paramètre de seuil de surveillance du réseau du groupe ne peut pas être modifié.
* **NVSHAS-9189**: Le scan restera bloqué dans le calendrier après l'arrêt et le redémarrage du contrôleur.
* **NVSHAS-9019**: Corriger l'état de lien non synchronisé pour l'interface hôte.
* **NVSHAS-8305**: Supprimer le certificat intégré.
* **NVSHAS-9013**: Supprimer le filtre BPF dans le moniteur de processus.
* **NVSHAS-7853**: TLS-Handshake EOF.
* **NVSHAS-9290**: La règle de profil de processus ajoutée par l'utilisateur n'a aucun effet avec ZD activé.
* **NVSHAS-9301**: NV, déployé sur Rancher Prime, ne peut pas reconnaître qu'il s'agit de la version Rancher.
* **NVSHAS-9289**: Autoriser la mise à niveau si RBAC est manquant.
* **NVSHAS-7601**: Améliorez la récupération à partir de la sauvegarde de configuration PV pendant les scénarios.
* **NVSHAS-7687**: Ajoutez le paramètre de niveau Syslog pour le contrôleur.
* **NVSHAS-9292**: Corrigez l'affichage de 0 vulnérabilités lors de l'entrée-sortie.
* **NVSHAS-9270**: Prise en charge de k3s pour le pipeline de référence CIS.
* **NVSHAS-9338**: Avertissement: 'Le cluster géré [id] est déconnecté du système principal.'
* **NVSHAS-9358**: L'analyse d'image via proxy a échoué.
* **NVSHAS-9337**: Envoyez un message de journal lorsque une attaque SYN-Flood est détectée.
* **NVSHAS-9209**: Supprimez le cache de domaine lorsque l'espace de noms est supprimé de k8s.
* **NVSHAS-8985**: Les enregistrements fédérés disparaissent après le redémarrage du contrôleur.

==== Problème connu :

* **NVSHAS-9443** : La mise à niveau/l'installation via ArgoCD échoue car l'objet leases.coordination.k8s.io ne peut pas être créé.
* **Solution de contournement** : Créez les objets de location spécifiés avant de mettre à jour vers 5.4.0 avec ARGO CD. Changez l'espace de noms s'il est différent de neuvector.
+
--
[,bash]
----
cat <<EOF | kubectl apply -f -
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-controller
  namespace: neuvector
spec:
  leaseTransitions: 0
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-cert-upgrader
  namespace: neuvector
spec:
  leaseTransitions: 0
EOF
----
--

=== 5.3.4 Juillet 2024

==== Corrections de bogues

* Les interfaces `+host+` et `+tunnel+` sont récupérées avec succès avec OpenShift CLI v4.15.
* La plage IP 169.254.x.x est exclue des IPs des interfaces hôtes.
* Vérifiez l'interface hôte après 1 minute après le démarrage du contrôleur.
* Un problème a été résolu où l'URL Regex de l'émetteur OpenID échouait.
* Corrige les CVEs suivants :
+
|===
| CVE | S'applique à | Impact

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.2.4-s5 Juillet 2024

* Corrige les CVEs suivants :

|===
| CVE | S'applique à | Impact

| CVE-2023-42363
| busybox
| {CVE-medium}

| CVE-2023-42364
| busybox
| {CVE-medium}

| CVE-2023-42365
| busybox
| {CVE-medium}

| CVE-2023-42366
| busybox
| {CVE-medium}

| CVE-2024-6197
| curl
| {CVE-medium}

| CVE-2024-6874
| curl
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4603
| openssl
| {CVE-medium}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.3.3 Juin 2024

==== Verbesserungen

* Permet aux utilisateurs de bloquer l'utilisation de certaines classes de stockage depuis la `+Admission Controls+` page.
* La `+LDAP Authentication+` a des champs séparés pour la configuration `+baseDN+` et `+groupDN+`.
* La `+Egress and Ingress chart+` a une nouvelle colonne de vulnérabilité de sécurité qui contient le nombre de vulnérabilités de sécurité `+High+` et `+Medium+` pour chaque service.

==== Corrections de bogues

* Correction d'un bug qui se produisait avec `+regex+` lorsque une virgule (`+,+`) était utilisée dans une entrée multiple `+Admission Control user criteria+`.
* Correction d'un bug où le scan CVE des paquets `+jar+` n'affichait pas tous les paquets affectés par le même CVE. Maintenant, toutes les occurrences sont signalées.
* Corrige les CVEs suivants :

|===
| CVE | S'applique à | Impact

| CVE-2024-35195
| python:requests
| {CVE-medium}

| CVE-2024-21011
| openjdk11
| {CVE-low}

| CVE-2024-21012
| openjdk11
| {CVE-low}

| CVE-2024-21068
| openjdk11
| {CVE-low}

| CVE-2024-21085
| openjdk11
| {CVE-low}

| CVE-2024-21094
| openjdk11
| {CVE-low}
|===

==== Autres

* Permet aux utilisateurs de définir des ressources pour `+updater-cron-job+` lorsque {product-name} est installé avec le graphique Helm.
* Vérification de la version du conteneur Prometheus-Exporter et dissociée de la version `+controller+`.
* (Scanner) Détectez le paquet/module `+R+` dans Ubuntu et Red Hat Enterprise Linux.
* (Scanner) Support pour le scan PHP Composer ajouté.

=== 5.2.4-s3 Avril 2024

* Corrige les CVEs suivants :

|===
| CVE | S'applique à | Impact

| CVE-2021-40633
| giflib
| {CVE-high}

| CVE-2023-48161
| giflib
| {CVE-high}

| CVE-2024-28757
| expat
| {CVE-high}

| CVE-2023-39742
| giflib
| {CVE-medium}

| CVE-2023-45288
| go:golang.org/x/net
| {CVE-medium}

| CVE-2024-25629
| c-ares
| {CVE-medium}

| CVE-2024-3651
| python:idna
| {CVE-medium}

| CVE-2024-2511
| openssl
| {CVE-low}
|===

=== 5.3.2 Avril 2024

==== Corrections de bogues

* Après la mise à niveau vers v5.3.1 à partir d'une version précédente {product-name}, des ressources personnalisées existantes de NvClusterSecurityRule peuvent être supprimées par inadvertance. REMARQUE : La version 5.3.1 a été retirée du Docker Hub pour éviter le problème de mise à niveau.

=== 5.3.1 Avril 2024

[IMPORTANT]
====
La version 5.3.1 a été retirée du Docker Hub pour éviter le problème de mise à niveau qui a été corrigé dans 5.3.2. Veuillez utiliser la version 5.3.2.
====

==== Verbesserungen

* Permettre aux utilisateurs de définir des vulnérabilités '\`+accepted\+`' lors de l'utilisation des actions GitHub afin qu'elles n'affectent pas les workflows.
* Ajouter des filtres de gravité, de score et d'évaluation des flux à Assets > Registry > Vue des vulnérabilités d'image.
* Permettre lors de la configuration d'un registre si le proxy défini doit être utilisé pour les analyses d'images de registre.

==== Corrections de bogues

* Les risques de sécurité > Vulnérabilités > Filtre avancé ne filtre pas 'CVE sans correctif'.
* Violation inattendue du conteneur au conteneur en mode hôte
* Accepter le format d'image OCI lors du passage à Docker API 1.24
* L'analyse du registre ne doit pas analyser les artefacts non-image / ne pas enregistrer d'erreur.
* Permettre la vérification de signature des paires de clés sans dépendance Internet ou sigstore.
* Événements de sécurité non autorisés par les règles réseau dans un nœud spécifique (en rapport avec les messages d'erreur "Container Task chan full")
* Le conteneur ne peut pas être ajouté avec succès à la charge de travail (occurrences fréquentes). Résultant d'un blocage des messages de canal.

==== Autres

* Mettre à jour les plugins de scanner pour Jenkins, GitHub Action et Bamboo.
* (Scanner) Accepter le format d'image OCI lors du passage à Docker API 1.24.
* (Scanner) Le scan du registre ne doit pas scanner les artefacts non-image / ne pas enregistrer d'erreurs.
* (Scanner) Ajouter le support pour le scan PHP Composer.

==== {product-name} Extension UI v. 1.0 pour Rancher mars 2024

* Après l'installation de {product-name}, xref:rancher.adoc#_suse_security_ui_extension_for_rancher[activer/installer] l'extension UI {product-name} de Rancher affichera un tableau de bord pour le cluster, y compris des liens vers SSO pour le cluster complet {product-name}. REMARQUE : L'extension peut être affichée comme un tiers, ce qui sera corrigé dans une version future. De plus, les utilisateurs de Rancher 2.7.x verront deux icônes d'extension UI {product-name} dans la liste après l'installation (erreur). Une icône dira Désinstaller (ce qui signifie qu'elle est installée), et l'autre devrait dire Installer. Cela peut rester tel quel, c'est-à-dire ne pas réinstaller si l'extension est déjà installée.

=== 5.2.4-s2 février 2024

* Corrige les CVEs suivants :
* Haute cve : CVE-2023-52425 dans expat, CVE-2024-20952 et CVE-2024-20918 dans openjdk11
* Moyenne cve : CVE-2023-52426 dans expat, CVE-2024-20926, CVE-2024-20921, CVE-2024-20945 et CVE-2024-20919 dans openjdk11, CVE-2024-0727 et CVE-2023-6237 dans openssl

=== 5.3.0 février 2024

==== Verbesserungen

* Afficher les URL cibles externes (FQDN) dans le tableau de bord (Egress), les rapports PDF et CSV, ainsi que dans l'écran d'activité réseau et les listes d'événements de sécurité (violations)
* Apprendre à découvrir automatiquement les Egress vers des groupes d'adresses FQDN externes. Un nouveau groupe personnalisé pour les FQDN externes sera créé, sauf si la connexion externe correspond à une règle existante.
* Activer l'apprentissage ICMP (mode découverte) et le blocage (mode protection) via la nouvelle variable d'environnement du contrôleur CTRL_EN_ICMP_POLICY = 1
* Exporter les CRDs vers Github pour prendre en charge gitops dans un dépôt standard via la console ou l'API REST.
* Support pour la déconnexion unique SAML avec ADFS iDP
* Ajouter le support pour la plateforme ARM64. Le téléchargement des plateformes basées sur ARM tire automatiquement les images ARM64 correspondantes {product-name}.
* Support des webhooks via un proxy
* Améliorer la fonction de vérification du contrôle d'admission pour inclure les résultats de toutes les règles. Lister le résultat de chaque règle et ajouter une autre entrée pour l'action finale qui se produirait si elle était évaluée dans un contrôle d'admission en direct.
* Appliquer les règles de contrôle d'admission désactivées via CRD ou yaml (kubectl)
* Exporter / importer des profils de vulnérabilités via la console, CRD ou REST-API. L'importation remplace le profil existant. La suppression de la CRD entraîne un profil vide.
* Exporter / importer des modèles de profil de conformité via la console, CRD ou REST-API. L'importation remplace le modèle existant.
* Ajouter un statut 'Manuel' dans les rapports de conformité pour les benchmarks CIS qui doivent être exécutés manuellement par les utilisateurs (non exécutés par {product-name}).
* Améliorer le chargement / la performance de l'interface utilisateur de la page de vulnérabilité
* Uniformiser la connexion de session du navigateur. Ainsi, tous les onglets dans le navigateur partagent la même session de connexion, l'ouverture d'un nouvel onglet à partir d'une session existante ne nécessite pas d'identifiants, et si un onglet se déconnecte, tous les onglets se déconnectent.
* Améliorations de la sécurité de la console (UI) : 1) Ajouter des en-têtes de sécurité obligatoires (X-Content-Type-Options nosniff; X-XSS-Protection 1; mode=block; X-Frame-Options SAMEORIGIN; Cache-Control private, no-cache, no-store, must-revalidate
HTTP Strict Transport Security max-age=15724800, 2) Ajouter l'en-tête CSP (z. B. setzen Sie eine '\`+default-src\+`' Direktive), 3) Entfernen Sie die Offenlegung des Servernamens.
* Support des versions plus récentes des benchmarks CIS. Kubernetes (1.8.0), Kubernetes V1.24 (1.0.0), Kubernetes V1.23 (1.0.1), RedHat OpenShift Container Platform (1.4.0)
* Affichez dans les actifs -> conteneurs -> les détails des conteneurs qui ont été scannés dans les enregistrements par rapport au temps d'exécution.
* Ajoutez un lien vers le groupe dans les risques de sécurité -> vulnérabilités -> ajouter un impact au popup pour modifier facilement le mode de groupe.
* Prise en charge du Deep Linking dans les URL vers la page des vulnérabilités d'image et/ou de conteneur.
* Ajoutez l'option de réinitialisation du mot de passe pour l'administrateur afin de réinitialiser le mot de passe utilisateur dans les paramètres de la console -> utilisateur.
* Autorisez l'envoi de journaux d'événements aux journaux du pod contrôleur dans les paramètres -> configuration -> notification. Les événements envoyés commencent par 'notification=' et ne sont stockés que dans le pod contrôleur principal. Notez qu'il y a un bug dans cette version où le niveau d'événement doit être activé pour SYSLOG (et peut être désactivé après le changement de niveau si souhaité).
* Supprimez l'exigence que le contrôleur/enforceur monte "/host/cgroup".
* Ajoutez le menu "Demander de l'aide" avec des liens vers Slack, la documentation et d'autres ressources.
* Remplissez le champ de message pour /v1/log/activity logs.

==== Corrections de bogues

* Erreur interne du serveur dans les risques de sécurité -> vulnérabilités avec un grand nombre de CVEs.
* SIGSEGV: Violation de segmentation dans le contrôleur.
* Das Löschen anfälliger Dateien (z.  jar) ne les supprime pas de la liste des vulnérabilités.
* Certificat Syslog invalide avec l'algorithme de signature SHA256withECDSA.
* {product-name} affiche les événements de sécurité qui devraient être autorisés par une règle réseau
* Nœud non géré avec un enforceur "Zombie" en cours d'exécution
* Le filtre avancé affiche les champs de correction et d'impact vides.
* Ajuster le traitement des chaînes pour éviter les redémarrages inattendus de l'agent
* Violations inattendues concernant les groupes intégrés
* Appel RPC de débogage de l'agent de bundle de support pour les données renvoie une erreur
* Le groupe ne correspond pas aux événements de sécurité
* L'envoi d'événements à Slack ne fonctionne pas - avec un proxy
* Affiche les événements de sécurité pour les règles réseau autorisées

==== Autres

* Ajouter la détection automatique du moteur de conteneurs d'exécution (Socket) au diagramme Helm
* Suppression de la configuration pour faire fonctionner le contrôleur en mode privilégié dans le diagramme Helm et de l'exigence que les contrôleurs/agents doivent monter "/host/cgroup".
* Les fichiers d'exemple de déploiement Kubernetes ont été supprimés des documents {product-name}. Veuillez vous référer au lien pour des exemples.

==== Modifications mises en évidence qui peuvent nécessiter des modifications pour les déploiements manuels (toutes les modifications sont déjà incluses dans le dernier diagramme Helm pour 5.3.x)

* La détection automatique de l'exécution des conteneurs (Socket) élimine la nécessité de spécifier l'exécution des conteneurs et le chemin du socket.
* La suppression de l'exigence d'exécuter le contrôleur en mode privilégié élimine la nécessité de monter le socket d'exécution et /host/cgroup/.
* Rôle/lien de rôle pour neuvector-binding-secret ainsi que neuvector-secret ajouté dans yaml.
* Nouveaux comptes de service et liaisons de rôle nécessaires pour 5.3
* Tous les fichiers yaml de déploiement référencés ont maintenant /5.3.0/ dans leurs chemins

=== 5.2.4-s1 Janvier 2024

==== Sicherheits-Patch-Veröffentlichung

* Corrige CVE-2023-6129 dans openssl ainsi que CVE-2023-46219 et CVE-2023-46218 dans curl.

=== 5.2.4 Novembre 2023

==== Corrections de bogues

* Modifications à Azure AKS ValidatingWebhookConfiguration et journalisation des erreurs.

=== 5.2.3 Novembre 2023

==== Verbesserungen

* Ajouter le support pour l'API NVD 2.0 dans le scanner.
* Scanner l'hôte du conteneur en mode autonome du scanner.

[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n
----

==== Corrections de bogues

* L'analyse sur un nœud échoue en raison d'un problème de docker cp / grpc bloqué.

=== 5.2.2-s1 Octobre 2023

==== Sicherheitsupdate

* Pakete aktualisieren, um CVEs zu beheben, einschließlich Hoch CVE-2023-38545 und CVE-2023-43804.

=== 5.2.2 Octobre 2023

==== Conseil de sécurité pour la CVE-2023-32188

* Corriger la CVE-2023-32188 "\`+la compromission du token JWT peut permettre des actions malveillantes, y compris l'exécution de code à distance (RCE)\+`" par la génération automatique du certificat utilisé pour signer le token JWT lors du déploiement et de la mise à niveau, ainsi que la génération automatique du certificat Manager/RESTful API lors des déploiements basés sur Helm.
 ** Le certificat pour la signature JWT est automatiquement créé par le contrôleur avec une validité de 90 jours et est automatiquement tourné.
 ** La génération automatique du certificat Manager, REST API et adaptateur d'enregistrement nécessite l'utilisation d'une installation basée sur Helm avec {product-name} version Helm 2.6.3 ou supérieure.
 ** Le certificat intégré continue d'être utilisé pour les déploiements basés sur yaml, sauf s'il est remplacé lors du déploiement ; il est cependant recommandé de le remplacer (voir la ligne suivante).
 ** Le xref:replacecert.adoc[remplacement manuel du certificat] est toujours pris en charge et recommandé pour les versions antérieures ou les déploiements basés sur yaml. Voir le {product-name} conseil de sécurité GitHub https://github.com/neuvector/neuvector/security/advisories/GHSA-622h-h2p8-743x[ici] pour une description.
 ** L'utilisation de certificats personnalisés est toujours prise en charge comme auparavant, tant pour les déploiements basés sur Helm que sur yaml.
* Ajouter des contrôles supplémentaires pour les scripts de conformité personnalisés. Par défaut, les scripts personnalisés ne peuvent maintenant pas être ajoutés, sauf si la variable d'environnement CUSTOM_CHECK_CONTROL est ajoutée au contrôleur et à l'enforcer. Les valeurs sont "désactiver" (par défaut, non autorisé), "strict" (rôle Admin uniquement) ou "lax" (rôles Admin, Conformité et Politique d'exécution).
* Prévenir l'injection LDAP - le champ nom d'utilisateur est échappé.

==== Verbesserungen

* Ajoutez des données de scan supplémentaires aux résultats CVE envoyés par SYSLOG pour les scans empilés.
* Prise en charge de l'API NVD 2.0 pour les scans de la base de données CVE.
* Indiquez la date de création de l'image du conteneur dans les détails du conteneur ->.
* Ajustez le tri pour les règles réseau : Désactivez le tri dans la vue des règles réseau, mais activez le tri des règles réseau dans la vue des groupes.
* Activez/désactivez la détection/l'alerte de TLS 1.0 et TLS 1.1 avec des variables d'environnement pour les enforceurs THRT_SSL_TLS_1DOT0, THRT_SSL_TLS_1DOT1. Standardmäßig deaktiviert.
* Ajoutez la variable d'environnement AUTO_PROFILE_COLLECT pour le contrôleur et l'enforceur afin d'aider à la collecte de l'utilisation de la mémoire lors de l'examen des événements de surcharge de mémoire. Définissez la valeur = 1 pour activer.
* Les évaluations de configuration contre le contrôle d'admission doivent afficher toutes les violations avec un scan.
* Ajoutez d'autres options pour les critères de rapport CVE dans les règles de réponse. Exemple 1 - "cve-high-with-fix:X" signifie : Si le nombre de (vulnérabilités critiques corrigées) >= X, déclenchez la règle de réponse. Exemple 2 - "cve-high-with-fix:X/Y" signifie : Si le nombre de (vulnérabilités critiques signalées il y a Y jours et corrigées) >= X, déclenchez la règle de réponse.

==== Corrections de bogues

* L'exportation de la stratégie de groupe ne renvoie aucun contenu YAML réel.
* Améliorez la réduction des espaces de noms avec une fonction spéciale.
* {product-name} Les utilisateurs de l'espace de noms ne peuvent pas voir les actifs-->Espaces de noms
* Ignorez le traitement des demandes CRD CREATE/UPDATE si l'espace de noms du CR a déjà été supprimé.
* Fournissez un contournement pour une partie des groupes CRD qui ne peuvent pas être réduits avec succès après la suppression des espaces de noms.

=== 5.2.1 Août 2023

==== Verbesserungen

* Signalez les résultats de scan stratifiés et les données CVE supplémentaires dans les messages SYSLOG. Cela est activé via une case à cocher dans les paramètres -> Configuration -> SYSLOG.
* Exporter les attributions NIST 800-53 (vers les benchmarks CIS Docker) dans le rapport de conformité CSV exporté.
* Prendre en charge le paramètre proxy lors de la vérification des signatures d'image.
* Fügen Sie das Ergebnis des Bildsignatur-Scans im heruntergeladenen CVE-Bericht hinzu.
* Prendre en charge les annotations de pod pour les politiques de contrôle d'admission disponibles via les critères personnalisés.
* Ajouter le champ "Dernière modification" pour filtrer le rapport sur les vulnérabilités, ainsi que le filtre avancé dans la vue des vulnérabilités.

==== Corrections de bogues

* Ne pas créer d'administrateur par défaut avec le mot de passe par défaut dans le déploiement initial {product-name} pour l'offre de facturation AWS (adaptateur CSP), de sorte que l'utilisateur doive utiliser un secret pour créer le nom d'utilisateur et le mot de passe administrateur.
* Corriger le fichier .json qui a augmenté en taille et a fait planter un nœud Kubernetes.
* Améliorer la logique de détection des injections SQL.
* Si le diagramme Helm-CRD est installé en premier, avant l'installation du diagramme {product-name} Core, les comptes de service manquent.
* Le résultat de l'audit de conformité du scan d'image I.4.1 est incorrect.
* Le rapport avancé sur les vulnérabilités affiche des images de tous les autres espaces de noms.

=== 5.2.0 Juillet 2023

==== Verbesserungen

* Prendre en charge les jetons pour l'accès à l'API {product-name}. Voir les paramètres -> Utilisateur, clé API..., pour créer une nouvelle clé API. Les clés peuvent être définies sur des rôles par défaut ou personnalisés.
* Prise en charge de la facturation AWS Marketplace PAYG pour les abonnements de support mensuels {product-name}. Les utilisateurs peuvent s'inscrire pour {product-name} via le support SUSE, qui est facturé mensuellement sur leur compte AWS en fonction de la consommation moyenne des nœuds du mois précédent. Détails https://open-docs.neuvector.com/deploying/awsmarketplace[hier].
* Support pour la signature d'images pour les contrôles d'admission. Les utilisateurs peuvent {product-name} demander de vérifier que les images sont signées par certaines parties avant qu'elles puissent être déployées dans l'environnement de production, via une intégration avec Sigstore/Cosign. Voir les actifs -> vérificateur Sigstore pour créer de nouveaux actifs de signature. Des règles peuvent ensuite être créées avec les critères de signature d'image et/ou de vérificateur Sigstore d'image.
* Activer chaque règle de contrôle d'admission pour qu'elle ait son propre mode de surveillance ou de protection. Une action de refus en mode surveillance déclenchera une alarme, et une action de refus en mode protection bloquera. Les actions autorisées ne sont pas affectées.
* Ajoutez un nouvel opérateur Regex dans la politique > Contrôle d'admission > Ajouter une règle pour les utilisateurs et les groupes d'utilisateurs afin de prendre en charge Regex. Prendre en charge les opérateurs "correspond à TOUT Regex dans" et "ne correspond à AUCUN Regex dans".
* Ajouter un support pour des critères de contrôle d'admission tels que les limites de ressources. Un nouveau critère sera ajouté pour les limites de ressources, et des critères supplémentaires seront pris en charge via les paramètres de critères personnalisés.
* Prendre en charge l'appel du {product-name} scanner des enregistrements Harbor via l'interface https://github.com/goharbor/pluggable-scanner-spec[pluggable scanner]. Cela nécessite la configuration de la connexion au contrôleur (API exposée). L'adaptateur Harbor appelle le point de terminaison du contrôleur pour déclencher un scan qui peut être automatiquement scanné lors du push. Les services d'interrogation peuvent être utilisés pour des scans réguliers. Les résultats de scan des contrôleurs principaux de la fédération sont propagés vers des clusters distants.  REMARQUE : Il y a un problème avec l'erreur de point de terminaison de l'adaptateur basé sur HTTPS : Veuillez ignorer l'erreur de test de connexion, cela fonctionne même si une erreur est affichée (sauter la validation du certificat).
* Service SaaS interrogeable pour les requêtes CVE. Parcourez la dernière base de données CVE {product-name} pour voir si un CVE spécifique est présent dans la base de données. Ce service est disponible pour les clients {product-name} Prime (abonnement de support payant). Contactez le support via votre portail SCC pour l'accès.
* Permettre à l'utilisateur de désactiver la protection réseau tout en maintenant WAF/DLP opérationnel. Configurer l'activation de la politique réseau dans les paramètres de configuration ->.
* Utilisez des comptes de service moins privilégiés, comme requis pour chaque composant {product-name}. Une variable "\`+leastPrivilege\+`" est introduite. La valeur par défaut est fausse. REMARQUE : L'utilisation du diagramme Helm actuel avec cette variable dans une version antérieure à 5.2.0 ne fonctionne pas correctement.
* Liez à un compte de service non standard pour répondre à la recommandation CIS 1.5 5.1.5.
* Permettre à l'administrateur de configurer le délai d'expiration de session par défaut pour les utilisateurs dans les paramètres -> Utilisateurs, clés API et rôles.
* Bannière de connexion personnalisable et texte d'en-tête UI personnalisable pour les déploiements réglementés et gouvernementaux. Les exigences pour la configuration se trouvent xref:customui.adoc[ici].
* Support SYSLOG pour le transport chiffré TLS. Sélectionnez TCP/TLS dans les paramètres de configuration -> pour SYSLOG.
* Activer le déploiement du diagramme d'assistance Monitor {product-name} de Rancher Manager.
* Supprimez la limite supérieure pour le domaine principal dans le validateur d'URL pour les analyses d'enregistrement.
* Scannen Sie Golang-Abhängigkeiten, einschließlich Laufzeitscans.
* Support pour l'analyse des vulnérabilités de Debian 12 (Bookworm).
* Exportation CSV pour le registre / Détails ajoutés pour exporter les CVE pour toutes les images dans le registre configuré dans les actifs -> Registres pour un registre sélectionné.
* Allow {product-name} to set multiple ADFS certificates in the x.509 certificate field in parallel.
* Add and display the comment field for response rules.
* Specify what {product-name} considers as a system container via the environment variable. For example, for Rancher and standard namespaces: NV_SYSTEM_GROUPS=*cattle-system;default
* Add support for Kubernetes 1.27 and OpenShift 4.12.

==== Corrections de bogues

* Reduce repetitive logs in the enforcement/control system logs.
* The multi-cluster page is not rendering.
* The automatic removal of empty groups takes 2 hours to delete instead of 1 hour as scheduled.
* Manually allowed network rule is not applied and results in a violation for the pause image.
* Block SSL connections even if a network rule allows traffic under certain initial conditions.
* Security events warn even with allowed network rules due to a policy update issue in synchronization.
* Network activities incorrectly map the traffic of the custom group externally.
* The default service account token of the namespace mounted in each pod has excessive permissions.
* Despite the definition of network rules, violations are logged in security events (false positives) when the container was stopped due to an out of memory (OOM) condition.
* Allow the user to disable/enable detection and protection against unmanaged containers in the cluster. This can be set via the manager CLI:

[,shell]
----
set system detect_unmanaged_wl status -h
Usage: cli set system detect_unmanaged_wl status [OPTIONS] {true|false}

  Enable/disable detect unmanaged container
----

==== Autres

* Fügen Sie die Einstellung "leastPrivilege" im Helm-Diagramm hinzu. Fügen Sie die Helm-Option für New_Service_Profile_Baseline hinzu. A new Helm chart (core) version will be released for 5.2.
* Enable integration options for the AWS Marketplace (billing adapter) in the Helm chart.
* Mettez à jour le ConfigMap pour prendre en charge de nouvelles fonctionnalités (plusieurs certificats ADFS, dérive nulle, New_Service_Profile_Baseline, SYSLOG TLS, délai d'attente utilisateur)
* Mettez à jour les versions Kubernetes prises en charge vers 1.19+ et OpenShift 4.6+ (1.19+ avec CRI-O)

=== 5.1.3 Mai 2023

==== Verbesserungen

* Ajoutez un nouveau flux de vulnérabilités pour scanner le framework Microsoft .NET.
* Les statistiques de l'enforcer sont désactivées par défaut dans l'exportateur Prometheus pour améliorer la scalabilité.
* Amélioration de l'utilisabilité : Utilisez le scanner pour analyser une seule image et imprimer le résultat (voir l'exemple ci-dessous).
* Ajoutez la vérification de l'imagePullPolicy aux critères des règles de contrôle d'admission.
* Affichez un message d'avertissement lorsque le schéma CRD est obsolète.

==== Corrections de bogues

* L'écran des activités réseau n'est pas rendu ou est mal rendu.
* The automatic removal of empty groups takes 2 hours to delete instead of 1 hour as scheduled.
* Le profil de conformité n'est pas affiché dans la console UI.
* Le filtre avancé dans les événements de sécurité manque le niveau "Erreur".
* Le mot de passe enregistré avec des caractères spéciaux échoue lors des tentatives d'authentification futures.
* La page des clusters multiples n'est pas correctement rendue lorsque les demandes sont élevées.
* Le champ de détail (en bas) de la zone d'enregistrement n'est pas mis à jour.

==== Scanner-Beispielausgabe

[,shell]
----
Image: https://registry.hub.docker.comlibrary/alpine:3.4
Base OS: alpine:3.4.6
TOTAL: 6, HIGH: 1, MEDIUM: 5, LOW: 0, UNKNOWN: 0
┌─────────┬───────────────┬──────────┬───────────┬───────────────┬────────────┐
│ PACKAGE │ VULNERABILITY │ SEVERITY │ VERSION   │ FIXED VERSION │ PUBLISHED  │
├─────────┼───────────────┼──────────┼───────────┼───────────────┼────────────┤
│ openssl │ CVE-2018-0732 │ High     │ 1.0.2n-r0 │ 1.0.2o-r1     │ 2018-06-12 │
│         ├───────────────┼──────────┤           ├───────────────┼────────────┤
│         │ CVE-2018-0733 │ Medium   │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0734 │          │           │ 1.0.2q-r0     │ 2018-10-30 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0737 │          │           │ 1.0.2o-r2     │ 2018-04-16 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0739 │          │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-5407 │          │           │ 1.0.2q-r0     │ 2018-11-15 │
└─────────┴───────────────┴──────────┴───────────┴───────────────┴────────────┘
----

=== 5.1.2 März 2023

==== Verbesserungen

* Prise en charge des groupes d'adresses basés sur des hôtes virtualisés et des politiques de conformité des mesures de protection réseau. Cela permet un cas d'utilisation où deux adresses FQDN différentes sont résolues sur la même adresse IP, mais des règles différentes pour chaque FQDN devraient être appliquées. Un nouveau groupe personnalisé avec '\`+address=vh:xxx.yyy\+`' peut être créé en utilisant l'indicateur '\`+vh:\+`' pour activer cette protection. Une règle de réseau peut alors utiliser le groupe personnalisé comme source '\`+From\+`' basé sur le nom d'hôte virtuel (plutôt que sur l'adresse IP résolue) pour appliquer des règles différentes pour les hôtes virtuels.
* Liste des conteneurs de conformité pour exclure les conteneurs terminés.
* Amélioration des règles DLP pour prendre en charge des jokers simples dans le modèle.
* Ajouter le support pour cri-o 1.26+ et OpenShift 4.11+.
* Rendre Gravatar optionnel.
* Afficher la ressource de namespace de cluster dans la console / UI.
* Quellschweregrad/Klassifizierung (z.B. Afficher Red Hat, Ubuntu...) avec la valeur de gravité NVD dans la console.
* Ne pas permettre la désactivation SSO/RBAC pour Rancher et OpenShift lorsque l'utilisateur est authentifié via SSO.
* Ajouter l'activation de la vérification automatique et de la suppression des groupes non utilisés âgés à configMap.
* Inclure l'adresse IP pour la source/destination externe dans csv/pdf pour les violations implicites.
* Différentes optimisations de performance et de scalabilité pour la consommation CPU et mémoire des contrôleurs et des enforceurs.

==== Corrections de bogues

* Corriger le ralentissement des applications sur les nœuds GKE Container Optimized OS (COS) en mode protection.
* SUSE Linux (SLES) 15.4 CVE ne correspond pas dans le scanner. Avec ce correctif, lorsque la gravité est fournie dans le flux, la vulnérabilité est ajoutée à la base de données, même si l'entrée NVD est manquante. Il est possible que le rapport contienne des vulnérabilités sans valeurs CVE.

==== Autres

* Amélioration des options pour le contrôle d'admission CRD dans helm https://github.com/neuvector/neuvector-helm/pull/237.
* Ajouter de nouvelles variables d'environnement d'enforceur au chart Helm.

=== 5.1.1 Février 2023

==== Verbesserungen

* Ajouter "\`+package\+`" comme informations sur l'événement Syslog pour une vulnérabilité détectée.
* Ajoutez la variable d'environnement Enforcer ENF_NETPOLICY_PULL_INTERVAL - valeur en secondes (valeur recommandée 60) pour réduire le trafic réseau et la consommation de ressources résultante par l'Enforcer en raison des mises à jour/recalculs de politiques. (Remarque : C'était un ajout non documenté jusqu'en août 2023).

[,yaml]
----
           - name: ENF_NETPOLICY_PULL_INTERVAL
             value: "60"   <== regulate the pulling gap by 60 seconds
----

==== Corrections de bogues

* Erreur lors de la suppression de groupes vides "Objet non trouvé"
* Alerter/bloquer le trafic à l'intérieur du même conteneur
* Violations implicites inattendues pour le trafic Egress Istio avec une règle d'autorisation existante
* Lors de la mise à niveau de {product-name} la version 4.x, un mauvais appartenance au groupe de pods provoque des violations de politique inattendues
* Échec de l'authentification OIDC avec ADFS lorsque des caractères d'encodage supplémentaires apparaissent dans la demande
* Consommation de mémoire élevée due à dp, qui crée et supprime des pods
* Mettez à jour Alpine pour corriger plusieurs CVE, y compris le gestionnaire : CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552
* Diverses erreurs d'interface utilisateur corrigées

==== Autre

* Graphique Helm mis à jour pour permettre l'échange de certificats pour la communication interne

=== 5.1.0 décembre 2022

==== Verbesserungen

* Base de données de scan centralisée multi-cluster (CVE). Le cluster principal (maître) peut scanner un registre/repo appelé registre fédéré. Les résultats de scan de ces enregistrements sont synchronisés avec tous les clusters gérés (distants). Cela permet d'afficher les résultats de scan dans la console du cluster géré ainsi que d'utiliser les résultats dans les règles de contrôle d'admission du cluster géré. Les enregistrements doivent être scannés une seule fois, au lieu de chaque cluster, ce qui réduit l'utilisation du CPU/mémoire et de la bande passante réseau.
* Améliorez les règles de contrôle d'admission :
 ** Benutzerdefinierte Kriterien für Zulassungssteuerungsregeln. Permettre aux utilisateurs de définir des critères de ressources pour tous les champs liés aux pods et de les utiliser dans des règles, par exemple. item.metadata.annotationsKey contient 'neuvector', item.metadata.name='xyzzy', etc.
 ** Ajoutez des critères pour vérifier les paramètres RBAC à haut risque pour les comptes de service lors du déploiement de pods. Cela inclut les critères 'toute action sur les ressources de charge de travail', 'toute action sur RBAC', 'créer des ressources de charge de travail', 'lister les secrets' et 'exécuter dans un conteneur'.
 ** Ajoutez une comparaison de version sémantique aux modules pour les règles de contrôle d'accès. Cela permet d'appliquer les opérateurs > ou < sur les numéros de version dans les règles (par exemple, ne pas permettre que le module curl<6.2.0 soit déployé). Cela permet des vérifications de version spécifiques pour les paquets installés.
 ** Ajoutez une règle de contrôle d'accès pour l'approbation de sécurité des pods (PSA) qui est prise en charge dans Kubernetes 1.25+.
* Ajoutez une nouvelle variable d'environnement NO_DEFAULT_ADMIN qui, si activée, ne crée pas d'utilisateur 'admin'. Ceci est utilisé par défaut pour l'intégration SSO de Rancher. Si non activé, avertissez l'utilisateur en permanence et consignez les événements pour changer le mot de passe admin par défaut s'il n'est pas modifié par défaut.
* Le blocage de la connexion après des tentatives de connexion échouées est désormais l'option par défaut. La valeur par défaut est de 5 tentatives et peut être configurée dans les paramètres -> Utilisateurs & Rôles-> Profil de mot de passe.
* Ajoutez une nouvelle variable d'environnement pour l'optimisation des performances ENF_NO_SYSTEM_PROFILES, valeur : "1". Si activé, les moniteurs de processus et de fichiers seront désactivés. Aucun processus d'apprentissage, aucun mode de profil, aucun incident de processus/fichier (paquet) et aucun moniteur d'activité de fichier ne sera effectué. Cela réduira l'utilisation des ressources CPU/mémoire et les opérations sur les fichiers.
* Ajoutez un paramètre d'auto-scaling personnalisé pour les pods de scanner, avec les valeurs Retardé, Immédiat et Désactivé. Important : L'auto-scaling des scanners n'est pas pris en charge lorsque le scanner est déployé avec un opérateur OpenShift, car l'opérateur modifie toujours le nombre de pods à la valeur configurée.
 ** *_Stratégie retardée :_*
  *** Si le contrôleur principal voit en continu que le "nombre de tâches" > 0 pendant > 90 secondes, un nouveau pod de scanner sera lancé si maxScannerPods n'est pas encore atteint.
  *** Si le contrôleur principal voit en continu que le "nombre de tâches" 0 pendant > 180 secondes, un pod de scanner sera arrêté si minScannerPods n'est pas encore atteint.
 ** *_Stratégie immédiate:_*
  *** Chaque fois que le contrôleur principal voit que le "nombre de tâches" > 0, un nouveau pod de scanner sera lancé si maxScannerPods n'est pas encore atteint.
  *** Si le contrôleur principal voit en continu que le "nombre de tâches" 0 pendant > 180 secondes, un pod de scanner sera arrêté si minScannerPods n'est pas encore atteint.
* Les groupes personnalisés peuvent maintenant utiliser des étiquettes de namespace, y compris les étiquettes de namespace de Rancher. En général, des étiquettes de pod et de namespace peuvent maintenant être ajoutées aux groupes personnalisés.
* Ajoutez la possibilité de masquer des namespaces et des groupes sélectionnés dans la vue d'activité réseau.
* Vollständige Unterstützung für Cilium cni.
* Vollständige Unterstützung für OpenShift 4.9 und 4.10.
* Les outils de construction sont maintenant disponibles pour le projet {product-name}/Open Zero Trust (OZT) sous https://github.com/openzerotrust/openzerotrust.io..
* {product-name} répertorie maintenant l'ID de version et le hash SHA256 pour chaque version du contrôleur, du gestionnaire, de l'appliqueur sous https://github.com/neuvector/manifests/tree/main/versions..
* Les données de télémétrie anonymes (nombre de nœuds, groupes, règles) sont maintenant signalées à un service cloud Rancher lors du déploiement pour aider l'équipe projet à comprendre le comportement d'utilisation. Cela peut être désactivé dans l'interface utilisateur ou avec configMap (No_Telemetry_Report) ou l'API REST (Opt-out).
* (Addendum janvier 2023). Unterstützung für ServiceEntry-basierte Netzwerkrichtlinien mit Istio. L'application des politiques réseau Egress a été ajoutée dans la version 5.1.0 pour les pods vers les cibles ServiceEntry déclarées avec Istio. Typiquement, un ServiceEntry définit comment un service externe, qui est adressé par le nom DNS, est résolu en une IP cible. Avant v5.1, {product-name} ne pouvait pas détecter et appliquer des règles pour les connexions à un ServiceEntry, de sorte que toutes les connexions étaient classées comme externes. Avec 5.1, des règles pour des cibles ServiceEntry spécifiques peuvent être appliquées. IMPORTANT: Si vous mettez à niveau vers v5.1 avec un déploiement basé sur Istio, vous devez créer de nouvelles règles pour autoriser ces connexions et éviter les avertissements de violation. Après la mise à niveau, des violations implicites seront signalées pour le trafic nouvellement visible s'il n'existe pas de règles d'autorisation. De nouvelles règles de trafic peuvent être apprises en mode découverte et créées automatiquement. Pour autoriser ce trafic, vous pouvez mettre le groupe en mode découverte ou créer un groupe personnalisé avec des adresses (ou des noms DNS) et une nouvelle règle réseau pour autoriser le trafic vers cette destination. REMARQUE : Il y a un bug dans 5.1.0 concernant la destination signalée par les violations de refus qui ne représente pas la bonne destination.  Le bug signale que server_name et client_name sont identiques.  Ce problème sera corrigé dans un prochain patch.

==== Corrections de bugs

* Réduisez l'utilisation de la mémoire du contrôleur en supprimant les données de référence cis inutiles créées lors des mises à jour progressives. Ce problème ne se produit pas avec de nouveaux déploiements.
* Lizenz von der Konfigurationsoberfläche entfernen (nicht mehr erforderlich).

=== 5.0.6-s1 Mars 2023

==== Corrections de bugs

* Mettez à jour les paquets Alpine pour corriger les CVE dans curl, y compris CVE-2023-23914, CVE-2023-23915 et CVE-2023-23916.

=== 5.0.6 Février 2023

==== Corrections de bugs

* Utilisation élevée de la mémoire dans dpMsgConnection
* Utilisation élevée de la mémoire dans le processus dp dans l'Enforcer lorsqu'il y a de nombreuses règles de politique apprises avec une charge de travail non gérée (fuite de mémoire)
* tcpdump ne peut pas être démarré avec succès lorsque le trafic est sniffé sur le conteneur
* Mettre à jour Alpine pour corriger plusieurs CVE, y compris le gestionnaire : CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552

=== 5.0.5 Novembre 2022

==== Corrections de bugs

* La mise à niveau vers 5.0.x entraîne un message d'erreur concernant le Manager, le Controller, l'Enforcer, qui exécutent des versions différentes.
* L'Enforcer rencontre une panique de Go-Routine, ce qui entraîne un dp kill.  WebUI ne montre pas l'Enforcer comme étant en ligne.
* Incident inattendu de Process.Profile.Violation dans le groupe NV.Protect, sur la commande sur coreos.

=== 5.0.4 Octobre 2022

==== Sicherheitsupdates

* Mettre à jour Alpine pour supprimer la CVE critique-2022-40674 dans la bibliothèque Manager-Expat ainsi que d'autres CVEs mineurs.

==== Verbesserungen

* Ajouter le support pour Antrea CNI

==== Corrections de bugs

* Corriger l'incident inattendu de process.profile.violation dans le groupe NV.Protect.
* Lorsque SSL est désactivé lors de l'accès à l'interface utilisateur du Manager, le mot de passe de l'utilisateur est affiché dans le journal du Manager.

=== 5.0.3 Septembre 2022

==== Verbesserungen

* Ne pas afficher l'EULA après un redémarrage réussi du volume persistant.
* Utilisez le filtre d'image dans les paramètres du profil de vulnérabilité pour ignorer les résultats du scan de conteneurs.
* Support du scanner dans les actions GitHub à https://github.com/neuvector/neuvector-image-scan-action.
* Ajouter des variables d'environnement pour l'Enforcer afin de désactiver le scan des secrets et d'exécuter les benchmarks CIS

[,yaml]
----
    env:
      - name: ENF_NO_SECRET_SCANS  (available after v4.4.4)
        value: "1"
      - name: ENF_NO_AUTO_BENCHMARK (after v5.0.3)
        value: "1"
----

==== Corrections de bugs

* L'Enforcer peut parfois ne pas démarrer.
* Fuite de connexion dans des environnements de fédération multi-clusters.
* La page de conformité ne se charge parfois pas dans les risques de sécurité -> Conformité

=== 5.0.2 Juillet 2022

==== Verbesserungen

* Les clusters Rancher et SELinux durcis sont pris en charge.

==== Corrections de bugs

* Le processus de l'agent a une utilisation élevée du CPU sur les systèmes k3s.
* Les groupes AD LDAP ne fonctionnent pas correctement après la mise à niveau vers 5.0.
* L'enforcer redémarre constamment en raison de l'erreur = trop de fichiers ouverts (rke2/cilium).
* Le journal de support ne peut pas être téléchargé avec succès.

=== 5.0.1 Juin 2022

==== Verbesserungen

* Prise en charge de l'analyse des vulnérabilités de openSUSE Leap OS (dans l'image du scanner).
* Scanner : Mise en œuvre des attributs de suppression lors de la reconstruction du dépôt d'images.
* Vérifiez {product-name} le déploiement et le support pour les hôtes avec SELinux activé. Voir ci-dessous pour les détails sur les correctifs temporaires, en attendant que le diagramme Helm soit mis à jour.
* Différencier clairement entre le diagramme des fonctionnalités et les diagrammes des partenaires dans l'interface utilisateur de Rancher. + Amélioration de l'annotation Ingress pour Nginx dans le diagramme Helm de Rancher. Ajouter / Mettre à jour ingress.kubernetes.io/protocol : https à nginx.ingress.kubernetes.io/backend-protocol : "HTTPS".
* L'opérateur OpenShift actuel prend en charge les routes de passage pour les services API et de fédération. Des paramètres de valeur Helm supplémentaires sont ajoutés pour prendre en charge les types de terminaison de routes Edge et Re-Encrypt.

==== Corrections de bugs

* Le cluster AKS pourrait ajouter une clé inattendue dans le webhook de contrôle d'admission.
* L'enforcer n'est pas opérationnel dans le cluster k8s 1.24 avec le runtime containerd 1.64. De plus, l'enforcer ne démarre parfois pas.
* Tout utilisateur avec un rôle d'administrateur (utilisateur local ou SSO) qui promeut un cluster au maître fed devrait être automatiquement promu au rôle fedAdmin.
* Si SSO utilise l'administrateur par défaut de Rancher dans {product-name} dans le cluster maître, le rôle de connexion {product-name} est admin, pas fedAdmin.
* Corriger plusieurs plantages de goroutine.
* Violation implicite de l'IP hôte, qui n'est pas connectée au nœud.
* Le profil de conformité n'affiche pas de balise PCI.
* L'attribution de groupe LDAP n'est parfois pas affichée.
* L'outil d'examen et d'amélioration des risques génère un message d'erreur : "Erreur lors de la mise à jour de la configuration système : Demande au format incorrect".
* OKD 3.11 - L'erreur de rôle de cluster s'affiche, même si elle existe.

==== CVE-Beseitigungen

* Haute CVE-2022-29458 cve trouvée dans le paquet ncurses dans toutes les images.
* Haute CVE-2022-27778 et CVE-2022-27782 trouvées dans le paquet curl dans l'image de mise à jour.

==== Détails sur le support SELinux

{product-name} ne nécessite aucun paramètre supplémentaire pour les clusters activés SELinux pour être déployés et exploités. Le déploiement de {product-name} sur un cluster RKE2 durci activé SELinux basé sur RHEL 8.5 a été testé. {product-name} a été déployé avec succès lorsque PSP est activé et le déploiement du gestionnaire de correctifs et du scanner. La prochaine version du graphique devrait résoudre le problème ci-dessous.

Exemple ci-joint pour activer PSP à partir du graphique Rancher et les commandes ci-dessous pour corriger le déploiement du gestionnaire et du scanner. L'ID utilisateur dans la commande de correctif peut être n'importe quel nombre.

[,shell]
----
kubectl patch deploy -ncattle-neuvector-system neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
kubectl patch deploy -ncattle-neuvector-system neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
----

Exemple pour activer PSP :

[,shell]
----
[neuvector@localhost nv]$ getenforce
Enforcing
[neuvector@localhost nv]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

[neuvector@localhost nv]$ kk get psp
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS                                      SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
global-restricted-psp     false                                             RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
neuvector-binding-psp     true    SYS_ADMIN,NET_ADMIN,SYS_PTRACE,IPC_LOCK   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
system-unrestricted-psp   true    *                                         RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
[neuvector@localhost nv]$ nvpo.sh
NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE                    NOMINATED NODE   READINESS GATES
neuvector-controller-pod-54f69f7f9c-6h822   1/1     Running   0          5m51s   10.42.0.29   localhost.localdomain   <none>           <none>
neuvector-enforcer-pod-jz77b                1/1     Running   0          5m51s   10.42.0.30   localhost.localdomain   <none>           <none>
neuvector-manager-pod-588488bb78-p6vf9      1/1     Running   0          111s    10.42.0.32   localhost.localdomain   <none>           <none>
neuvector-scanner-pod-87474dcff-s8vgt       1/1     Running   0          114s    10.42.0.31   localhost.localdomain   <none>           <none>
----

=== 5.0.0 Disponibilité générale (GA) publication mai 2022

==== Verbesserungen

* Automatisierte Förderung von Gruppenmodi. Promeut le mode de protection d'un groupe basé sur le temps écoulé et les critères. Ne s'applique pas aux groupes créés par CRD. Cette fonctionnalité permet à une nouvelle application de fonctionner dans Discover pendant une période déterminée, d'apprendre le comportement et de créer {product-name} règles pour la liste d'autorisation pour le réseau et le processus, puis de passer automatiquement en mode de surveillance puis en mode de protection. Critère de Discover à Monitor : Temps écoulé pour apprendre toutes les activités réseau et processus d'au moins un pod actif dans le groupe. Critère de Monitor à Protect : Il n'y a aucun événement de sécurité (réseau, processus, etc.) pour la période définie pour le groupe.
* Support pour les applications Rancher 2.6.5 et le graphique Marketplace. Déployé dans l'espace de noms cattle-neuvector-system et active SSO de Rancher vers {product-name}. Remarque : Les déploiements précédents de Rancher (par exemple, les graphiques du catalogue partenaire, version 1.9.x et antérieure) doivent être complètement supprimés pour mettre à jour vers le nouveau graphique.
* Support pour le scan de SUSE Linux (SLE, SLES) et Microsoft Mariner
* Protection des processus et des fichiers Zero-Drift. C'est le nouveau mode par défaut pour la protection des processus et des fichiers. Zero-Drift autorise automatiquement uniquement les processus provenant du processus parent inclus dans l'image de conteneur d'origine et n'autorise aucune mise à jour de fichiers ou installation de nouveaux fichiers. En mode découverte ou surveillance, Zero-Drift alertera sur les processus ou activités de fichiers suspects. Im Schutzmodus wird es solche Aktivitäten blockieren. Zero-Drift ne nécessite pas de processus à apprendre ou à ajouter à une liste d'autorisation. Désactiver Zero-Drift pour un groupe rendra effectives les règles de processus et de fichiers énumérées pour le groupe.
* Geteilte Richtlinienmodus-Schutz für Netzwerk, Prozess/Datei. Il existe maintenant un paramètre global dans les paramètres -> Configuration pour définir le mode de protection réseau séparément pour l'application des règles réseau. L'activation de cette fonctionnalité (désactivée par défaut) signifie que toutes les règles réseau sont en mode protection sélectionné (Découverte, Surveillance, Protection), tandis que les règles de processus/fichier restent en mode protection pour ce groupe, comme indiqué dans l'écran de groupe des politiques ->. De cette manière, les règles réseau peuvent être définies sur Protéger (bloquer), tandis que la politique de processus/fichier peut être définie sur Surveiller, ou vice versa.
* Détection des règles WAF, règles DLP améliorées (En-tête, URL, paquet complet). Utilisé pour les connexions entrantes aux pods d'application Web ainsi que pour les connexions sortantes aux services API pour faire respecter la sécurité API.
* CRD pour WAF, DLP et contrôles d'admission. REMARQUE : Zusätzliche Clusterrollenbindungen/Berechtigungen erforderlich. Voir les sections de déploiement Kubernetes et OpenShift. Importation/Exportation CRD et versionnage pour les contrôles d'admission pris en charge par CRD.
* Intégration SSO Rancher pour démarrer la console {product-name} via Rancher Manager. Cette fonctionnalité n'est disponible que si les conteneurs {product-name} sont déployés via Rancher. Ce déploiement tire de l'entrepôt Rancher miroir (par exemple, rancher/mirrored-neuvector-controller:5.0.0) et est déployé dans l'espace de noms cattle-neuvector-system. REMARQUE : Nécessite la version mise à jour de Rancher 2.6.5 de mai 2022 ou ultérieure, et seules les rôles d'administrateur et de propriétaire de cluster sont actuellement pris en charge.
* Prend en charge le déploiement sur RKE2.
* Unterstützung für die Föderation von Clustern (Multi-Cluster-Manager) über einen Proxy. Configurer le proxy dans les paramètres de configuration -> et activer le proxy lors de la configuration des connexions de fédération.
* Surveillez les rôles/bindings RBAC de cluster requis et avertissez dans les événements et l'interface utilisateur lorsqu'il en manque.
* Prendre en charge les critères de restrictions de ressources dans les règles de contrôle d'admission.
* Prendre en charge le format Microsoft Teams pour les webhooks.
* Prendre en charge les groupes AD/LDAP imbriqués sous le groupe de rôles associé.
* Prendre en charge les liaisons de rôles de cluster ou les liaisons de rôles avec des informations de groupe dans l'IDP pour Openshift.
* Autoriser les règles réseau et les règles de contrôle d'accès à être promues à une règle fédérée.

==== Corrections de bugs

* Résoudre le problème où la sauvegarde du rôle de fédération des travailleurs devrait être restaurée dans des clusters non fédérés.
* Améliorer les temps de chargement de la page pour un grand nombre de CVEs dans les vulnérabilités de sécurité -> vulnérabilités.
* Permettre à l'utilisateur de changer de mode lorsqu'il sélectionne tous les groupes dans le menu de politique -> groupes. Avertir si le groupe de nœuds est également sélectionné.
* Regrouper les articles de vérification de conformité avec le même nom et les rendre extensibles.
* Améliorer la sécurité de la communication gRPC.
* Résolu : impossible d'obtenir des informations privilégiées correctes sur la charge de travail dans l'installation rke2.
* Résoudre le problème de prise en charge d'openSUSE Leap 15.3 (k8s/crio).

==== Autres mises à jour

* Mise à jour de Helm Chart appVersion à 5.0.0 et version du chart à 2.2.0
* Fonction de scan sans serveur / menu supprimé.
* Prise en charge de l'intégration des résultats de scan Jfrog Xray supprimée (le scan de registre Artifactory est toujours pris en charge).
* La prise en charge du déploiement sur ECS n'est plus fournie. L'All-in-One devrait toujours pouvoir être déployé sur ECS, mais la documentation des étapes et des paramètres n'est plus prise en charge.

=== Mise à niveau de {product-name} 4.x à 5.x (avant 5.2.x)

[NOTE]
====
Les instructions suivantes s'appliquent aux mises à niveau vers 5.0.x et 5.1.x. Pour 5.2.x, les comptes de service et les liaisons ont changé et doivent être xref:kubernetes.adoc#_deploy_suse_security[vérifiés] pour planifier les mises à niveau.
====


Pour les utilisateurs de Helm, mettez à jour vers {product-name} Helm Chart 2.0.0 ou supérieur. Lorsque vous mettez à jour un opérateur ou une installation Helm sur OpenShift, consultez la note suivante.

. Supprimez l'ancienne définition de ressource personnalisée de liaison neuvector-binding-customresourcedefinition-Clusterrole

[,shell]
----
kubectl delete clusterrole neuvector-binding-customresourcedefinition
----

. Appliquez le nouveau verbe de mise à jour pour la définition de ressource personnalisée de liaison neuvector-binding-customresourcedefinition-Clusterrole

[,shell]
----
kubectl create clusterrole neuvector-binding-customresourcedefinition --verb=watch,create,get,update --resource=customresourcedefinitions
----

. Supprimez l'ancien schéma CRD pour Kubernetes 1.19+

[,shell]
----
kubectl delete -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/crd-k8s-1.19.yaml
----

. Créez un nouveau schéma CRD pour Kubernetes 1.19+

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/waf-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/dlp-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/admission-crd-k8s-1.19.yaml
----

. Créez un nouveau Clusterrole et Clusterrolebinding pour Admission, DLP et WAF

[,shell]
----
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----

. Mettez à jour les noms et chemins d'image pour récupérer {product-name} images de Docker Hub (docker.io), par exemple.

* neuvector/manager:5.0.0
* neuvector/controller:5.0.0
* neuvector/enforcer:5.0.0
* neuvector/scanner:latest
* neuvector/updater:latest

Optionnel, supprimez toutes les références à la licence {product-name} et au secret de registre dans les Helm-Charts, Deployment-YAML, ConfigMap, scripts, etc., car elles ne sont plus nécessaires pour récupérer les images ou utiliser {product-name}.

*Note sur SCC et mise à niveau via Operator/Helm*

Le SCC privilégié est ajouté au compte de service spécifié dans le Deployment-YAML de la version de l'opérateur 1.3.4 et supérieure dans les nouvelles déploiements. En cas de mise à niveau de l'opérateur {product-name} d'une version précédente vers 1.3.4 ou Helm vers 2.0.0, veuillez supprimer le SCC privilégié avant la mise à niveau.

[,shell]
----
oc delete rolebinding -n neuvector system:openshift:scc:privileged
----

==== Version bêta 1 publiée en avril 2022

* Funktional vollständig, einschließlich automatisierter Förderung von Gruppenmodi. Promeut le mode de protection d'un groupe basé sur le temps écoulé et les critères. Ne s'applique pas aux groupes créés par CRD. Cette fonctionnalité permet à une nouvelle application de fonctionner dans Discover pendant une période déterminée, d'apprendre le comportement et de créer {product-name} règles pour la liste d'autorisation pour le réseau et le processus, puis de passer automatiquement en mode de surveillance puis en mode de protection. Critère de Discover à Monitor : Temps écoulé pour apprendre toutes les activités réseau et processus d'au moins un pod actif dans le groupe. Critère de Monitor à Protect : Il n'y a aucun événement de sécurité (réseau, processus, etc.) pour la période définie pour le groupe.
* Support pour les applications Rancher 2.6.5 et le graphique Marketplace. Déployé dans l'espace de noms cattle-neuvector-system et active SSO de Rancher vers {product-name}. Remarque : Les déploiements précédents de Rancher (par exemple, les graphiques du catalogue partenaire, version 1.9.x et antérieure) doivent être complètement supprimés pour mettre à jour vers le nouveau graphique.
* Tags pour Exécuteur, Gestionnaire, Contrôleur : 5.0.0-b1 (z.B. neuvector/controller:5.0.0-b1)

==== Version Preview.3 publiée en mars 2022

[CAUTION]
.important
====

Pour mettre à jour les déploiements de prévisualisation précédents pour les nouvelles fonctionnalités CRD WAF, DLP et Admission-Control, veuillez mettre à jour le YAML CRD et ajouter de nouveaux liaisons rbacs/roles :

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/latest/crd-k8s-1.19.yaml
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----
====


==== Verbesserungen

* Support pour le scan de SUSE Linux (SLE, SLES) et Microsoft Mariner
* Protection des processus et des fichiers Zero-Drift. C'est le nouveau mode par défaut pour la protection des processus et des fichiers. Zero-Drift autorise automatiquement uniquement les processus provenant du processus parent inclus dans l'image de conteneur d'origine et n'autorise aucune mise à jour de fichiers ou installation de nouveaux fichiers. En mode découverte ou surveillance, Zero-Drift alertera sur les processus ou activités de fichiers suspects. Im Schutzmodus wird es solche Aktivitäten blockieren. Zero-Drift ne nécessite pas de processus à apprendre ou à ajouter à une liste d'autorisation. Désactiver Zero-Drift pour un groupe rendra effectives les règles de processus et de fichiers énumérées pour le groupe.
* Geteilte Richtlinienmodus-Schutz für Netzwerk, Prozess/Datei. Il existe maintenant un paramètre global dans les paramètres -> Configuration pour définir le mode de protection réseau séparément pour l'application des règles réseau. L'activation de cette fonctionnalité (désactivée par défaut) signifie que toutes les règles réseau sont en mode protection sélectionné (Découverte, Surveillance, Protection), tandis que les règles de processus/fichier restent en mode protection pour ce groupe, comme indiqué dans l'écran de groupe des politiques ->. De cette manière, les règles réseau peuvent être définies sur Protéger (bloquer), tandis que la politique de processus/fichier peut être définie sur Surveiller, ou vice versa.
* Détection de règles WAF, règles DLP améliorées (En-tête, URL, paquet complet)
* CRD pour WAF, DLP et contrôles d'admission. REMARQUE : Zusätzliche Clusterrollenbindungen/Berechtigungen erforderlich. Voir les sections de déploiement Kubernetes et OpenShift. Importation/Exportation CRD et versionnage pour les contrôles d'admission pris en charge par CRD.
* Intégration SSO Rancher pour démarrer la console {product-name} via Rancher Manager. Cette fonctionnalité n'est disponible que si les conteneurs {product-name} sont déployés via Rancher. REMARQUE : Nécessite une version mise à jour de Rancher (date/version à déterminer).
* Prend en charge le déploiement sur RKE2.
* Unterstützung für die Föderation von Clustern (Multi-Cluster-Manager) über einen Proxy.
* Surveillez les rôles/bindings RBAC de cluster requis et avertissez dans les événements et l'interface utilisateur lorsqu'il en manque.
* Prendre en charge les critères de restrictions de ressources dans les règles de contrôle d'admission.

==== Corrections de bugs

* Résoudre le problème où la sauvegarde du rôle de fédération des travailleurs devrait être restaurée dans des clusters non fédérés.

==== Version Preview.2 publiée en février 2022

* Petites modifications de fichiers et de licences dans le code source, aucune nouvelle fonctionnalité ajoutée.

==== Support pour le déploiement sur AWS ECS arrêté

La prise en charge du déploiement sur ECS n'est plus fournie. L'All-in-One devrait toujours pouvoir être déployé sur ECS, mais la documentation des étapes et des paramètres n'est plus prise en charge.

=== 5.0 'Aperçu technique' janvier 2022

==== Verbesserungen

* Première publication d'une version 'aperçu technique' non prise en charge de {product-name} 5.0 version open-source.
* Ajouter le support pour OWASP Top-10, des règles similaires à WAF pour détecter les attaques réseau dans les en-têtes ou dans le corps. Inclut le support pour les définitions CRD de signatures et leur application à des groupes appropriés.
* Supprime le scan sans serveur.

==== Corrections de bugs

* TBD

==== Sonstiges

* Le chart Helm v1.8.9 sera publié pour les déploiements 5.0.0. Si cela est utilisé avec la version Preview de 5.0.0, les modifications suivantes doivent être apportées à values.yml :
 ** Mettre à jour le registre sur docker.io
 ** Mettre à jour les noms/tags d'image vers la version preview sur Docker Hub
 ** Laisser les imagePullSecrets vides
