= Lignes directrices générales
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /13.special/01.general/01.general.md
:page-opendocs-slug:  /spécial/général

== Test de {product-name} à l'aide du conteneur Allinone

Les exemples de cette section déploient les conteneurs Allinone et Enforcer. Ceci est utile pour essayer {product-name}, en particulier sur des environnements non-Kubernetes (par exemple, docker native). Pour les déploiements basés sur Kubernetes, il est recommandé d'utiliser la dernière carte {product-name} Helm. Veuillez consulter la section Déploiement de {product-name}.

== Lignes directrices générales pour le déploiement

Préparez votre environnement hôte pour une installation correcte. Assurez-vous que les conteneurs {product-name} peuvent communiquer les uns avec les autres entre les hôtes. Ensuite, examinez et modifiez les fichiers d'exemple en fonction de votre environnement.

D'une manière générale, il est important de procéder comme suit :

. Étiqueter les nœuds de manière appropriée. Si vous utilisez des étiquettes de nœuds pour contrôler l'endroit où l'allinone ou le contrôleur est déployé, étiquetez-les avant de les déployer.
. Assurez-vous que les volumes peuvent être mappés correctement. Par exemple
+
[,yaml]
----
volumes:
        - /var/neuvector:/var/neuvector
        - /var/run/docker.sock:/var/run/docker.sock
        - /proc:/host/proc:ro
        - /sys/fs/cgroup:/host/cgroup:ro
----

. Ouvrir les ports nécessaires sur les hôtes. Assurez-vous que les ports requis sont correctement mappés et ouverts sur l'hôte. L'allinone nécessite 8443 (si vous utilisez la console), 18300, 18301, 18400 et 18401. L'Enforcer nécessite 18301 et 18401.
. Modifiez le champ CLUSTER_JOIN_ADDR. Trouvez l'adresse IP du nœud, le nom du nœud (si vous utilisez un serveur de noms) ou la variable du nœud (si vous utilisez des outils d'orchestration) pour l'allinone (contrôleur) à utiliser pour l'adresse "`node IP`" dans les fichiers d'exemple pour l'allinone et l'enforcer.

== Accès à la console

Veuillez consulter la première section Principes de base -> Connect to Manager pour connaître les options permettant de désactiver https ou d'accéder à la console via un pare-feu d'entreprise qui n'autorise pas le port 8443 pour l'accès à la console.
