= Scanners parallèles et autonomes
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /06.scanning/06.scanners/06.scanners.md
:page-opendocs-slug:  /scanning/scanners

== Augmenter l'évolutivité des scanners avec des scanners multiples

Pour améliorer les performances et l'évolutivité du scanner, {product-name} prend en charge le déploiement de plusieurs pods de scanner qui peuvent, en parallèle, scanner des images dans des registres. Le contrôleur attribue des tâches de numérisation à chaque module de numérisation disponible. Les pods du scanner peuvent être mis à l'échelle facilement selon les besoins à l'aide de Kubernetes.

Les modules de numérisation doivent être déployés sur des nœuds distincts afin de répartir la charge de travail sur différentes ressources hôtes. N'oubliez pas qu'un scanner a besoin de suffisamment de mémoire pour extraire et développer l'image, et qu'il doit donc disposer de plus de mémoire que la plus grande taille d'image à numériser. Si nécessaire, les scanners peuvent être placés sur des nœuds spécifiques ou éviter de placer plusieurs pods sur un nœud à l'aide d'étiquettes de nœuds Kubernetes standard, de taints/tolérances ou de configurations d'affinité de nœuds.

Par défaut, {product-name} déploie 2 pods d'analyse, dans le cadre des exemples de déploiement de la section Déploiement de {product-name}. Ces ensembles de répliques peuvent être augmentés ou réduits en fonction des besoins.

Le scanner contient la dernière base de données CVE et est régulièrement mis à jour (avec la balise "latest") par {product-name}. Le programme de mise à jour redéploie le scanner, ce qui oblige à extraire la dernière image du scanner afin d'obtenir la dernière base de données CVE. Voir la section xref:updating.adoc[Mise à jour de la base de données CVE] pour plus de détails sur l'outil de mise à jour.

Veuillez noter que dans les versions initiales, la présence et l'état des scanners multiples ne sont visibles que dans Kubernetes avec 'kubectl get pods -n neuvector' et ne seront pas affichés dans la console web.

Les résultats de l'analyse de tous les scanners sont affichés dans le menu Assets -> Registries. D'autres fonctions de surveillance des scanners seront ajoutées dans les prochaines versions.

=== Mise à l'échelle automatique des modules de numérisation

Les modules de numérisation peuvent être configurés pour une mise à l'échelle automatique en fonction de certains critères. Cela garantit que les travaux de numérisation sont traités rapidement et efficacement, surtout s'il y a des milliers d'images à numériser ou à re-numériser. Trois réglages sont possibles : retardé, immédiat et désactivé. Lorsque les images sont mises en file d'attente pour être numérisées par le contrôleur, celui-ci tient un "compte de tâches" de la taille de la file d'attente.

* Stratégie différée :
** Lorsque le contrôleur principal voit continuellement "task count" > 0 pendant > 90 secondes, un nouveau pod scanner est démarré si maxScannerPods n'est pas encore atteint.
** Lorsque le contrôleur principal constate en permanence que le "nombre de tâches" est égal à 0 pendant plus de 180 secondes, il réduit d'un pod le nombre de scanners si le nombre minScannerPods n'est pas encore atteint.
* Stratégie immédiate :
** Chaque fois que le contrôleur principal voit "task count" > 0, un nouveau pod scanner est démarré si maxScannerPods n'est pas encore atteint.
** Lorsque le contrôleur principal constate en permanence que le "nombre de tâches" est égal à 0 pendant plus de 180 secondes, il réduit d'un pod le nombre de scanners si le nombre minScannerPods n'est pas encore atteint.

La mise à l'échelle automatique du scanner est configurée dans Paramètres -> Configuration. Le paramètre minimumScannerPods définit le nombre minimum de pods d'analyse en cours d'exécution à tout moment, tandis que le paramètre maxScannerPods définit le nombre maximum de pods que la stratégie de mise à l'échelle automatique peut atteindre. NOTE : La définition d'une valeur minimale n'ajustera pas la valeur du jeu de répliques du déploiement du scanner d'origine. La valeur minimale sera appliquée lors du premier événement de montée/descente de l'échelle.

[IMPORTANT]
====
La mise à l'échelle automatique du scanner n'est pas prise en charge lorsque le scanner est déployé avec un opérateur OpenShift, car l'opérateur modifiera toujours le nombre de pods à sa valeur configurée.
====

=== Opérations et débogage

Chaque module de numérisation interrogera les registres à numériser pour obtenir la liste complète des images et autres données disponibles. Chaque scanner se verra ensuite attribuer une image à extraire du registre et à numériser.

Pour vérifier le comportement du scanner, les journaux de chaque module du scanner peuvent être examinés à l'aide de la fonction

[,shell]
----
kubectl logs <scanner-pod-name> -n neuvector
----

== Planification des performances

Expérimentez avec un nombre variable d'analyseurs sur des registres contenant un grand nombre d'images afin d'observer le comportement du temps d'exécution de l'analyse dans votre environnement. 2 à 5 scanners en tant que paramètre de réplique devraient suffire dans la plupart des cas.

Lorsqu'une tâche de numérisation est attribuée à un scanner, celui-ci extrait l'image du registre (après avoir interrogé le registre pour obtenir la liste des images disponibles). Le temps nécessaire à l'extraction de l'image (téléchargement) est généralement celui qui prend le plus de temps. Plusieurs scanners peuvent extraire en parallèle des images du même registre, de sorte que les performances peuvent être limitées par le registre ou la bande passante du réseau.

Les images de grande taille prendront plus de temps à être extraites et devront être agrandies pour être numérisées, ce qui consommera plus de mémoire. Assurez-vous que chaque scanner dispose de suffisamment de mémoire pour traiter plus que la plus grande image attendue (10 % de plus au minimum).

Plusieurs scanners peuvent être déployés sur le même hôte/nœud, mais il convient de s'assurer que l'hôte dispose de suffisamment de mémoire, de CPU et de bande passante réseau pour maximiser les performances du scanner.

== Scanner autonome pour la numérisation locale

{product-name} prend en charge les déploiements de scanners autonomes pour la numérisation locale d'images (qui ne nécessite pas de contrôleur). Dans l'exemple d'exécution de docker ci-dessous, l'image locale sera analysée et les résultats seront stockés localement dans /var/neuvector. Pour l'analyse locale, l'image doit être accessible via le docker.sock monté, sinon un registre peut être spécifié.

[,bash]
----
docker run --name neuvector.scanner --rm -e SCANNER_REPOSITORY=ubuntu -e SCANNER_TAG=16.04 -e SCANNER_ON_DEMAND=true -v /var/run/docker.sock:/var/run/docker.sock -v /var/neuvector:/var/neuvector  neuvector/scanner
----

Les variables d'environnement suivantes du scanner peuvent être utilisées dans la commande docker run :

* SCANNER_REGISTRY= url du registre (optionnel au lieu d'un scan local)
* SCANNER_REPOSITORY= répertoire à scanner
* SCANNER_TAG= étiquette de version
* SCANNER_REGISTRY_USERNAME= utilisateur (optionnel au lieu d'un scan local)
* SCANNER_REGISTRY_PASSWORD= mot de passe (optionnel au lieu du scan local)
* SCANNER_SCAN_LAYERS= true ou false (pour renvoyer des résultats de numérisation en couches)
* SCANNER_ON_DEMAND=true (obligatoire)
* CLUSTER_JOIN_ADDR (optionnel), CLUSTER_JOIN_PORT (optionnel) - pour envoyer les résultats au contrôleur afin qu'ils soient utilisés dans les règles de contrôle d'admission (contrôleur déployé par Kubernetes).
* CLUSTER_ADVERTISED_ADDR (facultatif) - si l'analyseur se trouve sur un hôte différent du contrôleur, pour envoyer les résultats à utiliser dans les règles de contrôle d'admission (contrôleur déployé par Kubernetes).

=== Analyse de l'hôte en mode autonome

Utilisez la commande suivante pour analyser l'hôte.

[CAUTION]
====
Nécessite le mode privilégié !
====


[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n neuvector
----

=== Déploiement manuel de plusieurs scanners sur Kubernetes

Pour déployer manuellement des scanners dans le cadre d'un déploiement Kubernetes existant, créez une nouvelle liaison de rôle :

[,shell]
----
kubectl create rolebinding neuvector-admin --clusterrole=admin --serviceaccount=neuvector:default -n neuvector
----

Ou pour OpenShift

[,shell]
----
oc adm policy add-role-to-user admin system:serviceaccount:neuvector:default -n neuvector
----

Utilisez le fichier ci-dessous pour déployer plusieurs scanners. Modifiez les répliques pour augmenter ou diminuer le nombre de scanners fonctionnant en parallèle.

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-scanner-pod
  namespace: neuvector
spec:
  selector:
    matchLabels:
      app: neuvector-scanner-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  template:
    metadata:
      labels:
        app: neuvector-scanner-pod
    spec:
      containers:
        - name: neuvector-scanner-pod
          image: neuvector/scanner
          imagePullPolicy: Always
          env:
            - name: CLUSTER_JOIN_ADDR
              value: neuvector-svc-controller.neuvector
# Commented out sections are required only for local build-phase scanning
#            - name: SCANNER_DOCKER_URL
#              value: tcp://192.168.1.10:2376
#          volumeMounts:
#            - mountPath: /var/run/docker.sock
#              name: docker-sock
#              readOnly: true
#      volumes:
#        - name: docker-sock
#          hostPath:
#            path: /var/run/docker.sock
      restartPolicy: Always
----

Ensuite, créez ou mettez à jour le job cron de mise à jour de la base de données CVE. La base de données CVE sera ainsi mise à jour chaque nuit.

[,yaml]
----
apiVersion: batch/v1
kind: CronJob
metadata:
  name: neuvector-updater-pod
  namespace: neuvector
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: neuvector-updater-pod
        spec:
          containers:
          - name: neuvector-updater-pod
            image: neuvector/updater
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`; /usr/bin/curl -kv -X PATCH -H "Authorization:Bearer $TOKEN" -H "Content-Type:application/strategic-merge-patch+json" -d '{"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"'`date +%Y-%m-%dT%H:%M:%S%z`'"}}}}}' 'https://kubernetes.default/apis/apps/v1/namespaces/neuvector/deployments/neuvector-scanner-pod'
          restartPolicy: Never
----
