= Dépannage
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /12.troubleshooting/01.troubleshooting/01.troubleshooting.md
:page-opendocs-slug:  /troubleshooting/troubleshooting

== Dépannage des déploiements {product-name} 

Les conteneurs {product-name} sont déployés, gérés et mis à jour à l'aide du même outil d'orchestration que celui utilisé pour les charges de travail des applications. Veillez à consulter la documentation en ligne pour chaque étape nécessaire au déploiement. Souvent, les déploiements sont tentés en copiant simplement les exemples de fichiers yaml et en les déployant sans passer en revue les étapes préalables, telles que la configuration correcte des registres, des secrets ou des RBACs/rolebindings.

=== Déploiement initial

* Vérifier que les conteneurs {product-name} peuvent être tirés avec une authentification correcte. Vérifiez le secret utilisé et assurez-vous que le cluster est capable d'accéder au registre approprié.
* Assurez-vous que les modifications apportées aux paramètres yaml requis (par exemple NodePort ou LoadBalancer) ou aux paramètres de valeurs Helm sont définies de manière appropriée.
* Vérifier la plate-forme et le temps d'exécution du conteneur et apporter les modifications nécessaires (par exemple, PKS, containerd, CRI-O).

=== Connexion et configuration initiale

* Vérifiez que l'accès approprié au gestionnaire (adresse IP, port, route) est autorisé par les pare-feux.

=== Opération en cours

* Intégration de l'annuaire. {product-name} prend en charge des configurations spécifiques pour LDAP/AD et d'autres intégrations pour les groupes et les rôles. Contactez {product-name} pour des étapes de dépannage supplémentaires et un outil de dépannage AD.
* Analyse du registre. La plupart des problèmes sont liés à des erreurs d'authentification du registre ou à l'impossibilité pour le contrôleur d'accéder au registre depuis le cluster.
* En cas de problèmes de performances, assurez-vous que le scanner dispose de suffisamment de mémoire pour numériser des images de grande taille. Il est également possible de spécifier des minima de CPU et de mémoire dans la politique de pods afin de garantir des performances adéquates à l'échelle.
* Contrôle d'admission. Voir la section Dépannage dans la section Risques de sécurité... -> Contrôles d'admission.

=== Mise à jour

* Utiliser des mises à jour continues pour le contrôleur. Si vous redémarrez les hôtes, assurez-vous de surveiller les contrôleurs lorsqu'ils sont déplacés vers d'autres hôtes ou redéployés sur les hôtes redémarrés, afin de vous assurer qu'ils sont capables de démarrer, de rejoindre le cluster de contrôleurs et de se stabiliser/synchroniser. Le redémarrage de tous les hôtes en même temps ou trop rapidement peut entraîner des états inconnus pour les contrôleurs.
* Utilisez un volume persistant pour stocker la configuration de {product-name} au cas où tous les contrôleurs/nœuds tomberaient en panne dans le cluster.
* Lors de la mise à jour vers une nouvelle version, consultez la documentation en ligne pour identifier les changements/ajouts au fichier yaml requis, ainsi que d'autres changements tels que les liaisons de rôles ou les nouveaux services (par exemple, le webhook de contrôle d'admission, la réclamation de volume persistante, etc.)

== Journaux de débogage

Pour consulter les journaux d'un conteneur {product-name}, par exemple un pod contrôleur

[,shell]
----
kubectl logs neuvector-controller-pod-777fdc5668-4jkjn -n neuvector
----

Ces journaux peuvent indiquer les problèmes de connectivité du cluster, les actions de l'administrateur, l'activité d'analyse et d'autres entrées utiles. Si plusieurs contrôleurs fonctionnent, il peut être nécessaire d'inspecter chacun d'entre eux. Ces journaux peuvent être transférés dans un fichier pour être envoyés à l'assistance {product-name}.

=== Activer le mode débogage pour les contrôleurs {product-name} 

Pour les problèmes nécessitant un examen approfondi, le mode de débogage peut être activé pour les contrôleurs/allinones, ce qui permet d'enregistrer des informations détaillées. Cela peut augmenter considérablement la taille du fichier journal, il est donc recommandé de le désactiver après l'avoir collecté.

=== Kubernetes, OpenShift et autres journaux d'orchestration

Il peut être utile d'inspecter les journaux des outils d'orchestration pour voir toute l'activité de déploiement, y compris les horodatages et l'état de la création des pods, les déploiements, les daemonsets et les autres actions de gestion des conteneurs {product-name} effectuées par l'outil d'orchestration.

[,shell]
----
kubectl get events -n neuvector
----

== Journal de support

Le journal d'assistance contient des informations supplémentaires utiles pour l'assistance {product-name}, notamment la configuration du système, les conteneurs, les politiques, les notifications et les détails du conteneur {product-name}.

Pour télécharger le journal d'assistance, allez dans Paramètres -> Configuration et sélectionnez Collecter le journal.

== Utilisation de l'interface de communication pour activer le mode débogage

Se connecter à {product-name} manager pod avec l'utilisateur et le mot de passe (recommandé dans une fenêtre de terminal séparée).

[,shell]
----
kubectl exec -it neuvector-manager-pod-5bb76b6754-rlmnp -n neuvector -- cli
----

[,shell]
----
#neuvector-svc-controller.neuvector> login
----

Obtenir la liste des contrôleurs. Trouvez le contrôleur avec la valeur Leader = True.

[,shell]
----
show controller
----

Activer le mode de débogage dans le contrôleur principal en utilisant l'ID ou le nom du contrôleur.

[,shell]
----
set controller 4fce427cf963 debug -c all
----

Pour activer le mode débogage sur tous les contrôleurs

[,shell]
----
set system controller_debug -c all
----

Effectuez sur {product-name} l'activité que vous souhaitez déboguer. Affichez ensuite les journaux du contrôleur (dans une fenêtre de terminal séparée).

[,shell]
----
kubectl logs <leader_controller_pod_name> -n neuvector
----

Si nécessaire, capturez les journaux et envoyez-les à {product-name}.

Désactivez le mode Debug sur le contrôleur (dans la fenêtre CLI).

[,shell]
----
set controller 4fce427cf963 debug
exit
----

Vérifier l'état de débogage du contrôleur.

[,shell]
----
show controller setting 289d67396fcb
----

== Utiliser l'API REST pour activer le mode débogage

Définissez un jeton d'accès avec votre IP, votre utilisateur et votre mot de passe :

[,shell]
----
_controllerIP_="<your_controller_ip>"
_controllerRESTAPIPort_="10443"
_neuvectorUsername_="admin"
_neuvectorPassword_="admin"
----

[NOTE]
====
Pour les déploiements basés sur Kubernetes, vous pouvez obtenir l'IP du contrôleur dans la sortie de commande suivante :
====

[,shell]
----
kubectl get pod -n neuvector -o wide | grep controller
----

[NOTE]
====
Si vous accédez à l'API REST depuis l'extérieur du cluster, consultez les instructions de la section Automatisation.
====

Obtenir le jeton d'authentification

[,shell]
----
curl -k -H "Content-Type: application/json" -d '{"password": {"username": "'$_neuvectorUsername_'", "password": "'$_neuvectorPassword_'"}}' "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/auth" > /dev/null 2>&1 > token.json
_TOKEN_=`cat token.json | jq -r '.token.token'`
----

[NOTE]
====
Vous pouvez avoir besoin d'installer jq ($sudo yum install jq)
====

Activer le mode débogage

[,shell]
----
curl -X PATCH -k -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_" -d '{"config": {"controller_debug": ["cpath", "conn"]}}' "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/system/config"  > /dev/null 2>&1   > set_debug.json
#debug options - cpath, conn, mutex, scan, cluster , all
----

Désactiver le débogage sur tous les contrôleurs d'un cluster

[,shell]
----
curl -X PATCH -k -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_" -d '{"config": {"controller_debug": []}}' "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/system/config"  > /dev/null 2>&1   > set_debug.json
----

Vérifier l'état de débogage du contrôleur dans un cluster

[,bash]
----
curl  -k -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_"  "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/system/config"  > /dev/null 2>&1   > system_setting.json

cat system_setting.json | jq .config.controller_debug
----

Déconnexion

[,shell]
----
echo `date +%Y%m%d_%H%M%S` log out
curl -k -X 'DELETE' -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_" "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/auth" > /dev/null 2>&1
----
