= Moteur Mirantis Kubernetes
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /13.special/02.docker/02.docker.md
:page-opendocs-slug:  /special/docker

== Déploiement vers le cluster Swarm

Pour déployer {product-name} à l'aide d'un cluster Swarm, tirez d'abord les images {product-name} à l'aide de Docker UCP dans le menu Images. Il se peut que vous deviez ajouter un numéro de version pour obtenir la dernière version sur Docker Hub.

Actuellement, Swarm/UCP ne supporte pas les capacités seccomp (options cap_add) ou le déploiement dans '`privileged mode`'. Les conteneurs {product-name} devront donc être déployés à partir de la ligne de commande en utilisant docker-compose ou run. Voir les exemples de fichiers de composition pour l'allinone et l'enforcer ci-dessous.

Le service Docker UCP HRM utilise le port par défaut 8443 qui entre en conflit avec le port de la console {product-name}. Si vous utilisez le port HRM par défaut, modifiez le mappage du port {product-name}, par exemple 9443:8443 pour le conteneur allinone dans les exemples ci-dessous. Une fois l'application {product-name} déployée avec succès, connectez-vous à la console sur le port 9443 de l'hôte allinone.

== Déployer sur Docker Swarm en mode privilégié

Voici un exemple de fichier docker-compose pour déployer le conteneur tout-en-un sur le premier nœud. Comme le conteneur tout-en-un contient un module enforcer, les conteneurs d'application sur le même nœud peuvent être sécurisés. Les déploiements sur sites vierges et sur sites industriels sont soutenus.

Déployer le tout-en-un en utilisant docker-compose (mode privilégié) :

[,yaml]
----
allinone:
    pid: host
    image: neuvector/allinone:<version>
    container_name: allinone
    privileged: true
    environment:
        - CLUSTER_JOIN_ADDR=node_ip
    ports:
        - 18300:18300
        - 18301:18301
        - 18400:18400
        - 18401:18401
        - 18301:18301/udp
        - 9443:8443
    volumes:
        - /lib/modules:/lib/modules
        - /var/neuvector:/var/neuvector
        - /var/run/docker.sock:/var/run/docker.sock
        - /proc:/host/proc:ro
        - /sys/fs/cgroup:/host/cgroup:ro
----

La variable d'environnement la plus importante est *CLUSTER_JOIN_ADDR*. Il s'agit de l'adresse IP à laquelle les autres agents d'exécution se connectent. Normalement, il doit être défini sur l'adresse IP du nœud où le conteneur tout-en-un est en cours d'exécution.

Les ports 18300 et 18301 sont des ports par défaut pour la communication avec les clusters. Ils doivent être identiques pour tous les contrôleurs et exécutants du cluster. Veuillez vous référer à la section _"Docker-compose Details"_ pour savoir comment changer les ports par défaut.

Ajouter un conteneur enforcer en utilisant docker-compose (mode privilégié)

Voici un exemple de fichier docker-compose pour joindre un enforcer au cluster. Les déploiements sur sites vierges et sur sites industriels sont soutenus.

[,yaml]
----
enforcer:
    pid: host
    image: neuvector/enforcer:<version>
    container_name: enforcer
    privileged: true
    environment:
        - CLUSTER_JOIN_ADDR=controller_node_ip
    ports:
        - 18301:18301
        - 18401:18401
        - 18301:18301/udp
    volumes:
        - /lib/modules:/lib/modules
        - /var/run/docker.sock:/var/run/docker.sock
        - /proc:/host/proc:ro
        - /sys/fs/cgroup/:/host/cgroup/:ro
----

La variable d'environnement la plus importante est *CLUSTER_JOIN_ADDR*. Pour les contrôleurs, remplacez `<controller_node_ip>` par l'adresse IP du nœud du contrôleur. Typiquement, *CLUSTER_JOIN_ADDR* dans le fichier docker-compose du contrôleur/all-in-one et le fichier docker-compose de enforcer ont la même valeur.

À partir de {product-name} 4.0+, un conteneur d'analyse distinct doit être déployé pour effectuer l'analyse des vulnérabilités.

Exemple de docker-compose pour le scanner :

[,yaml]
----
Scanner:
   image: neuvector/scanner
   container_name: scanner
   environment:
     - SCANNER_DOCKER_URL=tcp://192.168.1.10:2376
     - CLUSTER_JOIN_ADDR=controller_node_ip
   ports:
     - 18402:18402
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
----

== Déploiement sans utiliser le mode privilégié

Pour certaines configurations de plate-forme, il est possible de déployer les conteneurs {product-name} sans avoir à les exécuter en mode privilégié. La configuration doit permettre d'ajouter des capacités et de définir le profil de l'armement. Notez que Docker DataCenter/UCP et Swarm ne prennent actuellement pas en charge cette fonctionnalité, mais il est toujours possible de déployer {product-name} manuellement à l'aide de Compose ou Run.

Déployer allinone (NO mode privilégié) avec docker-compose

[,yaml]
----
allinone:
    pid: host
    image: neuvector/allinone
    container_name: neuvector.allinone
    cap_add:
        - SYS_ADMIN
        - NET_ADMIN
        - SYS_PTRACE
        - IPC_LOCK
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined
        - label=disable
    environment:
        - CLUSTER_JOIN_ADDR=[AllInOne Node IP Address]
    ports:
        - 18300:18300
        - 18301:18301
        - 18400:18400
        - 18401:18401
        - 18301:18301/udp
        - 9443:8443
    volumes:
        - /lib/modules:/lib/modules
        - /var/run/docker.sock:/var/run/docker.sock
        - /proc:/host/proc:ro
        - /sys/fs/cgroup:/host/cgroup:ro
        - /var/neuvector:/var/neuvector
----

Déployer enforcer (NO privileged mode) avec docker-compose

[,yaml]
----
enforcer:
    pid: host
    image: neuvector/enforcer
    container_name: neuvector.enforcer
    cap_add:
        - SYS_ADMIN
        - NET_ADMIN
        - SYS_PTRACE
        - IPC_LOCK
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined
        - label=disable
    environment:
        - CLUSTER_JOIN_ADDR=[AllInOne Node IP Address]
    ports:
        - 18301:18301
        - 18401:18401
        - 18301:18301/udp
    volumes:
        - /lib/modules:/lib/modules
        - /var/run/docker.sock:/var/run/docker.sock
        - /proc:/host/proc:ro
        - /sys/fs/cgroup/:/host/cgroup/:ro
----
